---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOSPITALIZATION_ORDER GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOSPITALIZATION_ORDER GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOSPITALIZATION_ORDER GROUP BY INP_NO;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER GROUP BY ORDER_TYPE_CODE;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOSPITALIZATION_ORDER GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOSPITALIZATION_ORDER GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOSPITALIZATION_ORDER GROUP BY INP_NO;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER GROUP BY ORDER_TYPE_CODE;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOSPITALIZATION_ORDER GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOSPITALIZATION_ORDER GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOSPITALIZATION_ORDER GROUP BY INP_NO;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER GROUP BY ORDER_TYPE_CODE;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER GROUP BY LAST_MODIFIC_TIME;

