---OPER_NURS_OBSER_ID  VARCHAR2(18)      手术护理观察ID      
SELECT OPER_NURS_OBSER_ID FROM OPER_NURS_OBSER GROUP BY OPER_NURS_OBSER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OBSER GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM OPER_NURS_OBSER GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN..1000
SELECT NURSING_OBSERVATION_RESULT FROM OPER_NURS_OBSER GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OBSER GROUP BY LAST_MODIFIC_TIME;

---OPER_NURS_OBSER_ID  VARCHAR2(18)      手术护理观察ID      
SELECT OPER_NURS_OBSER_ID FROM OPER_NURS_OBSER GROUP BY OPER_NURS_OBSER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OBSER GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM OPER_NURS_OBSER GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN..1000
SELECT NURSING_OBSERVATION_RESULT FROM OPER_NURS_OBSER GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OBSER GROUP BY LAST_MODIFIC_TIME;

---OPER_NURS_OBSER_ID  VARCHAR2(18)      手术护理观察ID      
SELECT OPER_NURS_OBSER_ID FROM OPER_NURS_OBSER GROUP BY OPER_NURS_OBSER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OBSER GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM OPER_NURS_OBSER GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN..1000
SELECT NURSING_OBSERVATION_RESULT FROM OPER_NURS_OBSER GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OBSER GROUP BY LAST_MODIFIC_TIME;

