---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM TRANSFERENCE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFERENCE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFERENCE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM TRANSFERENCE_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM TRANSFERENCE_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM TRANSFERENCE_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM TRANSFERENCE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM TRANSFERENCE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM TRANSFERENCE_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM TRANSFERENCE_RECORD GROUP BY CURRENTLY_SITUATION;

---TRANSFER_PURPOSE  VARCHAR2(200)  Y    转科目的    S1  AN..200
SELECT TRANSFER_PURPOSE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_PURPOSE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    转入诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM TRANSFERENCE_RECORD GROUP BY ASSESSMENT_PLAN;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    中药处方医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM TRANSFERENCE_RECORD GROUP BY ADVICE_CONTENT;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM TRANSFERENCE_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---TRANSFER_RCD_TYPE  NUMBER(1)  Y    转科记录类型  标准值：1.转入记录  2.转出记录  S2  N1
SELECT TRANSFER_RCD_TYPE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_RCD_TYPE;

---TRANSFER_DATATIME  DATE  Y    转出日期时间    DT  DT15
SELECT TRANSFER_DATATIME FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_DATATIME;

---TURNOUT_DEPT_NAME  VARCHAR2(50)  Y    转出科室    S1  AN..50
SELECT TURNOUT_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DEPT_NAME;

---TURNOUT_DOCTOR_SIGN  VARCHAR2(50)  Y    转出医师签名    S1  A..50
SELECT TURNOUT_DOCTOR_SIGN FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DOCTOR_SIGN;

---OVERINTO_DATATIME  DATE  Y    转入日期时间    DT  DT15
SELECT OVERINTO_DATATIME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DATATIME;

---OVERINTO_DEPT_NAME  VARCHAR2(50)  Y    转入科室    S1  AN..50
SELECT OVERINTO_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_NAME;

---OVERINTO_DEPT_SIGN  VARCHAR2(50)  Y    转入医师签名    S1  A..50
SELECT OVERINTO_DEPT_SIGN FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFERENCE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM TRANSFERENCE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFERENCE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFERENCE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM TRANSFERENCE_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM TRANSFERENCE_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM TRANSFERENCE_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM TRANSFERENCE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM TRANSFERENCE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM TRANSFERENCE_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM TRANSFERENCE_RECORD GROUP BY CURRENTLY_SITUATION;

---TRANSFER_PURPOSE  VARCHAR2(200)  Y    转科目的    S1  AN..200
SELECT TRANSFER_PURPOSE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_PURPOSE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    转入诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM TRANSFERENCE_RECORD GROUP BY ASSESSMENT_PLAN;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    中药处方医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM TRANSFERENCE_RECORD GROUP BY ADVICE_CONTENT;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM TRANSFERENCE_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---TRANSFER_RCD_TYPE  NUMBER(1)  Y    转科记录类型  标准值：1.转入记录  2.转出记录  S2  N1
SELECT TRANSFER_RCD_TYPE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_RCD_TYPE;

---TRANSFER_DATATIME  DATE  Y    转出日期时间    DT  DT15
SELECT TRANSFER_DATATIME FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_DATATIME;

---TURNOUT_DEPT_NAME  VARCHAR2(50)  Y    转出科室    S1  AN..50
SELECT TURNOUT_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DEPT_NAME;

---TURNOUT_DOCTOR_SIGN  VARCHAR2(50)  Y    转出医师签名    S1  A..50
SELECT TURNOUT_DOCTOR_SIGN FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DOCTOR_SIGN;

---OVERINTO_DATATIME  DATE  Y    转入日期时间    DT  DT15
SELECT OVERINTO_DATATIME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DATATIME;

---OVERINTO_DEPT_NAME  VARCHAR2(50)  Y    转入科室    S1  AN..50
SELECT OVERINTO_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_NAME;

---OVERINTO_DEPT_SIGN  VARCHAR2(50)  Y    转入医师签名    S1  A..50
SELECT OVERINTO_DEPT_SIGN FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFERENCE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM TRANSFERENCE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFERENCE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFERENCE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM TRANSFERENCE_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM TRANSFERENCE_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM TRANSFERENCE_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM TRANSFERENCE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM TRANSFERENCE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM TRANSFERENCE_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM TRANSFERENCE_RECORD GROUP BY CURRENTLY_SITUATION;

---TRANSFER_PURPOSE  VARCHAR2(200)  Y    转科目的    S1  AN..200
SELECT TRANSFER_PURPOSE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_PURPOSE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    转入诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM TRANSFERENCE_RECORD GROUP BY ASSESSMENT_PLAN;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    中药处方医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM TRANSFERENCE_RECORD GROUP BY ADVICE_CONTENT;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM TRANSFERENCE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM TRANSFERENCE_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---TRANSFER_RCD_TYPE  NUMBER(1)  Y    转科记录类型  标准值：1.转入记录  2.转出记录  S2  N1
SELECT TRANSFER_RCD_TYPE FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_RCD_TYPE;

---TRANSFER_DATATIME  DATE  Y    转出日期时间    DT  DT15
SELECT TRANSFER_DATATIME FROM TRANSFERENCE_RECORD GROUP BY TRANSFER_DATATIME;

---TURNOUT_DEPT_NAME  VARCHAR2(50)  Y    转出科室    S1  AN..50
SELECT TURNOUT_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DEPT_NAME;

---TURNOUT_DOCTOR_SIGN  VARCHAR2(50)  Y    转出医师签名    S1  A..50
SELECT TURNOUT_DOCTOR_SIGN FROM TRANSFERENCE_RECORD GROUP BY TURNOUT_DOCTOR_SIGN;

---OVERINTO_DATATIME  DATE  Y    转入日期时间    DT  DT15
SELECT OVERINTO_DATATIME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DATATIME;

---OVERINTO_DEPT_NAME  VARCHAR2(50)  Y    转入科室    S1  AN..50
SELECT OVERINTO_DEPT_NAME FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_NAME;

---OVERINTO_DEPT_SIGN  VARCHAR2(50)  Y    转入医师签名    S1  A..50
SELECT OVERINTO_DEPT_SIGN FROM TRANSFERENCE_RECORD GROUP BY OVERINTO_DEPT_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFERENCE_RECORD GROUP BY LAST_MODIFIC_TIME;

