---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---OPEATION_POSSIBLE_VENTURE  VARCHAR2(200)  Y    手术中可能出现的意外及风险    S1  A..200
SELECT OPEATION_POSSIBLE_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEATION_POSSIBLE_VENTURE;

---OPEA_AFTER_POS_VENTURE  VARCHAR2(1000)  Y    手术后可能出现的意外及并发症    S1  AN..1000
SELECT OPEA_AFTER_POS_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEA_AFTER_POS_VENTURE;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    S1  AN..1000
SELECT REPLACE_SCHEME FROM OPERATION_INFORMED_CONSENT GROUP BY REPLACE_SCHEME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION_CODE FROM OPERATION_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---TREATING_DOCTOR_SIGN  VARCHAR2(50)  Y    经治医师签名    S1  A..50
SELECT TREATING_DOCTOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY TREATING_DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---OPERATOR_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY OPERATOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---OPEATION_POSSIBLE_VENTURE  VARCHAR2(200)  Y    手术中可能出现的意外及风险    S1  A..200
SELECT OPEATION_POSSIBLE_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEATION_POSSIBLE_VENTURE;

---OPEA_AFTER_POS_VENTURE  VARCHAR2(1000)  Y    手术后可能出现的意外及并发症    S1  AN..1000
SELECT OPEA_AFTER_POS_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEA_AFTER_POS_VENTURE;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    S1  AN..1000
SELECT REPLACE_SCHEME FROM OPERATION_INFORMED_CONSENT GROUP BY REPLACE_SCHEME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION_CODE FROM OPERATION_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---TREATING_DOCTOR_SIGN  VARCHAR2(50)  Y    经治医师签名    S1  A..50
SELECT TREATING_DOCTOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY TREATING_DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---OPERATOR_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY OPERATOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM OPERATION_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OPERATION_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---OPEATION_POSSIBLE_VENTURE  VARCHAR2(200)  Y    手术中可能出现的意外及风险    S1  A..200
SELECT OPEATION_POSSIBLE_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEATION_POSSIBLE_VENTURE;

---OPEA_AFTER_POS_VENTURE  VARCHAR2(1000)  Y    手术后可能出现的意外及并发症    S1  AN..1000
SELECT OPEA_AFTER_POS_VENTURE FROM OPERATION_INFORMED_CONSENT GROUP BY OPEA_AFTER_POS_VENTURE;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    S1  AN..1000
SELECT REPLACE_SCHEME FROM OPERATION_INFORMED_CONSENT GROUP BY REPLACE_SCHEME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION_CODE FROM OPERATION_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---TREATING_DOCTOR_SIGN  VARCHAR2(50)  Y    经治医师签名    S1  A..50
SELECT TREATING_DOCTOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY TREATING_DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OPERATION_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---OPERATOR_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATOR_SIGN FROM OPERATION_INFORMED_CONSENT GROUP BY OPERATOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

