---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM FIRST_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM FIRST_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM FIRST_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM FIRST_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM FIRST_COURSE_RECORD GROUP BY RECORD_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM FIRST_COURSE_RECORD GROUP BY CHIEF_COMPLAINT;

---RECORD_FEATURE  VARCHAR2(2000)  Y    病例特点    S1  AN..2000
SELECT RECORD_FEATURE FROM FIRST_COURSE_RECORD GROUP BY RECORD_FEATURE;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM FIRST_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM FIRST_COURSE_RECORD GROUP BY DIAG_EVIDENCE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM FIRST_COURSE_RECORD GROUP BY ASSESSMENT_PLAN;

---IDENTIFY_WM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-西医诊断名称    S1  AN..50
SELECT IDENTIFY_WM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_WM_DIAGNAME;

---IDENTIFY_TCM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-中医病名名称    S1  AN..50
SELECT IDENTIFY_TCM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_DIAGNAME;

---IDENTIFY_TCM_SYMPTOMNAME  VARCHAR2(50)  Y    鉴别诊断-中医证候名称    S1  AN..50
SELECT IDENTIFY_TCM_SYMPTOMNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_SYMPTOMNAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM FIRST_COURSE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY INP_DOCTOR_SIGN;

---SUPER_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPER_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY SUPER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM FIRST_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM FIRST_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM FIRST_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM FIRST_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM FIRST_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM FIRST_COURSE_RECORD GROUP BY RECORD_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM FIRST_COURSE_RECORD GROUP BY CHIEF_COMPLAINT;

---RECORD_FEATURE  VARCHAR2(2000)  Y    病例特点    S1  AN..2000
SELECT RECORD_FEATURE FROM FIRST_COURSE_RECORD GROUP BY RECORD_FEATURE;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM FIRST_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM FIRST_COURSE_RECORD GROUP BY DIAG_EVIDENCE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM FIRST_COURSE_RECORD GROUP BY ASSESSMENT_PLAN;

---IDENTIFY_WM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-西医诊断名称    S1  AN..50
SELECT IDENTIFY_WM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_WM_DIAGNAME;

---IDENTIFY_TCM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-中医病名名称    S1  AN..50
SELECT IDENTIFY_TCM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_DIAGNAME;

---IDENTIFY_TCM_SYMPTOMNAME  VARCHAR2(50)  Y    鉴别诊断-中医证候名称    S1  AN..50
SELECT IDENTIFY_TCM_SYMPTOMNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_SYMPTOMNAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM FIRST_COURSE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY INP_DOCTOR_SIGN;

---SUPER_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPER_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY SUPER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM FIRST_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM FIRST_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM FIRST_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM FIRST_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM FIRST_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM FIRST_COURSE_RECORD GROUP BY RECORD_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM FIRST_COURSE_RECORD GROUP BY CHIEF_COMPLAINT;

---RECORD_FEATURE  VARCHAR2(2000)  Y    病例特点    S1  AN..2000
SELECT RECORD_FEATURE FROM FIRST_COURSE_RECORD GROUP BY RECORD_FEATURE;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM FIRST_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM FIRST_COURSE_RECORD GROUP BY DIAG_EVIDENCE;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM FIRST_COURSE_RECORD GROUP BY ASSESSMENT_PLAN;

---IDENTIFY_WM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-西医诊断名称    S1  AN..50
SELECT IDENTIFY_WM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_WM_DIAGNAME;

---IDENTIFY_TCM_DIAGNAME  VARCHAR2(50)  Y    鉴别诊断-中医病名名称    S1  AN..50
SELECT IDENTIFY_TCM_DIAGNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_DIAGNAME;

---IDENTIFY_TCM_SYMPTOMNAME  VARCHAR2(50)  Y    鉴别诊断-中医证候名称    S1  AN..50
SELECT IDENTIFY_TCM_SYMPTOMNAME FROM FIRST_COURSE_RECORD GROUP BY IDENTIFY_TCM_SYMPTOMNAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM FIRST_COURSE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY INP_DOCTOR_SIGN;

---SUPER_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPER_DOCTOR_SIGN FROM FIRST_COURSE_RECORD GROUP BY SUPER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM FIRST_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

