---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_DAYS;

---AFTER_OPERATION_DAY  NUMBER(5)  Y    手术或分娩后天数    N  N..5
SELECT AFTER_OPERATION_DAY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY AFTER_OPERATION_DAY;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY CREATE_DATETIME;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY BREATH_FREQUENCY;

---RESPIRATOR_FLAG  VARCHAR2(5)  Y    使用呼吸机标志  TRUE/FALSE  L  T/F
SELECT RESPIRATOR_FLAG FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY RESPIRATOR_FLAG;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SPHYGMUS;

---PACEMAKER_HEARTRATE  NUMBER(3)  Y    起搏器心率(次/min)    N  N2..3
SELECT PACEMAKER_HEARTRATE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PACEMAKER_HEARTRATE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY TEMPERATURE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DIASTOLIC_PRESSURE;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6.2
SELECT WEIGHT FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY WEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.1
SELECT ABDOMINAL_GIRTH FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY ABDOMINAL_GIRTH;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_DAYS;

---AFTER_OPERATION_DAY  NUMBER(5)  Y    手术或分娩后天数    N  N..5
SELECT AFTER_OPERATION_DAY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY AFTER_OPERATION_DAY;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY CREATE_DATETIME;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY BREATH_FREQUENCY;

---RESPIRATOR_FLAG  VARCHAR2(5)  Y    使用呼吸机标志  TRUE/FALSE  L  T/F
SELECT RESPIRATOR_FLAG FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY RESPIRATOR_FLAG;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SPHYGMUS;

---PACEMAKER_HEARTRATE  NUMBER(3)  Y    起搏器心率(次/min)    N  N2..3
SELECT PACEMAKER_HEARTRATE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PACEMAKER_HEARTRATE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY TEMPERATURE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DIASTOLIC_PRESSURE;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6.2
SELECT WEIGHT FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY WEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.1
SELECT ABDOMINAL_GIRTH FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY ABDOMINAL_GIRTH;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY INP_DAYS;

---AFTER_OPERATION_DAY  NUMBER(5)  Y    手术或分娩后天数    N  N..5
SELECT AFTER_OPERATION_DAY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY AFTER_OPERATION_DAY;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY CREATE_DATETIME;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY BREATH_FREQUENCY;

---RESPIRATOR_FLAG  VARCHAR2(5)  Y    使用呼吸机标志  TRUE/FALSE  L  T/F
SELECT RESPIRATOR_FLAG FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY RESPIRATOR_FLAG;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SPHYGMUS;

---PACEMAKER_HEARTRATE  NUMBER(3)  Y    起搏器心率(次/min)    N  N2..3
SELECT PACEMAKER_HEARTRATE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY PACEMAKER_HEARTRATE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY TEMPERATURE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY DIASTOLIC_PRESSURE;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6.2
SELECT WEIGHT FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY WEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.1
SELECT ABDOMINAL_GIRTH FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY ABDOMINAL_GIRTH;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM MONITOR_VITAL_SIGNS_RECORD GROUP BY LAST_MODIFIC_TIME;

