---ASSESSMENT_ITEMS_ID  VARCHAR2(18)      评估记录子表id    null  null
SELECT ASSESSMENT_ITEMS_ID FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY ASSESSMENT_ITEMS_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号    null  null
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY INPATIENT_SN;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN.. 1000
SELECT NURSING_OBSERVATION_RESULT FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY LAST_MODIFIC_TIME;

---ASSESSMENT_ITEMS_ID  VARCHAR2(18)      评估记录子表id    null  null
SELECT ASSESSMENT_ITEMS_ID FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY ASSESSMENT_ITEMS_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号    null  null
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY INPATIENT_SN;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN.. 1000
SELECT NURSING_OBSERVATION_RESULT FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY LAST_MODIFIC_TIME;

---ASSESSMENT_ITEMS_ID  VARCHAR2(18)      评估记录子表id    null  null
SELECT ASSESSMENT_ITEMS_ID FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY ASSESSMENT_ITEMS_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号    null  null
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY INPATIENT_SN;

---NURSING_OBSER_PROJECT_NAME  VARCHAR2(30)  Y    护理观察项目名称    S1  AN..30
SELECT NURSING_OBSER_PROJECT_NAME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSER_PROJECT_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    S1  AN.. 1000
SELECT NURSING_OBSERVATION_RESULT FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY NURSING_OBSERVATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT_ITEMS GROUP BY LAST_MODIFIC_TIME;

