---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY PRESC_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY INPATIENT_SN;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_TYPE_CODE;

---RECIPE_GROUP_NO  VARCHAR2(50)  Y    处方药品组号    S1  N..50
SELECT RECIPE_GROUP_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY RECIPE_GROUP_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY APPLY_NO;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  应符合国标：CV06.00.229  S3  N1
SELECT ORDER_ITEM_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---ADVICEPLAN_START_DATETIME  DATE  Y    医嘱计划开始日期时间    DT  DT15
SELECT ADVICEPLAN_START_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_START_DATETIME;

---ADVICEPLAN_END_DATETIME  DATE  Y    医嘱计划结束日期时间    DT  DT15
SELECT ADVICEPLAN_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_END_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_REMARK;

---ADVICE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDOCTOR_NAME;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPEN_DATETIME;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDEPT_NAME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核人签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_ADVICE_DATETIME;

---ADVICE_CHECKNURSE_SIGN  VARCHAR2(50)  Y    核对医嘱护士签名    S1  A..50
SELECT ADVICE_CHECKNURSE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECKNURSE_SIGN;

---ADVICE_CHECK_DATETIME  DATE  Y    医嘱核对日期时间    DT  DT15
SELECT ADVICE_CHECK_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECK_DATETIME;

---ADVICE_END_DATETIME  DATE  Y    医嘱停止日期时间    DT  DT15
SELECT ADVICE_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_END_DATETIME;

---ADVICE_ENDER_SIGN  VARCHAR2(50)  Y    停止医嘱者签名    S1  A..50
SELECT ADVICE_ENDER_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ENDER_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DT15
SELECT CANCEL_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_DATETIME;

---CANCEL_ADVICE_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_ADVICE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_SIGN;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A..50
SELECT EXEC_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DT15
SELECT ADVICE_EXEC_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_DEPT_NAME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_STATUS;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY LAST_MODIFIC_TIME;

---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY PRESC_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY INPATIENT_SN;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_TYPE_CODE;

---RECIPE_GROUP_NO  VARCHAR2(50)  Y    处方药品组号    S1  N..50
SELECT RECIPE_GROUP_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY RECIPE_GROUP_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY APPLY_NO;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  应符合国标：CV06.00.229  S3  N1
SELECT ORDER_ITEM_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---ADVICEPLAN_START_DATETIME  DATE  Y    医嘱计划开始日期时间    DT  DT15
SELECT ADVICEPLAN_START_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_START_DATETIME;

---ADVICEPLAN_END_DATETIME  DATE  Y    医嘱计划结束日期时间    DT  DT15
SELECT ADVICEPLAN_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_END_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_REMARK;

---ADVICE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDOCTOR_NAME;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPEN_DATETIME;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDEPT_NAME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核人签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_ADVICE_DATETIME;

---ADVICE_CHECKNURSE_SIGN  VARCHAR2(50)  Y    核对医嘱护士签名    S1  A..50
SELECT ADVICE_CHECKNURSE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECKNURSE_SIGN;

---ADVICE_CHECK_DATETIME  DATE  Y    医嘱核对日期时间    DT  DT15
SELECT ADVICE_CHECK_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECK_DATETIME;

---ADVICE_END_DATETIME  DATE  Y    医嘱停止日期时间    DT  DT15
SELECT ADVICE_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_END_DATETIME;

---ADVICE_ENDER_SIGN  VARCHAR2(50)  Y    停止医嘱者签名    S1  A..50
SELECT ADVICE_ENDER_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ENDER_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DT15
SELECT CANCEL_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_DATETIME;

---CANCEL_ADVICE_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_ADVICE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_SIGN;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A..50
SELECT EXEC_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DT15
SELECT ADVICE_EXEC_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_DEPT_NAME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_STATUS;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY LAST_MODIFIC_TIME;

---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY PRESC_ID;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY INPATIENT_SN;

---ORDER_TYPE_CODE  NUMBER(1)      医嘱类别代码  标准值：1.长期医嘱 2.临时医嘱  9.其他  S2  N1
SELECT ORDER_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_TYPE_CODE;

---RECIPE_GROUP_NO  VARCHAR2(50)  Y    处方药品组号    S1  N..50
SELECT RECIPE_GROUP_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY RECIPE_GROUP_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY APPLY_NO;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  应符合国标：CV06.00.229  S3  N1
SELECT ORDER_ITEM_TYPE_CODE FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---ADVICEPLAN_START_DATETIME  DATE  Y    医嘱计划开始日期时间    DT  DT15
SELECT ADVICEPLAN_START_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_START_DATETIME;

---ADVICEPLAN_END_DATETIME  DATE  Y    医嘱计划结束日期时间    DT  DT15
SELECT ADVICEPLAN_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICEPLAN_END_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_REMARK;

---ADVICE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDOCTOR_NAME;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPEN_DATETIME;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_OPENDEPT_NAME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核人签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CHECK_ADVICE_DATETIME;

---ADVICE_CHECKNURSE_SIGN  VARCHAR2(50)  Y    核对医嘱护士签名    S1  A..50
SELECT ADVICE_CHECKNURSE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECKNURSE_SIGN;

---ADVICE_CHECK_DATETIME  DATE  Y    医嘱核对日期时间    DT  DT15
SELECT ADVICE_CHECK_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_CHECK_DATETIME;

---ADVICE_END_DATETIME  DATE  Y    医嘱停止日期时间    DT  DT15
SELECT ADVICE_END_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_END_DATETIME;

---ADVICE_ENDER_SIGN  VARCHAR2(50)  Y    停止医嘱者签名    S1  A..50
SELECT ADVICE_ENDER_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_ENDER_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DT15
SELECT CANCEL_ADVICE_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_DATETIME;

---CANCEL_ADVICE_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_ADVICE_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY CANCEL_ADVICE_SIGN;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A..50
SELECT EXEC_PERSON_SIGN FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DT15
SELECT ADVICE_EXEC_DATETIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY EXEC_DEPT_NAME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY ADVICE_EXEC_STATUS;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM HOSPITALIZATION_ORDER_DETAIL GROUP BY LAST_MODIFIC_TIME;

