---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM VBNC_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VBNC_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VBNC_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VBNC_RECORD GROUP BY INP_NO;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM VBNC_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM VBNC_RECORD GROUP BY EDC_DESC;

---BIRTH_DATETIME  DATE  Y    临产日期时间    DT  DT15
SELECT BIRTH_DATETIME FROM VBNC_RECORD GROUP BY BIRTH_DATETIME;

---INP_DIAG_CODE  VARCHAR2(200)  Y    入院诊断    S1  AN..200
SELECT INP_DIAG_CODE FROM VBNC_RECORD GROUP BY INP_DIAG_CODE;

---RUPTURE_MEMBRANES_DATETIME  DATE  Y    胎膜破裂日期时间    DT  DT15
SELECT RUPTURE_MEMBRANES_DATETIME FROM VBNC_RECORD GROUP BY RUPTURE_MEMBRANES_DATETIME;

---FOREWATERS_VOLUME  VARCHAR2(100)  Y    前羊水性状    S1  AN..100
SELECT FOREWATERS_VOLUME FROM VBNC_RECORD GROUP BY FOREWATERS_VOLUME;

---PAMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    前羊水量(mL)    N  N..5
SELECT PAMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY PAMNIOTIC_FLUID_VOLUME;

---FIRST_DURATION_LABOR  NUMBER(4)  Y    第1产程时长（min)    N  N..4
SELECT FIRST_DURATION_LABOR FROM VBNC_RECORD GROUP BY FIRST_DURATION_LABOR;

---PMOUTH_OPFULL_TIME  DATE  Y    宫口开全日期时间    DT  DTI 5
SELECT PMOUTH_OPFULL_TIME FROM VBNC_RECORD GROUP BY PMOUTH_OPFULL_TIME;

---BIRTHPROCESS_DURATION_DELIVERY  NUMBER(4)  Y    第2产程时长(min)    N  N..4
SELECT BIRTHPROCESS_DURATION_DELIVERY FROM VBNC_RECORD GROUP BY BIRTHPROCESS_DURATION_DELIVERY;

---FETAL_DISENGAGE_TIME  DATE  Y    胎儿娩出日期时间    DT  DTI 5
SELECT FETAL_DISENGAGE_TIME FROM VBNC_RECORD GROUP BY FETAL_DISENGAGE_TIME;

---THIRD_DURATION_LABOR  NUMBER(4)  Y    第3产程时长（min)    N  N..4
SELECT THIRD_DURATION_LABOR FROM VBNC_RECORD GROUP BY THIRD_DURATION_LABOR;

---FULL_BIRTHPROCESS_TIME  NUMBER(4)  Y    总产程时长（min)    N  N1..4
SELECT FULL_BIRTHPROCESS_TIME FROM VBNC_RECORD GROUP BY FULL_BIRTHPROCESS_TIME;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国标：WS 364.10—2011 表 7  CV05.01.007胎方位代码表  S3  N2
SELECT FETAL_POSITION_CODE FROM VBNC_RECORD GROUP BY FETAL_POSITION_CODE;

---VAGINAL_DELIVERY_CODE  VARCHAR2(5)  Y    阴道助产标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_DELIVERY_CODE FROM VBNC_RECORD GROUP BY VAGINAL_DELIVERY_CODE;

---VAGINA_DELIVERY_METHOD  VARCHAR2(100)  Y    阴道助产方式    S1  AN..100
SELECT VAGINA_DELIVERY_METHOD FROM VBNC_RECORD GROUP BY VAGINA_DELIVERY_METHOD;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量(mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM VBNC_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM VBNC_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    跻带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICAL_CORD_ABNORMALITIES  VARCHAR2(200)  Y    脐带异常情况描述    S1  AN..200
SELECT UMBILICAL_CORD_ABNORMALITIES FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_ABNORMALITIES;

---DELIVERY_DRUG  VARCHAR2(50)  Y    产时用药    S1  AN..50
SELECT DELIVERY_DRUG FROM VBNC_RECORD GROUP BY DELIVERY_DRUG;

---PREVENTIVE  VARCHAR2(200)  Y    预防措施    S1  AN..200
SELECT PREVENTIVE FROM VBNC_RECORD GROUP BY PREVENTIVE;

---MATERNALPERINEAL_INCISION_CODE  VARCHAR2(5)  Y    产妇会阴切开标志  TRUE/FALSE  L  T/F
SELECT MATERNALPERINEAL_INCISION_CODE FROM VBNC_RECORD GROUP BY MATERNALPERINEAL_INCISION_CODE;

---INCISION_LOCATION  VARCHAR2(100)  Y    会阴切开位置    S1  AN..100
SELECT INCISION_LOCATION FROM VBNC_RECORD GROUP BY INCISION_LOCATION;

---SUTURE_NEEDLE_NUMBER  NUMBER(2)  Y    产妇会阴缝合针数    N  N..2
SELECT SUTURE_NEEDLE_NUMBER FROM VBNC_RECORD GROUP BY SUTURE_NEEDLE_NUMBER;

---PERINEAL_LACERATION_CODE  NUMBER(1)  Y    会阴裂伤情况代码  应符合国标：WS 364.10—2011 表 10 CV05.01.010会阴裂伤情况代码表  S3  N1
SELECT PERINEAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY PERINEAL_LACERATION_CODE;

---PERINEAL_HEMATOMA_CODE  VARCHAR2(5)  Y    会阴血肿标志  TRUE/FALSE  L  T/F
SELECT PERINEAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY PERINEAL_HEMATOMA_CODE;

---OPERATE_MZFS_ID  NUMBER(2)  Y    麻醉方法代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT OPERATE_MZFS_ID FROM VBNC_RECORD GROUP BY OPERATE_MZFS_ID;

---ANESTH_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    S1  AN..50
SELECT ANESTH_DRUG_NAME FROM VBNC_RECORD GROUP BY ANESTH_DRUG_NAME;

---LACERATION_VAGINA_CODE  VARCHAR2(5)  Y    阴道裂伤标忐  TRUE/FALSE  L  T/F
SELECT LACERATION_VAGINA_CODE FROM VBNC_RECORD GROUP BY LACERATION_VAGINA_CODE;

---VAGINAL_HEMATOMA_CODE  VARCHAR2(5)  Y    阴道血肿标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_CODE;

---VAGINAL_HEMATOMA_SIZE  VARCHAR2(50)  Y    阴道血肿大小    S1  AN..50
SELECT VAGINAL_HEMATOMA_SIZE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_SIZE;

---TREATMENT_VAGINAL_HEMATOMA  VARCHAR2(200)  Y    阴道血肿处理    S1  AN..200
SELECT TREATMENT_VAGINAL_HEMATOMA FROM VBNC_RECORD GROUP BY TREATMENT_VAGINAL_HEMATOMA;

---CERVICAL_LACERATION_CODE  VARCHAR2(5)  Y    宫颈裂伤标志  TRUE/FALSE  L  T/F
SELECT CERVICAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY CERVICAL_LACERATION_CODE;

---CERVICAL_SUTURE  VARCHAR2(100)  Y    宫颈缝合情况    S1  AN..100
SELECT CERVICAL_SUTURE FROM VBNC_RECORD GROUP BY CERVICAL_SUTURE;

---ANAL_INVESTIGATION  VARCHAR2(100)  Y    肛查    S1  AN..100
SELECT ANAL_INVESTIGATION FROM VBNC_RECORD GROUP BY ANAL_INVESTIGATION;

---AFTER_DELIVERY_DRUG  VARCHAR2(50)  Y    产后用药    S1  AN..50
SELECT AFTER_DELIVERY_DRUG FROM VBNC_RECORD GROUP BY AFTER_DELIVERY_DRUG;

---DELIVERY_SPECIAL_CONDITION  VARCHAR2(200)  Y    分娩过程特殊情况描述    S1  AN..200
SELECT DELIVERY_SPECIAL_CONDITION FROM VBNC_RECORD GROUP BY DELIVERY_SPECIAL_CONDITION;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM VBNC_RECORD GROUP BY CONTRACTIONS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM VBNC_RECORD GROUP BY UTERINE_CONDITIONS;

---ELU_STATUS  VARCHAR2(100)  Y    恶露状况    S1  AN..100
SELECT ELU_STATUS FROM VBNC_RECORD GROUP BY ELU_STATUS;

---REPAIR_PROCEDURE  VARCHAR2(100)  Y    修补手术过程    S1  AN..100
SELECT REPAIR_PROCEDURE FROM VBNC_RECORD GROUP BY REPAIR_PROCEDURE;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM VBNC_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---AFTDELIVERY_ICD_CODE  VARCHAR2(200)  Y    产后诊断    S1  AN..200
SELECT AFTDELIVERY_ICD_CODE FROM VBNC_RECORD GROUP BY AFTDELIVERY_ICD_CODE;

---POSTPARTUM_OBSERVATION_TIME  DATE  Y    产后观察日期时间    DT  DT15
SELECT POSTPARTUM_OBSERVATION_TIME FROM VBNC_RECORD GROUP BY POSTPARTUM_OBSERVATION_TIME;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    产后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM VBNC_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    产后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM VBNC_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    产后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM VBNC_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    产后脉搏（次/min）    . N  N2..3
SELECT PULSE FROM VBNC_RECORD GROUP BY PULSE;

---POSTPARTUM_HEART_RATE  NUMBER(3)  Y    产后心率（次/min）    N  N2..3
SELECT POSTPARTUM_HEART_RATE FROM VBNC_RECORD GROUP BY POSTPARTUM_HEART_RATE;

---BLOOD_LOSSED  NUMBER(5)  Y    产后出血量（mL)    N  N..5
SELECT BLOOD_LOSSED FROM VBNC_RECORD GROUP BY BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    产后宫缩    S1  AN.. 200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    产后宫底高度（cm）    N  N3..4,l
SELECT POSTPARTUM_UTERINE_HEIGHT FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---POSTPARTUM_BLADDER_FILLING  VARCHAR2(5)  Y    产后膀胱充盈标志  TRUE/FALSE  L  T/F
SELECT POSTPARTUM_BLADDER_FILLING FROM VBNC_RECORD GROUP BY POSTPARTUM_BLADDER_FILLING;

---NEWBORN_SEX  NUMBER(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM VBNC_RECORD GROUP BY NEWBORN_SEX;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身高（cm）    N  N4..5.1
SELECT NEWBORN_HEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM VBNC_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN..100
SELECT TUMOR_LOCATION FROM VBNC_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  NUMBER(1)  Y    Apgar评分间隔时间代码  标准值：
l、lmin
2、5min 
3、10mia  S2  N1
SELECT APGAR_CODE FROM VBNC_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM VBNC_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  NUMBER(1)  Y    分娩结局代码  标准值：1.活产  2.死胎  3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM VBNC_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  NUMBER(1)  Y    新生儿异常情况代码  应符合国标：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM VBNC_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---MIDWIVES_SIGN  VARCHAR2(50)  Y    接生人员签名    S1  A..50
SELECT MIDWIVES_SIGN FROM VBNC_RECORD GROUP BY MIDWIVES_SIGN;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生签名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM VBNC_RECORD GROUP BY OPERATION_DOCTOR_NAME;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM VBNC_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM VBNC_RECORD GROUP BY RECORD_SIGN;

---SIGNATURE_OF_MIDWIFE  VARCHAR2(50)  Y    助产者签名      
SELECT SIGNATURE_OF_MIDWIFE FROM VBNC_RECORD GROUP BY SIGNATURE_OF_MIDWIFE;

---ASSISTANT_SIGNATURE  VARCHAR2(50)  Y    助手签名      
SELECT ASSISTANT_SIGNATURE FROM VBNC_RECORD GROUP BY ASSISTANT_SIGNATURE;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM VBNC_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---INSTRUCTOR_SIGNATURE  VARCHAR2(50)  Y    指导者签名      
SELECT INSTRUCTOR_SIGNATURE FROM VBNC_RECORD GROUP BY INSTRUCTOR_SIGNATURE;

---UMBILICAL_ANOMALIES  VARCHAR2(5)  Y    脐带异常情况标志      
SELECT UMBILICAL_ANOMALIES FROM VBNC_RECORD GROUP BY UMBILICAL_ANOMALIES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VBNC_RECORD GROUP BY LAST_MODIFIC_TIME;

---CONTRACTIONS_STARTED_DATETIME  DATE  Y    宫缩开始时间日期      
SELECT CONTRACTIONS_STARTED_DATETIME FROM VBNC_RECORD GROUP BY CONTRACTIONS_STARTED_DATETIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM VBNC_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VBNC_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VBNC_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VBNC_RECORD GROUP BY INP_NO;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM VBNC_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM VBNC_RECORD GROUP BY EDC_DESC;

---BIRTH_DATETIME  DATE  Y    临产日期时间    DT  DT15
SELECT BIRTH_DATETIME FROM VBNC_RECORD GROUP BY BIRTH_DATETIME;

---INP_DIAG_CODE  VARCHAR2(200)  Y    入院诊断    S1  AN..200
SELECT INP_DIAG_CODE FROM VBNC_RECORD GROUP BY INP_DIAG_CODE;

---RUPTURE_MEMBRANES_DATETIME  DATE  Y    胎膜破裂日期时间    DT  DT15
SELECT RUPTURE_MEMBRANES_DATETIME FROM VBNC_RECORD GROUP BY RUPTURE_MEMBRANES_DATETIME;

---FOREWATERS_VOLUME  VARCHAR2(100)  Y    前羊水性状    S1  AN..100
SELECT FOREWATERS_VOLUME FROM VBNC_RECORD GROUP BY FOREWATERS_VOLUME;

---PAMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    前羊水量(mL)    N  N..5
SELECT PAMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY PAMNIOTIC_FLUID_VOLUME;

---FIRST_DURATION_LABOR  NUMBER(4)  Y    第1产程时长（min)    N  N..4
SELECT FIRST_DURATION_LABOR FROM VBNC_RECORD GROUP BY FIRST_DURATION_LABOR;

---PMOUTH_OPFULL_TIME  DATE  Y    宫口开全日期时间    DT  DTI 5
SELECT PMOUTH_OPFULL_TIME FROM VBNC_RECORD GROUP BY PMOUTH_OPFULL_TIME;

---BIRTHPROCESS_DURATION_DELIVERY  NUMBER(4)  Y    第2产程时长(min)    N  N..4
SELECT BIRTHPROCESS_DURATION_DELIVERY FROM VBNC_RECORD GROUP BY BIRTHPROCESS_DURATION_DELIVERY;

---FETAL_DISENGAGE_TIME  DATE  Y    胎儿娩出日期时间    DT  DTI 5
SELECT FETAL_DISENGAGE_TIME FROM VBNC_RECORD GROUP BY FETAL_DISENGAGE_TIME;

---THIRD_DURATION_LABOR  NUMBER(4)  Y    第3产程时长（min)    N  N..4
SELECT THIRD_DURATION_LABOR FROM VBNC_RECORD GROUP BY THIRD_DURATION_LABOR;

---FULL_BIRTHPROCESS_TIME  NUMBER(4)  Y    总产程时长（min)    N  N1..4
SELECT FULL_BIRTHPROCESS_TIME FROM VBNC_RECORD GROUP BY FULL_BIRTHPROCESS_TIME;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国标：WS 364.10—2011 表 7  CV05.01.007胎方位代码表  S3  N2
SELECT FETAL_POSITION_CODE FROM VBNC_RECORD GROUP BY FETAL_POSITION_CODE;

---VAGINAL_DELIVERY_CODE  VARCHAR2(5)  Y    阴道助产标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_DELIVERY_CODE FROM VBNC_RECORD GROUP BY VAGINAL_DELIVERY_CODE;

---VAGINA_DELIVERY_METHOD  VARCHAR2(100)  Y    阴道助产方式    S1  AN..100
SELECT VAGINA_DELIVERY_METHOD FROM VBNC_RECORD GROUP BY VAGINA_DELIVERY_METHOD;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量(mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM VBNC_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM VBNC_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    跻带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICAL_CORD_ABNORMALITIES  VARCHAR2(200)  Y    脐带异常情况描述    S1  AN..200
SELECT UMBILICAL_CORD_ABNORMALITIES FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_ABNORMALITIES;

---DELIVERY_DRUG  VARCHAR2(50)  Y    产时用药    S1  AN..50
SELECT DELIVERY_DRUG FROM VBNC_RECORD GROUP BY DELIVERY_DRUG;

---PREVENTIVE  VARCHAR2(200)  Y    预防措施    S1  AN..200
SELECT PREVENTIVE FROM VBNC_RECORD GROUP BY PREVENTIVE;

---MATERNALPERINEAL_INCISION_CODE  VARCHAR2(5)  Y    产妇会阴切开标志  TRUE/FALSE  L  T/F
SELECT MATERNALPERINEAL_INCISION_CODE FROM VBNC_RECORD GROUP BY MATERNALPERINEAL_INCISION_CODE;

---INCISION_LOCATION  VARCHAR2(100)  Y    会阴切开位置    S1  AN..100
SELECT INCISION_LOCATION FROM VBNC_RECORD GROUP BY INCISION_LOCATION;

---SUTURE_NEEDLE_NUMBER  NUMBER(2)  Y    产妇会阴缝合针数    N  N..2
SELECT SUTURE_NEEDLE_NUMBER FROM VBNC_RECORD GROUP BY SUTURE_NEEDLE_NUMBER;

---PERINEAL_LACERATION_CODE  NUMBER(1)  Y    会阴裂伤情况代码  应符合国标：WS 364.10—2011 表 10 CV05.01.010会阴裂伤情况代码表  S3  N1
SELECT PERINEAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY PERINEAL_LACERATION_CODE;

---PERINEAL_HEMATOMA_CODE  VARCHAR2(5)  Y    会阴血肿标志  TRUE/FALSE  L  T/F
SELECT PERINEAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY PERINEAL_HEMATOMA_CODE;

---OPERATE_MZFS_ID  NUMBER(2)  Y    麻醉方法代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT OPERATE_MZFS_ID FROM VBNC_RECORD GROUP BY OPERATE_MZFS_ID;

---ANESTH_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    S1  AN..50
SELECT ANESTH_DRUG_NAME FROM VBNC_RECORD GROUP BY ANESTH_DRUG_NAME;

---LACERATION_VAGINA_CODE  VARCHAR2(5)  Y    阴道裂伤标忐  TRUE/FALSE  L  T/F
SELECT LACERATION_VAGINA_CODE FROM VBNC_RECORD GROUP BY LACERATION_VAGINA_CODE;

---VAGINAL_HEMATOMA_CODE  VARCHAR2(5)  Y    阴道血肿标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_CODE;

---VAGINAL_HEMATOMA_SIZE  VARCHAR2(50)  Y    阴道血肿大小    S1  AN..50
SELECT VAGINAL_HEMATOMA_SIZE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_SIZE;

---TREATMENT_VAGINAL_HEMATOMA  VARCHAR2(200)  Y    阴道血肿处理    S1  AN..200
SELECT TREATMENT_VAGINAL_HEMATOMA FROM VBNC_RECORD GROUP BY TREATMENT_VAGINAL_HEMATOMA;

---CERVICAL_LACERATION_CODE  VARCHAR2(5)  Y    宫颈裂伤标志  TRUE/FALSE  L  T/F
SELECT CERVICAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY CERVICAL_LACERATION_CODE;

---CERVICAL_SUTURE  VARCHAR2(100)  Y    宫颈缝合情况    S1  AN..100
SELECT CERVICAL_SUTURE FROM VBNC_RECORD GROUP BY CERVICAL_SUTURE;

---ANAL_INVESTIGATION  VARCHAR2(100)  Y    肛查    S1  AN..100
SELECT ANAL_INVESTIGATION FROM VBNC_RECORD GROUP BY ANAL_INVESTIGATION;

---AFTER_DELIVERY_DRUG  VARCHAR2(50)  Y    产后用药    S1  AN..50
SELECT AFTER_DELIVERY_DRUG FROM VBNC_RECORD GROUP BY AFTER_DELIVERY_DRUG;

---DELIVERY_SPECIAL_CONDITION  VARCHAR2(200)  Y    分娩过程特殊情况描述    S1  AN..200
SELECT DELIVERY_SPECIAL_CONDITION FROM VBNC_RECORD GROUP BY DELIVERY_SPECIAL_CONDITION;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM VBNC_RECORD GROUP BY CONTRACTIONS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM VBNC_RECORD GROUP BY UTERINE_CONDITIONS;

---ELU_STATUS  VARCHAR2(100)  Y    恶露状况    S1  AN..100
SELECT ELU_STATUS FROM VBNC_RECORD GROUP BY ELU_STATUS;

---REPAIR_PROCEDURE  VARCHAR2(100)  Y    修补手术过程    S1  AN..100
SELECT REPAIR_PROCEDURE FROM VBNC_RECORD GROUP BY REPAIR_PROCEDURE;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM VBNC_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---AFTDELIVERY_ICD_CODE  VARCHAR2(200)  Y    产后诊断    S1  AN..200
SELECT AFTDELIVERY_ICD_CODE FROM VBNC_RECORD GROUP BY AFTDELIVERY_ICD_CODE;

---POSTPARTUM_OBSERVATION_TIME  DATE  Y    产后观察日期时间    DT  DT15
SELECT POSTPARTUM_OBSERVATION_TIME FROM VBNC_RECORD GROUP BY POSTPARTUM_OBSERVATION_TIME;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    产后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM VBNC_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    产后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM VBNC_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    产后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM VBNC_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    产后脉搏（次/min）    . N  N2..3
SELECT PULSE FROM VBNC_RECORD GROUP BY PULSE;

---POSTPARTUM_HEART_RATE  NUMBER(3)  Y    产后心率（次/min）    N  N2..3
SELECT POSTPARTUM_HEART_RATE FROM VBNC_RECORD GROUP BY POSTPARTUM_HEART_RATE;

---BLOOD_LOSSED  NUMBER(5)  Y    产后出血量（mL)    N  N..5
SELECT BLOOD_LOSSED FROM VBNC_RECORD GROUP BY BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    产后宫缩    S1  AN.. 200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    产后宫底高度（cm）    N  N3..4,l
SELECT POSTPARTUM_UTERINE_HEIGHT FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---POSTPARTUM_BLADDER_FILLING  VARCHAR2(5)  Y    产后膀胱充盈标志  TRUE/FALSE  L  T/F
SELECT POSTPARTUM_BLADDER_FILLING FROM VBNC_RECORD GROUP BY POSTPARTUM_BLADDER_FILLING;

---NEWBORN_SEX  NUMBER(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM VBNC_RECORD GROUP BY NEWBORN_SEX;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身高（cm）    N  N4..5.1
SELECT NEWBORN_HEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM VBNC_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN..100
SELECT TUMOR_LOCATION FROM VBNC_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  NUMBER(1)  Y    Apgar评分间隔时间代码  标准值：
l、lmin
2、5min 
3、10mia  S2  N1
SELECT APGAR_CODE FROM VBNC_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM VBNC_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  NUMBER(1)  Y    分娩结局代码  标准值：1.活产  2.死胎  3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM VBNC_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  NUMBER(1)  Y    新生儿异常情况代码  应符合国标：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM VBNC_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---MIDWIVES_SIGN  VARCHAR2(50)  Y    接生人员签名    S1  A..50
SELECT MIDWIVES_SIGN FROM VBNC_RECORD GROUP BY MIDWIVES_SIGN;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生签名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM VBNC_RECORD GROUP BY OPERATION_DOCTOR_NAME;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM VBNC_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM VBNC_RECORD GROUP BY RECORD_SIGN;

---SIGNATURE_OF_MIDWIFE  VARCHAR2(50)  Y    助产者签名      
SELECT SIGNATURE_OF_MIDWIFE FROM VBNC_RECORD GROUP BY SIGNATURE_OF_MIDWIFE;

---ASSISTANT_SIGNATURE  VARCHAR2(50)  Y    助手签名      
SELECT ASSISTANT_SIGNATURE FROM VBNC_RECORD GROUP BY ASSISTANT_SIGNATURE;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM VBNC_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---INSTRUCTOR_SIGNATURE  VARCHAR2(50)  Y    指导者签名      
SELECT INSTRUCTOR_SIGNATURE FROM VBNC_RECORD GROUP BY INSTRUCTOR_SIGNATURE;

---UMBILICAL_ANOMALIES  VARCHAR2(5)  Y    脐带异常情况标志      
SELECT UMBILICAL_ANOMALIES FROM VBNC_RECORD GROUP BY UMBILICAL_ANOMALIES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VBNC_RECORD GROUP BY LAST_MODIFIC_TIME;

---CONTRACTIONS_STARTED_DATETIME  DATE  Y    宫缩开始时间日期      
SELECT CONTRACTIONS_STARTED_DATETIME FROM VBNC_RECORD GROUP BY CONTRACTIONS_STARTED_DATETIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM VBNC_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VBNC_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VBNC_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VBNC_RECORD GROUP BY INP_NO;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM VBNC_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM VBNC_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM VBNC_RECORD GROUP BY EDC_DESC;

---BIRTH_DATETIME  DATE  Y    临产日期时间    DT  DT15
SELECT BIRTH_DATETIME FROM VBNC_RECORD GROUP BY BIRTH_DATETIME;

---INP_DIAG_CODE  VARCHAR2(200)  Y    入院诊断    S1  AN..200
SELECT INP_DIAG_CODE FROM VBNC_RECORD GROUP BY INP_DIAG_CODE;

---RUPTURE_MEMBRANES_DATETIME  DATE  Y    胎膜破裂日期时间    DT  DT15
SELECT RUPTURE_MEMBRANES_DATETIME FROM VBNC_RECORD GROUP BY RUPTURE_MEMBRANES_DATETIME;

---FOREWATERS_VOLUME  VARCHAR2(100)  Y    前羊水性状    S1  AN..100
SELECT FOREWATERS_VOLUME FROM VBNC_RECORD GROUP BY FOREWATERS_VOLUME;

---PAMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    前羊水量(mL)    N  N..5
SELECT PAMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY PAMNIOTIC_FLUID_VOLUME;

---FIRST_DURATION_LABOR  NUMBER(4)  Y    第1产程时长（min)    N  N..4
SELECT FIRST_DURATION_LABOR FROM VBNC_RECORD GROUP BY FIRST_DURATION_LABOR;

---PMOUTH_OPFULL_TIME  DATE  Y    宫口开全日期时间    DT  DTI 5
SELECT PMOUTH_OPFULL_TIME FROM VBNC_RECORD GROUP BY PMOUTH_OPFULL_TIME;

---BIRTHPROCESS_DURATION_DELIVERY  NUMBER(4)  Y    第2产程时长(min)    N  N..4
SELECT BIRTHPROCESS_DURATION_DELIVERY FROM VBNC_RECORD GROUP BY BIRTHPROCESS_DURATION_DELIVERY;

---FETAL_DISENGAGE_TIME  DATE  Y    胎儿娩出日期时间    DT  DTI 5
SELECT FETAL_DISENGAGE_TIME FROM VBNC_RECORD GROUP BY FETAL_DISENGAGE_TIME;

---THIRD_DURATION_LABOR  NUMBER(4)  Y    第3产程时长（min)    N  N..4
SELECT THIRD_DURATION_LABOR FROM VBNC_RECORD GROUP BY THIRD_DURATION_LABOR;

---FULL_BIRTHPROCESS_TIME  NUMBER(4)  Y    总产程时长（min)    N  N1..4
SELECT FULL_BIRTHPROCESS_TIME FROM VBNC_RECORD GROUP BY FULL_BIRTHPROCESS_TIME;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国标：WS 364.10—2011 表 7  CV05.01.007胎方位代码表  S3  N2
SELECT FETAL_POSITION_CODE FROM VBNC_RECORD GROUP BY FETAL_POSITION_CODE;

---VAGINAL_DELIVERY_CODE  VARCHAR2(5)  Y    阴道助产标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_DELIVERY_CODE FROM VBNC_RECORD GROUP BY VAGINAL_DELIVERY_CODE;

---VAGINA_DELIVERY_METHOD  VARCHAR2(100)  Y    阴道助产方式    S1  AN..100
SELECT VAGINA_DELIVERY_METHOD FROM VBNC_RECORD GROUP BY VAGINA_DELIVERY_METHOD;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量(mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM VBNC_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM VBNC_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM VBNC_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM VBNC_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    跻带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICAL_CORD_ABNORMALITIES  VARCHAR2(200)  Y    脐带异常情况描述    S1  AN..200
SELECT UMBILICAL_CORD_ABNORMALITIES FROM VBNC_RECORD GROUP BY UMBILICAL_CORD_ABNORMALITIES;

---DELIVERY_DRUG  VARCHAR2(50)  Y    产时用药    S1  AN..50
SELECT DELIVERY_DRUG FROM VBNC_RECORD GROUP BY DELIVERY_DRUG;

---PREVENTIVE  VARCHAR2(200)  Y    预防措施    S1  AN..200
SELECT PREVENTIVE FROM VBNC_RECORD GROUP BY PREVENTIVE;

---MATERNALPERINEAL_INCISION_CODE  VARCHAR2(5)  Y    产妇会阴切开标志  TRUE/FALSE  L  T/F
SELECT MATERNALPERINEAL_INCISION_CODE FROM VBNC_RECORD GROUP BY MATERNALPERINEAL_INCISION_CODE;

---INCISION_LOCATION  VARCHAR2(100)  Y    会阴切开位置    S1  AN..100
SELECT INCISION_LOCATION FROM VBNC_RECORD GROUP BY INCISION_LOCATION;

---SUTURE_NEEDLE_NUMBER  NUMBER(2)  Y    产妇会阴缝合针数    N  N..2
SELECT SUTURE_NEEDLE_NUMBER FROM VBNC_RECORD GROUP BY SUTURE_NEEDLE_NUMBER;

---PERINEAL_LACERATION_CODE  NUMBER(1)  Y    会阴裂伤情况代码  应符合国标：WS 364.10—2011 表 10 CV05.01.010会阴裂伤情况代码表  S3  N1
SELECT PERINEAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY PERINEAL_LACERATION_CODE;

---PERINEAL_HEMATOMA_CODE  VARCHAR2(5)  Y    会阴血肿标志  TRUE/FALSE  L  T/F
SELECT PERINEAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY PERINEAL_HEMATOMA_CODE;

---OPERATE_MZFS_ID  NUMBER(2)  Y    麻醉方法代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT OPERATE_MZFS_ID FROM VBNC_RECORD GROUP BY OPERATE_MZFS_ID;

---ANESTH_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    S1  AN..50
SELECT ANESTH_DRUG_NAME FROM VBNC_RECORD GROUP BY ANESTH_DRUG_NAME;

---LACERATION_VAGINA_CODE  VARCHAR2(5)  Y    阴道裂伤标忐  TRUE/FALSE  L  T/F
SELECT LACERATION_VAGINA_CODE FROM VBNC_RECORD GROUP BY LACERATION_VAGINA_CODE;

---VAGINAL_HEMATOMA_CODE  VARCHAR2(5)  Y    阴道血肿标志  TRUE/FALSE  L  T/F
SELECT VAGINAL_HEMATOMA_CODE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_CODE;

---VAGINAL_HEMATOMA_SIZE  VARCHAR2(50)  Y    阴道血肿大小    S1  AN..50
SELECT VAGINAL_HEMATOMA_SIZE FROM VBNC_RECORD GROUP BY VAGINAL_HEMATOMA_SIZE;

---TREATMENT_VAGINAL_HEMATOMA  VARCHAR2(200)  Y    阴道血肿处理    S1  AN..200
SELECT TREATMENT_VAGINAL_HEMATOMA FROM VBNC_RECORD GROUP BY TREATMENT_VAGINAL_HEMATOMA;

---CERVICAL_LACERATION_CODE  VARCHAR2(5)  Y    宫颈裂伤标志  TRUE/FALSE  L  T/F
SELECT CERVICAL_LACERATION_CODE FROM VBNC_RECORD GROUP BY CERVICAL_LACERATION_CODE;

---CERVICAL_SUTURE  VARCHAR2(100)  Y    宫颈缝合情况    S1  AN..100
SELECT CERVICAL_SUTURE FROM VBNC_RECORD GROUP BY CERVICAL_SUTURE;

---ANAL_INVESTIGATION  VARCHAR2(100)  Y    肛查    S1  AN..100
SELECT ANAL_INVESTIGATION FROM VBNC_RECORD GROUP BY ANAL_INVESTIGATION;

---AFTER_DELIVERY_DRUG  VARCHAR2(50)  Y    产后用药    S1  AN..50
SELECT AFTER_DELIVERY_DRUG FROM VBNC_RECORD GROUP BY AFTER_DELIVERY_DRUG;

---DELIVERY_SPECIAL_CONDITION  VARCHAR2(200)  Y    分娩过程特殊情况描述    S1  AN..200
SELECT DELIVERY_SPECIAL_CONDITION FROM VBNC_RECORD GROUP BY DELIVERY_SPECIAL_CONDITION;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM VBNC_RECORD GROUP BY CONTRACTIONS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM VBNC_RECORD GROUP BY UTERINE_CONDITIONS;

---ELU_STATUS  VARCHAR2(100)  Y    恶露状况    S1  AN..100
SELECT ELU_STATUS FROM VBNC_RECORD GROUP BY ELU_STATUS;

---REPAIR_PROCEDURE  VARCHAR2(100)  Y    修补手术过程    S1  AN..100
SELECT REPAIR_PROCEDURE FROM VBNC_RECORD GROUP BY REPAIR_PROCEDURE;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM VBNC_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---AFTDELIVERY_ICD_CODE  VARCHAR2(200)  Y    产后诊断    S1  AN..200
SELECT AFTDELIVERY_ICD_CODE FROM VBNC_RECORD GROUP BY AFTDELIVERY_ICD_CODE;

---POSTPARTUM_OBSERVATION_TIME  DATE  Y    产后观察日期时间    DT  DT15
SELECT POSTPARTUM_OBSERVATION_TIME FROM VBNC_RECORD GROUP BY POSTPARTUM_OBSERVATION_TIME;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    产后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM VBNC_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    产后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM VBNC_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    产后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM VBNC_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    产后脉搏（次/min）    . N  N2..3
SELECT PULSE FROM VBNC_RECORD GROUP BY PULSE;

---POSTPARTUM_HEART_RATE  NUMBER(3)  Y    产后心率（次/min）    N  N2..3
SELECT POSTPARTUM_HEART_RATE FROM VBNC_RECORD GROUP BY POSTPARTUM_HEART_RATE;

---BLOOD_LOSSED  NUMBER(5)  Y    产后出血量（mL)    N  N..5
SELECT BLOOD_LOSSED FROM VBNC_RECORD GROUP BY BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    产后宫缩    S1  AN.. 200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    产后宫底高度（cm）    N  N3..4,l
SELECT POSTPARTUM_UTERINE_HEIGHT FROM VBNC_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---POSTPARTUM_BLADDER_FILLING  VARCHAR2(5)  Y    产后膀胱充盈标志  TRUE/FALSE  L  T/F
SELECT POSTPARTUM_BLADDER_FILLING FROM VBNC_RECORD GROUP BY POSTPARTUM_BLADDER_FILLING;

---NEWBORN_SEX  NUMBER(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM VBNC_RECORD GROUP BY NEWBORN_SEX;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身高（cm）    N  N4..5.1
SELECT NEWBORN_HEIGHT FROM VBNC_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM VBNC_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN..100
SELECT TUMOR_LOCATION FROM VBNC_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  NUMBER(1)  Y    Apgar评分间隔时间代码  标准值：
l、lmin
2、5min 
3、10mia  S2  N1
SELECT APGAR_CODE FROM VBNC_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM VBNC_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  NUMBER(1)  Y    分娩结局代码  标准值：1.活产  2.死胎  3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM VBNC_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  NUMBER(1)  Y    新生儿异常情况代码  应符合国标：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM VBNC_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---MIDWIVES_SIGN  VARCHAR2(50)  Y    接生人员签名    S1  A..50
SELECT MIDWIVES_SIGN FROM VBNC_RECORD GROUP BY MIDWIVES_SIGN;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生签名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM VBNC_RECORD GROUP BY OPERATION_DOCTOR_NAME;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM VBNC_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM VBNC_RECORD GROUP BY RECORD_SIGN;

---SIGNATURE_OF_MIDWIFE  VARCHAR2(50)  Y    助产者签名      
SELECT SIGNATURE_OF_MIDWIFE FROM VBNC_RECORD GROUP BY SIGNATURE_OF_MIDWIFE;

---ASSISTANT_SIGNATURE  VARCHAR2(50)  Y    助手签名      
SELECT ASSISTANT_SIGNATURE FROM VBNC_RECORD GROUP BY ASSISTANT_SIGNATURE;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM VBNC_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---INSTRUCTOR_SIGNATURE  VARCHAR2(50)  Y    指导者签名      
SELECT INSTRUCTOR_SIGNATURE FROM VBNC_RECORD GROUP BY INSTRUCTOR_SIGNATURE;

---UMBILICAL_ANOMALIES  VARCHAR2(5)  Y    脐带异常情况标志      
SELECT UMBILICAL_ANOMALIES FROM VBNC_RECORD GROUP BY UMBILICAL_ANOMALIES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VBNC_RECORD GROUP BY LAST_MODIFIC_TIME;

---CONTRACTIONS_STARTED_DATETIME  DATE  Y    宫缩开始时间日期      
SELECT CONTRACTIONS_STARTED_DATETIME FROM VBNC_RECORD GROUP BY CONTRACTIONS_STARTED_DATETIME;

