---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CRITICALLY_ILL_NOTICE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CRITICALLY_ILL_NOTICE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INFORMED_CONSENT_NO;

---CONDITION_EMERGENCY_MEASURES  VARCHAR2(2000)  Y    病情概括及主要抢救措施    S1  AN..2000
SELECT CONDITION_EMERGENCY_MEASURES FROM CRITICALLY_ILL_NOTICE GROUP BY CONDITION_EMERGENCY_MEASURES;

---CRITICAL_ILLNESS_CONTENT  VARCHAR2(2000)  Y    病危（重）通知内容    S1  AN..1000
SELECT CRITICAL_ILLNESS_CONTENT FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_CONTENT;

---CRITICAL_ILLNESS_DATETIME  DATE  Y    病危（重）通知日期时间    DT  DT15
SELECT CRITICAL_ILLNESS_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_DATETIME;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM CRITICALLY_ILL_NOTICE GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CRITICALLY_ILL_NOTICE GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CRITICALLY_ILL_NOTICE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CRITICALLY_ILL_NOTICE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INFORMED_CONSENT_NO;

---CONDITION_EMERGENCY_MEASURES  VARCHAR2(2000)  Y    病情概括及主要抢救措施    S1  AN..2000
SELECT CONDITION_EMERGENCY_MEASURES FROM CRITICALLY_ILL_NOTICE GROUP BY CONDITION_EMERGENCY_MEASURES;

---CRITICAL_ILLNESS_CONTENT  VARCHAR2(2000)  Y    病危（重）通知内容    S1  AN..1000
SELECT CRITICAL_ILLNESS_CONTENT FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_CONTENT;

---CRITICAL_ILLNESS_DATETIME  DATE  Y    病危（重）通知日期时间    DT  DT15
SELECT CRITICAL_ILLNESS_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_DATETIME;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM CRITICALLY_ILL_NOTICE GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CRITICALLY_ILL_NOTICE GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CRITICALLY_ILL_NOTICE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CRITICALLY_ILL_NOTICE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CRITICALLY_ILL_NOTICE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CRITICALLY_ILL_NOTICE GROUP BY INFORMED_CONSENT_NO;

---CONDITION_EMERGENCY_MEASURES  VARCHAR2(2000)  Y    病情概括及主要抢救措施    S1  AN..2000
SELECT CONDITION_EMERGENCY_MEASURES FROM CRITICALLY_ILL_NOTICE GROUP BY CONDITION_EMERGENCY_MEASURES;

---CRITICAL_ILLNESS_CONTENT  VARCHAR2(2000)  Y    病危（重）通知内容    S1  AN..1000
SELECT CRITICAL_ILLNESS_CONTENT FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_CONTENT;

---CRITICAL_ILLNESS_DATETIME  DATE  Y    病危（重）通知日期时间    DT  DT15
SELECT CRITICAL_ILLNESS_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY CRITICAL_ILLNESS_DATETIME;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM CRITICALLY_ILL_NOTICE GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM CRITICALLY_ILL_NOTICE GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CRITICALLY_ILL_NOTICE GROUP BY LAST_MODIFIC_TIME;

