---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ANESTHESIA_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM ANESTHESIA_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM ANESTHESIA_RECORDS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN.. 18
SELECT INP_NO FROM ANESTHESIA_RECORDS GROUP BY INP_NO;

---DIAGNOSE_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAGNOSE_DESC FROM ANESTHESIA_RECORDS GROUP BY DIAGNOSE_DESC;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOOD_TRANSFUSION_VARIETY_CODE  NUMBER(2)  Y    输血品种代码    S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM ANESTHESIA_RECORDS GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOODTRANSFERED_REACTION_CODE;

---OPERATE_INFUSION_ITEM  VARCHAR2(50)  Y    术中输液项目    S1  AN..50
SELECT OPERATE_INFUSION_ITEM FROM ANESTHESIA_RECORDS GROUP BY OPERATE_INFUSION_ITEM;

---OPERATION_BLEEDING  NUMBER(5)  Y    出血量（mL)    N  N..5
SELECT OPERATION_BLEEDING FROM ANESTHESIA_RECORDS GROUP BY OPERATION_BLEEDING;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(1)  Y    患者去向代码    S3  N1
SELECT PATIENT_WHEREABOUTS_CODE FROM ANESTHESIA_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM ANESTHESIA_RECORDS GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ANESTHESIA_RECORDS GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）      
SELECT OPER_REQ_SN FROM ANESTHESIA_RECORDS GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ANESTHESIA_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ANESTHESIA_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM ANESTHESIA_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM ANESTHESIA_RECORDS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN.. 18
SELECT INP_NO FROM ANESTHESIA_RECORDS GROUP BY INP_NO;

---DIAGNOSE_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAGNOSE_DESC FROM ANESTHESIA_RECORDS GROUP BY DIAGNOSE_DESC;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOOD_TRANSFUSION_VARIETY_CODE  NUMBER(2)  Y    输血品种代码    S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM ANESTHESIA_RECORDS GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOODTRANSFERED_REACTION_CODE;

---OPERATE_INFUSION_ITEM  VARCHAR2(50)  Y    术中输液项目    S1  AN..50
SELECT OPERATE_INFUSION_ITEM FROM ANESTHESIA_RECORDS GROUP BY OPERATE_INFUSION_ITEM;

---OPERATION_BLEEDING  NUMBER(5)  Y    出血量（mL)    N  N..5
SELECT OPERATION_BLEEDING FROM ANESTHESIA_RECORDS GROUP BY OPERATION_BLEEDING;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(1)  Y    患者去向代码    S3  N1
SELECT PATIENT_WHEREABOUTS_CODE FROM ANESTHESIA_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM ANESTHESIA_RECORDS GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ANESTHESIA_RECORDS GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）      
SELECT OPER_REQ_SN FROM ANESTHESIA_RECORDS GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ANESTHESIA_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM ANESTHESIA_RECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ANESTHESIA_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM ANESTHESIA_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM ANESTHESIA_RECORDS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN.. 18
SELECT INP_NO FROM ANESTHESIA_RECORDS GROUP BY INP_NO;

---DIAGNOSE_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAGNOSE_DESC FROM ANESTHESIA_RECORDS GROUP BY DIAGNOSE_DESC;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOOD_TRANSFUSION_VARIETY_CODE  NUMBER(2)  Y    输血品种代码    S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM ANESTHESIA_RECORDS GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM ANESTHESIA_RECORDS GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM ANESTHESIA_RECORDS GROUP BY BLOODTRANSFERED_REACTION_CODE;

---OPERATE_INFUSION_ITEM  VARCHAR2(50)  Y    术中输液项目    S1  AN..50
SELECT OPERATE_INFUSION_ITEM FROM ANESTHESIA_RECORDS GROUP BY OPERATE_INFUSION_ITEM;

---OPERATION_BLEEDING  NUMBER(5)  Y    出血量（mL)    N  N..5
SELECT OPERATION_BLEEDING FROM ANESTHESIA_RECORDS GROUP BY OPERATION_BLEEDING;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(1)  Y    患者去向代码    S3  N1
SELECT PATIENT_WHEREABOUTS_CODE FROM ANESTHESIA_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM ANESTHESIA_RECORDS GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ANESTHESIA_RECORDS GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）      
SELECT OPER_REQ_SN FROM ANESTHESIA_RECORDS GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ANESTHESIA_RECORDS GROUP BY LAST_MODIFIC_TIME;

