---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  
SELECT INPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  AN..18
SELECT OUTP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  AN..18
SELECT INP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    null  AN..20
SELECT INFORMED_CONSENT_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INFORMED_CONSENT_NO;

---SPEICAL_EXAMTREAT_ITEM  VARCHAR2(100)  Y    特殊检查及特殊治疗项目名称    null  AN..100
SELECT SPEICAL_EXAMTREAT_ITEM FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEICAL_EXAMTREAT_ITEM;

---SPECIAL_INSPEC_SPEC_TREAT  VARCHAR2(100)  Y    特殊检查及特殊治疗目的    null  A..100
SELECT SPECIAL_INSPEC_SPEC_TREAT FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPECIAL_INSPEC_SPEC_TREAT;

---SPEXAMINATIONS_SPTREAT_COMPL  VARCHAR2(1000)  Y    特殊检查及特殊治疗可能引起的并发症及风险    null  AN..1000
SELECT SPEXAMINATIONS_SPTREAT_COMPL FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEXAMINATIONS_SPTREAT_COMPL;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    null  AN..1000
SELECT REPLACE_SCHEME FROM SPECIAL_TREATMENT_CONSENT GROUP BY REPLACE_SCHEME;

---PATIENT_AGENT_SIGN  VARCHAR2(50)  Y    患者/法定代理人签名    null  A..50
SELECT PATIENT_AGENT_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761-2008  null  N1
SELECT RELATION_CODE FROM SPECIAL_TREATMENT_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    null  DT15
SELECT SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    null  A..50
SELECT DOCTOR_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    null  DT15
SELECT DOCTOR_SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    null  
SELECT ORG_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    null  
SELECT PATIENT_AGENT_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  
SELECT INPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  AN..18
SELECT OUTP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  AN..18
SELECT INP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    null  AN..20
SELECT INFORMED_CONSENT_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INFORMED_CONSENT_NO;

---SPEICAL_EXAMTREAT_ITEM  VARCHAR2(100)  Y    特殊检查及特殊治疗项目名称    null  AN..100
SELECT SPEICAL_EXAMTREAT_ITEM FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEICAL_EXAMTREAT_ITEM;

---SPECIAL_INSPEC_SPEC_TREAT  VARCHAR2(100)  Y    特殊检查及特殊治疗目的    null  A..100
SELECT SPECIAL_INSPEC_SPEC_TREAT FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPECIAL_INSPEC_SPEC_TREAT;

---SPEXAMINATIONS_SPTREAT_COMPL  VARCHAR2(1000)  Y    特殊检查及特殊治疗可能引起的并发症及风险    null  AN..1000
SELECT SPEXAMINATIONS_SPTREAT_COMPL FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEXAMINATIONS_SPTREAT_COMPL;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    null  AN..1000
SELECT REPLACE_SCHEME FROM SPECIAL_TREATMENT_CONSENT GROUP BY REPLACE_SCHEME;

---PATIENT_AGENT_SIGN  VARCHAR2(50)  Y    患者/法定代理人签名    null  A..50
SELECT PATIENT_AGENT_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761-2008  null  N1
SELECT RELATION_CODE FROM SPECIAL_TREATMENT_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    null  DT15
SELECT SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    null  A..50
SELECT DOCTOR_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    null  DT15
SELECT DOCTOR_SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    null  
SELECT ORG_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    null  
SELECT PATIENT_AGENT_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  
SELECT INPATIENT_SN FROM SPECIAL_TREATMENT_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  AN..18
SELECT OUTP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  AN..18
SELECT INP_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    null  AN..20
SELECT INFORMED_CONSENT_NO FROM SPECIAL_TREATMENT_CONSENT GROUP BY INFORMED_CONSENT_NO;

---SPEICAL_EXAMTREAT_ITEM  VARCHAR2(100)  Y    特殊检查及特殊治疗项目名称    null  AN..100
SELECT SPEICAL_EXAMTREAT_ITEM FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEICAL_EXAMTREAT_ITEM;

---SPECIAL_INSPEC_SPEC_TREAT  VARCHAR2(100)  Y    特殊检查及特殊治疗目的    null  A..100
SELECT SPECIAL_INSPEC_SPEC_TREAT FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPECIAL_INSPEC_SPEC_TREAT;

---SPEXAMINATIONS_SPTREAT_COMPL  VARCHAR2(1000)  Y    特殊检查及特殊治疗可能引起的并发症及风险    null  AN..1000
SELECT SPEXAMINATIONS_SPTREAT_COMPL FROM SPECIAL_TREATMENT_CONSENT GROUP BY SPEXAMINATIONS_SPTREAT_COMPL;

---REPLACE_SCHEME  VARCHAR2(1000)  Y    替代方案    null  AN..1000
SELECT REPLACE_SCHEME FROM SPECIAL_TREATMENT_CONSENT GROUP BY REPLACE_SCHEME;

---PATIENT_AGENT_SIGN  VARCHAR2(50)  Y    患者/法定代理人签名    null  A..50
SELECT PATIENT_AGENT_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761-2008  null  N1
SELECT RELATION_CODE FROM SPECIAL_TREATMENT_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    null  DT15
SELECT SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    null  A..50
SELECT DOCTOR_SIGN FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    null  DT15
SELECT DOCTOR_SIGN_DATETIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    null  
SELECT ORG_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    null  
SELECT PATIENT_AGENT_OPINION FROM SPECIAL_TREATMENT_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM SPECIAL_TREATMENT_CONSENT GROUP BY LAST_MODIFIC_TIME;

