---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HANDOVER_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HANDOVER_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HANDOVER_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HANDOVER_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM HANDOVER_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HANDOVER_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HANDOVER_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HANDOVER_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM HANDOVER_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM HANDOVER_RECORD GROUP BY CURRENTLY_SITUATION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM HANDOVER_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---SUCC_ASSESSMENT_PLAN  VARCHAR2(2000)  Y    接班诊疗计划    S1  AN..2000
SELECT SUCC_ASSESSMENT_PLAN FROM HANDOVER_RECORD GROUP BY SUCC_ASSESSMENT_PLAN;

---HANDOVER_DATATIME  DATE  Y    交班日期时间    DT  DT15
SELECT HANDOVER_DATATIME FROM HANDOVER_RECORD GROUP BY HANDOVER_DATATIME;

---HANDOVER_SIGN  VARCHAR2(50)  Y    交班者签名    S1  A..50
SELECT HANDOVER_SIGN FROM HANDOVER_RECORD GROUP BY HANDOVER_SIGN;

---TAKE_DATATIME  DATE  Y    接班日期时间    DT  DT15
SELECT TAKE_DATATIME FROM HANDOVER_RECORD GROUP BY TAKE_DATATIME;

---TAKE_SIGN  VARCHAR2(50)  Y    接班者签名    S1  A..50
SELECT TAKE_SIGN FROM HANDOVER_RECORD GROUP BY TAKE_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HANDOVER_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HANDOVER_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HANDOVER_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HANDOVER_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HANDOVER_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM HANDOVER_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HANDOVER_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HANDOVER_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HANDOVER_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM HANDOVER_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM HANDOVER_RECORD GROUP BY CURRENTLY_SITUATION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM HANDOVER_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---SUCC_ASSESSMENT_PLAN  VARCHAR2(2000)  Y    接班诊疗计划    S1  AN..2000
SELECT SUCC_ASSESSMENT_PLAN FROM HANDOVER_RECORD GROUP BY SUCC_ASSESSMENT_PLAN;

---HANDOVER_DATATIME  DATE  Y    交班日期时间    DT  DT15
SELECT HANDOVER_DATATIME FROM HANDOVER_RECORD GROUP BY HANDOVER_DATATIME;

---HANDOVER_SIGN  VARCHAR2(50)  Y    交班者签名    S1  A..50
SELECT HANDOVER_SIGN FROM HANDOVER_RECORD GROUP BY HANDOVER_SIGN;

---TAKE_DATATIME  DATE  Y    接班日期时间    DT  DT15
SELECT TAKE_DATATIME FROM HANDOVER_RECORD GROUP BY TAKE_DATATIME;

---TAKE_SIGN  VARCHAR2(50)  Y    接班者签名    S1  A..50
SELECT TAKE_SIGN FROM HANDOVER_RECORD GROUP BY TAKE_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HANDOVER_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HANDOVER_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HANDOVER_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HANDOVER_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HANDOVER_RECORD GROUP BY INP_NO;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM HANDOVER_RECORD GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HANDOVER_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HANDOVER_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HANDOVER_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM HANDOVER_RECORD GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM HANDOVER_RECORD GROUP BY CURRENTLY_SITUATION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM HANDOVER_RECORD GROUP BY MATTERS_NEED_ATTENTION;

---SUCC_ASSESSMENT_PLAN  VARCHAR2(2000)  Y    接班诊疗计划    S1  AN..2000
SELECT SUCC_ASSESSMENT_PLAN FROM HANDOVER_RECORD GROUP BY SUCC_ASSESSMENT_PLAN;

---HANDOVER_DATATIME  DATE  Y    交班日期时间    DT  DT15
SELECT HANDOVER_DATATIME FROM HANDOVER_RECORD GROUP BY HANDOVER_DATATIME;

---HANDOVER_SIGN  VARCHAR2(50)  Y    交班者签名    S1  A..50
SELECT HANDOVER_SIGN FROM HANDOVER_RECORD GROUP BY HANDOVER_SIGN;

---TAKE_DATATIME  DATE  Y    接班日期时间    DT  DT15
SELECT TAKE_DATATIME FROM HANDOVER_RECORD GROUP BY TAKE_DATATIME;

---TAKE_SIGN  VARCHAR2(50)  Y    接班者签名    S1  A..50
SELECT TAKE_SIGN FROM HANDOVER_RECORD GROUP BY TAKE_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HANDOVER_RECORD GROUP BY LAST_MODIFIC_TIME;

