---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM EXPECTANT_RECORD GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EXPECTANT_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EXPECTANT_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM EXPECTANT_RECORD GROUP BY INP_NO;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY PREDELIVERY_DATETIME;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM EXPECTANT_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---CONCEPTION_CODE  NUMBER(1)  Y    受孕形式代码    S2  N1
SELECT CONCEPTION_CODE FROM EXPECTANT_RECORD GROUP BY CONCEPTION_CODE;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM EXPECTANT_RECORD GROUP BY EDC_DESC;

---PRENATAL_EXAMINATION_CODE  VARCHAR2(10)  Y    产前检查标志    L  T/F
SELECT PRENATAL_EXAMINATION_CODE FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_CODE;

---PRENATAL_EXAMINATION_ABNORMAL  VARCHAR2(200)  Y    产前检查异常情况    S1  A..200
SELECT PRENATAL_EXAMINATION_ABNORMAL FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_ABNORMAL;

---PREPREGNANCY_WEIGHT  NUMBER(6,2)  Y    孕前体重（kg）    N  N3..6,2
SELECT PREPREGNANCY_WEIGHT FROM EXPECTANT_RECORD GROUP BY PREPREGNANCY_WEIGHT;

---ANTE_PARTUM_WEIGHT  NUMBER(6,2)  Y    分娩前体重（kg）    N  N3..6.2
SELECT ANTE_PARTUM_WEIGHT FROM EXPECTANT_RECORD GROUP BY ANTE_PARTUM_WEIGHT;

---SPECIAL_CASES_PREGNANCY  VARCHAR2(200)  Y    此次妊娠特殊情况    S1  AN..200
SELECT SPECIAL_CASES_PREGNANCY FROM EXPECTANT_RECORD GROUP BY SPECIAL_CASES_PREGNANCY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    S1  AN..1000
SELECT PAST_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM EXPECTANT_RECORD GROUP BY OPERATION_HISTORY;

---PAST_PREGNANCY_HISTORY  VARCHAR2(1000)  Y    既往孕产史    S1  AN..1000
SELECT PAST_PREGNANCY_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_PREGNANCY_HISTORY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM EXPECTANT_RECORD GROUP BY TEMPERATURE;

---PULSE_RATE  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT PULSE_RATE FROM EXPECTANT_RECORD GROUP BY PULSE_RATE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM EXPECTANT_RECORD GROUP BY BREATH_FREQUENCY;

---FUNDUS_HEIGHT  NUMBER(4,1)  Y    宫底高度（cm）    N  N3..4,l
SELECT FUNDUS_HEIGHT FROM EXPECTANT_RECORD GROUP BY FUNDUS_HEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.l
SELECT ABDOMINAL_GIRTH FROM EXPECTANT_RECORD GROUP BY ABDOMINAL_GIRTH;

---FETAL_HEART_RATE  NUMBER(3)  Y    胎心率(次/min)    N  N2..3
SELECT FETAL_HEART_RATE FROM EXPECTANT_RECORD GROUP BY FETAL_HEART_RATE;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码    S3  N2
SELECT FETAL_POSITION_CODE FROM EXPECTANT_RECORD GROUP BY FETAL_POSITION_CODE;

---ESTIMATED_FETAL_WEIGHT  NUMBER(4)  Y    估计胎儿体重(g)--cda模板没有该字段    N  N..4
SELECT ESTIMATED_FETAL_WEIGHT FROM EXPECTANT_RECORD GROUP BY ESTIMATED_FETAL_WEIGHT;

---HEADPOS_DYSTOCIA_EVAL  VARCHAR2(200)  Y    头位难产情况的评估    S1  AN..200
SELECT HEADPOS_DYSTOCIA_EVAL FROM EXPECTANT_RECORD GROUP BY HEADPOS_DYSTOCIA_EVAL;

---SACRAL_EXTERNAL_DIAMETER  NUMBER(4,1)  Y    骶耻外径（cm）    N  N4..l
SELECT SACRAL_EXTERNAL_DIAMETER FROM EXPECTANT_RECORD GROUP BY SACRAL_EXTERNAL_DIAMETER;

---INTERTUBEROUS_DIAMETER  NUMBER(4,1)  Y    坐骨结节间径（cm）    N  N3..4.1
SELECT INTERTUBEROUS_DIAMETER FROM EXPECTANT_RECORD GROUP BY INTERTUBEROUS_DIAMETER;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM EXPECTANT_RECORD GROUP BY CONTRACTIONS;

---CERVICAL_CONDITION  VARCHAR2(100)  Y    宫颈情况    S1  A..100
SELECT CERVICAL_CONDITION FROM EXPECTANT_RECORD GROUP BY CERVICAL_CONDITION;

---UTERINE_ORIFICE_CONDITION  VARCHAR2(100)  Y    宫口情况    S1  A..100
SELECT UTERINE_ORIFICE_CONDITION FROM EXPECTANT_RECORD GROUP BY UTERINE_ORIFICE_CONDITION;

---EMBRYOLEMMA_CODE  NUMBER(1)  Y    胎膜情况代码    S2  N1
SELECT EMBRYOLEMMA_CODE FROM EXPECTANT_RECORD GROUP BY EMBRYOLEMMA_CODE;

---RUPTURE_MEMBRANE_CODE  NUMBER(1)  Y    破膜方式代码    S2  N1
SELECT RUPTURE_MEMBRANE_CODE FROM EXPECTANT_RECORD GROUP BY RUPTURE_MEMBRANE_CODE;

---PRESENTATION_POSITION  VARCHAR2(100)  Y    先露位置    S1  A..100
SELECT PRESENTATION_POSITION FROM EXPECTANT_RECORD GROUP BY PRESENTATION_POSITION;

---AMNIOTIC_FLUID_CONDITION  VARCHAR2(100)  Y    羊水情况    S1  AN..100
SELECT AMNIOTIC_FLUID_CONDITION FROM EXPECTANT_RECORD GROUP BY AMNIOTIC_FLUID_CONDITION;

---BLADDER_FILLING_CODE  VARCHAR2(10)  Y    膀胱充盈标志    L  T/F
SELECT BLADDER_FILLING_CODE FROM EXPECTANT_RECORD GROUP BY BLADDER_FILLING_CODE;

---FLATULENCE_CODE  VARCHAR2(10)  Y    肠胀气标志    L  T/F
SELECT FLATULENCE_CODE FROM EXPECTANT_RECORD GROUP BY FLATULENCE_CODE;

---EXAM_METHOD_CODE  NUMBER(1)  Y    检查方式代码    S2  N1
SELECT EXAM_METHOD_CODE FROM EXPECTANT_RECORD GROUP BY EXAM_METHOD_CODE;

---DISPOSITION_PLAN  VARCHAR2(2000)  Y    处置计划    S1  AN..2000
SELECT DISPOSITION_PLAN FROM EXPECTANT_RECORD GROUP BY DISPOSITION_PLAN;

---PLANNED_DELIVERY_CODE  VARCHAR2(2)  Y    计划选取的分娩方式代码    S3  N..2
SELECT PLANNED_DELIVERY_CODE FROM EXPECTANT_RECORD GROUP BY PLANNED_DELIVERY_CODE;

---DELIVERY_DATETIME  DATE  Y    产程记录日期时间    DT  DT15
SELECT DELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_DATETIME;

---BIRTH_PROCESS  VARCHAR2(200)  Y    产程经过    S1  AN..200
SELECT BIRTH_PROCESS FROM EXPECTANT_RECORD GROUP BY BIRTH_PROCESS;

---LABOR_INSPECTION_SIG  VARCHAR2(50)  Y    产程检查者签名    S1  A..50
SELECT LABOR_INSPECTION_SIG FROM EXPECTANT_RECORD GROUP BY LABOR_INSPECTION_SIG;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM EXPECTANT_RECORD GROUP BY RECORD_SIGN;

---EXIT_DIAMETER  NUMBER(4,1)  Y    出口横经（CM）      
SELECT EXIT_DIAMETER FROM EXPECTANT_RECORD GROUP BY EXIT_DIAMETER;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EXPECTANT_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM EXPECTANT_RECORD GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EXPECTANT_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EXPECTANT_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM EXPECTANT_RECORD GROUP BY INP_NO;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY PREDELIVERY_DATETIME;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM EXPECTANT_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---CONCEPTION_CODE  NUMBER(1)  Y    受孕形式代码    S2  N1
SELECT CONCEPTION_CODE FROM EXPECTANT_RECORD GROUP BY CONCEPTION_CODE;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM EXPECTANT_RECORD GROUP BY EDC_DESC;

---PRENATAL_EXAMINATION_CODE  VARCHAR2(10)  Y    产前检查标志    L  T/F
SELECT PRENATAL_EXAMINATION_CODE FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_CODE;

---PRENATAL_EXAMINATION_ABNORMAL  VARCHAR2(200)  Y    产前检查异常情况    S1  A..200
SELECT PRENATAL_EXAMINATION_ABNORMAL FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_ABNORMAL;

---PREPREGNANCY_WEIGHT  NUMBER(6,2)  Y    孕前体重（kg）    N  N3..6,2
SELECT PREPREGNANCY_WEIGHT FROM EXPECTANT_RECORD GROUP BY PREPREGNANCY_WEIGHT;

---ANTE_PARTUM_WEIGHT  NUMBER(6,2)  Y    分娩前体重（kg）    N  N3..6.2
SELECT ANTE_PARTUM_WEIGHT FROM EXPECTANT_RECORD GROUP BY ANTE_PARTUM_WEIGHT;

---SPECIAL_CASES_PREGNANCY  VARCHAR2(200)  Y    此次妊娠特殊情况    S1  AN..200
SELECT SPECIAL_CASES_PREGNANCY FROM EXPECTANT_RECORD GROUP BY SPECIAL_CASES_PREGNANCY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    S1  AN..1000
SELECT PAST_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM EXPECTANT_RECORD GROUP BY OPERATION_HISTORY;

---PAST_PREGNANCY_HISTORY  VARCHAR2(1000)  Y    既往孕产史    S1  AN..1000
SELECT PAST_PREGNANCY_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_PREGNANCY_HISTORY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM EXPECTANT_RECORD GROUP BY TEMPERATURE;

---PULSE_RATE  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT PULSE_RATE FROM EXPECTANT_RECORD GROUP BY PULSE_RATE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM EXPECTANT_RECORD GROUP BY BREATH_FREQUENCY;

---FUNDUS_HEIGHT  NUMBER(4,1)  Y    宫底高度（cm）    N  N3..4,l
SELECT FUNDUS_HEIGHT FROM EXPECTANT_RECORD GROUP BY FUNDUS_HEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.l
SELECT ABDOMINAL_GIRTH FROM EXPECTANT_RECORD GROUP BY ABDOMINAL_GIRTH;

---FETAL_HEART_RATE  NUMBER(3)  Y    胎心率(次/min)    N  N2..3
SELECT FETAL_HEART_RATE FROM EXPECTANT_RECORD GROUP BY FETAL_HEART_RATE;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码    S3  N2
SELECT FETAL_POSITION_CODE FROM EXPECTANT_RECORD GROUP BY FETAL_POSITION_CODE;

---ESTIMATED_FETAL_WEIGHT  NUMBER(4)  Y    估计胎儿体重(g)--cda模板没有该字段    N  N..4
SELECT ESTIMATED_FETAL_WEIGHT FROM EXPECTANT_RECORD GROUP BY ESTIMATED_FETAL_WEIGHT;

---HEADPOS_DYSTOCIA_EVAL  VARCHAR2(200)  Y    头位难产情况的评估    S1  AN..200
SELECT HEADPOS_DYSTOCIA_EVAL FROM EXPECTANT_RECORD GROUP BY HEADPOS_DYSTOCIA_EVAL;

---SACRAL_EXTERNAL_DIAMETER  NUMBER(4,1)  Y    骶耻外径（cm）    N  N4..l
SELECT SACRAL_EXTERNAL_DIAMETER FROM EXPECTANT_RECORD GROUP BY SACRAL_EXTERNAL_DIAMETER;

---INTERTUBEROUS_DIAMETER  NUMBER(4,1)  Y    坐骨结节间径（cm）    N  N3..4.1
SELECT INTERTUBEROUS_DIAMETER FROM EXPECTANT_RECORD GROUP BY INTERTUBEROUS_DIAMETER;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM EXPECTANT_RECORD GROUP BY CONTRACTIONS;

---CERVICAL_CONDITION  VARCHAR2(100)  Y    宫颈情况    S1  A..100
SELECT CERVICAL_CONDITION FROM EXPECTANT_RECORD GROUP BY CERVICAL_CONDITION;

---UTERINE_ORIFICE_CONDITION  VARCHAR2(100)  Y    宫口情况    S1  A..100
SELECT UTERINE_ORIFICE_CONDITION FROM EXPECTANT_RECORD GROUP BY UTERINE_ORIFICE_CONDITION;

---EMBRYOLEMMA_CODE  NUMBER(1)  Y    胎膜情况代码    S2  N1
SELECT EMBRYOLEMMA_CODE FROM EXPECTANT_RECORD GROUP BY EMBRYOLEMMA_CODE;

---RUPTURE_MEMBRANE_CODE  NUMBER(1)  Y    破膜方式代码    S2  N1
SELECT RUPTURE_MEMBRANE_CODE FROM EXPECTANT_RECORD GROUP BY RUPTURE_MEMBRANE_CODE;

---PRESENTATION_POSITION  VARCHAR2(100)  Y    先露位置    S1  A..100
SELECT PRESENTATION_POSITION FROM EXPECTANT_RECORD GROUP BY PRESENTATION_POSITION;

---AMNIOTIC_FLUID_CONDITION  VARCHAR2(100)  Y    羊水情况    S1  AN..100
SELECT AMNIOTIC_FLUID_CONDITION FROM EXPECTANT_RECORD GROUP BY AMNIOTIC_FLUID_CONDITION;

---BLADDER_FILLING_CODE  VARCHAR2(10)  Y    膀胱充盈标志    L  T/F
SELECT BLADDER_FILLING_CODE FROM EXPECTANT_RECORD GROUP BY BLADDER_FILLING_CODE;

---FLATULENCE_CODE  VARCHAR2(10)  Y    肠胀气标志    L  T/F
SELECT FLATULENCE_CODE FROM EXPECTANT_RECORD GROUP BY FLATULENCE_CODE;

---EXAM_METHOD_CODE  NUMBER(1)  Y    检查方式代码    S2  N1
SELECT EXAM_METHOD_CODE FROM EXPECTANT_RECORD GROUP BY EXAM_METHOD_CODE;

---DISPOSITION_PLAN  VARCHAR2(2000)  Y    处置计划    S1  AN..2000
SELECT DISPOSITION_PLAN FROM EXPECTANT_RECORD GROUP BY DISPOSITION_PLAN;

---PLANNED_DELIVERY_CODE  VARCHAR2(2)  Y    计划选取的分娩方式代码    S3  N..2
SELECT PLANNED_DELIVERY_CODE FROM EXPECTANT_RECORD GROUP BY PLANNED_DELIVERY_CODE;

---DELIVERY_DATETIME  DATE  Y    产程记录日期时间    DT  DT15
SELECT DELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_DATETIME;

---BIRTH_PROCESS  VARCHAR2(200)  Y    产程经过    S1  AN..200
SELECT BIRTH_PROCESS FROM EXPECTANT_RECORD GROUP BY BIRTH_PROCESS;

---LABOR_INSPECTION_SIG  VARCHAR2(50)  Y    产程检查者签名    S1  A..50
SELECT LABOR_INSPECTION_SIG FROM EXPECTANT_RECORD GROUP BY LABOR_INSPECTION_SIG;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM EXPECTANT_RECORD GROUP BY RECORD_SIGN;

---EXIT_DIAMETER  NUMBER(4,1)  Y    出口横经（CM）      
SELECT EXIT_DIAMETER FROM EXPECTANT_RECORD GROUP BY EXIT_DIAMETER;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EXPECTANT_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM EXPECTANT_RECORD GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EXPECTANT_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EXPECTANT_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM EXPECTANT_RECORD GROUP BY INP_NO;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY PREDELIVERY_DATETIME;

---DELIVERY_TIMEGRAVIDITY_TIME  NUMBER(2)  Y    孕次    N  N..2
SELECT DELIVERY_TIMEGRAVIDITY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIMEGRAVIDITY_TIME;

---DELIVERY_TIME  NUMBER(2)  Y    产次    N  N..2
SELECT DELIVERY_TIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_TIME;

---LAST_MENSTRUAL_PERIOD  DATE  Y    末次月经日期    D  D8
SELECT LAST_MENSTRUAL_PERIOD FROM EXPECTANT_RECORD GROUP BY LAST_MENSTRUAL_PERIOD;

---CONCEPTION_CODE  NUMBER(1)  Y    受孕形式代码    S2  N1
SELECT CONCEPTION_CODE FROM EXPECTANT_RECORD GROUP BY CONCEPTION_CODE;

---EDC_DESC  DATE  Y    预产期    D  D8
SELECT EDC_DESC FROM EXPECTANT_RECORD GROUP BY EDC_DESC;

---PRENATAL_EXAMINATION_CODE  VARCHAR2(10)  Y    产前检查标志    L  T/F
SELECT PRENATAL_EXAMINATION_CODE FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_CODE;

---PRENATAL_EXAMINATION_ABNORMAL  VARCHAR2(200)  Y    产前检查异常情况    S1  A..200
SELECT PRENATAL_EXAMINATION_ABNORMAL FROM EXPECTANT_RECORD GROUP BY PRENATAL_EXAMINATION_ABNORMAL;

---PREPREGNANCY_WEIGHT  NUMBER(6,2)  Y    孕前体重（kg）    N  N3..6,2
SELECT PREPREGNANCY_WEIGHT FROM EXPECTANT_RECORD GROUP BY PREPREGNANCY_WEIGHT;

---ANTE_PARTUM_WEIGHT  NUMBER(6,2)  Y    分娩前体重（kg）    N  N3..6.2
SELECT ANTE_PARTUM_WEIGHT FROM EXPECTANT_RECORD GROUP BY ANTE_PARTUM_WEIGHT;

---SPECIAL_CASES_PREGNANCY  VARCHAR2(200)  Y    此次妊娠特殊情况    S1  AN..200
SELECT SPECIAL_CASES_PREGNANCY FROM EXPECTANT_RECORD GROUP BY SPECIAL_CASES_PREGNANCY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    S1  AN..1000
SELECT PAST_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM EXPECTANT_RECORD GROUP BY OPERATION_HISTORY;

---PAST_PREGNANCY_HISTORY  VARCHAR2(1000)  Y    既往孕产史    S1  AN..1000
SELECT PAST_PREGNANCY_HISTORY FROM EXPECTANT_RECORD GROUP BY PAST_PREGNANCY_HISTORY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM EXPECTANT_RECORD GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM EXPECTANT_RECORD GROUP BY TEMPERATURE;

---PULSE_RATE  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT PULSE_RATE FROM EXPECTANT_RECORD GROUP BY PULSE_RATE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM EXPECTANT_RECORD GROUP BY BREATH_FREQUENCY;

---FUNDUS_HEIGHT  NUMBER(4,1)  Y    宫底高度（cm）    N  N3..4,l
SELECT FUNDUS_HEIGHT FROM EXPECTANT_RECORD GROUP BY FUNDUS_HEIGHT;

---ABDOMINAL_GIRTH  NUMBER(5,1)  Y    腹围（cm）    N  N4..5.l
SELECT ABDOMINAL_GIRTH FROM EXPECTANT_RECORD GROUP BY ABDOMINAL_GIRTH;

---FETAL_HEART_RATE  NUMBER(3)  Y    胎心率(次/min)    N  N2..3
SELECT FETAL_HEART_RATE FROM EXPECTANT_RECORD GROUP BY FETAL_HEART_RATE;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码    S3  N2
SELECT FETAL_POSITION_CODE FROM EXPECTANT_RECORD GROUP BY FETAL_POSITION_CODE;

---ESTIMATED_FETAL_WEIGHT  NUMBER(4)  Y    估计胎儿体重(g)--cda模板没有该字段    N  N..4
SELECT ESTIMATED_FETAL_WEIGHT FROM EXPECTANT_RECORD GROUP BY ESTIMATED_FETAL_WEIGHT;

---HEADPOS_DYSTOCIA_EVAL  VARCHAR2(200)  Y    头位难产情况的评估    S1  AN..200
SELECT HEADPOS_DYSTOCIA_EVAL FROM EXPECTANT_RECORD GROUP BY HEADPOS_DYSTOCIA_EVAL;

---SACRAL_EXTERNAL_DIAMETER  NUMBER(4,1)  Y    骶耻外径（cm）    N  N4..l
SELECT SACRAL_EXTERNAL_DIAMETER FROM EXPECTANT_RECORD GROUP BY SACRAL_EXTERNAL_DIAMETER;

---INTERTUBEROUS_DIAMETER  NUMBER(4,1)  Y    坐骨结节间径（cm）    N  N3..4.1
SELECT INTERTUBEROUS_DIAMETER FROM EXPECTANT_RECORD GROUP BY INTERTUBEROUS_DIAMETER;

---CONTRACTIONS  VARCHAR2(200)  Y    宫缩情况    S1  AN..200
SELECT CONTRACTIONS FROM EXPECTANT_RECORD GROUP BY CONTRACTIONS;

---CERVICAL_CONDITION  VARCHAR2(100)  Y    宫颈情况    S1  A..100
SELECT CERVICAL_CONDITION FROM EXPECTANT_RECORD GROUP BY CERVICAL_CONDITION;

---UTERINE_ORIFICE_CONDITION  VARCHAR2(100)  Y    宫口情况    S1  A..100
SELECT UTERINE_ORIFICE_CONDITION FROM EXPECTANT_RECORD GROUP BY UTERINE_ORIFICE_CONDITION;

---EMBRYOLEMMA_CODE  NUMBER(1)  Y    胎膜情况代码    S2  N1
SELECT EMBRYOLEMMA_CODE FROM EXPECTANT_RECORD GROUP BY EMBRYOLEMMA_CODE;

---RUPTURE_MEMBRANE_CODE  NUMBER(1)  Y    破膜方式代码    S2  N1
SELECT RUPTURE_MEMBRANE_CODE FROM EXPECTANT_RECORD GROUP BY RUPTURE_MEMBRANE_CODE;

---PRESENTATION_POSITION  VARCHAR2(100)  Y    先露位置    S1  A..100
SELECT PRESENTATION_POSITION FROM EXPECTANT_RECORD GROUP BY PRESENTATION_POSITION;

---AMNIOTIC_FLUID_CONDITION  VARCHAR2(100)  Y    羊水情况    S1  AN..100
SELECT AMNIOTIC_FLUID_CONDITION FROM EXPECTANT_RECORD GROUP BY AMNIOTIC_FLUID_CONDITION;

---BLADDER_FILLING_CODE  VARCHAR2(10)  Y    膀胱充盈标志    L  T/F
SELECT BLADDER_FILLING_CODE FROM EXPECTANT_RECORD GROUP BY BLADDER_FILLING_CODE;

---FLATULENCE_CODE  VARCHAR2(10)  Y    肠胀气标志    L  T/F
SELECT FLATULENCE_CODE FROM EXPECTANT_RECORD GROUP BY FLATULENCE_CODE;

---EXAM_METHOD_CODE  NUMBER(1)  Y    检查方式代码    S2  N1
SELECT EXAM_METHOD_CODE FROM EXPECTANT_RECORD GROUP BY EXAM_METHOD_CODE;

---DISPOSITION_PLAN  VARCHAR2(2000)  Y    处置计划    S1  AN..2000
SELECT DISPOSITION_PLAN FROM EXPECTANT_RECORD GROUP BY DISPOSITION_PLAN;

---PLANNED_DELIVERY_CODE  VARCHAR2(2)  Y    计划选取的分娩方式代码    S3  N..2
SELECT PLANNED_DELIVERY_CODE FROM EXPECTANT_RECORD GROUP BY PLANNED_DELIVERY_CODE;

---DELIVERY_DATETIME  DATE  Y    产程记录日期时间    DT  DT15
SELECT DELIVERY_DATETIME FROM EXPECTANT_RECORD GROUP BY DELIVERY_DATETIME;

---BIRTH_PROCESS  VARCHAR2(200)  Y    产程经过    S1  AN..200
SELECT BIRTH_PROCESS FROM EXPECTANT_RECORD GROUP BY BIRTH_PROCESS;

---LABOR_INSPECTION_SIG  VARCHAR2(50)  Y    产程检查者签名    S1  A..50
SELECT LABOR_INSPECTION_SIG FROM EXPECTANT_RECORD GROUP BY LABOR_INSPECTION_SIG;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM EXPECTANT_RECORD GROUP BY RECORD_SIGN;

---EXIT_DIAMETER  NUMBER(4,1)  Y    出口横经（CM）      
SELECT EXIT_DIAMETER FROM EXPECTANT_RECORD GROUP BY EXIT_DIAMETER;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EXPECTANT_RECORD GROUP BY LAST_MODIFIC_TIME;

