---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CSE_INFORMED_CONSENT GROUP BY OUTP_NO;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CSE_INFORMED_CONSENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CSE_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_ID;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CSE_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---PATIENT_UNDERLYING_DISEASE  VARCHAR2(500)  Y    患者基础疾病    S1  AN..500
SELECT PATIENT_UNDERLYING_DISEASE FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_UNDERLYING_DISEASE;

---BASE_DESEASE_POSSIBLE_INFLU  VARCHAR2(1000)  Y    基础疾病对麻醉可能产生的影响    S1  AN..1000
SELECT BASE_DESEASE_POSSIBLE_INFLU FROM CSE_INFORMED_CONSENT GROUP BY BASE_DESEASE_POSSIBLE_INFLU;

---INT_INVASE_OP_MON_WAY  VARCHAR2(2000)  Y    拟行有创操作和监测方法    S1  AN..2000
SELECT INT_INVASE_OP_MON_WAY FROM CSE_INFORMED_CONSENT GROUP BY INT_INVASE_OP_MON_WAY;

---ANAESTHESIA_POSSIBLE_ACCIDENT  VARCHAR2(1000)  Y    麻醉中、麻醉后可能发生的意外及并发症    S1  AN..1000
SELECT ANAESTHESIA_POSSIBLE_ACCIDENT FROM CSE_INFORMED_CONSENT GROUP BY ANAESTHESIA_POSSIBLE_ACCIDENT;

---ANESTHESIA_SAFETY_INSUR_FLAG  VARCHAR2(5)  Y    使用麻醉钺痛泵标志    L  T/F
SELECT ANESTHESIA_SAFETY_INSUR_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFETY_INSUR_FLAG;

---ANESTHESIA_SAFE_FLAG  VARCHAR2(5)  Y    参加麻醉安全保险标志    L  T/F
SELECT ANESTHESIA_SAFE_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFE_FLAG;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM CSE_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761-2008  S3  N1
SELECT RELATION_CODE FROM CSE_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_DOCTOR_SIGN;

---ANESTHESIA_SIGN_DATETIME  DATE  Y    麻醉医师签名日期时间    DT  DT15
SELECT ANESTHESIA_SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM CSE_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CSE_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CSE_INFORMED_CONSENT GROUP BY OUTP_NO;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CSE_INFORMED_CONSENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CSE_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_ID;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CSE_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---PATIENT_UNDERLYING_DISEASE  VARCHAR2(500)  Y    患者基础疾病    S1  AN..500
SELECT PATIENT_UNDERLYING_DISEASE FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_UNDERLYING_DISEASE;

---BASE_DESEASE_POSSIBLE_INFLU  VARCHAR2(1000)  Y    基础疾病对麻醉可能产生的影响    S1  AN..1000
SELECT BASE_DESEASE_POSSIBLE_INFLU FROM CSE_INFORMED_CONSENT GROUP BY BASE_DESEASE_POSSIBLE_INFLU;

---INT_INVASE_OP_MON_WAY  VARCHAR2(2000)  Y    拟行有创操作和监测方法    S1  AN..2000
SELECT INT_INVASE_OP_MON_WAY FROM CSE_INFORMED_CONSENT GROUP BY INT_INVASE_OP_MON_WAY;

---ANAESTHESIA_POSSIBLE_ACCIDENT  VARCHAR2(1000)  Y    麻醉中、麻醉后可能发生的意外及并发症    S1  AN..1000
SELECT ANAESTHESIA_POSSIBLE_ACCIDENT FROM CSE_INFORMED_CONSENT GROUP BY ANAESTHESIA_POSSIBLE_ACCIDENT;

---ANESTHESIA_SAFETY_INSUR_FLAG  VARCHAR2(5)  Y    使用麻醉钺痛泵标志    L  T/F
SELECT ANESTHESIA_SAFETY_INSUR_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFETY_INSUR_FLAG;

---ANESTHESIA_SAFE_FLAG  VARCHAR2(5)  Y    参加麻醉安全保险标志    L  T/F
SELECT ANESTHESIA_SAFE_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFE_FLAG;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM CSE_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761-2008  S3  N1
SELECT RELATION_CODE FROM CSE_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_DOCTOR_SIGN;

---ANESTHESIA_SIGN_DATETIME  DATE  Y    麻醉医师签名日期时间    DT  DT15
SELECT ANESTHESIA_SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM CSE_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CSE_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM CSE_INFORMED_CONSENT GROUP BY OUTP_NO;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM CSE_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CSE_INFORMED_CONSENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CSE_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_ID;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM CSE_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---PATIENT_UNDERLYING_DISEASE  VARCHAR2(500)  Y    患者基础疾病    S1  AN..500
SELECT PATIENT_UNDERLYING_DISEASE FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_UNDERLYING_DISEASE;

---BASE_DESEASE_POSSIBLE_INFLU  VARCHAR2(1000)  Y    基础疾病对麻醉可能产生的影响    S1  AN..1000
SELECT BASE_DESEASE_POSSIBLE_INFLU FROM CSE_INFORMED_CONSENT GROUP BY BASE_DESEASE_POSSIBLE_INFLU;

---INT_INVASE_OP_MON_WAY  VARCHAR2(2000)  Y    拟行有创操作和监测方法    S1  AN..2000
SELECT INT_INVASE_OP_MON_WAY FROM CSE_INFORMED_CONSENT GROUP BY INT_INVASE_OP_MON_WAY;

---ANAESTHESIA_POSSIBLE_ACCIDENT  VARCHAR2(1000)  Y    麻醉中、麻醉后可能发生的意外及并发症    S1  AN..1000
SELECT ANAESTHESIA_POSSIBLE_ACCIDENT FROM CSE_INFORMED_CONSENT GROUP BY ANAESTHESIA_POSSIBLE_ACCIDENT;

---ANESTHESIA_SAFETY_INSUR_FLAG  VARCHAR2(5)  Y    使用麻醉钺痛泵标志    L  T/F
SELECT ANESTHESIA_SAFETY_INSUR_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFETY_INSUR_FLAG;

---ANESTHESIA_SAFE_FLAG  VARCHAR2(5)  Y    参加麻醉安全保险标志    L  T/F
SELECT ANESTHESIA_SAFE_FLAG FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SAFE_FLAG;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM CSE_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM CSE_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T 4761-2008  S3  N1
SELECT RELATION_CODE FROM CSE_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_DOCTOR_SIGN;

---ANESTHESIA_SIGN_DATETIME  DATE  Y    麻醉医师签名日期时间    DT  DT15
SELECT ANESTHESIA_SIGN_DATETIME FROM CSE_INFORMED_CONSENT GROUP BY ANESTHESIA_SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM CSE_INFORMED_CONSENT GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CSE_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

