---OPER_NURS_OPER_ID  VARCHAR2(18)      手术护理操作ID      
SELECT OPER_NURS_OPER_ID FROM OPER_NURS_OPER GROUP BY OPER_NURS_OPER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OPER GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    S1  AN..100
SELECT NURSING_OPERATION_ITEM FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    S1  AN..100
SELECT NURSING_OPERATION_NAME FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    S1  AN..1000
SELECT NURSING_OPERATION_RESULT FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OPER GROUP BY LAST_MODIFIC_TIME;

---OPER_NURS_OPER_ID  VARCHAR2(18)      手术护理操作ID      
SELECT OPER_NURS_OPER_ID FROM OPER_NURS_OPER GROUP BY OPER_NURS_OPER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OPER GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    S1  AN..100
SELECT NURSING_OPERATION_ITEM FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    S1  AN..100
SELECT NURSING_OPERATION_NAME FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    S1  AN..1000
SELECT NURSING_OPERATION_RESULT FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OPER GROUP BY LAST_MODIFIC_TIME;

---OPER_NURS_OPER_ID  VARCHAR2(18)      手术护理操作ID      
SELECT OPER_NURS_OPER_ID FROM OPER_NURS_OPER GROUP BY OPER_NURS_OPER_ID;

---GENERAL_NURSING_ID  VARCHAR2(18)      护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPER_NURS_OPER GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    S1  AN..100
SELECT NURSING_OPERATION_ITEM FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    S1  AN..100
SELECT NURSING_OPERATION_NAME FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    S1  AN..1000
SELECT NURSING_OPERATION_RESULT FROM OPER_NURS_OPER GROUP BY NURSING_OPERATION_RESULT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPER_NURS_OPER GROUP BY LAST_MODIFIC_TIME;

