---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM DRUGPERSON_NAME_DETAIL GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM DRUGPERSON_NAME_DETAIL GROUP BY PRESC_ID;

---CHECK_PERSON_NAME  VARCHAR2(50)  Y    处方审核药剂师签名    null  null
SELECT CHECK_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY CHECK_PERSON_NAME;

---VERIFY_PERSON_NAME  VARCHAR2(50)  Y    处方核对药剂师签名    null  null
SELECT VERIFY_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY VERIFY_PERSON_NAME;

---DISPENSING_PERSON_NAME  VARCHAR2(50)  Y    处方发药药剂师签名    null  null
SELECT DISPENSING_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY DISPENSING_PERSON_NAME;

---ALLOCATE_PERSON_NAME  VARCHAR2(50)  Y    处方调配药剂师签名    null  null
SELECT ALLOCATE_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY ALLOCATE_PERSON_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    null  null
SELECT RECIPE_REMARK FROM DRUGPERSON_NAME_DETAIL GROUP BY RECIPE_REMARK;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM DRUGPERSON_NAME_DETAIL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM DRUGPERSON_NAME_DETAIL GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM DRUGPERSON_NAME_DETAIL GROUP BY PRESC_ID;

---CHECK_PERSON_NAME  VARCHAR2(50)  Y    处方审核药剂师签名    null  null
SELECT CHECK_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY CHECK_PERSON_NAME;

---VERIFY_PERSON_NAME  VARCHAR2(50)  Y    处方核对药剂师签名    null  null
SELECT VERIFY_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY VERIFY_PERSON_NAME;

---DISPENSING_PERSON_NAME  VARCHAR2(50)  Y    处方发药药剂师签名    null  null
SELECT DISPENSING_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY DISPENSING_PERSON_NAME;

---ALLOCATE_PERSON_NAME  VARCHAR2(50)  Y    处方调配药剂师签名    null  null
SELECT ALLOCATE_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY ALLOCATE_PERSON_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    null  null
SELECT RECIPE_REMARK FROM DRUGPERSON_NAME_DETAIL GROUP BY RECIPE_REMARK;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM DRUGPERSON_NAME_DETAIL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM DRUGPERSON_NAME_DETAIL GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM DRUGPERSON_NAME_DETAIL GROUP BY PRESC_ID;

---CHECK_PERSON_NAME  VARCHAR2(50)  Y    处方审核药剂师签名    null  null
SELECT CHECK_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY CHECK_PERSON_NAME;

---VERIFY_PERSON_NAME  VARCHAR2(50)  Y    处方核对药剂师签名    null  null
SELECT VERIFY_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY VERIFY_PERSON_NAME;

---DISPENSING_PERSON_NAME  VARCHAR2(50)  Y    处方发药药剂师签名    null  null
SELECT DISPENSING_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY DISPENSING_PERSON_NAME;

---ALLOCATE_PERSON_NAME  VARCHAR2(50)  Y    处方调配药剂师签名    null  null
SELECT ALLOCATE_PERSON_NAME FROM DRUGPERSON_NAME_DETAIL GROUP BY ALLOCATE_PERSON_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    null  null
SELECT RECIPE_REMARK FROM DRUGPERSON_NAME_DETAIL GROUP BY RECIPE_REMARK;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM DRUGPERSON_NAME_DETAIL GROUP BY LAST_MODIFIC_TIME;

