---USAGE_ID  VARCHAR2(50)      药品ID    null  null
SELECT USAGE_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_ID;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY PRESC_ID;

---RECIPE_GROUP_NO  NUMBER(38)  Y    处方药品组号    null  null
SELECT RECIPE_GROUP_NO FROM OUTP_PRESCIPTION_DETAIL GROUP BY RECIPE_GROUP_NO;

---ADVICE_ITEM_CODE  VARCHAR2(50)  Y    医嘱项目编码/处方药物编码    null  null
SELECT ADVICE_ITEM_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目名称/处方药物名称    null  null
SELECT ADVICE_ITEM_CONTENT FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE;

---DRUG_SPEC  VARCHAR2(20)  Y    药物规格    null  null
SELECT DRUG_SPEC FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_SPEC;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  Y    药物剂型代码    null  null
SELECT DRUG_DOSAGE_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE  NUMBER(5,2)  Y    药物使用次剂    null  null
SELECT DRUG_DOSAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DOSAGE_UNIT FROM OUTP_PRESCIPTION_DETAIL GROUP BY DOSAGE_UNIT;

---DRUG_USAGE_FREQUENCY  VARCHAR2(2)  Y    药物使用频次代码    null  null
SELECT DRUG_USAGE_FREQUENCY FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE_FREQUENCY;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码    null  null
SELECT ROUTE_ADMINISTRATION FROM OUTP_PRESCIPTION_DETAIL GROUP BY ROUTE_ADMINISTRATION;

---USAGE_DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT USAGE_DOSAGE_TOTAL FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_DOSAGE_TOTAL;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM OUTP_PRESCIPTION_DETAIL GROUP BY LAST_MODIFIC_TIME;

---USAGE_ID  VARCHAR2(50)      药品ID    null  null
SELECT USAGE_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_ID;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY PRESC_ID;

---RECIPE_GROUP_NO  NUMBER(38)  Y    处方药品组号    null  null
SELECT RECIPE_GROUP_NO FROM OUTP_PRESCIPTION_DETAIL GROUP BY RECIPE_GROUP_NO;

---ADVICE_ITEM_CODE  VARCHAR2(50)  Y    医嘱项目编码/处方药物编码    null  null
SELECT ADVICE_ITEM_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目名称/处方药物名称    null  null
SELECT ADVICE_ITEM_CONTENT FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE;

---DRUG_SPEC  VARCHAR2(20)  Y    药物规格    null  null
SELECT DRUG_SPEC FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_SPEC;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  Y    药物剂型代码    null  null
SELECT DRUG_DOSAGE_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE  NUMBER(5,2)  Y    药物使用次剂    null  null
SELECT DRUG_DOSAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DOSAGE_UNIT FROM OUTP_PRESCIPTION_DETAIL GROUP BY DOSAGE_UNIT;

---DRUG_USAGE_FREQUENCY  VARCHAR2(2)  Y    药物使用频次代码    null  null
SELECT DRUG_USAGE_FREQUENCY FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE_FREQUENCY;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码    null  null
SELECT ROUTE_ADMINISTRATION FROM OUTP_PRESCIPTION_DETAIL GROUP BY ROUTE_ADMINISTRATION;

---USAGE_DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT USAGE_DOSAGE_TOTAL FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_DOSAGE_TOTAL;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM OUTP_PRESCIPTION_DETAIL GROUP BY LAST_MODIFIC_TIME;

---USAGE_ID  VARCHAR2(50)      药品ID    null  null
SELECT USAGE_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_ID;

---PRESC_ID  VARCHAR2(50)      处方编号    null  null
SELECT PRESC_ID FROM OUTP_PRESCIPTION_DETAIL GROUP BY PRESC_ID;

---RECIPE_GROUP_NO  NUMBER(38)  Y    处方药品组号    null  null
SELECT RECIPE_GROUP_NO FROM OUTP_PRESCIPTION_DETAIL GROUP BY RECIPE_GROUP_NO;

---ADVICE_ITEM_CODE  VARCHAR2(50)  Y    医嘱项目编码/处方药物编码    null  null
SELECT ADVICE_ITEM_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目名称/处方药物名称    null  null
SELECT ADVICE_ITEM_CONTENT FROM OUTP_PRESCIPTION_DETAIL GROUP BY ADVICE_ITEM_CONTENT;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE;

---DRUG_SPEC  VARCHAR2(20)  Y    药物规格    null  null
SELECT DRUG_SPEC FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_SPEC;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  Y    药物剂型代码    null  null
SELECT DRUG_DOSAGE_CODE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE  NUMBER(5,2)  Y    药物使用次剂    null  null
SELECT DRUG_DOSAGE FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_DOSAGE;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DOSAGE_UNIT FROM OUTP_PRESCIPTION_DETAIL GROUP BY DOSAGE_UNIT;

---DRUG_USAGE_FREQUENCY  VARCHAR2(2)  Y    药物使用频次代码    null  null
SELECT DRUG_USAGE_FREQUENCY FROM OUTP_PRESCIPTION_DETAIL GROUP BY DRUG_USAGE_FREQUENCY;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码    null  null
SELECT ROUTE_ADMINISTRATION FROM OUTP_PRESCIPTION_DETAIL GROUP BY ROUTE_ADMINISTRATION;

---USAGE_DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT USAGE_DOSAGE_TOTAL FROM OUTP_PRESCIPTION_DETAIL GROUP BY USAGE_DOSAGE_TOTAL;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间    null  null
SELECT LAST_MODIFIC_TIME FROM OUTP_PRESCIPTION_DETAIL GROUP BY LAST_MODIFIC_TIME;

