---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM BSVISIT_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM BSVISIT_INFO GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM BSVISIT_INFO GROUP BY PATIENT_ID;

---VISIT_TYPE_NO  NUMBER(1)  Y    患者类型代码    null  null
SELECT VISIT_TYPE_NO FROM BSVISIT_INFO GROUP BY VISIT_TYPE_NO;

---MEDICAL_INSURANCE_TYPE  NUMBER(1)  Y    患者医保类型    null  null
SELECT MEDICAL_INSURANCE_TYPE FROM BSVISIT_INFO GROUP BY MEDICAL_INSURANCE_TYPE;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTP_NO FROM BSVISIT_INFO GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  null
SELECT INP_NO FROM BSVISIT_INFO GROUP BY INP_NO;

---VISIT_DATETIME  DATE  Y    就诊日期时间    null  null
SELECT VISIT_DATETIME FROM BSVISIT_INFO GROUP BY VISIT_DATETIME;

---INP_DATETIME  DATE  Y    入院日期时间    null  null
SELECT INP_DATETIME FROM BSVISIT_INFO GROUP BY INP_DATETIME;

---DISHOSPITAL_DATETIME  DATE  Y    出院日期时间    null  null
SELECT DISHOSPITAL_DATETIME FROM BSVISIT_INFO GROUP BY DISHOSPITAL_DATETIME;

---MORBIDITY_DATETIME  DATE  Y    发病日期时间    null  null
SELECT MORBIDITY_DATETIME FROM BSVISIT_INFO GROUP BY MORBIDITY_DATETIME;

---CLINIC_REASON  VARCHAR2(100)  Y    就诊原因    null  null
SELECT CLINIC_REASON FROM BSVISIT_INFO GROUP BY CLINIC_REASON;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    null  null
SELECT AGE_YEAR FROM BSVISIT_INFO GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    null  null
SELECT PATIENT_MONTH FROM BSVISIT_INFO GROUP BY PATIENT_MONTH;

---DEPT_NAME  VARCHAR2(50)  Y    就诊科室名称    null  null
SELECT DEPT_NAME FROM BSVISIT_INFO GROUP BY DEPT_NAME;

---AREA_NAME  VARCHAR2(50)  Y    病区名称    null  null
SELECT AREA_NAME FROM BSVISIT_INFO GROUP BY AREA_NAME;

---ROOM_NO  VARCHAR2(10)  Y    病房号    null  null
SELECT ROOM_NO FROM BSVISIT_INFO GROUP BY ROOM_NO;

---BED_NO  VARCHAR2(10)  Y    病床号    null  null
SELECT BED_NO FROM BSVISIT_INFO GROUP BY BED_NO;

---BODY_WEIGHT  NUMBER(6,2)  Y    体重（kg）    null  null
SELECT BODY_WEIGHT FROM BSVISIT_INFO GROUP BY BODY_WEIGHT;

---HEIGHT  NUMBER(5,1)  Y    身高    null  null
SELECT HEIGHT FROM BSVISIT_INFO GROUP BY HEIGHT;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSVISIT_INFO GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM BSVISIT_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM BSVISIT_INFO GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM BSVISIT_INFO GROUP BY PATIENT_ID;

---VISIT_TYPE_NO  NUMBER(1)  Y    患者类型代码    null  null
SELECT VISIT_TYPE_NO FROM BSVISIT_INFO GROUP BY VISIT_TYPE_NO;

---MEDICAL_INSURANCE_TYPE  NUMBER(1)  Y    患者医保类型    null  null
SELECT MEDICAL_INSURANCE_TYPE FROM BSVISIT_INFO GROUP BY MEDICAL_INSURANCE_TYPE;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTP_NO FROM BSVISIT_INFO GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  null
SELECT INP_NO FROM BSVISIT_INFO GROUP BY INP_NO;

---VISIT_DATETIME  DATE  Y    就诊日期时间    null  null
SELECT VISIT_DATETIME FROM BSVISIT_INFO GROUP BY VISIT_DATETIME;

---INP_DATETIME  DATE  Y    入院日期时间    null  null
SELECT INP_DATETIME FROM BSVISIT_INFO GROUP BY INP_DATETIME;

---DISHOSPITAL_DATETIME  DATE  Y    出院日期时间    null  null
SELECT DISHOSPITAL_DATETIME FROM BSVISIT_INFO GROUP BY DISHOSPITAL_DATETIME;

---MORBIDITY_DATETIME  DATE  Y    发病日期时间    null  null
SELECT MORBIDITY_DATETIME FROM BSVISIT_INFO GROUP BY MORBIDITY_DATETIME;

---CLINIC_REASON  VARCHAR2(100)  Y    就诊原因    null  null
SELECT CLINIC_REASON FROM BSVISIT_INFO GROUP BY CLINIC_REASON;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    null  null
SELECT AGE_YEAR FROM BSVISIT_INFO GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    null  null
SELECT PATIENT_MONTH FROM BSVISIT_INFO GROUP BY PATIENT_MONTH;

---DEPT_NAME  VARCHAR2(50)  Y    就诊科室名称    null  null
SELECT DEPT_NAME FROM BSVISIT_INFO GROUP BY DEPT_NAME;

---AREA_NAME  VARCHAR2(50)  Y    病区名称    null  null
SELECT AREA_NAME FROM BSVISIT_INFO GROUP BY AREA_NAME;

---ROOM_NO  VARCHAR2(10)  Y    病房号    null  null
SELECT ROOM_NO FROM BSVISIT_INFO GROUP BY ROOM_NO;

---BED_NO  VARCHAR2(10)  Y    病床号    null  null
SELECT BED_NO FROM BSVISIT_INFO GROUP BY BED_NO;

---BODY_WEIGHT  NUMBER(6,2)  Y    体重（kg）    null  null
SELECT BODY_WEIGHT FROM BSVISIT_INFO GROUP BY BODY_WEIGHT;

---HEIGHT  NUMBER(5,1)  Y    身高    null  null
SELECT HEIGHT FROM BSVISIT_INFO GROUP BY HEIGHT;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSVISIT_INFO GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM BSVISIT_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM BSVISIT_INFO GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM BSVISIT_INFO GROUP BY PATIENT_ID;

---VISIT_TYPE_NO  NUMBER(1)  Y    患者类型代码    null  null
SELECT VISIT_TYPE_NO FROM BSVISIT_INFO GROUP BY VISIT_TYPE_NO;

---MEDICAL_INSURANCE_TYPE  NUMBER(1)  Y    患者医保类型    null  null
SELECT MEDICAL_INSURANCE_TYPE FROM BSVISIT_INFO GROUP BY MEDICAL_INSURANCE_TYPE;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTP_NO FROM BSVISIT_INFO GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    null  null
SELECT INP_NO FROM BSVISIT_INFO GROUP BY INP_NO;

---VISIT_DATETIME  DATE  Y    就诊日期时间    null  null
SELECT VISIT_DATETIME FROM BSVISIT_INFO GROUP BY VISIT_DATETIME;

---INP_DATETIME  DATE  Y    入院日期时间    null  null
SELECT INP_DATETIME FROM BSVISIT_INFO GROUP BY INP_DATETIME;

---DISHOSPITAL_DATETIME  DATE  Y    出院日期时间    null  null
SELECT DISHOSPITAL_DATETIME FROM BSVISIT_INFO GROUP BY DISHOSPITAL_DATETIME;

---MORBIDITY_DATETIME  DATE  Y    发病日期时间    null  null
SELECT MORBIDITY_DATETIME FROM BSVISIT_INFO GROUP BY MORBIDITY_DATETIME;

---CLINIC_REASON  VARCHAR2(100)  Y    就诊原因    null  null
SELECT CLINIC_REASON FROM BSVISIT_INFO GROUP BY CLINIC_REASON;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    null  null
SELECT AGE_YEAR FROM BSVISIT_INFO GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    null  null
SELECT PATIENT_MONTH FROM BSVISIT_INFO GROUP BY PATIENT_MONTH;

---DEPT_NAME  VARCHAR2(50)  Y    就诊科室名称    null  null
SELECT DEPT_NAME FROM BSVISIT_INFO GROUP BY DEPT_NAME;

---AREA_NAME  VARCHAR2(50)  Y    病区名称    null  null
SELECT AREA_NAME FROM BSVISIT_INFO GROUP BY AREA_NAME;

---ROOM_NO  VARCHAR2(10)  Y    病房号    null  null
SELECT ROOM_NO FROM BSVISIT_INFO GROUP BY ROOM_NO;

---BED_NO  VARCHAR2(10)  Y    病床号    null  null
SELECT BED_NO FROM BSVISIT_INFO GROUP BY BED_NO;

---BODY_WEIGHT  NUMBER(6,2)  Y    体重（kg）    null  null
SELECT BODY_WEIGHT FROM BSVISIT_INFO GROUP BY BODY_WEIGHT;

---HEIGHT  NUMBER(5,1)  Y    身高    null  null
SELECT HEIGHT FROM BSVISIT_INFO GROUP BY HEIGHT;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSVISIT_INFO GROUP BY LAST_MODIFIC_TIME;

