---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM INPATIENT_MEDICAL_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_ID;

---ORG_NAME  VARCHAR2(70)  Y    医疗机构名称    S1  AN..70
SELECT ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY ORG_NAME;

---ORGAN_CODE  VARCHAR2(70)  Y    医疗机构组织机构代码  应符合国标：WS 218—2002  S3  AN10
SELECT ORGAN_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ORGAN_CODE;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  应符合国标：CV07.10.005  S3  N2
SELECT PAY_WAY FROM INPATIENT_MEDICAL_RECORD GROUP BY PAY_WAY;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY HEALTH_CARD_NO;

---INHOS_COUNT  NUMBER(2)  Y    住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_NO;

---MR_NO  VARCHAR2(18)  Y    病案号    S1  AN..18
SELECT MR_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_NO;

---PATIENT_NAME  VARCHAR2(50)  Y    姓名    S1  A..50
SELECT PATIENT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_NAME;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT PATIENT_SEX FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_SEX;

---BIRTHDAY  DATE  Y    出生日期    D  D8
SELECT BIRTHDAY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHDAY;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    N  N1..3
SELECT AGE_YEAR FROM INPATIENT_MEDICAL_RECORD GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    S1  AN..8
SELECT PATIENT_MONTH FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_MONTH;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码  应符合国标：GB/T 2659—2000  S3  AN3
SELECT NATIONNALITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIONNALITY;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_INP_WEIGHT  NUMBER(4)  Y    新生儿入院体重(g)    N  N2..4
SELECT NEWBORN_INP_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_INP_WEIGHT;

---BIRTHPLACE_PROVINCE  VARCHAR2(70)  Y    出生地-省（自治区、直辖市）    S1  AN..70
SELECT BIRTHPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_PROVINCE;

---BIRTHPLACE_CITY  VARCHAR2(70)  Y    出生地-市（地区、州）    S1  AN..70
SELECT BIRTHPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_CITY;

---BIRTHPLACE_COUNTY  VARCHAR2(70)  Y    出生地-县（区）    S1  AN..70
SELECT BIRTHPLACE_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_COUNTY;

---NATIVEPLACE_PROVINCE  VARCHAR2(70)  Y    籍贯-省（自治区、直辖市）    S1  AN..70
SELECT NATIVEPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_PROVINCE;

---NATIVEPLACE_CITY  VARCHAR2(70)  Y    籍贯-市（地区、州）    S1  AN..70
SELECT NATIVEPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_CITY;

---NATION  VARCHAR2(2)  Y    民族  应符合国标：GB/T 3304-1991  S3  N2
SELECT NATION FROM INPATIENT_MEDICAL_RECORD GROUP BY NATION;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码  应符合国标：WS 364.3—2011 表 1CV02.01.101身份征件类别代码表  S3  N2
SELECT IDENTITY_TYPE FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_TYPE;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    S1  AN..18
SELECT IDENTITY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_NO;

---OCCUPATION_TYPE_CODE  VARCHAR2(2)  Y    职业类别代码  应符合国标：GB/T 2261.4—2003  S3  N2
SELECT OCCUPATION_TYPE_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY OCCUPATION_TYPE_CODE;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码  应符合国标：GB/T 2261.2—2003  S3  N2
SELECT MARITAL_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MARITAL_STATUS_CODE;

---CURRENT_PROVINCE  VARCHAR2(70)  Y    现住址-省（自治区、直辖市）    S1  AN..70
SELECT CURRENT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PROVINCE;

---CURRENT_CITY  VARCHAR2(70)  Y    现住址-市（地区、州）    S1  AN..70
SELECT CURRENT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_CITY;

---CURRENT_COUNTY  VARCHAR2(70)  Y    现住址-县（区）    S1  AN..70
SELECT CURRENT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_COUNTY;

---CURRENT_TOWNSHIP  VARCHAR2(70)  Y    现住址-乡（镇、街道办事处）    S1  AN..70
SELECT CURRENT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_TOWNSHIP;

---CURRENT_VILLAGE  VARCHAR2(70)  Y    现住址-村（街、路、弄等）    S1  AN..70
SELECT CURRENT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_VILLAGE;

---CURRENT_DOORS  VARCHAR2(70)  Y    现住址-门牌号码    S1  AN..70
SELECT CURRENT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_DOORS;

---CURRENT_PHONE  VARCHAR2(20)  Y    电话号码    S1  AN..20
SELECT CURRENT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PHONE;

---CURRENT_ZIP_CODE  VARCHAR2(6)  Y    现住址-邮政编码    S1  N6
SELECT CURRENT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_ZIP_CODE;

---ACCOUNT_PROVINCE  VARCHAR2(70)  Y    户口地址-省（自治区、直辖市）    S1  AN..70
SELECT ACCOUNT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_PROVINCE;

---ACCOUNT_CITY  VARCHAR2(70)  Y    户口地址-市（地区、州）    S1  AN..70
SELECT ACCOUNT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_CITY;

---ACCOUNT_COUNTY  VARCHAR2(70)  Y    户口地址-县（区）    S1  AN..70
SELECT ACCOUNT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_COUNTY;

---ACCOUNT_TOWNSHIP  VARCHAR2(70)  Y    户口地址-乡（镇、街道办事处）    S1  AN..70
SELECT ACCOUNT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_TOWNSHIP;

---ACCOUNT_VILLAGE  VARCHAR2(70)  Y    户口地址-村（街、路、弄等）    S1  AN..70
SELECT ACCOUNT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_VILLAGE;

---ACCOUNT_DOORS  VARCHAR2(70)  Y    户口地址-门牌号码    S1  AN..70
SELECT ACCOUNT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_DOORS;

---ACCOUNT_ZIP_CODE  VARCHAR2(6)  Y    户口地址-邮政编码    S1  N6
SELECT ACCOUNT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_ZIP_CODE;

---WORKUNIT_NAME  VARCHAR2(70)  Y    工作单位名称    S1  AN..70
SELECT WORKUNIT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_NAME;

---WORKUNIT_PROVINCE  VARCHAR2(70)  Y    工作单位地址-省（自治区、直辖市）    S1  AN..70
SELECT WORKUNIT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PROVINCE;

---WORKUNIT_CITY  VARCHAR2(70)  Y    工作单位地址-市（地区、州）    S1  AN..70
SELECT WORKUNIT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_CITY;

---WORKUNIT_COUNTY  VARCHAR2(70)  Y    工作单位地址-县（区）    S1  AN..70
SELECT WORKUNIT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_COUNTY;

---WORKUNIT_TOWNSHIP  VARCHAR2(70)  Y    工作单位地址-乡（镇、街道办事处）    S1  AN..70
SELECT WORKUNIT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_TOWNSHIP;

---WORKUNIT_VILLAGE  VARCHAR2(70)  Y    工作单位地址-村（街、路、弄等）    S1  AN..70
SELECT WORKUNIT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_VILLAGE;

---WORKUNIT_DOORS  VARCHAR2(70)  Y    工作单位地址-门牌号码    S1  AN..70
SELECT WORKUNIT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_DOORS;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    S1  AN..20
SELECT WORKUNIT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PHONE;

---WORKUNIT_ZIP_CODE  VARCHAR2(6)  Y    工作单位地址-邮政编码    S1  N6
SELECT WORKUNIT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_ZIP_CODE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    S1  A..50
SELECT CONTACT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_NAME;

---RELATION  VARCHAR2(1)  Y    联系人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION FROM INPATIENT_MEDICAL_RECORD GROUP BY RELATION;

---CAPROVINCE  VARCHAR2(70)  Y    联系人地址-省（自治区、直辖市）    S1  AN..70
SELECT CAPROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CAPROVINCE;

---CACITY  VARCHAR2(70)  Y    联系人地址-市（地区、州）    S1  AN..70
SELECT CACITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACITY;

---CACOUNTY  VARCHAR2(70)  Y    联系人地址-县（区）    S1  AN..70
SELECT CACOUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACOUNTY;

---CATOWN_SHIP  VARCHAR2(70)  Y    联系人地址-乡（镇、街道办事处）    S1  AN..70
SELECT CATOWN_SHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CATOWN_SHIP;

---CASTREET  VARCHAR2(70)  Y    联系人地址-村（街、路、弄等）    S1  AN..70
SELECT CASTREET FROM INPATIENT_MEDICAL_RECORD GROUP BY CASTREET;

---CAHOUSE_NUMBER  VARCHAR2(70)  Y    联系人地址-门牌号码    S1  AN..70
SELECT CAHOUSE_NUMBER FROM INPATIENT_MEDICAL_RECORD GROUP BY CAHOUSE_NUMBER;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    S1  AN..20
SELECT CONTACT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_PHONE;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_APPROACH_CODE;

---INP_DATE  DATE  Y    入院日期时间    DT  DT15
SELECT INP_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DATE;

---INP_DEPT_NAME  VARCHAR2(50)  Y    入院科别    S1  AN..50
SELECT INP_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DEPT_NAME;

---INP_ROOM  VARCHAR2(10)  Y    入院病房    S1  AN..10
SELECT INP_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_ROOM;

---TRANSITION_DEP  VARCHAR2(50)  Y    转科科别    S1  AN..50
SELECT TRANSITION_DEP FROM INPATIENT_MEDICAL_RECORD GROUP BY TRANSITION_DEP;

---DISHOSPITAL_DATE  DATE  Y    出院日期时间    DT  DT15
SELECT DISHOSPITAL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DATE;

---DISHOSPITAL_DEPT_NAME  VARCHAR2(50)  Y    出院科别    S1  AN..50
SELECT DISHOSPITAL_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DEPT_NAME;

---DISHOSPITAL_ROOM  VARCHAR2(10)  Y    出院病房    S1  AN..10
SELECT DISHOSPITAL_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_ROOM;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    .N  N..4
SELECT INP_DAYS FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DAYS;

---PATHOLOGY_NO  VARCHAR2(18)  Y    病理号    S1  AN..18
SELECT PATHOLOGY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY PATHOLOGY_NO;

---DRUG_ALLERGY_FLAG  VARCHAR2(5)  Y    药物过敏标志  TRUE/FALSE  L  T/F
SELECT DRUG_ALLERGY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ALLERGY_FLAG;

---ALLERGY_DRUG  VARCHAR2(1000)  Y    过敏药物    S1  AN..1000
SELECT ALLERGY_DRUG FROM INPATIENT_MEDICAL_RECORD GROUP BY ALLERGY_DRUG;

---INHOS_AUTOPSY_FLAG  VARCHAR2(5)  Y    死亡患者尸检标志  TRUE/FALSE  L  T/F
SELECT INHOS_AUTOPSY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_AUTOPSY_FLAG;

---BLOOD_ABO_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国标：WS 364.9—2011 表 5  S3  N1
SELECT BLOOD_ABO_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ABO_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国标：CV04.50.020  S3  N1
SELECT RH_BLOOD_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY RH_BLOOD_CODE;

---DEPT_DIRECTOR_SIGN  VARCHAR2(50)  Y    科主任签名    S1  A..50
SELECT DEPT_DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DEPT_DIRECTOR_SIGN;

---DIRECTOR_SIGN  VARCHAR2(50)  Y    主任（副主任）医师签名    S1  A..50
SELECT DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DIRECTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DOCTOR_SIGN;

---DUTY_NURSE_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT DUTY_NURSE_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DUTY_NURSE_SIGN;

---REFRESHER_DOCTOR_SIGN  VARCHAR2(50)  Y    进修医师签名    S1  A..50
SELECT REFRESHER_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY REFRESHER_DOCTOR_SIGN;

---INTERNSHIP_DOCTOR_SIGN  VARCHAR2(50)  Y    实习医师签名    S1  A..50
SELECT INTERNSHIP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INTERNSHIP_DOCTOR_SIGN;

---CODER_SIGN  VARCHAR2(50)  Y    编码员签名    S1  A..50
SELECT CODER_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY CODER_SIGN;

---MR_QUALITY_CODE  NUMBER(1)  Y    病案质量代码  标准值：1,甲  2.乙  3.丙  S2  N1
SELECT MR_QUALITY_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_QUALITY_CODE;

---QC_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    质控医师签名    S1  A..50
SELECT QC_DOCTOR_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_DOCTOR_SIGNATURE;

---QC_NURSE_SIGNATURE  VARCHAR2(50)  Y    质控护士签名    S1  A..50
SELECT QC_NURSE_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_NURSE_SIGNATURE;

---QUALITYCONTROL_DATE  DATE  Y    质控日期    D  D8
SELECT QUALITYCONTROL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY QUALITYCONTROL_DATE;

---DISHOSPITAL_DISPOSITION_CODE  VARCHAR2(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---RECEIVE_ORG_NAME  VARCHAR2(70)  Y    拟接收医疗机构名称    S1  AN..70
SELECT RECEIVE_ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY RECEIVE_ORG_NAME;

---OUTHOS_FLAG  VARCHAR2(5)  Y    出院31天内再住院标志  TRUE/FALSE  L  T/F
SELECT OUTHOS_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_FLAG;

---OUTHOS_PURPOSE  VARCHAR2(100)  Y    出院31天内再住院目的    S1  AN..100
SELECT OUTHOS_PURPOSE FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_PURPOSE;

---HEADINJURY_INPBEFORECOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院前昏迷时间-d    N  N..5
SELECT HEADINJURY_INPBEFORECOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_DAY;

---HEADINJURY_INPBEFORECOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-h    N  N..2
SELECT HEADINJURY_INPBEFORECOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_HOUR;

---HEADINJURY_INPBEFORE_MIN  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-min    N  N..2
SELECT HEADINJURY_INPBEFORE_MIN FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORE_MIN;

---HEADINJURY_INPAFTERCOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院后昏迷时间-d    N  N..5
SELECT HEADINJURY_INPAFTERCOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_DAY;

---HEADINJURY_INPAFTERCOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-h    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_HOUR;

---HEADINJURY_INPAFTERCOMA_MINUTE  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-min    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_MINUTE FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_MINUTE;

---INP_TOTALCOST  NUMBER(10,2)  Y    住院总费用    N  N..10,2
SELECT INP_TOTALCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST;

---INP_TOTALCOST_OWNPAY  NUMBER(10,2)  Y    住院总费用-自付金额    N  N..10,2
SELECT INP_TOTALCOST_OWNPAY FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST_OWNPAY;

---MEDICAL_COMMONLYSERVICE_COST  NUMBER(10,2)  Y    综合医疗服务类-一般医疗服务费    N  N..10,2
SELECT MEDICAL_COMMONLYSERVICE_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYSERVICE_COST;

---MEDICAL_COMMONLYOPERATION_COST  NUMBER(10,2)  Y    综合医疗服务类-一般治疗操作费    N  N..10,2
SELECT MEDICAL_COMMONLYOPERATION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYOPERATION_COST;

---MEDICAL_NURSING_COST  NUMBER(10,2)  Y    综合医疗服务类-护理费    N  N..10,2
SELECT MEDICAL_NURSING_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_NURSING_COST;

---MEDICAL_OTHER_COST  NUMBER(10,2)  Y    综合医疗服务类-其他费用    N  N..10,2
SELECT MEDICAL_OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_OTHER_COST;

---DIAG_PATHOLOGY_COST  NUMBER(10,2)  Y    诊断类-病理诊断费    N  N..10,2
SELECT DIAG_PATHOLOGY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_PATHOLOGY_COST;

---DIAG_LABORATORY_COST  NUMBER(10,2)  Y    诊断类-实验室诊断费    N  N..10,2
SELECT DIAG_LABORATORY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_LABORATORY_COST;

---IMAGING_DIAGNOSIS_EXPENSE  NUMBER(10,2)  Y    诊断类-影像学诊断费    N  N..10,2
SELECT IMAGING_DIAGNOSIS_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY IMAGING_DIAGNOSIS_EXPENSE;

---DIAG_CLINICAL_COST  NUMBER(10,2)  Y    诊断类-临床诊断项目费    N  N..10,2
SELECT DIAG_CLINICAL_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_CLINICAL_COST;

---TREAT_NOOPERATION_ITEMCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费    N  N..10,2
SELECT TREAT_NOOPERATION_ITEMCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_ITEMCOST;

---TREAT_NOOPERATION_PHYSICSCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费-临床物理治疗费    N  N..10,2
SELECT TREAT_NOOPERATION_PHYSICSCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_PHYSICSCOST;

---TREAT_OPERATIONTREAT_COST  NUMBER(10,2)  Y    治疗类-手术治疗费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_COST;

---TREAT_OPER_ANAESTHESIACOST  NUMBER(10,2)  Y    治疗类-手术治疗费-麻醉费    N  N..10,2
SELECT TREAT_OPER_ANAESTHESIACOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPER_ANAESTHESIACOST;

---TREAT_OPERATIONTREAT_OPERCOST  NUMBER(10,2)  Y    治疗类-手术治疗费-手术费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_OPERCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_OPERCOST;

---RECOVERY_COST  NUMBER(10,2)  Y    康复类-康复费    N  N..10,2
SELECT RECOVERY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY RECOVERY_COST;

---TCM_TREAT_COST  NUMBER(10,2)  Y    中医类-中医治疗费    N  N..10,2
SELECT TCM_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCM_TREAT_COST;

---DRUG_COST  NUMBER(10,2)  Y    西药类-西药费    N  N..10,2
SELECT DRUG_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_COST;

---DRUG_ANTIBIOTICS_COST  NUMBER(10,2)  Y    西药类-西药费-抗菌药物费用    N  N..10,2
SELECT DRUG_ANTIBIOTICS_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ANTIBIOTICS_COST;

---PROPRIETARY_CM_EXPENSE  NUMBER(10,2)  Y    中药类-中成药费    N  N..10,2
SELECT PROPRIETARY_CM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY PROPRIETARY_CM_EXPENSE;

---TCD_CHM_COST  NUMBER(10,2)  Y    中药类-中草药费    N  N..10,2
SELECT TCD_CHM_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCD_CHM_COST;

---BLOOD_COST  NUMBER(10,2)  Y    血液和血液制品类-血费    N  N..10,2
SELECT BLOOD_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COST;

---BLOOD_ALBURMIN_COST  NUMBER(10,2)  Y    血液和血液制品类-白蛋白类制品费    N  N..10,2
SELECT BLOOD_ALBURMIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ALBURMIN_COST;

---BLOOD_GLOBULIN_COST  NUMBER(10,2)  Y    血液和血液制品类-球蛋白类制品费    N  N..10,2
SELECT BLOOD_GLOBULIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_GLOBULIN_COST;

---BLOOD_COGULATIONFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-凝血因子类制品费    N  N..10,2
SELECT BLOOD_COGULATIONFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COGULATIONFACTOR_COST;

---BLOOD_CELLFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-细胞因子类制品费    N  N..10,2
SELECT BLOOD_CELLFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_CELLFACTOR_COST;

---CHECK_DMM_EXPENSE  NUMBER(10,2)  Y    耗材类-检查用一次性医用材料费    N  N..10,2
SELECT CHECK_DMM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY CHECK_DMM_EXPENSE;

---EXP_TREAT_COST  NUMBER(10,2)  Y    耗材类-治疗用一次性医用材料费    N  N..10,2
SELECT EXP_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_TREAT_COST;

---EXP_OPERTION_COST  NUMBER(10,2)  Y    耗材类-手术用一次性医用材料费    N  N..10,2
SELECT EXP_OPERTION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_OPERTION_COST;

---OTHER_COST  NUMBER(10,2)  Y    其他类-其他费    N  N..10,2
SELECT OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY OTHER_COST;

---DISEASE_STATUS_CODE  VARCHAR2(2)  Y    住院者疾病状态代码  应符合国标：CV05.01.001    
SELECT DISEASE_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISEASE_STATUS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_MEDICAL_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM INPATIENT_MEDICAL_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_ID;

---ORG_NAME  VARCHAR2(70)  Y    医疗机构名称    S1  AN..70
SELECT ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY ORG_NAME;

---ORGAN_CODE  VARCHAR2(70)  Y    医疗机构组织机构代码  应符合国标：WS 218—2002  S3  AN10
SELECT ORGAN_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ORGAN_CODE;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  应符合国标：CV07.10.005  S3  N2
SELECT PAY_WAY FROM INPATIENT_MEDICAL_RECORD GROUP BY PAY_WAY;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY HEALTH_CARD_NO;

---INHOS_COUNT  NUMBER(2)  Y    住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_NO;

---MR_NO  VARCHAR2(18)  Y    病案号    S1  AN..18
SELECT MR_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_NO;

---PATIENT_NAME  VARCHAR2(50)  Y    姓名    S1  A..50
SELECT PATIENT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_NAME;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT PATIENT_SEX FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_SEX;

---BIRTHDAY  DATE  Y    出生日期    D  D8
SELECT BIRTHDAY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHDAY;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    N  N1..3
SELECT AGE_YEAR FROM INPATIENT_MEDICAL_RECORD GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    S1  AN..8
SELECT PATIENT_MONTH FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_MONTH;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码  应符合国标：GB/T 2659—2000  S3  AN3
SELECT NATIONNALITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIONNALITY;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_INP_WEIGHT  NUMBER(4)  Y    新生儿入院体重(g)    N  N2..4
SELECT NEWBORN_INP_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_INP_WEIGHT;

---BIRTHPLACE_PROVINCE  VARCHAR2(70)  Y    出生地-省（自治区、直辖市）    S1  AN..70
SELECT BIRTHPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_PROVINCE;

---BIRTHPLACE_CITY  VARCHAR2(70)  Y    出生地-市（地区、州）    S1  AN..70
SELECT BIRTHPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_CITY;

---BIRTHPLACE_COUNTY  VARCHAR2(70)  Y    出生地-县（区）    S1  AN..70
SELECT BIRTHPLACE_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_COUNTY;

---NATIVEPLACE_PROVINCE  VARCHAR2(70)  Y    籍贯-省（自治区、直辖市）    S1  AN..70
SELECT NATIVEPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_PROVINCE;

---NATIVEPLACE_CITY  VARCHAR2(70)  Y    籍贯-市（地区、州）    S1  AN..70
SELECT NATIVEPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_CITY;

---NATION  VARCHAR2(2)  Y    民族  应符合国标：GB/T 3304-1991  S3  N2
SELECT NATION FROM INPATIENT_MEDICAL_RECORD GROUP BY NATION;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码  应符合国标：WS 364.3—2011 表 1CV02.01.101身份征件类别代码表  S3  N2
SELECT IDENTITY_TYPE FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_TYPE;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    S1  AN..18
SELECT IDENTITY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_NO;

---OCCUPATION_TYPE_CODE  VARCHAR2(2)  Y    职业类别代码  应符合国标：GB/T 2261.4—2003  S3  N2
SELECT OCCUPATION_TYPE_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY OCCUPATION_TYPE_CODE;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码  应符合国标：GB/T 2261.2—2003  S3  N2
SELECT MARITAL_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MARITAL_STATUS_CODE;

---CURRENT_PROVINCE  VARCHAR2(70)  Y    现住址-省（自治区、直辖市）    S1  AN..70
SELECT CURRENT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PROVINCE;

---CURRENT_CITY  VARCHAR2(70)  Y    现住址-市（地区、州）    S1  AN..70
SELECT CURRENT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_CITY;

---CURRENT_COUNTY  VARCHAR2(70)  Y    现住址-县（区）    S1  AN..70
SELECT CURRENT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_COUNTY;

---CURRENT_TOWNSHIP  VARCHAR2(70)  Y    现住址-乡（镇、街道办事处）    S1  AN..70
SELECT CURRENT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_TOWNSHIP;

---CURRENT_VILLAGE  VARCHAR2(70)  Y    现住址-村（街、路、弄等）    S1  AN..70
SELECT CURRENT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_VILLAGE;

---CURRENT_DOORS  VARCHAR2(70)  Y    现住址-门牌号码    S1  AN..70
SELECT CURRENT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_DOORS;

---CURRENT_PHONE  VARCHAR2(20)  Y    电话号码    S1  AN..20
SELECT CURRENT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PHONE;

---CURRENT_ZIP_CODE  VARCHAR2(6)  Y    现住址-邮政编码    S1  N6
SELECT CURRENT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_ZIP_CODE;

---ACCOUNT_PROVINCE  VARCHAR2(70)  Y    户口地址-省（自治区、直辖市）    S1  AN..70
SELECT ACCOUNT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_PROVINCE;

---ACCOUNT_CITY  VARCHAR2(70)  Y    户口地址-市（地区、州）    S1  AN..70
SELECT ACCOUNT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_CITY;

---ACCOUNT_COUNTY  VARCHAR2(70)  Y    户口地址-县（区）    S1  AN..70
SELECT ACCOUNT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_COUNTY;

---ACCOUNT_TOWNSHIP  VARCHAR2(70)  Y    户口地址-乡（镇、街道办事处）    S1  AN..70
SELECT ACCOUNT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_TOWNSHIP;

---ACCOUNT_VILLAGE  VARCHAR2(70)  Y    户口地址-村（街、路、弄等）    S1  AN..70
SELECT ACCOUNT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_VILLAGE;

---ACCOUNT_DOORS  VARCHAR2(70)  Y    户口地址-门牌号码    S1  AN..70
SELECT ACCOUNT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_DOORS;

---ACCOUNT_ZIP_CODE  VARCHAR2(6)  Y    户口地址-邮政编码    S1  N6
SELECT ACCOUNT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_ZIP_CODE;

---WORKUNIT_NAME  VARCHAR2(70)  Y    工作单位名称    S1  AN..70
SELECT WORKUNIT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_NAME;

---WORKUNIT_PROVINCE  VARCHAR2(70)  Y    工作单位地址-省（自治区、直辖市）    S1  AN..70
SELECT WORKUNIT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PROVINCE;

---WORKUNIT_CITY  VARCHAR2(70)  Y    工作单位地址-市（地区、州）    S1  AN..70
SELECT WORKUNIT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_CITY;

---WORKUNIT_COUNTY  VARCHAR2(70)  Y    工作单位地址-县（区）    S1  AN..70
SELECT WORKUNIT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_COUNTY;

---WORKUNIT_TOWNSHIP  VARCHAR2(70)  Y    工作单位地址-乡（镇、街道办事处）    S1  AN..70
SELECT WORKUNIT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_TOWNSHIP;

---WORKUNIT_VILLAGE  VARCHAR2(70)  Y    工作单位地址-村（街、路、弄等）    S1  AN..70
SELECT WORKUNIT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_VILLAGE;

---WORKUNIT_DOORS  VARCHAR2(70)  Y    工作单位地址-门牌号码    S1  AN..70
SELECT WORKUNIT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_DOORS;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    S1  AN..20
SELECT WORKUNIT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PHONE;

---WORKUNIT_ZIP_CODE  VARCHAR2(6)  Y    工作单位地址-邮政编码    S1  N6
SELECT WORKUNIT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_ZIP_CODE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    S1  A..50
SELECT CONTACT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_NAME;

---RELATION  VARCHAR2(1)  Y    联系人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION FROM INPATIENT_MEDICAL_RECORD GROUP BY RELATION;

---CAPROVINCE  VARCHAR2(70)  Y    联系人地址-省（自治区、直辖市）    S1  AN..70
SELECT CAPROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CAPROVINCE;

---CACITY  VARCHAR2(70)  Y    联系人地址-市（地区、州）    S1  AN..70
SELECT CACITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACITY;

---CACOUNTY  VARCHAR2(70)  Y    联系人地址-县（区）    S1  AN..70
SELECT CACOUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACOUNTY;

---CATOWN_SHIP  VARCHAR2(70)  Y    联系人地址-乡（镇、街道办事处）    S1  AN..70
SELECT CATOWN_SHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CATOWN_SHIP;

---CASTREET  VARCHAR2(70)  Y    联系人地址-村（街、路、弄等）    S1  AN..70
SELECT CASTREET FROM INPATIENT_MEDICAL_RECORD GROUP BY CASTREET;

---CAHOUSE_NUMBER  VARCHAR2(70)  Y    联系人地址-门牌号码    S1  AN..70
SELECT CAHOUSE_NUMBER FROM INPATIENT_MEDICAL_RECORD GROUP BY CAHOUSE_NUMBER;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    S1  AN..20
SELECT CONTACT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_PHONE;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_APPROACH_CODE;

---INP_DATE  DATE  Y    入院日期时间    DT  DT15
SELECT INP_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DATE;

---INP_DEPT_NAME  VARCHAR2(50)  Y    入院科别    S1  AN..50
SELECT INP_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DEPT_NAME;

---INP_ROOM  VARCHAR2(10)  Y    入院病房    S1  AN..10
SELECT INP_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_ROOM;

---TRANSITION_DEP  VARCHAR2(50)  Y    转科科别    S1  AN..50
SELECT TRANSITION_DEP FROM INPATIENT_MEDICAL_RECORD GROUP BY TRANSITION_DEP;

---DISHOSPITAL_DATE  DATE  Y    出院日期时间    DT  DT15
SELECT DISHOSPITAL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DATE;

---DISHOSPITAL_DEPT_NAME  VARCHAR2(50)  Y    出院科别    S1  AN..50
SELECT DISHOSPITAL_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DEPT_NAME;

---DISHOSPITAL_ROOM  VARCHAR2(10)  Y    出院病房    S1  AN..10
SELECT DISHOSPITAL_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_ROOM;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    .N  N..4
SELECT INP_DAYS FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DAYS;

---PATHOLOGY_NO  VARCHAR2(18)  Y    病理号    S1  AN..18
SELECT PATHOLOGY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY PATHOLOGY_NO;

---DRUG_ALLERGY_FLAG  VARCHAR2(5)  Y    药物过敏标志  TRUE/FALSE  L  T/F
SELECT DRUG_ALLERGY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ALLERGY_FLAG;

---ALLERGY_DRUG  VARCHAR2(1000)  Y    过敏药物    S1  AN..1000
SELECT ALLERGY_DRUG FROM INPATIENT_MEDICAL_RECORD GROUP BY ALLERGY_DRUG;

---INHOS_AUTOPSY_FLAG  VARCHAR2(5)  Y    死亡患者尸检标志  TRUE/FALSE  L  T/F
SELECT INHOS_AUTOPSY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_AUTOPSY_FLAG;

---BLOOD_ABO_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国标：WS 364.9—2011 表 5  S3  N1
SELECT BLOOD_ABO_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ABO_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国标：CV04.50.020  S3  N1
SELECT RH_BLOOD_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY RH_BLOOD_CODE;

---DEPT_DIRECTOR_SIGN  VARCHAR2(50)  Y    科主任签名    S1  A..50
SELECT DEPT_DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DEPT_DIRECTOR_SIGN;

---DIRECTOR_SIGN  VARCHAR2(50)  Y    主任（副主任）医师签名    S1  A..50
SELECT DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DIRECTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DOCTOR_SIGN;

---DUTY_NURSE_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT DUTY_NURSE_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DUTY_NURSE_SIGN;

---REFRESHER_DOCTOR_SIGN  VARCHAR2(50)  Y    进修医师签名    S1  A..50
SELECT REFRESHER_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY REFRESHER_DOCTOR_SIGN;

---INTERNSHIP_DOCTOR_SIGN  VARCHAR2(50)  Y    实习医师签名    S1  A..50
SELECT INTERNSHIP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INTERNSHIP_DOCTOR_SIGN;

---CODER_SIGN  VARCHAR2(50)  Y    编码员签名    S1  A..50
SELECT CODER_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY CODER_SIGN;

---MR_QUALITY_CODE  NUMBER(1)  Y    病案质量代码  标准值：1,甲  2.乙  3.丙  S2  N1
SELECT MR_QUALITY_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_QUALITY_CODE;

---QC_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    质控医师签名    S1  A..50
SELECT QC_DOCTOR_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_DOCTOR_SIGNATURE;

---QC_NURSE_SIGNATURE  VARCHAR2(50)  Y    质控护士签名    S1  A..50
SELECT QC_NURSE_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_NURSE_SIGNATURE;

---QUALITYCONTROL_DATE  DATE  Y    质控日期    D  D8
SELECT QUALITYCONTROL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY QUALITYCONTROL_DATE;

---DISHOSPITAL_DISPOSITION_CODE  VARCHAR2(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---RECEIVE_ORG_NAME  VARCHAR2(70)  Y    拟接收医疗机构名称    S1  AN..70
SELECT RECEIVE_ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY RECEIVE_ORG_NAME;

---OUTHOS_FLAG  VARCHAR2(5)  Y    出院31天内再住院标志  TRUE/FALSE  L  T/F
SELECT OUTHOS_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_FLAG;

---OUTHOS_PURPOSE  VARCHAR2(100)  Y    出院31天内再住院目的    S1  AN..100
SELECT OUTHOS_PURPOSE FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_PURPOSE;

---HEADINJURY_INPBEFORECOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院前昏迷时间-d    N  N..5
SELECT HEADINJURY_INPBEFORECOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_DAY;

---HEADINJURY_INPBEFORECOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-h    N  N..2
SELECT HEADINJURY_INPBEFORECOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_HOUR;

---HEADINJURY_INPBEFORE_MIN  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-min    N  N..2
SELECT HEADINJURY_INPBEFORE_MIN FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORE_MIN;

---HEADINJURY_INPAFTERCOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院后昏迷时间-d    N  N..5
SELECT HEADINJURY_INPAFTERCOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_DAY;

---HEADINJURY_INPAFTERCOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-h    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_HOUR;

---HEADINJURY_INPAFTERCOMA_MINUTE  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-min    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_MINUTE FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_MINUTE;

---INP_TOTALCOST  NUMBER(10,2)  Y    住院总费用    N  N..10,2
SELECT INP_TOTALCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST;

---INP_TOTALCOST_OWNPAY  NUMBER(10,2)  Y    住院总费用-自付金额    N  N..10,2
SELECT INP_TOTALCOST_OWNPAY FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST_OWNPAY;

---MEDICAL_COMMONLYSERVICE_COST  NUMBER(10,2)  Y    综合医疗服务类-一般医疗服务费    N  N..10,2
SELECT MEDICAL_COMMONLYSERVICE_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYSERVICE_COST;

---MEDICAL_COMMONLYOPERATION_COST  NUMBER(10,2)  Y    综合医疗服务类-一般治疗操作费    N  N..10,2
SELECT MEDICAL_COMMONLYOPERATION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYOPERATION_COST;

---MEDICAL_NURSING_COST  NUMBER(10,2)  Y    综合医疗服务类-护理费    N  N..10,2
SELECT MEDICAL_NURSING_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_NURSING_COST;

---MEDICAL_OTHER_COST  NUMBER(10,2)  Y    综合医疗服务类-其他费用    N  N..10,2
SELECT MEDICAL_OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_OTHER_COST;

---DIAG_PATHOLOGY_COST  NUMBER(10,2)  Y    诊断类-病理诊断费    N  N..10,2
SELECT DIAG_PATHOLOGY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_PATHOLOGY_COST;

---DIAG_LABORATORY_COST  NUMBER(10,2)  Y    诊断类-实验室诊断费    N  N..10,2
SELECT DIAG_LABORATORY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_LABORATORY_COST;

---IMAGING_DIAGNOSIS_EXPENSE  NUMBER(10,2)  Y    诊断类-影像学诊断费    N  N..10,2
SELECT IMAGING_DIAGNOSIS_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY IMAGING_DIAGNOSIS_EXPENSE;

---DIAG_CLINICAL_COST  NUMBER(10,2)  Y    诊断类-临床诊断项目费    N  N..10,2
SELECT DIAG_CLINICAL_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_CLINICAL_COST;

---TREAT_NOOPERATION_ITEMCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费    N  N..10,2
SELECT TREAT_NOOPERATION_ITEMCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_ITEMCOST;

---TREAT_NOOPERATION_PHYSICSCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费-临床物理治疗费    N  N..10,2
SELECT TREAT_NOOPERATION_PHYSICSCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_PHYSICSCOST;

---TREAT_OPERATIONTREAT_COST  NUMBER(10,2)  Y    治疗类-手术治疗费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_COST;

---TREAT_OPER_ANAESTHESIACOST  NUMBER(10,2)  Y    治疗类-手术治疗费-麻醉费    N  N..10,2
SELECT TREAT_OPER_ANAESTHESIACOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPER_ANAESTHESIACOST;

---TREAT_OPERATIONTREAT_OPERCOST  NUMBER(10,2)  Y    治疗类-手术治疗费-手术费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_OPERCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_OPERCOST;

---RECOVERY_COST  NUMBER(10,2)  Y    康复类-康复费    N  N..10,2
SELECT RECOVERY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY RECOVERY_COST;

---TCM_TREAT_COST  NUMBER(10,2)  Y    中医类-中医治疗费    N  N..10,2
SELECT TCM_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCM_TREAT_COST;

---DRUG_COST  NUMBER(10,2)  Y    西药类-西药费    N  N..10,2
SELECT DRUG_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_COST;

---DRUG_ANTIBIOTICS_COST  NUMBER(10,2)  Y    西药类-西药费-抗菌药物费用    N  N..10,2
SELECT DRUG_ANTIBIOTICS_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ANTIBIOTICS_COST;

---PROPRIETARY_CM_EXPENSE  NUMBER(10,2)  Y    中药类-中成药费    N  N..10,2
SELECT PROPRIETARY_CM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY PROPRIETARY_CM_EXPENSE;

---TCD_CHM_COST  NUMBER(10,2)  Y    中药类-中草药费    N  N..10,2
SELECT TCD_CHM_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCD_CHM_COST;

---BLOOD_COST  NUMBER(10,2)  Y    血液和血液制品类-血费    N  N..10,2
SELECT BLOOD_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COST;

---BLOOD_ALBURMIN_COST  NUMBER(10,2)  Y    血液和血液制品类-白蛋白类制品费    N  N..10,2
SELECT BLOOD_ALBURMIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ALBURMIN_COST;

---BLOOD_GLOBULIN_COST  NUMBER(10,2)  Y    血液和血液制品类-球蛋白类制品费    N  N..10,2
SELECT BLOOD_GLOBULIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_GLOBULIN_COST;

---BLOOD_COGULATIONFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-凝血因子类制品费    N  N..10,2
SELECT BLOOD_COGULATIONFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COGULATIONFACTOR_COST;

---BLOOD_CELLFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-细胞因子类制品费    N  N..10,2
SELECT BLOOD_CELLFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_CELLFACTOR_COST;

---CHECK_DMM_EXPENSE  NUMBER(10,2)  Y    耗材类-检查用一次性医用材料费    N  N..10,2
SELECT CHECK_DMM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY CHECK_DMM_EXPENSE;

---EXP_TREAT_COST  NUMBER(10,2)  Y    耗材类-治疗用一次性医用材料费    N  N..10,2
SELECT EXP_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_TREAT_COST;

---EXP_OPERTION_COST  NUMBER(10,2)  Y    耗材类-手术用一次性医用材料费    N  N..10,2
SELECT EXP_OPERTION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_OPERTION_COST;

---OTHER_COST  NUMBER(10,2)  Y    其他类-其他费    N  N..10,2
SELECT OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY OTHER_COST;

---DISEASE_STATUS_CODE  VARCHAR2(2)  Y    住院者疾病状态代码  应符合国标：CV05.01.001    
SELECT DISEASE_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISEASE_STATUS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_MEDICAL_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM INPATIENT_MEDICAL_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_ID;

---ORG_NAME  VARCHAR2(70)  Y    医疗机构名称    S1  AN..70
SELECT ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY ORG_NAME;

---ORGAN_CODE  VARCHAR2(70)  Y    医疗机构组织机构代码  应符合国标：WS 218—2002  S3  AN10
SELECT ORGAN_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ORGAN_CODE;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  应符合国标：CV07.10.005  S3  N2
SELECT PAY_WAY FROM INPATIENT_MEDICAL_RECORD GROUP BY PAY_WAY;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY HEALTH_CARD_NO;

---INHOS_COUNT  NUMBER(2)  Y    住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_NO;

---MR_NO  VARCHAR2(18)  Y    病案号    S1  AN..18
SELECT MR_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_NO;

---PATIENT_NAME  VARCHAR2(50)  Y    姓名    S1  A..50
SELECT PATIENT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_NAME;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT PATIENT_SEX FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_SEX;

---BIRTHDAY  DATE  Y    出生日期    D  D8
SELECT BIRTHDAY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHDAY;

---AGE_YEAR  NUMBER(3)  Y    年龄（岁）    N  N1..3
SELECT AGE_YEAR FROM INPATIENT_MEDICAL_RECORD GROUP BY AGE_YEAR;

---PATIENT_MONTH  NUMBER(2)  Y    年龄（月）    S1  AN..8
SELECT PATIENT_MONTH FROM INPATIENT_MEDICAL_RECORD GROUP BY PATIENT_MONTH;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码  应符合国标：GB/T 2659—2000  S3  AN3
SELECT NATIONNALITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIONNALITY;

---NEWBORN_BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT NEWBORN_BIRTH_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_BIRTH_WEIGHT;

---NEWBORN_INP_WEIGHT  NUMBER(4)  Y    新生儿入院体重(g)    N  N2..4
SELECT NEWBORN_INP_WEIGHT FROM INPATIENT_MEDICAL_RECORD GROUP BY NEWBORN_INP_WEIGHT;

---BIRTHPLACE_PROVINCE  VARCHAR2(70)  Y    出生地-省（自治区、直辖市）    S1  AN..70
SELECT BIRTHPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_PROVINCE;

---BIRTHPLACE_CITY  VARCHAR2(70)  Y    出生地-市（地区、州）    S1  AN..70
SELECT BIRTHPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_CITY;

---BIRTHPLACE_COUNTY  VARCHAR2(70)  Y    出生地-县（区）    S1  AN..70
SELECT BIRTHPLACE_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY BIRTHPLACE_COUNTY;

---NATIVEPLACE_PROVINCE  VARCHAR2(70)  Y    籍贯-省（自治区、直辖市）    S1  AN..70
SELECT NATIVEPLACE_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_PROVINCE;

---NATIVEPLACE_CITY  VARCHAR2(70)  Y    籍贯-市（地区、州）    S1  AN..70
SELECT NATIVEPLACE_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY NATIVEPLACE_CITY;

---NATION  VARCHAR2(2)  Y    民族  应符合国标：GB/T 3304-1991  S3  N2
SELECT NATION FROM INPATIENT_MEDICAL_RECORD GROUP BY NATION;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码  应符合国标：WS 364.3—2011 表 1CV02.01.101身份征件类别代码表  S3  N2
SELECT IDENTITY_TYPE FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_TYPE;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    S1  AN..18
SELECT IDENTITY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY IDENTITY_NO;

---OCCUPATION_TYPE_CODE  VARCHAR2(2)  Y    职业类别代码  应符合国标：GB/T 2261.4—2003  S3  N2
SELECT OCCUPATION_TYPE_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY OCCUPATION_TYPE_CODE;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码  应符合国标：GB/T 2261.2—2003  S3  N2
SELECT MARITAL_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MARITAL_STATUS_CODE;

---CURRENT_PROVINCE  VARCHAR2(70)  Y    现住址-省（自治区、直辖市）    S1  AN..70
SELECT CURRENT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PROVINCE;

---CURRENT_CITY  VARCHAR2(70)  Y    现住址-市（地区、州）    S1  AN..70
SELECT CURRENT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_CITY;

---CURRENT_COUNTY  VARCHAR2(70)  Y    现住址-县（区）    S1  AN..70
SELECT CURRENT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_COUNTY;

---CURRENT_TOWNSHIP  VARCHAR2(70)  Y    现住址-乡（镇、街道办事处）    S1  AN..70
SELECT CURRENT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_TOWNSHIP;

---CURRENT_VILLAGE  VARCHAR2(70)  Y    现住址-村（街、路、弄等）    S1  AN..70
SELECT CURRENT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_VILLAGE;

---CURRENT_DOORS  VARCHAR2(70)  Y    现住址-门牌号码    S1  AN..70
SELECT CURRENT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_DOORS;

---CURRENT_PHONE  VARCHAR2(20)  Y    电话号码    S1  AN..20
SELECT CURRENT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_PHONE;

---CURRENT_ZIP_CODE  VARCHAR2(6)  Y    现住址-邮政编码    S1  N6
SELECT CURRENT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY CURRENT_ZIP_CODE;

---ACCOUNT_PROVINCE  VARCHAR2(70)  Y    户口地址-省（自治区、直辖市）    S1  AN..70
SELECT ACCOUNT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_PROVINCE;

---ACCOUNT_CITY  VARCHAR2(70)  Y    户口地址-市（地区、州）    S1  AN..70
SELECT ACCOUNT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_CITY;

---ACCOUNT_COUNTY  VARCHAR2(70)  Y    户口地址-县（区）    S1  AN..70
SELECT ACCOUNT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_COUNTY;

---ACCOUNT_TOWNSHIP  VARCHAR2(70)  Y    户口地址-乡（镇、街道办事处）    S1  AN..70
SELECT ACCOUNT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_TOWNSHIP;

---ACCOUNT_VILLAGE  VARCHAR2(70)  Y    户口地址-村（街、路、弄等）    S1  AN..70
SELECT ACCOUNT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_VILLAGE;

---ACCOUNT_DOORS  VARCHAR2(70)  Y    户口地址-门牌号码    S1  AN..70
SELECT ACCOUNT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_DOORS;

---ACCOUNT_ZIP_CODE  VARCHAR2(6)  Y    户口地址-邮政编码    S1  N6
SELECT ACCOUNT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY ACCOUNT_ZIP_CODE;

---WORKUNIT_NAME  VARCHAR2(70)  Y    工作单位名称    S1  AN..70
SELECT WORKUNIT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_NAME;

---WORKUNIT_PROVINCE  VARCHAR2(70)  Y    工作单位地址-省（自治区、直辖市）    S1  AN..70
SELECT WORKUNIT_PROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PROVINCE;

---WORKUNIT_CITY  VARCHAR2(70)  Y    工作单位地址-市（地区、州）    S1  AN..70
SELECT WORKUNIT_CITY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_CITY;

---WORKUNIT_COUNTY  VARCHAR2(70)  Y    工作单位地址-县（区）    S1  AN..70
SELECT WORKUNIT_COUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_COUNTY;

---WORKUNIT_TOWNSHIP  VARCHAR2(70)  Y    工作单位地址-乡（镇、街道办事处）    S1  AN..70
SELECT WORKUNIT_TOWNSHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_TOWNSHIP;

---WORKUNIT_VILLAGE  VARCHAR2(70)  Y    工作单位地址-村（街、路、弄等）    S1  AN..70
SELECT WORKUNIT_VILLAGE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_VILLAGE;

---WORKUNIT_DOORS  VARCHAR2(70)  Y    工作单位地址-门牌号码    S1  AN..70
SELECT WORKUNIT_DOORS FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_DOORS;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    S1  AN..20
SELECT WORKUNIT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_PHONE;

---WORKUNIT_ZIP_CODE  VARCHAR2(6)  Y    工作单位地址-邮政编码    S1  N6
SELECT WORKUNIT_ZIP_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY WORKUNIT_ZIP_CODE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    S1  A..50
SELECT CONTACT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_NAME;

---RELATION  VARCHAR2(1)  Y    联系人与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT RELATION FROM INPATIENT_MEDICAL_RECORD GROUP BY RELATION;

---CAPROVINCE  VARCHAR2(70)  Y    联系人地址-省（自治区、直辖市）    S1  AN..70
SELECT CAPROVINCE FROM INPATIENT_MEDICAL_RECORD GROUP BY CAPROVINCE;

---CACITY  VARCHAR2(70)  Y    联系人地址-市（地区、州）    S1  AN..70
SELECT CACITY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACITY;

---CACOUNTY  VARCHAR2(70)  Y    联系人地址-县（区）    S1  AN..70
SELECT CACOUNTY FROM INPATIENT_MEDICAL_RECORD GROUP BY CACOUNTY;

---CATOWN_SHIP  VARCHAR2(70)  Y    联系人地址-乡（镇、街道办事处）    S1  AN..70
SELECT CATOWN_SHIP FROM INPATIENT_MEDICAL_RECORD GROUP BY CATOWN_SHIP;

---CASTREET  VARCHAR2(70)  Y    联系人地址-村（街、路、弄等）    S1  AN..70
SELECT CASTREET FROM INPATIENT_MEDICAL_RECORD GROUP BY CASTREET;

---CAHOUSE_NUMBER  VARCHAR2(70)  Y    联系人地址-门牌号码    S1  AN..70
SELECT CAHOUSE_NUMBER FROM INPATIENT_MEDICAL_RECORD GROUP BY CAHOUSE_NUMBER;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    S1  AN..20
SELECT CONTACT_PHONE FROM INPATIENT_MEDICAL_RECORD GROUP BY CONTACT_PHONE;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_APPROACH_CODE;

---INP_DATE  DATE  Y    入院日期时间    DT  DT15
SELECT INP_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DATE;

---INP_DEPT_NAME  VARCHAR2(50)  Y    入院科别    S1  AN..50
SELECT INP_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DEPT_NAME;

---INP_ROOM  VARCHAR2(10)  Y    入院病房    S1  AN..10
SELECT INP_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_ROOM;

---TRANSITION_DEP  VARCHAR2(50)  Y    转科科别    S1  AN..50
SELECT TRANSITION_DEP FROM INPATIENT_MEDICAL_RECORD GROUP BY TRANSITION_DEP;

---DISHOSPITAL_DATE  DATE  Y    出院日期时间    DT  DT15
SELECT DISHOSPITAL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DATE;

---DISHOSPITAL_DEPT_NAME  VARCHAR2(50)  Y    出院科别    S1  AN..50
SELECT DISHOSPITAL_DEPT_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DEPT_NAME;

---DISHOSPITAL_ROOM  VARCHAR2(10)  Y    出院病房    S1  AN..10
SELECT DISHOSPITAL_ROOM FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_ROOM;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    .N  N..4
SELECT INP_DAYS FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DAYS;

---PATHOLOGY_NO  VARCHAR2(18)  Y    病理号    S1  AN..18
SELECT PATHOLOGY_NO FROM INPATIENT_MEDICAL_RECORD GROUP BY PATHOLOGY_NO;

---DRUG_ALLERGY_FLAG  VARCHAR2(5)  Y    药物过敏标志  TRUE/FALSE  L  T/F
SELECT DRUG_ALLERGY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ALLERGY_FLAG;

---ALLERGY_DRUG  VARCHAR2(1000)  Y    过敏药物    S1  AN..1000
SELECT ALLERGY_DRUG FROM INPATIENT_MEDICAL_RECORD GROUP BY ALLERGY_DRUG;

---INHOS_AUTOPSY_FLAG  VARCHAR2(5)  Y    死亡患者尸检标志  TRUE/FALSE  L  T/F
SELECT INHOS_AUTOPSY_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY INHOS_AUTOPSY_FLAG;

---BLOOD_ABO_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国标：WS 364.9—2011 表 5  S3  N1
SELECT BLOOD_ABO_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ABO_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国标：CV04.50.020  S3  N1
SELECT RH_BLOOD_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY RH_BLOOD_CODE;

---DEPT_DIRECTOR_SIGN  VARCHAR2(50)  Y    科主任签名    S1  A..50
SELECT DEPT_DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DEPT_DIRECTOR_SIGN;

---DIRECTOR_SIGN  VARCHAR2(50)  Y    主任（副主任）医师签名    S1  A..50
SELECT DIRECTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DIRECTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_DOCTOR_SIGN;

---DUTY_NURSE_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT DUTY_NURSE_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY DUTY_NURSE_SIGN;

---REFRESHER_DOCTOR_SIGN  VARCHAR2(50)  Y    进修医师签名    S1  A..50
SELECT REFRESHER_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY REFRESHER_DOCTOR_SIGN;

---INTERNSHIP_DOCTOR_SIGN  VARCHAR2(50)  Y    实习医师签名    S1  A..50
SELECT INTERNSHIP_DOCTOR_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY INTERNSHIP_DOCTOR_SIGN;

---CODER_SIGN  VARCHAR2(50)  Y    编码员签名    S1  A..50
SELECT CODER_SIGN FROM INPATIENT_MEDICAL_RECORD GROUP BY CODER_SIGN;

---MR_QUALITY_CODE  NUMBER(1)  Y    病案质量代码  标准值：1,甲  2.乙  3.丙  S2  N1
SELECT MR_QUALITY_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY MR_QUALITY_CODE;

---QC_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    质控医师签名    S1  A..50
SELECT QC_DOCTOR_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_DOCTOR_SIGNATURE;

---QC_NURSE_SIGNATURE  VARCHAR2(50)  Y    质控护士签名    S1  A..50
SELECT QC_NURSE_SIGNATURE FROM INPATIENT_MEDICAL_RECORD GROUP BY QC_NURSE_SIGNATURE;

---QUALITYCONTROL_DATE  DATE  Y    质控日期    D  D8
SELECT QUALITYCONTROL_DATE FROM INPATIENT_MEDICAL_RECORD GROUP BY QUALITYCONTROL_DATE;

---DISHOSPITAL_DISPOSITION_CODE  VARCHAR2(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---RECEIVE_ORG_NAME  VARCHAR2(70)  Y    拟接收医疗机构名称    S1  AN..70
SELECT RECEIVE_ORG_NAME FROM INPATIENT_MEDICAL_RECORD GROUP BY RECEIVE_ORG_NAME;

---OUTHOS_FLAG  VARCHAR2(5)  Y    出院31天内再住院标志  TRUE/FALSE  L  T/F
SELECT OUTHOS_FLAG FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_FLAG;

---OUTHOS_PURPOSE  VARCHAR2(100)  Y    出院31天内再住院目的    S1  AN..100
SELECT OUTHOS_PURPOSE FROM INPATIENT_MEDICAL_RECORD GROUP BY OUTHOS_PURPOSE;

---HEADINJURY_INPBEFORECOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院前昏迷时间-d    N  N..5
SELECT HEADINJURY_INPBEFORECOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_DAY;

---HEADINJURY_INPBEFORECOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-h    N  N..2
SELECT HEADINJURY_INPBEFORECOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORECOMA_HOUR;

---HEADINJURY_INPBEFORE_MIN  NUMBER(2)  Y    颅脑损伤患者入院前昏迷时间-min    N  N..2
SELECT HEADINJURY_INPBEFORE_MIN FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPBEFORE_MIN;

---HEADINJURY_INPAFTERCOMA_DAY  NUMBER(5)  Y    颅脑损伤患者入院后昏迷时间-d    N  N..5
SELECT HEADINJURY_INPAFTERCOMA_DAY FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_DAY;

---HEADINJURY_INPAFTERCOMA_HOUR  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-h    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_HOUR FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_HOUR;

---HEADINJURY_INPAFTERCOMA_MINUTE  NUMBER(2)  Y    颅脑损伤患者入院后昏迷时间-min    N  N..2
SELECT HEADINJURY_INPAFTERCOMA_MINUTE FROM INPATIENT_MEDICAL_RECORD GROUP BY HEADINJURY_INPAFTERCOMA_MINUTE;

---INP_TOTALCOST  NUMBER(10,2)  Y    住院总费用    N  N..10,2
SELECT INP_TOTALCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST;

---INP_TOTALCOST_OWNPAY  NUMBER(10,2)  Y    住院总费用-自付金额    N  N..10,2
SELECT INP_TOTALCOST_OWNPAY FROM INPATIENT_MEDICAL_RECORD GROUP BY INP_TOTALCOST_OWNPAY;

---MEDICAL_COMMONLYSERVICE_COST  NUMBER(10,2)  Y    综合医疗服务类-一般医疗服务费    N  N..10,2
SELECT MEDICAL_COMMONLYSERVICE_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYSERVICE_COST;

---MEDICAL_COMMONLYOPERATION_COST  NUMBER(10,2)  Y    综合医疗服务类-一般治疗操作费    N  N..10,2
SELECT MEDICAL_COMMONLYOPERATION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_COMMONLYOPERATION_COST;

---MEDICAL_NURSING_COST  NUMBER(10,2)  Y    综合医疗服务类-护理费    N  N..10,2
SELECT MEDICAL_NURSING_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_NURSING_COST;

---MEDICAL_OTHER_COST  NUMBER(10,2)  Y    综合医疗服务类-其他费用    N  N..10,2
SELECT MEDICAL_OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY MEDICAL_OTHER_COST;

---DIAG_PATHOLOGY_COST  NUMBER(10,2)  Y    诊断类-病理诊断费    N  N..10,2
SELECT DIAG_PATHOLOGY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_PATHOLOGY_COST;

---DIAG_LABORATORY_COST  NUMBER(10,2)  Y    诊断类-实验室诊断费    N  N..10,2
SELECT DIAG_LABORATORY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_LABORATORY_COST;

---IMAGING_DIAGNOSIS_EXPENSE  NUMBER(10,2)  Y    诊断类-影像学诊断费    N  N..10,2
SELECT IMAGING_DIAGNOSIS_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY IMAGING_DIAGNOSIS_EXPENSE;

---DIAG_CLINICAL_COST  NUMBER(10,2)  Y    诊断类-临床诊断项目费    N  N..10,2
SELECT DIAG_CLINICAL_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DIAG_CLINICAL_COST;

---TREAT_NOOPERATION_ITEMCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费    N  N..10,2
SELECT TREAT_NOOPERATION_ITEMCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_ITEMCOST;

---TREAT_NOOPERATION_PHYSICSCOST  NUMBER(10,2)  Y    治疗类-非手术治疗项目费-临床物理治疗费    N  N..10,2
SELECT TREAT_NOOPERATION_PHYSICSCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_NOOPERATION_PHYSICSCOST;

---TREAT_OPERATIONTREAT_COST  NUMBER(10,2)  Y    治疗类-手术治疗费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_COST;

---TREAT_OPER_ANAESTHESIACOST  NUMBER(10,2)  Y    治疗类-手术治疗费-麻醉费    N  N..10,2
SELECT TREAT_OPER_ANAESTHESIACOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPER_ANAESTHESIACOST;

---TREAT_OPERATIONTREAT_OPERCOST  NUMBER(10,2)  Y    治疗类-手术治疗费-手术费    N  N..10,2
SELECT TREAT_OPERATIONTREAT_OPERCOST FROM INPATIENT_MEDICAL_RECORD GROUP BY TREAT_OPERATIONTREAT_OPERCOST;

---RECOVERY_COST  NUMBER(10,2)  Y    康复类-康复费    N  N..10,2
SELECT RECOVERY_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY RECOVERY_COST;

---TCM_TREAT_COST  NUMBER(10,2)  Y    中医类-中医治疗费    N  N..10,2
SELECT TCM_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCM_TREAT_COST;

---DRUG_COST  NUMBER(10,2)  Y    西药类-西药费    N  N..10,2
SELECT DRUG_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_COST;

---DRUG_ANTIBIOTICS_COST  NUMBER(10,2)  Y    西药类-西药费-抗菌药物费用    N  N..10,2
SELECT DRUG_ANTIBIOTICS_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY DRUG_ANTIBIOTICS_COST;

---PROPRIETARY_CM_EXPENSE  NUMBER(10,2)  Y    中药类-中成药费    N  N..10,2
SELECT PROPRIETARY_CM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY PROPRIETARY_CM_EXPENSE;

---TCD_CHM_COST  NUMBER(10,2)  Y    中药类-中草药费    N  N..10,2
SELECT TCD_CHM_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY TCD_CHM_COST;

---BLOOD_COST  NUMBER(10,2)  Y    血液和血液制品类-血费    N  N..10,2
SELECT BLOOD_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COST;

---BLOOD_ALBURMIN_COST  NUMBER(10,2)  Y    血液和血液制品类-白蛋白类制品费    N  N..10,2
SELECT BLOOD_ALBURMIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_ALBURMIN_COST;

---BLOOD_GLOBULIN_COST  NUMBER(10,2)  Y    血液和血液制品类-球蛋白类制品费    N  N..10,2
SELECT BLOOD_GLOBULIN_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_GLOBULIN_COST;

---BLOOD_COGULATIONFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-凝血因子类制品费    N  N..10,2
SELECT BLOOD_COGULATIONFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_COGULATIONFACTOR_COST;

---BLOOD_CELLFACTOR_COST  NUMBER(10,2)  Y    血液和血液制品类-细胞因子类制品费    N  N..10,2
SELECT BLOOD_CELLFACTOR_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY BLOOD_CELLFACTOR_COST;

---CHECK_DMM_EXPENSE  NUMBER(10,2)  Y    耗材类-检查用一次性医用材料费    N  N..10,2
SELECT CHECK_DMM_EXPENSE FROM INPATIENT_MEDICAL_RECORD GROUP BY CHECK_DMM_EXPENSE;

---EXP_TREAT_COST  NUMBER(10,2)  Y    耗材类-治疗用一次性医用材料费    N  N..10,2
SELECT EXP_TREAT_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_TREAT_COST;

---EXP_OPERTION_COST  NUMBER(10,2)  Y    耗材类-手术用一次性医用材料费    N  N..10,2
SELECT EXP_OPERTION_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY EXP_OPERTION_COST;

---OTHER_COST  NUMBER(10,2)  Y    其他类-其他费    N  N..10,2
SELECT OTHER_COST FROM INPATIENT_MEDICAL_RECORD GROUP BY OTHER_COST;

---DISEASE_STATUS_CODE  VARCHAR2(2)  Y    住院者疾病状态代码  应符合国标：CV05.01.001    
SELECT DISEASE_STATUS_CODE FROM INPATIENT_MEDICAL_RECORD GROUP BY DISEASE_STATUS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_MEDICAL_RECORD GROUP BY LAST_MODIFIC_TIME;

