---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EMR_HEALTHEVENTS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM EMR_HEALTHEVENTS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM EMR_HEALTHEVENTS GROUP BY INP_NO;

---CHINESE_MEDICINE_TYPE_NAME  VARCHAR2(2000)  Y    其他医学处置    S3  AN..11
SELECT CHINESE_MEDICINE_TYPE_NAME FROM EMR_HEALTHEVENTS GROUP BY CHINESE_MEDICINE_TYPE_NAME;

---OTHER_MEDICAL_TREATMENT  VARCHAR2(50)  Y    根本死因代码  ICD-10  S3  AN..5+
SELECT OTHER_MEDICAL_TREATMENT FROM EMR_HEALTHEVENTS GROUP BY OTHER_MEDICAL_TREATMENT;

---UNDERLYING_DEATH_CODE  VARCHAR2(1)  Y    病情转归代码  WS 364.11—2011 表 10CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM EMR_HEALTHEVENTS GROUP BY UNDERLYING_DEATH_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医师姓名    S1  A..50
SELECT RESPONSIBLE_DOCTOR FROM EMR_HEALTHEVENTS GROUP BY RESPONSIBLE_DOCTOR;

---STATE  VARCHAR2(1)  Y    cda文档生成状态 Y:成功，N:失败，P:部分      
SELECT STATE FROM EMR_HEALTHEVENTS GROUP BY STATE;

---BATCH_NUM  VARCHAR2(32)  Y    cda生成批次号      
SELECT BATCH_NUM FROM EMR_HEALTHEVENTS GROUP BY BATCH_NUM;

---GEN_DATETIME  DATE  Y    cda文档生成时间      
SELECT GEN_DATETIME FROM EMR_HEALTHEVENTS GROUP BY GEN_DATETIME;

---CREATE_TIME  DATE  Y    子集创建时间      
SELECT CREATE_TIME FROM EMR_HEALTHEVENTS GROUP BY CREATE_TIME;

---EVENT_SEQ  NUMBER(11)      序列号      
SELECT EVENT_SEQ FROM EMR_HEALTHEVENTS GROUP BY EVENT_SEQ;

---SYS_SOURCE  VARCHAR2(50)  Y    系统来源      
SELECT SYS_SOURCE FROM EMR_HEALTHEVENTS GROUP BY SYS_SOURCE;

---DRUG_NAME  VARCHAR2(50)  Y    关键药物名称    S1  AN..50
SELECT DRUG_NAME FROM EMR_HEALTHEVENTS GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    关键药物用法    S1  AN..100
SELECT DRUG_USAGE FROM EMR_HEALTHEVENTS GROUP BY DRUG_USAGE;

---ADVERSE_DRUG_REACTIONS  VARCHAR2(100)  Y    药物不良反应情况    S1  AN..100
SELECT ADVERSE_DRUG_REACTIONS FROM EMR_HEALTHEVENTS GROUP BY ADVERSE_DRUG_REACTIONS;

---TCD_TYPE_CODE  VARCHAR2(1)  Y    中药使用类别代码  WS 364.12—2011 表 1CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM EMR_HEALTHEVENTS GROUP BY TCD_TYPE_CODE;

---DOC_NO  VARCHAR2(50)      主键      
SELECT DOC_NO FROM EMR_HEALTHEVENTS GROUP BY DOC_NO;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_HEALTHEVENTS GROUP BY HEALTH_CARD_NO;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_HEALTHEVENTS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EMR_HEALTHEVENTS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM EMR_HEALTHEVENTS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM EMR_HEALTHEVENTS GROUP BY INP_NO;

---CHINESE_MEDICINE_TYPE_NAME  VARCHAR2(2000)  Y    其他医学处置    S3  AN..11
SELECT CHINESE_MEDICINE_TYPE_NAME FROM EMR_HEALTHEVENTS GROUP BY CHINESE_MEDICINE_TYPE_NAME;

---OTHER_MEDICAL_TREATMENT  VARCHAR2(50)  Y    根本死因代码  ICD-10  S3  AN..5+
SELECT OTHER_MEDICAL_TREATMENT FROM EMR_HEALTHEVENTS GROUP BY OTHER_MEDICAL_TREATMENT;

---UNDERLYING_DEATH_CODE  VARCHAR2(1)  Y    病情转归代码  WS 364.11—2011 表 10CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM EMR_HEALTHEVENTS GROUP BY UNDERLYING_DEATH_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医师姓名    S1  A..50
SELECT RESPONSIBLE_DOCTOR FROM EMR_HEALTHEVENTS GROUP BY RESPONSIBLE_DOCTOR;

---STATE  VARCHAR2(1)  Y    cda文档生成状态 Y:成功，N:失败，P:部分      
SELECT STATE FROM EMR_HEALTHEVENTS GROUP BY STATE;

---BATCH_NUM  VARCHAR2(32)  Y    cda生成批次号      
SELECT BATCH_NUM FROM EMR_HEALTHEVENTS GROUP BY BATCH_NUM;

---GEN_DATETIME  DATE  Y    cda文档生成时间      
SELECT GEN_DATETIME FROM EMR_HEALTHEVENTS GROUP BY GEN_DATETIME;

---CREATE_TIME  DATE  Y    子集创建时间      
SELECT CREATE_TIME FROM EMR_HEALTHEVENTS GROUP BY CREATE_TIME;

---EVENT_SEQ  NUMBER(11)      序列号      
SELECT EVENT_SEQ FROM EMR_HEALTHEVENTS GROUP BY EVENT_SEQ;

---SYS_SOURCE  VARCHAR2(50)  Y    系统来源      
SELECT SYS_SOURCE FROM EMR_HEALTHEVENTS GROUP BY SYS_SOURCE;

---DRUG_NAME  VARCHAR2(50)  Y    关键药物名称    S1  AN..50
SELECT DRUG_NAME FROM EMR_HEALTHEVENTS GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    关键药物用法    S1  AN..100
SELECT DRUG_USAGE FROM EMR_HEALTHEVENTS GROUP BY DRUG_USAGE;

---ADVERSE_DRUG_REACTIONS  VARCHAR2(100)  Y    药物不良反应情况    S1  AN..100
SELECT ADVERSE_DRUG_REACTIONS FROM EMR_HEALTHEVENTS GROUP BY ADVERSE_DRUG_REACTIONS;

---TCD_TYPE_CODE  VARCHAR2(1)  Y    中药使用类别代码  WS 364.12—2011 表 1CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM EMR_HEALTHEVENTS GROUP BY TCD_TYPE_CODE;

---DOC_NO  VARCHAR2(50)      主键      
SELECT DOC_NO FROM EMR_HEALTHEVENTS GROUP BY DOC_NO;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_HEALTHEVENTS GROUP BY HEALTH_CARD_NO;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_HEALTHEVENTS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_HEALTHEVENTS GROUP BY INPATIENT_SN;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM EMR_HEALTHEVENTS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM EMR_HEALTHEVENTS GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM EMR_HEALTHEVENTS GROUP BY INP_NO;

---CHINESE_MEDICINE_TYPE_NAME  VARCHAR2(2000)  Y    其他医学处置    S3  AN..11
SELECT CHINESE_MEDICINE_TYPE_NAME FROM EMR_HEALTHEVENTS GROUP BY CHINESE_MEDICINE_TYPE_NAME;

---OTHER_MEDICAL_TREATMENT  VARCHAR2(50)  Y    根本死因代码  ICD-10  S3  AN..5+
SELECT OTHER_MEDICAL_TREATMENT FROM EMR_HEALTHEVENTS GROUP BY OTHER_MEDICAL_TREATMENT;

---UNDERLYING_DEATH_CODE  VARCHAR2(1)  Y    病情转归代码  WS 364.11—2011 表 10CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM EMR_HEALTHEVENTS GROUP BY UNDERLYING_DEATH_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医师姓名    S1  A..50
SELECT RESPONSIBLE_DOCTOR FROM EMR_HEALTHEVENTS GROUP BY RESPONSIBLE_DOCTOR;

---STATE  VARCHAR2(1)  Y    cda文档生成状态 Y:成功，N:失败，P:部分      
SELECT STATE FROM EMR_HEALTHEVENTS GROUP BY STATE;

---BATCH_NUM  VARCHAR2(32)  Y    cda生成批次号      
SELECT BATCH_NUM FROM EMR_HEALTHEVENTS GROUP BY BATCH_NUM;

---GEN_DATETIME  DATE  Y    cda文档生成时间      
SELECT GEN_DATETIME FROM EMR_HEALTHEVENTS GROUP BY GEN_DATETIME;

---CREATE_TIME  DATE  Y    子集创建时间      
SELECT CREATE_TIME FROM EMR_HEALTHEVENTS GROUP BY CREATE_TIME;

---EVENT_SEQ  NUMBER(11)      序列号      
SELECT EVENT_SEQ FROM EMR_HEALTHEVENTS GROUP BY EVENT_SEQ;

---SYS_SOURCE  VARCHAR2(50)  Y    系统来源      
SELECT SYS_SOURCE FROM EMR_HEALTHEVENTS GROUP BY SYS_SOURCE;

---DRUG_NAME  VARCHAR2(50)  Y    关键药物名称    S1  AN..50
SELECT DRUG_NAME FROM EMR_HEALTHEVENTS GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    关键药物用法    S1  AN..100
SELECT DRUG_USAGE FROM EMR_HEALTHEVENTS GROUP BY DRUG_USAGE;

---ADVERSE_DRUG_REACTIONS  VARCHAR2(100)  Y    药物不良反应情况    S1  AN..100
SELECT ADVERSE_DRUG_REACTIONS FROM EMR_HEALTHEVENTS GROUP BY ADVERSE_DRUG_REACTIONS;

---TCD_TYPE_CODE  VARCHAR2(1)  Y    中药使用类别代码  WS 364.12—2011 表 1CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM EMR_HEALTHEVENTS GROUP BY TCD_TYPE_CODE;

---DOC_NO  VARCHAR2(50)      主键      
SELECT DOC_NO FROM EMR_HEALTHEVENTS GROUP BY DOC_NO;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_HEALTHEVENTS GROUP BY HEALTH_CARD_NO;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_HEALTHEVENTS GROUP BY LAST_MODIFIC_TIME;

