---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM ADMISSION_ASSESSMENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_ASSESSMENT GROUP BY PATIENT_ID;

---INTO_ROOM_WAY  VARCHAR2(20)  Y    入病房方式    S1  AN..20
SELECT INTO_ROOM_WAY FROM ADMISSION_ASSESSMENT GROUP BY INTO_ROOM_WAY;

---SYMPTOMPTOM  VARCHAR2(50)  Y    主要症状    S1  AN..50
SELECT SYMPTOMPTOM FROM ADMISSION_ASSESSMENT GROUP BY SYMPTOMPTOM;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6,2
SELECT WEIGHT FROM ADMISSION_ASSESSMENT GROUP BY WEIGHT;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4,l
SELECT TEMPERATURE FROM ADMISSION_ASSESSMENT GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM ADMISSION_ASSESSMENT GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY DIASTOLIC_PRESSURE;

---INP_REASON  VARCHAR2(1000)  Y    入院原因    S1  AN..1000
SELECT INP_REASON FROM ADMISSION_ASSESSMENT GROUP BY INP_REASON;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM ADMISSION_ASSESSMENT GROUP BY INP_APPROACH_CODE;

---APGAR_GRADE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_GRADE FROM ADMISSION_ASSESSMENT GROUP BY APGAR_GRADE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM ADMISSION_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---DEVELOPMENT_DEGREE_CODE  NUMBER(1)  Y    发育程度代码  标准值：1.正力型  2.无力型 3.超力型  S2  N1
SELECT DEVELOPMENT_DEGREE_CODE FROM ADMISSION_ASSESSMENT GROUP BY DEVELOPMENT_DEGREE_CODE;

---SPIRIT_STATUS_FLAG  VARCHAR2(5)  Y    精神状态正常标志  TRUE/FALSE  .L  T/F
SELECT SPIRIT_STATUS_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SPIRIT_STATUS_FLAG;

---SLEEP_STATUS  VARCHAR2(1000)  Y    睡眠状况    S1  AN..1000
SELECT SLEEP_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SLEEP_STATUS;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况    S1  AN..1000
SELECT SPECIAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SPECIAL_STATUS;

---PSYCHOLOGICAL_STATUS  VARCHAR2(1)  Y    心理状态代码  应符合国标：WS 364.11—2011 表 2 CV05.10.002心理状态代码表  S3  N1
SELECT PSYCHOLOGICAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY PSYCHOLOGICAL_STATUS;

---NUTRITION_STATUS  NUMBER(1)  Y    营养状态代码  标准值：1.良好  2.中等  3.差  S2  N1
SELECT NUTRITION_STATUS FROM ADMISSION_ASSESSMENT GROUP BY NUTRITION_STATUS;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY ALLERGY_HISTORY;

---HEALTH_STATUS  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE  L  T/F
SELECT HEALTH_STATUS FROM ADMISSION_ASSESSMENT GROUP BY HEALTH_STATUS;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    S1  AN..1000
SELECT DISEASE_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY DISEASE_HISTORY;

---INFECT_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE  L  T/F
SELECT INFECT_FLAG FROM ADMISSION_ASSESSMENT GROUP BY INFECT_FLAG;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    S1  AN" 1000
SELECT INFECT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    S1  AN..1000
SELECT PREVENT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    S1  AN..1000
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY BLOOD_TRANSFUSION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    S1  AN..1000
SELECT FAMILY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY FAMILY_HISTORY;

---SMOKING_FLAG  VARCHAR2(5)  Y    吸烟标志  TRUE/FALSE  L  T/F
SELECT SMOKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_FLAG;

---STOP_SMOKING_DAY  NUMBER(5)  Y    停止吸烟天数    N  N..5
SELECT STOP_SMOKING_DAY FROM ADMISSION_ASSESSMENT GROUP BY STOP_SMOKING_DAY;

---SMOKING_STATUS  NUMBER(1)  Y    吸烟状况代码  标准值：1.从不吸烟  2.过去吸，已戒烟  3.吸烟  S2  N1
SELECT SMOKING_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_STATUS;

---SMOKING_PER_DAY  NUMBER(3)  Y    日吸烟量（支）    N  N..3
SELECT SMOKING_PER_DAY FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_PER_DAY;

---DRINKING_FLAG  VARCHAR2(5)  Y    饮酒标志  TRUE/FALSE  L  T/F
SELECT DRINKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FLAG;

---DRINKING_FREQUENCY  VARCHAR2(2)  Y    饮酒频率代码  应符合国标：WS 364.5—2011 表 4 CV03.00.104饮酒频率代码表  S3  N..2
SELECT DRINKING_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FREQUENCY;

---DAILY_DRINK  NUMBER(3)  Y    日饮酒量（mL)    N  N..3
SELECT DAILY_DRINK FROM ADMISSION_ASSESSMENT GROUP BY DAILY_DRINK;

---INFORM_DOCTOR_FLG  VARCHAR2(5)  Y    通知医师标志  TRUE/FALSE  L  T/F
SELECT INFORM_DOCTOR_FLG FROM ADMISSION_ASSESSMENT GROUP BY INFORM_DOCTOR_FLG;

---NOTIFY_PHYSICIAN_DATETIME  DATE  Y    通知医师日期时间    DT  DT15
SELECT NOTIFY_PHYSICIAN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY NOTIFY_PHYSICIAN_DATETIME;

---ASSESSMENT_DATETIME  DATE  Y    评估日期时间    DT  DT15
SELECT ASSESSMENT_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY ASSESSMENT_DATETIME;

---NURSING_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY NURSING_SIGN;

---RECEPTION_NURSING_SIGN  VARCHAR2(50)  Y    接诊护士签名    S1  A..50
SELECT RECEPTION_NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY RECEPTION_NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM ADMISSION_ASSESSMENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_ASSESSMENT GROUP BY PATIENT_ID;

---INTO_ROOM_WAY  VARCHAR2(20)  Y    入病房方式    S1  AN..20
SELECT INTO_ROOM_WAY FROM ADMISSION_ASSESSMENT GROUP BY INTO_ROOM_WAY;

---SYMPTOMPTOM  VARCHAR2(50)  Y    主要症状    S1  AN..50
SELECT SYMPTOMPTOM FROM ADMISSION_ASSESSMENT GROUP BY SYMPTOMPTOM;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6,2
SELECT WEIGHT FROM ADMISSION_ASSESSMENT GROUP BY WEIGHT;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4,l
SELECT TEMPERATURE FROM ADMISSION_ASSESSMENT GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM ADMISSION_ASSESSMENT GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY DIASTOLIC_PRESSURE;

---INP_REASON  VARCHAR2(1000)  Y    入院原因    S1  AN..1000
SELECT INP_REASON FROM ADMISSION_ASSESSMENT GROUP BY INP_REASON;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM ADMISSION_ASSESSMENT GROUP BY INP_APPROACH_CODE;

---APGAR_GRADE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_GRADE FROM ADMISSION_ASSESSMENT GROUP BY APGAR_GRADE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM ADMISSION_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---DEVELOPMENT_DEGREE_CODE  NUMBER(1)  Y    发育程度代码  标准值：1.正力型  2.无力型 3.超力型  S2  N1
SELECT DEVELOPMENT_DEGREE_CODE FROM ADMISSION_ASSESSMENT GROUP BY DEVELOPMENT_DEGREE_CODE;

---SPIRIT_STATUS_FLAG  VARCHAR2(5)  Y    精神状态正常标志  TRUE/FALSE  .L  T/F
SELECT SPIRIT_STATUS_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SPIRIT_STATUS_FLAG;

---SLEEP_STATUS  VARCHAR2(1000)  Y    睡眠状况    S1  AN..1000
SELECT SLEEP_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SLEEP_STATUS;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况    S1  AN..1000
SELECT SPECIAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SPECIAL_STATUS;

---PSYCHOLOGICAL_STATUS  VARCHAR2(1)  Y    心理状态代码  应符合国标：WS 364.11—2011 表 2 CV05.10.002心理状态代码表  S3  N1
SELECT PSYCHOLOGICAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY PSYCHOLOGICAL_STATUS;

---NUTRITION_STATUS  NUMBER(1)  Y    营养状态代码  标准值：1.良好  2.中等  3.差  S2  N1
SELECT NUTRITION_STATUS FROM ADMISSION_ASSESSMENT GROUP BY NUTRITION_STATUS;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY ALLERGY_HISTORY;

---HEALTH_STATUS  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE  L  T/F
SELECT HEALTH_STATUS FROM ADMISSION_ASSESSMENT GROUP BY HEALTH_STATUS;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    S1  AN..1000
SELECT DISEASE_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY DISEASE_HISTORY;

---INFECT_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE  L  T/F
SELECT INFECT_FLAG FROM ADMISSION_ASSESSMENT GROUP BY INFECT_FLAG;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    S1  AN" 1000
SELECT INFECT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    S1  AN..1000
SELECT PREVENT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    S1  AN..1000
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY BLOOD_TRANSFUSION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    S1  AN..1000
SELECT FAMILY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY FAMILY_HISTORY;

---SMOKING_FLAG  VARCHAR2(5)  Y    吸烟标志  TRUE/FALSE  L  T/F
SELECT SMOKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_FLAG;

---STOP_SMOKING_DAY  NUMBER(5)  Y    停止吸烟天数    N  N..5
SELECT STOP_SMOKING_DAY FROM ADMISSION_ASSESSMENT GROUP BY STOP_SMOKING_DAY;

---SMOKING_STATUS  NUMBER(1)  Y    吸烟状况代码  标准值：1.从不吸烟  2.过去吸，已戒烟  3.吸烟  S2  N1
SELECT SMOKING_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_STATUS;

---SMOKING_PER_DAY  NUMBER(3)  Y    日吸烟量（支）    N  N..3
SELECT SMOKING_PER_DAY FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_PER_DAY;

---DRINKING_FLAG  VARCHAR2(5)  Y    饮酒标志  TRUE/FALSE  L  T/F
SELECT DRINKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FLAG;

---DRINKING_FREQUENCY  VARCHAR2(2)  Y    饮酒频率代码  应符合国标：WS 364.5—2011 表 4 CV03.00.104饮酒频率代码表  S3  N..2
SELECT DRINKING_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FREQUENCY;

---DAILY_DRINK  NUMBER(3)  Y    日饮酒量（mL)    N  N..3
SELECT DAILY_DRINK FROM ADMISSION_ASSESSMENT GROUP BY DAILY_DRINK;

---INFORM_DOCTOR_FLG  VARCHAR2(5)  Y    通知医师标志  TRUE/FALSE  L  T/F
SELECT INFORM_DOCTOR_FLG FROM ADMISSION_ASSESSMENT GROUP BY INFORM_DOCTOR_FLG;

---NOTIFY_PHYSICIAN_DATETIME  DATE  Y    通知医师日期时间    DT  DT15
SELECT NOTIFY_PHYSICIAN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY NOTIFY_PHYSICIAN_DATETIME;

---ASSESSMENT_DATETIME  DATE  Y    评估日期时间    DT  DT15
SELECT ASSESSMENT_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY ASSESSMENT_DATETIME;

---NURSING_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY NURSING_SIGN;

---RECEPTION_NURSING_SIGN  VARCHAR2(50)  Y    接诊护士签名    S1  A..50
SELECT RECEPTION_NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY RECEPTION_NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_ASSESSMENT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM ADMISSION_ASSESSMENT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_ASSESSMENT GROUP BY PATIENT_ID;

---INTO_ROOM_WAY  VARCHAR2(20)  Y    入病房方式    S1  AN..20
SELECT INTO_ROOM_WAY FROM ADMISSION_ASSESSMENT GROUP BY INTO_ROOM_WAY;

---SYMPTOMPTOM  VARCHAR2(50)  Y    主要症状    S1  AN..50
SELECT SYMPTOMPTOM FROM ADMISSION_ASSESSMENT GROUP BY SYMPTOMPTOM;

---WEIGHT  NUMBER(6,2)  Y    体重（kg）    N  N3..6,2
SELECT WEIGHT FROM ADMISSION_ASSESSMENT GROUP BY WEIGHT;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4,l
SELECT TEMPERATURE FROM ADMISSION_ASSESSMENT GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    N  N2..3
SELECT SPHYGMUS FROM ADMISSION_ASSESSMENT GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM ADMISSION_ASSESSMENT GROUP BY DIASTOLIC_PRESSURE;

---INP_REASON  VARCHAR2(1000)  Y    入院原因    S1  AN..1000
SELECT INP_REASON FROM ADMISSION_ASSESSMENT GROUP BY INP_REASON;

---INP_APPROACH_CODE  VARCHAR2(1)  Y    入院途径代码  应符合国标：CV09.00.403  S3  N1
SELECT INP_APPROACH_CODE FROM ADMISSION_ASSESSMENT GROUP BY INP_APPROACH_CODE;

---APGAR_GRADE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_GRADE FROM ADMISSION_ASSESSMENT GROUP BY APGAR_GRADE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM ADMISSION_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---DEVELOPMENT_DEGREE_CODE  NUMBER(1)  Y    发育程度代码  标准值：1.正力型  2.无力型 3.超力型  S2  N1
SELECT DEVELOPMENT_DEGREE_CODE FROM ADMISSION_ASSESSMENT GROUP BY DEVELOPMENT_DEGREE_CODE;

---SPIRIT_STATUS_FLAG  VARCHAR2(5)  Y    精神状态正常标志  TRUE/FALSE  .L  T/F
SELECT SPIRIT_STATUS_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SPIRIT_STATUS_FLAG;

---SLEEP_STATUS  VARCHAR2(1000)  Y    睡眠状况    S1  AN..1000
SELECT SLEEP_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SLEEP_STATUS;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况    S1  AN..1000
SELECT SPECIAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SPECIAL_STATUS;

---PSYCHOLOGICAL_STATUS  VARCHAR2(1)  Y    心理状态代码  应符合国标：WS 364.11—2011 表 2 CV05.10.002心理状态代码表  S3  N1
SELECT PSYCHOLOGICAL_STATUS FROM ADMISSION_ASSESSMENT GROUP BY PSYCHOLOGICAL_STATUS;

---NUTRITION_STATUS  NUMBER(1)  Y    营养状态代码  标准值：1.良好  2.中等  3.差  S2  N1
SELECT NUTRITION_STATUS FROM ADMISSION_ASSESSMENT GROUP BY NUTRITION_STATUS;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY ALLERGY_HISTORY;

---HEALTH_STATUS  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE  L  T/F
SELECT HEALTH_STATUS FROM ADMISSION_ASSESSMENT GROUP BY HEALTH_STATUS;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    S1  AN..1000
SELECT DISEASE_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY DISEASE_HISTORY;

---INFECT_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE  L  T/F
SELECT INFECT_FLAG FROM ADMISSION_ASSESSMENT GROUP BY INFECT_FLAG;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    S1  AN" 1000
SELECT INFECT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    S1  AN..1000
SELECT PREVENT_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    S1  AN..1000
SELECT OPERATION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    S1  AN..1000
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY BLOOD_TRANSFUSION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    S1  AN..1000
SELECT FAMILY_HISTORY FROM ADMISSION_ASSESSMENT GROUP BY FAMILY_HISTORY;

---SMOKING_FLAG  VARCHAR2(5)  Y    吸烟标志  TRUE/FALSE  L  T/F
SELECT SMOKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_FLAG;

---STOP_SMOKING_DAY  NUMBER(5)  Y    停止吸烟天数    N  N..5
SELECT STOP_SMOKING_DAY FROM ADMISSION_ASSESSMENT GROUP BY STOP_SMOKING_DAY;

---SMOKING_STATUS  NUMBER(1)  Y    吸烟状况代码  标准值：1.从不吸烟  2.过去吸，已戒烟  3.吸烟  S2  N1
SELECT SMOKING_STATUS FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_STATUS;

---SMOKING_PER_DAY  NUMBER(3)  Y    日吸烟量（支）    N  N..3
SELECT SMOKING_PER_DAY FROM ADMISSION_ASSESSMENT GROUP BY SMOKING_PER_DAY;

---DRINKING_FLAG  VARCHAR2(5)  Y    饮酒标志  TRUE/FALSE  L  T/F
SELECT DRINKING_FLAG FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FLAG;

---DRINKING_FREQUENCY  VARCHAR2(2)  Y    饮酒频率代码  应符合国标：WS 364.5—2011 表 4 CV03.00.104饮酒频率代码表  S3  N..2
SELECT DRINKING_FREQUENCY FROM ADMISSION_ASSESSMENT GROUP BY DRINKING_FREQUENCY;

---DAILY_DRINK  NUMBER(3)  Y    日饮酒量（mL)    N  N..3
SELECT DAILY_DRINK FROM ADMISSION_ASSESSMENT GROUP BY DAILY_DRINK;

---INFORM_DOCTOR_FLG  VARCHAR2(5)  Y    通知医师标志  TRUE/FALSE  L  T/F
SELECT INFORM_DOCTOR_FLG FROM ADMISSION_ASSESSMENT GROUP BY INFORM_DOCTOR_FLG;

---NOTIFY_PHYSICIAN_DATETIME  DATE  Y    通知医师日期时间    DT  DT15
SELECT NOTIFY_PHYSICIAN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY NOTIFY_PHYSICIAN_DATETIME;

---ASSESSMENT_DATETIME  DATE  Y    评估日期时间    DT  DT15
SELECT ASSESSMENT_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY ASSESSMENT_DATETIME;

---NURSING_SIGN  VARCHAR2(50)  Y    责任护士签名    S1  A..50
SELECT NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY NURSING_SIGN;

---RECEPTION_NURSING_SIGN  VARCHAR2(50)  Y    接诊护士签名    S1  A..50
SELECT RECEPTION_NURSING_SIGN FROM ADMISSION_ASSESSMENT GROUP BY RECEPTION_NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM ADMISSION_ASSESSMENT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

