---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CONSULTATION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CONSULTATION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号      
SELECT INP_NO FROM CONSULTATION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CONSULTATION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号      
SELECT APPLY_NO FROM CONSULTATION_RECORD GROUP BY APPLY_NO;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM CONSULTATION_RECORD GROUP BY MR_EXCERPTS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM CONSULTATION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM CONSULTATION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM CONSULTATION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAGTREAT_PROCESSES_NAME  VARCHAR2(1000)  Y    诊疗过程名称    S1  AN..1000
SELECT DIAGTREAT_PROCESSES_NAME FROM CONSULTATION_RECORD GROUP BY DIAGTREAT_PROCESSES_NAME;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM CONSULTATION_RECORD GROUP BY DIAG_DESC;

---CONSULTATION_TYPE  VARCHAR2(50)  Y    会诊类型    S1  AN..50
SELECT CONSULTATION_TYPE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_TYPE;

---CONSULTATION_REASON  VARCHAR2(200)  Y    会诊原因    S1  AN..200
SELECT CONSULTATION_REASON FROM CONSULTATION_RECORD GROUP BY CONSULTATION_REASON;

---CONSULTATION_PURPOSE  VARCHAR2(50)  Y    会诊目的    S1  AN..50
SELECT CONSULTATION_PURPOSE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_PURPOSE;

---APPLY_DOCTOR_NAME  VARCHAR2(50)  Y    会诊申请医师签名    S1  A..50
SELECT APPLY_DOCTOR_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DOCTOR_NAME;

---APPLY_DEPT_NAME  VARCHAR2(50)  Y    会诊申请科室    S1  AN..50
SELECT APPLY_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DEPT_NAME;

---APPLY_ORG_NAME  VARCHAR2(70)  Y    会诊申请医疗机构名称    S1  AN..70
SELECT APPLY_ORG_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_ORG_NAME;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊怠见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM CONSULTATION_RECORD GROUP BY CONSULTATION_SUGGESTION;

---CONSULTATION_DOCTOR_SIGN  VARCHAR2(50)  Y    会诊医师签名    S1  A..50
SELECT CONSULTATION_DOCTOR_SIGN FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_SIGN;

---CONSULTATION_DEPT_NAME  VARCHAR2(50)  Y    会诊科室名称    S1  AN..50
SELECT CONSULTATION_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DEPT_NAME;

---CONSULTATION_DOCTOR_ORGNAME  VARCHAR2(70)  Y    会诊医师所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_DOCTOR_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_ORGNAME;

---CONSULTATION_ORGNAME  VARCHAR2(70)  Y    会诊所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_ORGNAME;

---CONSULTATION_DATATIME  DATE  Y    会诊日期时间    DT  DT15
SELECT CONSULTATION_DATATIME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CONSULTATION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CONSULTATION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CONSULTATION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号      
SELECT INP_NO FROM CONSULTATION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CONSULTATION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号      
SELECT APPLY_NO FROM CONSULTATION_RECORD GROUP BY APPLY_NO;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM CONSULTATION_RECORD GROUP BY MR_EXCERPTS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM CONSULTATION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM CONSULTATION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM CONSULTATION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAGTREAT_PROCESSES_NAME  VARCHAR2(1000)  Y    诊疗过程名称    S1  AN..1000
SELECT DIAGTREAT_PROCESSES_NAME FROM CONSULTATION_RECORD GROUP BY DIAGTREAT_PROCESSES_NAME;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM CONSULTATION_RECORD GROUP BY DIAG_DESC;

---CONSULTATION_TYPE  VARCHAR2(50)  Y    会诊类型    S1  AN..50
SELECT CONSULTATION_TYPE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_TYPE;

---CONSULTATION_REASON  VARCHAR2(200)  Y    会诊原因    S1  AN..200
SELECT CONSULTATION_REASON FROM CONSULTATION_RECORD GROUP BY CONSULTATION_REASON;

---CONSULTATION_PURPOSE  VARCHAR2(50)  Y    会诊目的    S1  AN..50
SELECT CONSULTATION_PURPOSE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_PURPOSE;

---APPLY_DOCTOR_NAME  VARCHAR2(50)  Y    会诊申请医师签名    S1  A..50
SELECT APPLY_DOCTOR_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DOCTOR_NAME;

---APPLY_DEPT_NAME  VARCHAR2(50)  Y    会诊申请科室    S1  AN..50
SELECT APPLY_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DEPT_NAME;

---APPLY_ORG_NAME  VARCHAR2(70)  Y    会诊申请医疗机构名称    S1  AN..70
SELECT APPLY_ORG_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_ORG_NAME;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊怠见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM CONSULTATION_RECORD GROUP BY CONSULTATION_SUGGESTION;

---CONSULTATION_DOCTOR_SIGN  VARCHAR2(50)  Y    会诊医师签名    S1  A..50
SELECT CONSULTATION_DOCTOR_SIGN FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_SIGN;

---CONSULTATION_DEPT_NAME  VARCHAR2(50)  Y    会诊科室名称    S1  AN..50
SELECT CONSULTATION_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DEPT_NAME;

---CONSULTATION_DOCTOR_ORGNAME  VARCHAR2(70)  Y    会诊医师所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_DOCTOR_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_ORGNAME;

---CONSULTATION_ORGNAME  VARCHAR2(70)  Y    会诊所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_ORGNAME;

---CONSULTATION_DATATIME  DATE  Y    会诊日期时间    DT  DT15
SELECT CONSULTATION_DATATIME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CONSULTATION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CONSULTATION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CONSULTATION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号      
SELECT INP_NO FROM CONSULTATION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CONSULTATION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号      
SELECT APPLY_NO FROM CONSULTATION_RECORD GROUP BY APPLY_NO;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM CONSULTATION_RECORD GROUP BY MR_EXCERPTS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM CONSULTATION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM CONSULTATION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM CONSULTATION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAGTREAT_PROCESSES_NAME  VARCHAR2(1000)  Y    诊疗过程名称    S1  AN..1000
SELECT DIAGTREAT_PROCESSES_NAME FROM CONSULTATION_RECORD GROUP BY DIAGTREAT_PROCESSES_NAME;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM CONSULTATION_RECORD GROUP BY DIAG_DESC;

---CONSULTATION_TYPE  VARCHAR2(50)  Y    会诊类型    S1  AN..50
SELECT CONSULTATION_TYPE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_TYPE;

---CONSULTATION_REASON  VARCHAR2(200)  Y    会诊原因    S1  AN..200
SELECT CONSULTATION_REASON FROM CONSULTATION_RECORD GROUP BY CONSULTATION_REASON;

---CONSULTATION_PURPOSE  VARCHAR2(50)  Y    会诊目的    S1  AN..50
SELECT CONSULTATION_PURPOSE FROM CONSULTATION_RECORD GROUP BY CONSULTATION_PURPOSE;

---APPLY_DOCTOR_NAME  VARCHAR2(50)  Y    会诊申请医师签名    S1  A..50
SELECT APPLY_DOCTOR_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DOCTOR_NAME;

---APPLY_DEPT_NAME  VARCHAR2(50)  Y    会诊申请科室    S1  AN..50
SELECT APPLY_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_DEPT_NAME;

---APPLY_ORG_NAME  VARCHAR2(70)  Y    会诊申请医疗机构名称    S1  AN..70
SELECT APPLY_ORG_NAME FROM CONSULTATION_RECORD GROUP BY APPLY_ORG_NAME;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊怠见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM CONSULTATION_RECORD GROUP BY CONSULTATION_SUGGESTION;

---CONSULTATION_DOCTOR_SIGN  VARCHAR2(50)  Y    会诊医师签名    S1  A..50
SELECT CONSULTATION_DOCTOR_SIGN FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_SIGN;

---CONSULTATION_DEPT_NAME  VARCHAR2(50)  Y    会诊科室名称    S1  AN..50
SELECT CONSULTATION_DEPT_NAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DEPT_NAME;

---CONSULTATION_DOCTOR_ORGNAME  VARCHAR2(70)  Y    会诊医师所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_DOCTOR_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DOCTOR_ORGNAME;

---CONSULTATION_ORGNAME  VARCHAR2(70)  Y    会诊所在医疗机构名称    S1  AN..70
SELECT CONSULTATION_ORGNAME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_ORGNAME;

---CONSULTATION_DATATIME  DATE  Y    会诊日期时间    DT  DT15
SELECT CONSULTATION_DATATIME FROM CONSULTATION_RECORD GROUP BY CONSULTATION_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM CONSULTATION_RECORD GROUP BY LAST_MODIFIC_TIME;

