---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OPERATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OPERATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OPERATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    null  null
SELECT NURSING_OPERATION_NAME FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    null  null
SELECT NURSING_OPERATION_ITEM FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    null  null
SELECT NURSING_OPERATION_RESULT FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_RESULT;

---NURSING_OPERATION_DATE  DATE  Y    护理操作时间    null  null
SELECT NURSING_OPERATION_DATE FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_DATE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OPERATION GROUP BY NURSE_SIGN;

---NURSING_OPERATION_ID  VARCHAR2(18)      护理操作ID    null  null
SELECT NURSING_OPERATION_ID FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OPERATION GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OPERATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OPERATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OPERATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    null  null
SELECT NURSING_OPERATION_NAME FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    null  null
SELECT NURSING_OPERATION_ITEM FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    null  null
SELECT NURSING_OPERATION_RESULT FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_RESULT;

---NURSING_OPERATION_DATE  DATE  Y    护理操作时间    null  null
SELECT NURSING_OPERATION_DATE FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_DATE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OPERATION GROUP BY NURSE_SIGN;

---NURSING_OPERATION_ID  VARCHAR2(18)      护理操作ID    null  null
SELECT NURSING_OPERATION_ID FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OPERATION GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OPERATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OPERATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OPERATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OPERATION_NAME  VARCHAR2(100)  Y    护理操作名称    null  null
SELECT NURSING_OPERATION_NAME FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_NAME;

---NURSING_OPERATION_ITEM  VARCHAR2(100)  Y    护理操作项目类目名称    null  null
SELECT NURSING_OPERATION_ITEM FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ITEM;

---NURSING_OPERATION_RESULT  VARCHAR2(1000)  Y    护理操作结果    null  null
SELECT NURSING_OPERATION_RESULT FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_RESULT;

---NURSING_OPERATION_DATE  DATE  Y    护理操作时间    null  null
SELECT NURSING_OPERATION_DATE FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_DATE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OPERATION GROUP BY NURSE_SIGN;

---NURSING_OPERATION_ID  VARCHAR2(18)      护理操作ID    null  null
SELECT NURSING_OPERATION_ID FROM NURSING_OPERATION GROUP BY NURSING_OPERATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OPERATION GROUP BY LAST_MODIFIC_TIME;

