---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_WEST GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_WEST GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_WEST GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_WEST GROUP BY OUTP_NO;

---RECIPE_NO  NUMBER(30)  Y    处方编号，用于CDA显示    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_WEST GROUP BY RECIPE_NO;

---PRESC_ID  VARCHAR2(50)  Y    处方编号，用于关联明细表      
SELECT PRESC_ID FROM PRESCRIPTION_WEST GROUP BY PRESC_ID;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_WEST GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDEPT_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN.. 100
SELECT RECIPE_REMARK FROM PRESCRIPTION_WEST GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8.2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_WEST GROUP BY RECIPE_COSTS_AMOUNT;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDOCTOR_NAME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_WEST GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_WEST GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_WEST GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_WEST GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_WEST GROUP BY OUTP_NO;

---RECIPE_NO  NUMBER(30)  Y    处方编号，用于CDA显示    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_WEST GROUP BY RECIPE_NO;

---PRESC_ID  VARCHAR2(50)  Y    处方编号，用于关联明细表      
SELECT PRESC_ID FROM PRESCRIPTION_WEST GROUP BY PRESC_ID;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_WEST GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDEPT_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN.. 100
SELECT RECIPE_REMARK FROM PRESCRIPTION_WEST GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8.2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_WEST GROUP BY RECIPE_COSTS_AMOUNT;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDOCTOR_NAME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_WEST GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_WEST GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_WEST GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_WEST GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_WEST GROUP BY OUTP_NO;

---RECIPE_NO  NUMBER(30)  Y    处方编号，用于CDA显示    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_WEST GROUP BY RECIPE_NO;

---PRESC_ID  VARCHAR2(50)  Y    处方编号，用于关联明细表      
SELECT PRESC_ID FROM PRESCRIPTION_WEST GROUP BY PRESC_ID;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_WEST GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDEPT_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN.. 100
SELECT RECIPE_REMARK FROM PRESCRIPTION_WEST GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8.2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_WEST GROUP BY RECIPE_COSTS_AMOUNT;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_WEST GROUP BY RECIPE_OPENDOCTOR_NAME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_WEST GROUP BY LAST_MODIFIC_TIME;

