---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INP_NO;

---PREOPERATIVE_COMORBIDITY  VARCHAR2(100)  Y    术前合并疾病  —  S1  AN..100
SELECT PREOPERATIVE_COMORBIDITY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PREOPERATIVE_COMORBIDITY;

---BRIEF_HISTORY  VARCHAR2(100)  Y    简要病史  —  S1  AN..100
SELECT BRIEF_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BRIEF_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ALLERGY_HISTORY;

---ECG_RESULTS  VARCHAR2(100)  Y    心电图检查结果  —  S1  AN..100
SELECT ECG_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ECG_RESULTS;

---XLINE_RESULT  VARCHAR2(100)  Y    胸部X线检查结果  —  S1  AN..100
SELECT XLINE_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY XLINE_RESULT;

---CT_RESULT  VARCHAR2(100)  Y    CT检查结采  —  S1  AN..100
SELECT CT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CT_RESULT;

---B_INSPECTION  VARCHAR2(100)  Y    B超检查结果  —  S1  AN..100
SELECT B_INSPECTION FROM VISITS_REC_BEF_ANESTHESIA GROUP BY B_INSPECTION;

---MRI_RESULT  VARCHAR2(1000)  Y    MRI超检查结果  —  S1  AN..1000
SELECT MRI_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MRI_RESULT;

---PULMONARY_FUNCTION_RESULTS  VARCHAR2(1000)  Y    肺功能检查结果  —  S1  AN..1000
SELECT PULMONARY_FUNCTION_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PULMONARY_FUNCTION_RESULTS;

---BLOOD_ROUT_RESULT  VARCHAR2(1000)  Y    血常规检查结果  —  S1  AN..1000
SELECT BLOOD_ROUT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOOD_ROUT_RESULT;

---URINE_TEST_RESULTS  VARCHAR2(100)  Y    尿常规检查结果  —  S1  AN..100
SELECT URINE_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY URINE_TEST_RESULTS;

---COAGULATION_TEST_RESULTS  VARCHAR2(100)  Y    凝血功能检查结果  —  S1  AN..100
SELECT COAGULATION_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY COAGULATION_TEST_RESULTS;

---LIVER_FUNCTION_RESULT  VARCHAR2(100)  Y    肝功能检查结果  —  S1  AN..100
SELECT LIVER_FUNCTION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIVER_FUNCTION_RESULT;

---BLOODGAS_ANALYSIS_TEST_RESULT  VARCHAR2(1000)  Y    血气分析检查结果  —  S1  AN..1000
SELECT BLOODGAS_ANALYSIS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOODGAS_ANALYSIS_TEST_RESULT;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---MENTAL_STATE_FLAG  VARCHAR2(5)  Y    精神状态正常标志  —  L  T/F
SELECT MENTAL_STATE_FLAG FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MENTAL_STATE_FLAG;

---CARDIAC_AUSCULTATION_RESULT  VARCHAR2(100)  Y    心脏听诊结果  —  S1  AN..100
SELECT CARDIAC_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CARDIAC_AUSCULTATION_RESULT;

---LUNG_AUSCULTATION_RESULT  VARCHAR2(100)  Y    肺部听诊结果  —  S1  AN..100
SELECT LUNG_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LUNG_AUSCULTATION_RESULT;

---LIMBS_TEST_RESULT  VARCHAR2(1000)  Y    四肢检查结果  —  S1  AN..1000
SELECT LIMBS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIMBS_TEST_RESULT;

---SPINAL_RESULT  VARCHAR2(1000)  Y    脊柱检查结果  —  S1  AN..1000
SELECT SPINAL_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SPINAL_RESULT;

---ABDOMINAL_EXAM_RESULT  VARCHAR2(1000)  Y    腹部检查结果  —  S1  AN..1000
SELECT ABDOMINAL_EXAM_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ABDOMINAL_EXAM_RESULT;

---TRACHEA_TEST_RESULT  VARCHAR2(100)  Y    气管检查结果  —  S1  AN..100
SELECT TRACHEA_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY TRACHEA_TEST_RESULT;

---DENTAL_EXAMINATION_RESULT  VARCHAR2(100)  Y    牙齿检查结果  —  S1  AN..100
SELECT DENTAL_EXAMINATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DENTAL_EXAMINATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INP_NO;

---PREOPERATIVE_COMORBIDITY  VARCHAR2(100)  Y    术前合并疾病  —  S1  AN..100
SELECT PREOPERATIVE_COMORBIDITY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PREOPERATIVE_COMORBIDITY;

---BRIEF_HISTORY  VARCHAR2(100)  Y    简要病史  —  S1  AN..100
SELECT BRIEF_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BRIEF_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ALLERGY_HISTORY;

---ECG_RESULTS  VARCHAR2(100)  Y    心电图检查结果  —  S1  AN..100
SELECT ECG_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ECG_RESULTS;

---XLINE_RESULT  VARCHAR2(100)  Y    胸部X线检查结果  —  S1  AN..100
SELECT XLINE_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY XLINE_RESULT;

---CT_RESULT  VARCHAR2(100)  Y    CT检查结采  —  S1  AN..100
SELECT CT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CT_RESULT;

---B_INSPECTION  VARCHAR2(100)  Y    B超检查结果  —  S1  AN..100
SELECT B_INSPECTION FROM VISITS_REC_BEF_ANESTHESIA GROUP BY B_INSPECTION;

---MRI_RESULT  VARCHAR2(1000)  Y    MRI超检查结果  —  S1  AN..1000
SELECT MRI_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MRI_RESULT;

---PULMONARY_FUNCTION_RESULTS  VARCHAR2(1000)  Y    肺功能检查结果  —  S1  AN..1000
SELECT PULMONARY_FUNCTION_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PULMONARY_FUNCTION_RESULTS;

---BLOOD_ROUT_RESULT  VARCHAR2(1000)  Y    血常规检查结果  —  S1  AN..1000
SELECT BLOOD_ROUT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOOD_ROUT_RESULT;

---URINE_TEST_RESULTS  VARCHAR2(100)  Y    尿常规检查结果  —  S1  AN..100
SELECT URINE_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY URINE_TEST_RESULTS;

---COAGULATION_TEST_RESULTS  VARCHAR2(100)  Y    凝血功能检查结果  —  S1  AN..100
SELECT COAGULATION_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY COAGULATION_TEST_RESULTS;

---LIVER_FUNCTION_RESULT  VARCHAR2(100)  Y    肝功能检查结果  —  S1  AN..100
SELECT LIVER_FUNCTION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIVER_FUNCTION_RESULT;

---BLOODGAS_ANALYSIS_TEST_RESULT  VARCHAR2(1000)  Y    血气分析检查结果  —  S1  AN..1000
SELECT BLOODGAS_ANALYSIS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOODGAS_ANALYSIS_TEST_RESULT;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---MENTAL_STATE_FLAG  VARCHAR2(5)  Y    精神状态正常标志  —  L  T/F
SELECT MENTAL_STATE_FLAG FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MENTAL_STATE_FLAG;

---CARDIAC_AUSCULTATION_RESULT  VARCHAR2(100)  Y    心脏听诊结果  —  S1  AN..100
SELECT CARDIAC_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CARDIAC_AUSCULTATION_RESULT;

---LUNG_AUSCULTATION_RESULT  VARCHAR2(100)  Y    肺部听诊结果  —  S1  AN..100
SELECT LUNG_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LUNG_AUSCULTATION_RESULT;

---LIMBS_TEST_RESULT  VARCHAR2(1000)  Y    四肢检查结果  —  S1  AN..1000
SELECT LIMBS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIMBS_TEST_RESULT;

---SPINAL_RESULT  VARCHAR2(1000)  Y    脊柱检查结果  —  S1  AN..1000
SELECT SPINAL_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SPINAL_RESULT;

---ABDOMINAL_EXAM_RESULT  VARCHAR2(1000)  Y    腹部检查结果  —  S1  AN..1000
SELECT ABDOMINAL_EXAM_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ABDOMINAL_EXAM_RESULT;

---TRACHEA_TEST_RESULT  VARCHAR2(100)  Y    气管检查结果  —  S1  AN..100
SELECT TRACHEA_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY TRACHEA_TEST_RESULT;

---DENTAL_EXAMINATION_RESULT  VARCHAR2(100)  Y    牙齿检查结果  —  S1  AN..100
SELECT DENTAL_EXAMINATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DENTAL_EXAMINATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM VISITS_REC_BEF_ANESTHESIA GROUP BY INP_NO;

---PREOPERATIVE_COMORBIDITY  VARCHAR2(100)  Y    术前合并疾病  —  S1  AN..100
SELECT PREOPERATIVE_COMORBIDITY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PREOPERATIVE_COMORBIDITY;

---BRIEF_HISTORY  VARCHAR2(100)  Y    简要病史  —  S1  AN..100
SELECT BRIEF_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BRIEF_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ALLERGY_HISTORY;

---ECG_RESULTS  VARCHAR2(100)  Y    心电图检查结果  —  S1  AN..100
SELECT ECG_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ECG_RESULTS;

---XLINE_RESULT  VARCHAR2(100)  Y    胸部X线检查结果  —  S1  AN..100
SELECT XLINE_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY XLINE_RESULT;

---CT_RESULT  VARCHAR2(100)  Y    CT检查结采  —  S1  AN..100
SELECT CT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CT_RESULT;

---B_INSPECTION  VARCHAR2(100)  Y    B超检查结果  —  S1  AN..100
SELECT B_INSPECTION FROM VISITS_REC_BEF_ANESTHESIA GROUP BY B_INSPECTION;

---MRI_RESULT  VARCHAR2(1000)  Y    MRI超检查结果  —  S1  AN..1000
SELECT MRI_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MRI_RESULT;

---PULMONARY_FUNCTION_RESULTS  VARCHAR2(1000)  Y    肺功能检查结果  —  S1  AN..1000
SELECT PULMONARY_FUNCTION_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY PULMONARY_FUNCTION_RESULTS;

---BLOOD_ROUT_RESULT  VARCHAR2(1000)  Y    血常规检查结果  —  S1  AN..1000
SELECT BLOOD_ROUT_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOOD_ROUT_RESULT;

---URINE_TEST_RESULTS  VARCHAR2(100)  Y    尿常规检查结果  —  S1  AN..100
SELECT URINE_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY URINE_TEST_RESULTS;

---COAGULATION_TEST_RESULTS  VARCHAR2(100)  Y    凝血功能检查结果  —  S1  AN..100
SELECT COAGULATION_TEST_RESULTS FROM VISITS_REC_BEF_ANESTHESIA GROUP BY COAGULATION_TEST_RESULTS;

---LIVER_FUNCTION_RESULT  VARCHAR2(100)  Y    肝功能检查结果  —  S1  AN..100
SELECT LIVER_FUNCTION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIVER_FUNCTION_RESULT;

---BLOODGAS_ANALYSIS_TEST_RESULT  VARCHAR2(1000)  Y    血气分析检查结果  —  S1  AN..1000
SELECT BLOODGAS_ANALYSIS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY BLOODGAS_ANALYSIS_TEST_RESULT;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---MENTAL_STATE_FLAG  VARCHAR2(5)  Y    精神状态正常标志  —  L  T/F
SELECT MENTAL_STATE_FLAG FROM VISITS_REC_BEF_ANESTHESIA GROUP BY MENTAL_STATE_FLAG;

---CARDIAC_AUSCULTATION_RESULT  VARCHAR2(100)  Y    心脏听诊结果  —  S1  AN..100
SELECT CARDIAC_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY CARDIAC_AUSCULTATION_RESULT;

---LUNG_AUSCULTATION_RESULT  VARCHAR2(100)  Y    肺部听诊结果  —  S1  AN..100
SELECT LUNG_AUSCULTATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LUNG_AUSCULTATION_RESULT;

---LIMBS_TEST_RESULT  VARCHAR2(1000)  Y    四肢检查结果  —  S1  AN..1000
SELECT LIMBS_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LIMBS_TEST_RESULT;

---SPINAL_RESULT  VARCHAR2(1000)  Y    脊柱检查结果  —  S1  AN..1000
SELECT SPINAL_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SPINAL_RESULT;

---ABDOMINAL_EXAM_RESULT  VARCHAR2(1000)  Y    腹部检查结果  —  S1  AN..1000
SELECT ABDOMINAL_EXAM_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ABDOMINAL_EXAM_RESULT;

---TRACHEA_TEST_RESULT  VARCHAR2(100)  Y    气管检查结果  —  S1  AN..100
SELECT TRACHEA_TEST_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY TRACHEA_TEST_RESULT;

---DENTAL_EXAMINATION_RESULT  VARCHAR2(100)  Y    牙齿检查结果  —  S1  AN..100
SELECT DENTAL_EXAMINATION_RESULT FROM VISITS_REC_BEF_ANESTHESIA GROUP BY DENTAL_EXAMINATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY SIGN_DATETIME;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_BEF_ANESTHESIA GROUP BY OPER_REQ_SN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_BEF_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

