---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICPATIENT GROUP BY PATIENT_ID;

---HEALTH_FILE_NO  VARCHAR2(17)  Y    城乡居民健康档案编号    null  null
SELECT HEALTH_FILE_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_FILE_NO;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    null  null
SELECT IDENTITY_NO FROM EMR_BASICPATIENT GROUP BY IDENTITY_NO;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码    null  null
SELECT IDENTITY_TYPE FROM EMR_BASICPATIENT GROUP BY IDENTITY_TYPE;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_CARD_NO;

---PAYMENT_TYPE  VARCHAR2(2)  Y    医疗保险类别代码    null  null
SELECT PAYMENT_TYPE FROM EMR_BASICPATIENT GROUP BY PAYMENT_TYPE;

---PATIENT_NAME  VARCHAR2(50)  Y    患者姓名    null  null
SELECT PATIENT_NAME FROM EMR_BASICPATIENT GROUP BY PATIENT_NAME;

---BIRTHDAY  DATE  Y    出生日期    null  null
SELECT BIRTHDAY FROM EMR_BASICPATIENT GROUP BY BIRTHDAY;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码    null  null
SELECT PATIENT_SEX FROM EMR_BASICPATIENT GROUP BY PATIENT_SEX;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码    null  null
SELECT MARITAL_STATUS_CODE FROM EMR_BASICPATIENT GROUP BY MARITAL_STATUS_CODE;

---NATION  VARCHAR2(2)  Y    民族代码    null  null
SELECT NATION FROM EMR_BASICPATIENT GROUP BY NATION;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码    null  null
SELECT NATIONNALITY FROM EMR_BASICPATIENT GROUP BY NATIONNALITY;

---DEGREE_CODE  NUMBER(2)  Y    学历代码    null  null
SELECT DEGREE_CODE FROM EMR_BASICPATIENT GROUP BY DEGREE_CODE;

---OCCUPATIENTION_CLASS_CODE  NUMBER(2)  Y    从业状况代码    null  null
SELECT OCCUPATIENTION_CLASS_CODE FROM EMR_BASICPATIENT GROUP BY OCCUPATIENTION_CLASS_CODE;

---OCCUPATION_NAME  VARCHAR2(70)  Y    工作单位名称    null  null
SELECT OCCUPATION_NAME FROM EMR_BASICPATIENT GROUP BY OCCUPATION_NAME;

---CURRENT_EMAIL  VARCHAR2(70)  Y    患者电子邮件地址    null  null
SELECT CURRENT_EMAIL FROM EMR_BASICPATIENT GROUP BY CURRENT_EMAIL;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    null  null
SELECT WORKUNIT_PHONE FROM EMR_BASICPATIENT GROUP BY WORKUNIT_PHONE;

---INPUT_DATE  DATE  Y    建档日期时间    null  null
SELECT INPUT_DATE FROM EMR_BASICPATIENT GROUP BY INPUT_DATE;

---INPUT_ORGAN_CODE  VARCHAR2(10)  Y    建档医疗机构组织机构    null  null
SELECT INPUT_ORGAN_CODE FROM EMR_BASICPATIENT GROUP BY INPUT_ORGAN_CODE;

---INPUT_NAME  VARCHAR2(50)  Y    建档者姓名    null  null
SELECT INPUT_NAME FROM EMR_BASICPATIENT GROUP BY INPUT_NAME;

---CURRENT_PHONE  VARCHAR2(20)  Y    患者电话号码    null  null
SELECT CURRENT_PHONE FROM EMR_BASICPATIENT GROUP BY CURRENT_PHONE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    null  null
SELECT CONTACT_NAME FROM EMR_BASICPATIENT GROUP BY CONTACT_NAME;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    null  null
SELECT CONTACT_PHONE FROM EMR_BASICPATIENT GROUP BY CONTACT_PHONE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICPATIENT GROUP BY LAST_MODIFIC_TIME;

---EMPI_ID  VARCHAR2(32)      empi号    null  null
SELECT EMPI_ID FROM EMR_BASICPATIENT GROUP BY EMPI_ID;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICPATIENT GROUP BY PATIENT_ID;

---HEALTH_FILE_NO  VARCHAR2(17)  Y    城乡居民健康档案编号    null  null
SELECT HEALTH_FILE_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_FILE_NO;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    null  null
SELECT IDENTITY_NO FROM EMR_BASICPATIENT GROUP BY IDENTITY_NO;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码    null  null
SELECT IDENTITY_TYPE FROM EMR_BASICPATIENT GROUP BY IDENTITY_TYPE;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_CARD_NO;

---PAYMENT_TYPE  VARCHAR2(2)  Y    医疗保险类别代码    null  null
SELECT PAYMENT_TYPE FROM EMR_BASICPATIENT GROUP BY PAYMENT_TYPE;

---PATIENT_NAME  VARCHAR2(50)  Y    患者姓名    null  null
SELECT PATIENT_NAME FROM EMR_BASICPATIENT GROUP BY PATIENT_NAME;

---BIRTHDAY  DATE  Y    出生日期    null  null
SELECT BIRTHDAY FROM EMR_BASICPATIENT GROUP BY BIRTHDAY;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码    null  null
SELECT PATIENT_SEX FROM EMR_BASICPATIENT GROUP BY PATIENT_SEX;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码    null  null
SELECT MARITAL_STATUS_CODE FROM EMR_BASICPATIENT GROUP BY MARITAL_STATUS_CODE;

---NATION  VARCHAR2(2)  Y    民族代码    null  null
SELECT NATION FROM EMR_BASICPATIENT GROUP BY NATION;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码    null  null
SELECT NATIONNALITY FROM EMR_BASICPATIENT GROUP BY NATIONNALITY;

---DEGREE_CODE  NUMBER(2)  Y    学历代码    null  null
SELECT DEGREE_CODE FROM EMR_BASICPATIENT GROUP BY DEGREE_CODE;

---OCCUPATIENTION_CLASS_CODE  NUMBER(2)  Y    从业状况代码    null  null
SELECT OCCUPATIENTION_CLASS_CODE FROM EMR_BASICPATIENT GROUP BY OCCUPATIENTION_CLASS_CODE;

---OCCUPATION_NAME  VARCHAR2(70)  Y    工作单位名称    null  null
SELECT OCCUPATION_NAME FROM EMR_BASICPATIENT GROUP BY OCCUPATION_NAME;

---CURRENT_EMAIL  VARCHAR2(70)  Y    患者电子邮件地址    null  null
SELECT CURRENT_EMAIL FROM EMR_BASICPATIENT GROUP BY CURRENT_EMAIL;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    null  null
SELECT WORKUNIT_PHONE FROM EMR_BASICPATIENT GROUP BY WORKUNIT_PHONE;

---INPUT_DATE  DATE  Y    建档日期时间    null  null
SELECT INPUT_DATE FROM EMR_BASICPATIENT GROUP BY INPUT_DATE;

---INPUT_ORGAN_CODE  VARCHAR2(10)  Y    建档医疗机构组织机构    null  null
SELECT INPUT_ORGAN_CODE FROM EMR_BASICPATIENT GROUP BY INPUT_ORGAN_CODE;

---INPUT_NAME  VARCHAR2(50)  Y    建档者姓名    null  null
SELECT INPUT_NAME FROM EMR_BASICPATIENT GROUP BY INPUT_NAME;

---CURRENT_PHONE  VARCHAR2(20)  Y    患者电话号码    null  null
SELECT CURRENT_PHONE FROM EMR_BASICPATIENT GROUP BY CURRENT_PHONE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    null  null
SELECT CONTACT_NAME FROM EMR_BASICPATIENT GROUP BY CONTACT_NAME;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    null  null
SELECT CONTACT_PHONE FROM EMR_BASICPATIENT GROUP BY CONTACT_PHONE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICPATIENT GROUP BY LAST_MODIFIC_TIME;

---EMPI_ID  VARCHAR2(32)      empi号    null  null
SELECT EMPI_ID FROM EMR_BASICPATIENT GROUP BY EMPI_ID;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICPATIENT GROUP BY PATIENT_ID;

---HEALTH_FILE_NO  VARCHAR2(17)  Y    城乡居民健康档案编号    null  null
SELECT HEALTH_FILE_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_FILE_NO;

---IDENTITY_NO  VARCHAR2(18)  Y    患者身份证件号码    null  null
SELECT IDENTITY_NO FROM EMR_BASICPATIENT GROUP BY IDENTITY_NO;

---IDENTITY_TYPE  VARCHAR2(2)  Y    身份证件类别代码    null  null
SELECT IDENTITY_TYPE FROM EMR_BASICPATIENT GROUP BY IDENTITY_TYPE;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICPATIENT GROUP BY HEALTH_CARD_NO;

---PAYMENT_TYPE  VARCHAR2(2)  Y    医疗保险类别代码    null  null
SELECT PAYMENT_TYPE FROM EMR_BASICPATIENT GROUP BY PAYMENT_TYPE;

---PATIENT_NAME  VARCHAR2(50)  Y    患者姓名    null  null
SELECT PATIENT_NAME FROM EMR_BASICPATIENT GROUP BY PATIENT_NAME;

---BIRTHDAY  DATE  Y    出生日期    null  null
SELECT BIRTHDAY FROM EMR_BASICPATIENT GROUP BY BIRTHDAY;

---PATIENT_SEX  VARCHAR2(1)  Y    性别代码    null  null
SELECT PATIENT_SEX FROM EMR_BASICPATIENT GROUP BY PATIENT_SEX;

---MARITAL_STATUS_CODE  VARCHAR2(2)  Y    婚姻状况代码    null  null
SELECT MARITAL_STATUS_CODE FROM EMR_BASICPATIENT GROUP BY MARITAL_STATUS_CODE;

---NATION  VARCHAR2(2)  Y    民族代码    null  null
SELECT NATION FROM EMR_BASICPATIENT GROUP BY NATION;

---NATIONNALITY  VARCHAR2(3)  Y    国籍代码    null  null
SELECT NATIONNALITY FROM EMR_BASICPATIENT GROUP BY NATIONNALITY;

---DEGREE_CODE  NUMBER(2)  Y    学历代码    null  null
SELECT DEGREE_CODE FROM EMR_BASICPATIENT GROUP BY DEGREE_CODE;

---OCCUPATIENTION_CLASS_CODE  NUMBER(2)  Y    从业状况代码    null  null
SELECT OCCUPATIENTION_CLASS_CODE FROM EMR_BASICPATIENT GROUP BY OCCUPATIENTION_CLASS_CODE;

---OCCUPATION_NAME  VARCHAR2(70)  Y    工作单位名称    null  null
SELECT OCCUPATION_NAME FROM EMR_BASICPATIENT GROUP BY OCCUPATION_NAME;

---CURRENT_EMAIL  VARCHAR2(70)  Y    患者电子邮件地址    null  null
SELECT CURRENT_EMAIL FROM EMR_BASICPATIENT GROUP BY CURRENT_EMAIL;

---WORKUNIT_PHONE  VARCHAR2(20)  Y    工作单位电话号码    null  null
SELECT WORKUNIT_PHONE FROM EMR_BASICPATIENT GROUP BY WORKUNIT_PHONE;

---INPUT_DATE  DATE  Y    建档日期时间    null  null
SELECT INPUT_DATE FROM EMR_BASICPATIENT GROUP BY INPUT_DATE;

---INPUT_ORGAN_CODE  VARCHAR2(10)  Y    建档医疗机构组织机构    null  null
SELECT INPUT_ORGAN_CODE FROM EMR_BASICPATIENT GROUP BY INPUT_ORGAN_CODE;

---INPUT_NAME  VARCHAR2(50)  Y    建档者姓名    null  null
SELECT INPUT_NAME FROM EMR_BASICPATIENT GROUP BY INPUT_NAME;

---CURRENT_PHONE  VARCHAR2(20)  Y    患者电话号码    null  null
SELECT CURRENT_PHONE FROM EMR_BASICPATIENT GROUP BY CURRENT_PHONE;

---CONTACT_NAME  VARCHAR2(50)  Y    联系人姓名    null  null
SELECT CONTACT_NAME FROM EMR_BASICPATIENT GROUP BY CONTACT_NAME;

---CONTACT_PHONE  VARCHAR2(20)  Y    联系人电话号码    null  null
SELECT CONTACT_PHONE FROM EMR_BASICPATIENT GROUP BY CONTACT_PHONE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICPATIENT GROUP BY LAST_MODIFIC_TIME;

---EMPI_ID  VARCHAR2(32)      empi号    null  null
SELECT EMPI_ID FROM EMR_BASICPATIENT GROUP BY EMPI_ID;

