---REP_DETAIL_ID  VARCHAR2(100)      检验报告细项ID      
SELECT REP_DETAIL_ID FROM SURVEY_RECORD_DETAIL GROUP BY REP_DETAIL_ID;

---INSPECTION_REPORT_NO  VARCHAR2(20)      检验报告单编号    S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_REPORT_NO;

---EXAM_ITEM_CODE  VARCHAR2(20)  Y    检验报告细项项目代码      
SELECT EXAM_ITEM_CODE FROM SURVEY_RECORD_DETAIL GROUP BY EXAM_ITEM_CODE;

---INSPECTION_RESULT_CODE  VARCHAR2(1)  Y    检验结果代码  1.正常2.异常3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检验定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUANTIFY_UNIT FROM SURVEY_RECORD_DETAIL GROUP BY EXAMINATION_QUANTIFY_UNIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD_DETAIL GROUP BY LAST_MODIFIC_TIME;

---REP_DETAIL_ID  VARCHAR2(100)      检验报告细项ID      
SELECT REP_DETAIL_ID FROM SURVEY_RECORD_DETAIL GROUP BY REP_DETAIL_ID;

---INSPECTION_REPORT_NO  VARCHAR2(20)      检验报告单编号    S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_REPORT_NO;

---EXAM_ITEM_CODE  VARCHAR2(20)  Y    检验报告细项项目代码      
SELECT EXAM_ITEM_CODE FROM SURVEY_RECORD_DETAIL GROUP BY EXAM_ITEM_CODE;

---INSPECTION_RESULT_CODE  VARCHAR2(1)  Y    检验结果代码  1.正常2.异常3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检验定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUANTIFY_UNIT FROM SURVEY_RECORD_DETAIL GROUP BY EXAMINATION_QUANTIFY_UNIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD_DETAIL GROUP BY LAST_MODIFIC_TIME;

---REP_DETAIL_ID  VARCHAR2(100)      检验报告细项ID      
SELECT REP_DETAIL_ID FROM SURVEY_RECORD_DETAIL GROUP BY REP_DETAIL_ID;

---INSPECTION_REPORT_NO  VARCHAR2(20)      检验报告单编号    S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_REPORT_NO;

---EXAM_ITEM_CODE  VARCHAR2(20)  Y    检验报告细项项目代码      
SELECT EXAM_ITEM_CODE FROM SURVEY_RECORD_DETAIL GROUP BY EXAM_ITEM_CODE;

---INSPECTION_RESULT_CODE  VARCHAR2(1)  Y    检验结果代码  1.正常2.异常3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SURVEY_RECORD_DETAIL GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检验定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUANTIFY_UNIT FROM SURVEY_RECORD_DETAIL GROUP BY EXAMINATION_QUANTIFY_UNIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD_DETAIL GROUP BY LAST_MODIFIC_TIME;

