---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CAESAREAN_SECTION_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CAESAREAN_SECTION_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CAESAREAN_SECTION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CAESAREAN_SECTION_RECORD GROUP BY PATIENT_ID;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号      
SELECT OPERA_SN FROM CAESAREAN_SECTION_RECORD GROUP BY OPERA_SN;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM CAESAREAN_SECTION_RECORD GROUP BY PREDELIVERY_DATETIME;

---PREOPERATION_DIAG  VARCHAR2(200)  Y    术前诊断    S1  AN..200
SELECT PREOPERATION_DIAG FROM CAESAREAN_SECTION_RECORD GROUP BY PREOPERATION_DIAG;

---CESAREAN_PROCESS  VARCHAR2(2000)  Y    剖宫产手术过程    S1  AN..2000
SELECT CESAREAN_PROCESS FROM CAESAREAN_SECTION_RECORD GROUP BY CESAREAN_PROCESS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_CONDITIONS;

---FETAL_CHILDBIRTH_WAY  VARCHAR2(100)  Y    胎儿娩出方式    S1  AN..100
SELECT FETAL_CHILDBIRTH_WAY FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_CHILDBIRTH_WAY;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量（mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    脐带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---ABNUMBERRMAL_UMBILICAL_CORD  VARCHAR2(200)  Y    胳带异常情况描述    S1  AN..200
SELECT ABNUMBERRMAL_UMBILICAL_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY ABNUMBERRMAL_UMBILICAL_CORD;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---UTERINE_WALL_SUTURE  VARCHAR2(100)  Y    子宫壁缝合情况    S1  AN..100
SELECT UTERINE_WALL_SUTURE FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_WALL_SUTURE;

---UTEROTONICS_NAME  VARCHAR2(50)  Y    宫缩剂名称    S1  AN..50
SELECT UTEROTONICS_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_NAME;

---UTEROTONICS_USE  VARCHAR2(100)  Y    宫缩剂使用方法    S1  AN..100
SELECT UTEROTONICS_USE FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_USE;

---OPERATE_DRUG  VARCHAR2(50)  Y    手术用药    S1  AN..50
SELECT OPERATE_DRUG FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG;

---OPERATE_DRUG_DOSAGE  VARCHAR2(50)  Y    手术用药量    S1  AN..50
SELECT OPERATE_DRUG_DOSAGE FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG_DOSAGE;

---ABDOMINAL_EXPLORATION_UTERUS  VARCHAR2(100)  Y    腹腔探查子宫    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_UTERUS FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_UTERUS;

---ABDOMINAL_EXPLORATION_ANNEX  VARCHAR2(100)  Y    腹腔探查附件    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_ANNEX FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_ANNEX;

---INTRAUTER_EXPLORAT_ANOMALIES  VARCHAR2(1000)  Y    宫腔探查异常情况描述    S1  AN.. 1000
SELECT INTRAUTER_EXPLORAT_ANOMALIES FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTER_EXPLORAT_ANOMALIES;

---INTRAUTERINE_EXPLORAT_TREAT  VARCHAR2(100)  Y    宫腔探查处理情_况    S1  AN..100
SELECT INTRAUTERINE_EXPLORAT_TREAT FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTERINE_EXPLORAT_TREAT;

---OPERATION_MATERNITY  VARCHAR2(1000)  Y    手术时产妇情况    S1  AN..1000
SELECT OPERATION_MATERNITY FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_MATERNITY;

---BLOOD_LOSSED  NUMBER(5)  Y    出血量(mL)    N  N..5
SELECT BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_LOSSED;

---TRANS_INGREDIENTS  VARCHAR2(100)  Y    输血成分    S1  AN..100
SELECT TRANS_INGREDIENTS FROM CAESAREAN_SECTION_RECORD GROUP BY TRANS_INGREDIENTS;

---BLOOD_TRANSFERED  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_TRANSFERED;

---OPERATION_INFUSION  NUMBER(5)  Y    输液最（mL)    N  N"5
SELECT OPERATION_INFUSION FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INFUSION;

---OXYGEN_SUPPLY_TIME  NUMBER(4)  Y    供氧时间（min)    N  N..4
SELECT OXYGEN_SUPPLY_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OXYGEN_SUPPLY_TIME;

---OTHER_DRUG_NAME  VARCHAR2(50)  Y    其他用药    S1  AN..50
SELECT OTHER_DRUG_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_NAME;

---OTHER_DRUG_USE  VARCHAR2(100)  Y    其他用药情况    S1  AN..100
SELECT OTHER_DRUG_USE FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_USE;

---OPERATION_FULL_TIME  NUMBER(4)  Y    手术全程时间（min)    N  N1..4
SELECT OPERATION_FULL_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_FULL_TIME;

---OPERATE_AFTER_NAME  VARCHAR2(200)  Y    术后诊断    S1  AN..200
SELECT OPERATE_AFTER_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_AFTER_NAME;

---POSTOPER_OBSERVATION_DATE  DATE  Y    术后观察日期时间    DT  DT15
SELECT POSTOPER_OBSERVATION_DATE FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_OBSERVATION_DATE;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    术后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    术后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    术后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    术后脉搏（次/min）    N  N2..3
SELECT PULSE FROM CAESAREAN_SECTION_RECORD GROUP BY PULSE;

---CARDIOTACH  NUMBER(3)  Y    术后心率（次/min）    N  N2..3
SELECT CARDIOTACH FROM CAESAREAN_SECTION_RECORD GROUP BY CARDIOTACH;

---POSTOPER_BLOOD_LOSSED  NUMBER(5)  Y    术后出血量（mL)    N  N..5
SELECT POSTOPER_BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    术后宫缩    S1  AN..200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    术后宫底高度（cm）    N  N3..4.1
SELECT POSTPARTUM_UTERINE_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---NEWBORN_SEX  VARCHAR2(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_SEX;

---BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT BIRTH_WEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身长（cm）    _ N  N4..5,l
SELECT NEWBORN_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN.. 100
SELECT TUMOR_LOCATION FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  VARCHAR2(1)  Y    Apgar评分间隔时间代码  标准值：
1、1 min
2、5 min
3、10 min  S2  N1
SELECT APGAR_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  VARCHAR2(1)  Y    分娩结局代码  标准值：1.活产2.死胎3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  VARCHAR2(1)  Y    新生儿异常情况代码  应符合国家标准：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY RECORD_SIGN;

---OPERATION_INDICATIONS  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATION_INDICATIONS FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INDICATIONS;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM CAESAREAN_SECTION_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---UMBILICAL_CORD_TWIST  VARCHAR2(10)  Y    脐带扭转（周）      
SELECT UMBILICAL_CORD_TWIST FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_TWIST;

---EXPLORE_FIBROIDS_FLAG  VARCHAR2(5)  Y    宫腔探查肌瘤标志  TRUE/FALSE    
SELECT EXPLORE_FIBROIDS_FLAG FROM CAESAREAN_SECTION_RECORD GROUP BY EXPLORE_FIBROIDS_FLAG;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国家标准：CV05.01.007    
SELECT FETAL_POSITION_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_POSITION_CODE;

---YELLOW_STAINING_OF_PLACENTA  VARCHAR2(200)  Y    胎盘黄染描述      
SELECT YELLOW_STAINING_OF_PLACENTA FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINING_OF_PLACENTA;

---YELLOW_STAINED_MEMBRANES  VARCHAR2(200)  Y    胎膜黄染描述      
SELECT YELLOW_STAINED_MEMBRANES FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINED_MEMBRANES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间，抽数据用      
SELECT LAST_MODIFIC_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CAESAREAN_SECTION_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CAESAREAN_SECTION_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CAESAREAN_SECTION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CAESAREAN_SECTION_RECORD GROUP BY PATIENT_ID;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号      
SELECT OPERA_SN FROM CAESAREAN_SECTION_RECORD GROUP BY OPERA_SN;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM CAESAREAN_SECTION_RECORD GROUP BY PREDELIVERY_DATETIME;

---PREOPERATION_DIAG  VARCHAR2(200)  Y    术前诊断    S1  AN..200
SELECT PREOPERATION_DIAG FROM CAESAREAN_SECTION_RECORD GROUP BY PREOPERATION_DIAG;

---CESAREAN_PROCESS  VARCHAR2(2000)  Y    剖宫产手术过程    S1  AN..2000
SELECT CESAREAN_PROCESS FROM CAESAREAN_SECTION_RECORD GROUP BY CESAREAN_PROCESS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_CONDITIONS;

---FETAL_CHILDBIRTH_WAY  VARCHAR2(100)  Y    胎儿娩出方式    S1  AN..100
SELECT FETAL_CHILDBIRTH_WAY FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_CHILDBIRTH_WAY;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量（mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    脐带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---ABNUMBERRMAL_UMBILICAL_CORD  VARCHAR2(200)  Y    胳带异常情况描述    S1  AN..200
SELECT ABNUMBERRMAL_UMBILICAL_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY ABNUMBERRMAL_UMBILICAL_CORD;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---UTERINE_WALL_SUTURE  VARCHAR2(100)  Y    子宫壁缝合情况    S1  AN..100
SELECT UTERINE_WALL_SUTURE FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_WALL_SUTURE;

---UTEROTONICS_NAME  VARCHAR2(50)  Y    宫缩剂名称    S1  AN..50
SELECT UTEROTONICS_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_NAME;

---UTEROTONICS_USE  VARCHAR2(100)  Y    宫缩剂使用方法    S1  AN..100
SELECT UTEROTONICS_USE FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_USE;

---OPERATE_DRUG  VARCHAR2(50)  Y    手术用药    S1  AN..50
SELECT OPERATE_DRUG FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG;

---OPERATE_DRUG_DOSAGE  VARCHAR2(50)  Y    手术用药量    S1  AN..50
SELECT OPERATE_DRUG_DOSAGE FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG_DOSAGE;

---ABDOMINAL_EXPLORATION_UTERUS  VARCHAR2(100)  Y    腹腔探查子宫    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_UTERUS FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_UTERUS;

---ABDOMINAL_EXPLORATION_ANNEX  VARCHAR2(100)  Y    腹腔探查附件    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_ANNEX FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_ANNEX;

---INTRAUTER_EXPLORAT_ANOMALIES  VARCHAR2(1000)  Y    宫腔探查异常情况描述    S1  AN.. 1000
SELECT INTRAUTER_EXPLORAT_ANOMALIES FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTER_EXPLORAT_ANOMALIES;

---INTRAUTERINE_EXPLORAT_TREAT  VARCHAR2(100)  Y    宫腔探查处理情_况    S1  AN..100
SELECT INTRAUTERINE_EXPLORAT_TREAT FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTERINE_EXPLORAT_TREAT;

---OPERATION_MATERNITY  VARCHAR2(1000)  Y    手术时产妇情况    S1  AN..1000
SELECT OPERATION_MATERNITY FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_MATERNITY;

---BLOOD_LOSSED  NUMBER(5)  Y    出血量(mL)    N  N..5
SELECT BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_LOSSED;

---TRANS_INGREDIENTS  VARCHAR2(100)  Y    输血成分    S1  AN..100
SELECT TRANS_INGREDIENTS FROM CAESAREAN_SECTION_RECORD GROUP BY TRANS_INGREDIENTS;

---BLOOD_TRANSFERED  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_TRANSFERED;

---OPERATION_INFUSION  NUMBER(5)  Y    输液最（mL)    N  N"5
SELECT OPERATION_INFUSION FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INFUSION;

---OXYGEN_SUPPLY_TIME  NUMBER(4)  Y    供氧时间（min)    N  N..4
SELECT OXYGEN_SUPPLY_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OXYGEN_SUPPLY_TIME;

---OTHER_DRUG_NAME  VARCHAR2(50)  Y    其他用药    S1  AN..50
SELECT OTHER_DRUG_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_NAME;

---OTHER_DRUG_USE  VARCHAR2(100)  Y    其他用药情况    S1  AN..100
SELECT OTHER_DRUG_USE FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_USE;

---OPERATION_FULL_TIME  NUMBER(4)  Y    手术全程时间（min)    N  N1..4
SELECT OPERATION_FULL_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_FULL_TIME;

---OPERATE_AFTER_NAME  VARCHAR2(200)  Y    术后诊断    S1  AN..200
SELECT OPERATE_AFTER_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_AFTER_NAME;

---POSTOPER_OBSERVATION_DATE  DATE  Y    术后观察日期时间    DT  DT15
SELECT POSTOPER_OBSERVATION_DATE FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_OBSERVATION_DATE;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    术后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    术后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    术后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    术后脉搏（次/min）    N  N2..3
SELECT PULSE FROM CAESAREAN_SECTION_RECORD GROUP BY PULSE;

---CARDIOTACH  NUMBER(3)  Y    术后心率（次/min）    N  N2..3
SELECT CARDIOTACH FROM CAESAREAN_SECTION_RECORD GROUP BY CARDIOTACH;

---POSTOPER_BLOOD_LOSSED  NUMBER(5)  Y    术后出血量（mL)    N  N..5
SELECT POSTOPER_BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    术后宫缩    S1  AN..200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    术后宫底高度（cm）    N  N3..4.1
SELECT POSTPARTUM_UTERINE_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---NEWBORN_SEX  VARCHAR2(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_SEX;

---BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT BIRTH_WEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身长（cm）    _ N  N4..5,l
SELECT NEWBORN_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN.. 100
SELECT TUMOR_LOCATION FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  VARCHAR2(1)  Y    Apgar评分间隔时间代码  标准值：
1、1 min
2、5 min
3、10 min  S2  N1
SELECT APGAR_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  VARCHAR2(1)  Y    分娩结局代码  标准值：1.活产2.死胎3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  VARCHAR2(1)  Y    新生儿异常情况代码  应符合国家标准：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY RECORD_SIGN;

---OPERATION_INDICATIONS  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATION_INDICATIONS FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INDICATIONS;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM CAESAREAN_SECTION_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---UMBILICAL_CORD_TWIST  VARCHAR2(10)  Y    脐带扭转（周）      
SELECT UMBILICAL_CORD_TWIST FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_TWIST;

---EXPLORE_FIBROIDS_FLAG  VARCHAR2(5)  Y    宫腔探查肌瘤标志  TRUE/FALSE    
SELECT EXPLORE_FIBROIDS_FLAG FROM CAESAREAN_SECTION_RECORD GROUP BY EXPLORE_FIBROIDS_FLAG;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国家标准：CV05.01.007    
SELECT FETAL_POSITION_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_POSITION_CODE;

---YELLOW_STAINING_OF_PLACENTA  VARCHAR2(200)  Y    胎盘黄染描述      
SELECT YELLOW_STAINING_OF_PLACENTA FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINING_OF_PLACENTA;

---YELLOW_STAINED_MEMBRANES  VARCHAR2(200)  Y    胎膜黄染描述      
SELECT YELLOW_STAINED_MEMBRANES FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINED_MEMBRANES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间，抽数据用      
SELECT LAST_MODIFIC_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM CAESAREAN_SECTION_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM CAESAREAN_SECTION_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM CAESAREAN_SECTION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM CAESAREAN_SECTION_RECORD GROUP BY PATIENT_ID;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号      
SELECT OPERA_SN FROM CAESAREAN_SECTION_RECORD GROUP BY OPERA_SN;

---PREDELIVERY_DATETIME  DATE  Y    待产日期时间    DT  DTI 5
SELECT PREDELIVERY_DATETIME FROM CAESAREAN_SECTION_RECORD GROUP BY PREDELIVERY_DATETIME;

---PREOPERATION_DIAG  VARCHAR2(200)  Y    术前诊断    S1  AN..200
SELECT PREOPERATION_DIAG FROM CAESAREAN_SECTION_RECORD GROUP BY PREOPERATION_DIAG;

---CESAREAN_PROCESS  VARCHAR2(2000)  Y    剖宫产手术过程    S1  AN..2000
SELECT CESAREAN_PROCESS FROM CAESAREAN_SECTION_RECORD GROUP BY CESAREAN_PROCESS;

---UTERINE_CONDITIONS  VARCHAR2(100)  Y    子宫情况    S1  AN..100
SELECT UTERINE_CONDITIONS FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_CONDITIONS;

---FETAL_CHILDBIRTH_WAY  VARCHAR2(100)  Y    胎儿娩出方式    S1  AN..100
SELECT FETAL_CHILDBIRTH_WAY FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_CHILDBIRTH_WAY;

---AMNIOTIC_FLUID_CHARACTER  VARCHAR2(100)  Y    羊水性状    S1  AN..100
SELECT AMNIOTIC_FLUID_CHARACTER FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_CHARACTER;

---AMNIOTIC_FLUID_VOLUME  NUMBER(5)  Y    羊水量（mL)    N  N..5
SELECT AMNIOTIC_FLUID_VOLUME FROM CAESAREAN_SECTION_RECORD GROUP BY AMNIOTIC_FLUID_VOLUME;

---PLACENTAL_EXPULSION_TIME  DATE  Y    胎盘娩出日期时间    DT  DTI 5
SELECT PLACENTAL_EXPULSION_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_TIME;

---PLACENTAL_EXPULSION_SITUATION  VARCHAR2(100)  Y    胎盘娩出情况    S1  AN..100
SELECT PLACENTAL_EXPULSION_SITUATION FROM CAESAREAN_SECTION_RECORD GROUP BY PLACENTAL_EXPULSION_SITUATION;

---INTACT_FETALMEMBRANES_CODE  VARCHAR2(5)  Y    胎膜完整情况标志  TRUE/FALSE  L  T/F
SELECT INTACT_FETALMEMBRANES_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY INTACT_FETALMEMBRANES_CODE;

---UMBILICAL_CORD_LENGTH  NUMBER(5)  Y    脐带长度（cm）    N  N..5
SELECT UMBILICAL_CORD_LENGTH FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_LENGTH;

---UMBILICALCORD_WINDING_NUMBER  NUMBER(3)  Y    绕颈身（周）    N  N..3
SELECT UMBILICALCORD_WINDING_NUMBER FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICALCORD_WINDING_NUMBER;

---ABNUMBERRMAL_UMBILICAL_CORD  VARCHAR2(200)  Y    胳带异常情况描述    S1  AN..200
SELECT ABNUMBERRMAL_UMBILICAL_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY ABNUMBERRMAL_UMBILICAL_CORD;

---UMBILICAL_BLOOD_CORD  VARCHAR2(5)  Y    存脐带血情况标志  TRUE/FALSE  L  T/F
SELECT UMBILICAL_BLOOD_CORD FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_BLOOD_CORD;

---UTERINE_WALL_SUTURE  VARCHAR2(100)  Y    子宫壁缝合情况    S1  AN..100
SELECT UTERINE_WALL_SUTURE FROM CAESAREAN_SECTION_RECORD GROUP BY UTERINE_WALL_SUTURE;

---UTEROTONICS_NAME  VARCHAR2(50)  Y    宫缩剂名称    S1  AN..50
SELECT UTEROTONICS_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_NAME;

---UTEROTONICS_USE  VARCHAR2(100)  Y    宫缩剂使用方法    S1  AN..100
SELECT UTEROTONICS_USE FROM CAESAREAN_SECTION_RECORD GROUP BY UTEROTONICS_USE;

---OPERATE_DRUG  VARCHAR2(50)  Y    手术用药    S1  AN..50
SELECT OPERATE_DRUG FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG;

---OPERATE_DRUG_DOSAGE  VARCHAR2(50)  Y    手术用药量    S1  AN..50
SELECT OPERATE_DRUG_DOSAGE FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_DRUG_DOSAGE;

---ABDOMINAL_EXPLORATION_UTERUS  VARCHAR2(100)  Y    腹腔探查子宫    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_UTERUS FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_UTERUS;

---ABDOMINAL_EXPLORATION_ANNEX  VARCHAR2(100)  Y    腹腔探查附件    S1  AN..100
SELECT ABDOMINAL_EXPLORATION_ANNEX FROM CAESAREAN_SECTION_RECORD GROUP BY ABDOMINAL_EXPLORATION_ANNEX;

---INTRAUTER_EXPLORAT_ANOMALIES  VARCHAR2(1000)  Y    宫腔探查异常情况描述    S1  AN.. 1000
SELECT INTRAUTER_EXPLORAT_ANOMALIES FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTER_EXPLORAT_ANOMALIES;

---INTRAUTERINE_EXPLORAT_TREAT  VARCHAR2(100)  Y    宫腔探查处理情_况    S1  AN..100
SELECT INTRAUTERINE_EXPLORAT_TREAT FROM CAESAREAN_SECTION_RECORD GROUP BY INTRAUTERINE_EXPLORAT_TREAT;

---OPERATION_MATERNITY  VARCHAR2(1000)  Y    手术时产妇情况    S1  AN..1000
SELECT OPERATION_MATERNITY FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_MATERNITY;

---BLOOD_LOSSED  NUMBER(5)  Y    出血量(mL)    N  N..5
SELECT BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_LOSSED;

---TRANS_INGREDIENTS  VARCHAR2(100)  Y    输血成分    S1  AN..100
SELECT TRANS_INGREDIENTS FROM CAESAREAN_SECTION_RECORD GROUP BY TRANS_INGREDIENTS;

---BLOOD_TRANSFERED  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED FROM CAESAREAN_SECTION_RECORD GROUP BY BLOOD_TRANSFERED;

---OPERATION_INFUSION  NUMBER(5)  Y    输液最（mL)    N  N"5
SELECT OPERATION_INFUSION FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INFUSION;

---OXYGEN_SUPPLY_TIME  NUMBER(4)  Y    供氧时间（min)    N  N..4
SELECT OXYGEN_SUPPLY_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OXYGEN_SUPPLY_TIME;

---OTHER_DRUG_NAME  VARCHAR2(50)  Y    其他用药    S1  AN..50
SELECT OTHER_DRUG_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_NAME;

---OTHER_DRUG_USE  VARCHAR2(100)  Y    其他用药情况    S1  AN..100
SELECT OTHER_DRUG_USE FROM CAESAREAN_SECTION_RECORD GROUP BY OTHER_DRUG_USE;

---OPERATION_FULL_TIME  NUMBER(4)  Y    手术全程时间（min)    N  N1..4
SELECT OPERATION_FULL_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_FULL_TIME;

---OPERATE_AFTER_NAME  VARCHAR2(200)  Y    术后诊断    S1  AN..200
SELECT OPERATE_AFTER_NAME FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATE_AFTER_NAME;

---POSTOPER_OBSERVATION_DATE  DATE  Y    术后观察日期时间    DT  DT15
SELECT POSTOPER_OBSERVATION_DATE FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_OBSERVATION_DATE;

---POSTOPERATIVE_CHECK_TIME  NUMBER(3)  Y    术后检查时间（min)    N  N..3
SELECT POSTOPERATIVE_CHECK_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPERATIVE_CHECK_TIME;

---BLOODPRESSUREH  NUMBER(3)  Y    术后收缩压(mmHg)    N  N2..3
SELECT BLOODPRESSUREH FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREH;

---BLOODPRESSUREL  NUMBER(3)  Y    术后舒张压(mmHg)    N  N2..3
SELECT BLOODPRESSUREL FROM CAESAREAN_SECTION_RECORD GROUP BY BLOODPRESSUREL;

---PULSE  NUMBER(3)  Y    术后脉搏（次/min）    N  N2..3
SELECT PULSE FROM CAESAREAN_SECTION_RECORD GROUP BY PULSE;

---CARDIOTACH  NUMBER(3)  Y    术后心率（次/min）    N  N2..3
SELECT CARDIOTACH FROM CAESAREAN_SECTION_RECORD GROUP BY CARDIOTACH;

---POSTOPER_BLOOD_LOSSED  NUMBER(5)  Y    术后出血量（mL)    N  N..5
SELECT POSTOPER_BLOOD_LOSSED FROM CAESAREAN_SECTION_RECORD GROUP BY POSTOPER_BLOOD_LOSSED;

---POSTPARTUM_UTERINE_CONTRACTION  VARCHAR2(200)  Y    术后宫缩    S1  AN..200
SELECT POSTPARTUM_UTERINE_CONTRACTION FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_CONTRACTION;

---POSTPARTUM_UTERINE_HEIGHT  NUMBER(4,1)  Y    术后宫底高度（cm）    N  N3..4.1
SELECT POSTPARTUM_UTERINE_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY POSTPARTUM_UTERINE_HEIGHT;

---NEWBORN_SEX  VARCHAR2(1)  Y    新生儿性别代码  应符合国标：GB/T 2261.1—2003  S3  N1
SELECT NEWBORN_SEX FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_SEX;

---BIRTH_WEIGHT  NUMBER(4)  Y    新生儿出生体重(g)    N  N2..4
SELECT BIRTH_WEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY BIRTH_WEIGHT;

---NEWBORN_HEIGHT  NUMBER(5,1)  Y    新生儿出生身长（cm）    _ N  N4..5,l
SELECT NEWBORN_HEIGHT FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_HEIGHT;

---TUMOR_SIZE  VARCHAR2(100)  Y    产瘤大小    S1  AN..100
SELECT TUMOR_SIZE FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_SIZE;

---TUMOR_LOCATION  VARCHAR2(100)  Y    产瘤部位    S1  AN.. 100
SELECT TUMOR_LOCATION FROM CAESAREAN_SECTION_RECORD GROUP BY TUMOR_LOCATION;

---APGAR_CODE  VARCHAR2(1)  Y    Apgar评分间隔时间代码  标准值：
1、1 min
2、5 min
3、10 min  S2  N1
SELECT APGAR_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_CODE;

---APGAR_SCORE  NUMBER(2)  Y    Apgar评分值    N  N..2
SELECT APGAR_SCORE FROM CAESAREAN_SECTION_RECORD GROUP BY APGAR_SCORE;

---DELIVERY_OUTCOME_CODE  VARCHAR2(1)  Y    分娩结局代码  标准值：1.活产2.死胎3.死产  S2  N1
SELECT DELIVERY_OUTCOME_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY DELIVERY_OUTCOME_CODE;

---NEWBORN_ABNORMAL_CODE  VARCHAR2(1)  Y    新生儿异常情况代码  应符合国家标准：CV05.10.020  S3  N1
SELECT NEWBORN_ABNORMAL_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY NEWBORN_ABNORMAL_CODE;

---PEDIATRICIAN_SIGN  VARCHAR2(50)  Y    儿科医生签名    S1  A..50
SELECT PEDIATRICIAN_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY PEDIATRICIAN_SIGN;

---RECORD_SIGN  VARCHAR2(50)  Y    记录人员签名    S1  A..50
SELECT RECORD_SIGN FROM CAESAREAN_SECTION_RECORD GROUP BY RECORD_SIGN;

---OPERATION_INDICATIONS  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATION_INDICATIONS FROM CAESAREAN_SECTION_RECORD GROUP BY OPERATION_INDICATIONS;

---SIGNATURE_OF_BABY_SITTER  VARCHAR2(50)  Y    护婴者签名      
SELECT SIGNATURE_OF_BABY_SITTER FROM CAESAREAN_SECTION_RECORD GROUP BY SIGNATURE_OF_BABY_SITTER;

---UMBILICAL_CORD_TWIST  VARCHAR2(10)  Y    脐带扭转（周）      
SELECT UMBILICAL_CORD_TWIST FROM CAESAREAN_SECTION_RECORD GROUP BY UMBILICAL_CORD_TWIST;

---EXPLORE_FIBROIDS_FLAG  VARCHAR2(5)  Y    宫腔探查肌瘤标志  TRUE/FALSE    
SELECT EXPLORE_FIBROIDS_FLAG FROM CAESAREAN_SECTION_RECORD GROUP BY EXPLORE_FIBROIDS_FLAG;

---FETAL_POSITION_CODE  VARCHAR2(2)  Y    胎方位代码  应符合国家标准：CV05.01.007    
SELECT FETAL_POSITION_CODE FROM CAESAREAN_SECTION_RECORD GROUP BY FETAL_POSITION_CODE;

---YELLOW_STAINING_OF_PLACENTA  VARCHAR2(200)  Y    胎盘黄染描述      
SELECT YELLOW_STAINING_OF_PLACENTA FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINING_OF_PLACENTA;

---YELLOW_STAINED_MEMBRANES  VARCHAR2(200)  Y    胎膜黄染描述      
SELECT YELLOW_STAINED_MEMBRANES FROM CAESAREAN_SECTION_RECORD GROUP BY YELLOW_STAINED_MEMBRANES;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间，抽数据用      
SELECT LAST_MODIFIC_TIME FROM CAESAREAN_SECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

