---OUTPATIENT_SN  VARCHAR2(18)      急诊流水号    null  
SELECT OUTPATIENT_SN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      急诊号    null  AN..18
SELECT OUTP_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTP_NO;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  AN..1000
SELECT ALLERGY_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---IN_OBSERVATION_DATETIME  DATE  Y    收人观察室日期时间    null  DTI 5
SELECT IN_OBSERVATION_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY IN_OBSERVATION_DATETIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    null  AN..100
SELECT CHIEF_COMPLAINT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史    null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    null  AN..1000
SELECT PAST_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查    null  AN..500
SELECT PHYSICAL_EXAMINATION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果    null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM EMERGENCY_MEDICAL_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检杳项目    null  AN.. 100
SELECT AUXILIARYEXAMI_ITEM FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据    null  AN..100
SELECT DIALECTICAL_ACCROD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN.. 100
SELECT THERAPEUTIC_PRINCIPLE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  AN..20
SELECT APPLY_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY APPLY_NO;

---EMERGENCY_OBSERVATION_COURSE  VARCHAR2(2000)  Y    急诊留观病程记录    null  AN..2000
SELECT EMERGENCY_OBSERVATION_COURSE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_OBSERVATION_COURSE;

---RESCUE_BEGIN_DATETIME  DATE  Y    抢救开始日期时间    null  DT15
SELECT RESCUE_BEGIN_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_BEGIN_DATETIME;

---RESCUE_END_DATETIME  DATE  Y    抢救结束日期时间    null  DT15
SELECT RESCUE_END_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_END_DATETIME;

---EMERGENCY_RESCUE_RECORD  VARCHAR2(2000)  Y    急诊抢救记录    null  AN..2000
SELECT EMERGENCY_RESCUE_RECORD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_RESCUE_RECORD;

---CREATE_DATETIME  DATE  Y    记录日期时间    null  DTI 5
SELECT CREATE_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CREATE_DATETIME;

---MATTERS_NEEDING_ATTENTION  VARCHAR2(1000)  Y    注意事项    null  AN..1000
SELECT MATTERS_NEEDING_ATTENTION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY MATTERS_NEEDING_ATTENTION;

---RESCUE_PERSONNEL_LIST  VARCHAR2(200)  Y    参加抢救人员名单    null  A..200
SELECT RESCUE_PERSONNEL_LIST FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_PERSONNEL_LIST;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  WS 364.15—2011 表 5  CV08.30.005专业技术职务类别代码表  null  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PROFESSIONAL_CATAGORY_CODE;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(2)  Y    患者去向代码    null  
SELECT PATIENT_WHEREABOUTS_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医生签名    null  
SELECT RESPONSIBLE_DOCTOR FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESPONSIBLE_DOCTOR;

---VISITING_DOCTOR_SIGN  VARCHAR2(50)  Y    就诊医生签名    null  
SELECT VISITING_DOCTOR_SIGN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY VISITING_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间-抽数据使用    null  
SELECT LAST_MODIFIC_TIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      急诊流水号    null  
SELECT OUTPATIENT_SN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      急诊号    null  AN..18
SELECT OUTP_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTP_NO;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  AN..1000
SELECT ALLERGY_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---IN_OBSERVATION_DATETIME  DATE  Y    收人观察室日期时间    null  DTI 5
SELECT IN_OBSERVATION_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY IN_OBSERVATION_DATETIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    null  AN..100
SELECT CHIEF_COMPLAINT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史    null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    null  AN..1000
SELECT PAST_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查    null  AN..500
SELECT PHYSICAL_EXAMINATION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果    null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM EMERGENCY_MEDICAL_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检杳项目    null  AN.. 100
SELECT AUXILIARYEXAMI_ITEM FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据    null  AN..100
SELECT DIALECTICAL_ACCROD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN.. 100
SELECT THERAPEUTIC_PRINCIPLE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  AN..20
SELECT APPLY_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY APPLY_NO;

---EMERGENCY_OBSERVATION_COURSE  VARCHAR2(2000)  Y    急诊留观病程记录    null  AN..2000
SELECT EMERGENCY_OBSERVATION_COURSE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_OBSERVATION_COURSE;

---RESCUE_BEGIN_DATETIME  DATE  Y    抢救开始日期时间    null  DT15
SELECT RESCUE_BEGIN_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_BEGIN_DATETIME;

---RESCUE_END_DATETIME  DATE  Y    抢救结束日期时间    null  DT15
SELECT RESCUE_END_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_END_DATETIME;

---EMERGENCY_RESCUE_RECORD  VARCHAR2(2000)  Y    急诊抢救记录    null  AN..2000
SELECT EMERGENCY_RESCUE_RECORD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_RESCUE_RECORD;

---CREATE_DATETIME  DATE  Y    记录日期时间    null  DTI 5
SELECT CREATE_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CREATE_DATETIME;

---MATTERS_NEEDING_ATTENTION  VARCHAR2(1000)  Y    注意事项    null  AN..1000
SELECT MATTERS_NEEDING_ATTENTION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY MATTERS_NEEDING_ATTENTION;

---RESCUE_PERSONNEL_LIST  VARCHAR2(200)  Y    参加抢救人员名单    null  A..200
SELECT RESCUE_PERSONNEL_LIST FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_PERSONNEL_LIST;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  WS 364.15—2011 表 5  CV08.30.005专业技术职务类别代码表  null  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PROFESSIONAL_CATAGORY_CODE;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(2)  Y    患者去向代码    null  
SELECT PATIENT_WHEREABOUTS_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医生签名    null  
SELECT RESPONSIBLE_DOCTOR FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESPONSIBLE_DOCTOR;

---VISITING_DOCTOR_SIGN  VARCHAR2(50)  Y    就诊医生签名    null  
SELECT VISITING_DOCTOR_SIGN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY VISITING_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间-抽数据使用    null  
SELECT LAST_MODIFIC_TIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      急诊流水号    null  
SELECT OUTPATIENT_SN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      急诊号    null  AN..18
SELECT OUTP_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY OUTP_NO;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  AN..1000
SELECT ALLERGY_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---IN_OBSERVATION_DATETIME  DATE  Y    收人观察室日期时间    null  DTI 5
SELECT IN_OBSERVATION_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY IN_OBSERVATION_DATETIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    null  AN..100
SELECT CHIEF_COMPLAINT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史    null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史    null  AN..1000
SELECT PAST_HISTORY FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查    null  AN..500
SELECT PHYSICAL_EXAMINATION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果    null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM EMERGENCY_MEDICAL_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检杳项目    null  AN.. 100
SELECT AUXILIARYEXAMI_ITEM FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM EMERGENCY_MEDICAL_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据    null  AN..100
SELECT DIALECTICAL_ACCROD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN.. 100
SELECT THERAPEUTIC_PRINCIPLE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  AN..20
SELECT APPLY_NO FROM EMERGENCY_MEDICAL_RECORDS GROUP BY APPLY_NO;

---EMERGENCY_OBSERVATION_COURSE  VARCHAR2(2000)  Y    急诊留观病程记录    null  AN..2000
SELECT EMERGENCY_OBSERVATION_COURSE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_OBSERVATION_COURSE;

---RESCUE_BEGIN_DATETIME  DATE  Y    抢救开始日期时间    null  DT15
SELECT RESCUE_BEGIN_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_BEGIN_DATETIME;

---RESCUE_END_DATETIME  DATE  Y    抢救结束日期时间    null  DT15
SELECT RESCUE_END_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_END_DATETIME;

---EMERGENCY_RESCUE_RECORD  VARCHAR2(2000)  Y    急诊抢救记录    null  AN..2000
SELECT EMERGENCY_RESCUE_RECORD FROM EMERGENCY_MEDICAL_RECORDS GROUP BY EMERGENCY_RESCUE_RECORD;

---CREATE_DATETIME  DATE  Y    记录日期时间    null  DTI 5
SELECT CREATE_DATETIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY CREATE_DATETIME;

---MATTERS_NEEDING_ATTENTION  VARCHAR2(1000)  Y    注意事项    null  AN..1000
SELECT MATTERS_NEEDING_ATTENTION FROM EMERGENCY_MEDICAL_RECORDS GROUP BY MATTERS_NEEDING_ATTENTION;

---RESCUE_PERSONNEL_LIST  VARCHAR2(200)  Y    参加抢救人员名单    null  A..200
SELECT RESCUE_PERSONNEL_LIST FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESCUE_PERSONNEL_LIST;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  WS 364.15—2011 表 5  CV08.30.005专业技术职务类别代码表  null  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PROFESSIONAL_CATAGORY_CODE;

---PATIENT_WHEREABOUTS_CODE  VARCHAR2(2)  Y    患者去向代码    null  
SELECT PATIENT_WHEREABOUTS_CODE FROM EMERGENCY_MEDICAL_RECORDS GROUP BY PATIENT_WHEREABOUTS_CODE;

---RESPONSIBLE_DOCTOR  VARCHAR2(50)  Y    责任医生签名    null  
SELECT RESPONSIBLE_DOCTOR FROM EMERGENCY_MEDICAL_RECORDS GROUP BY RESPONSIBLE_DOCTOR;

---VISITING_DOCTOR_SIGN  VARCHAR2(50)  Y    就诊医生签名    null  
SELECT VISITING_DOCTOR_SIGN FROM EMERGENCY_MEDICAL_RECORDS GROUP BY VISITING_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间-抽数据使用    null  
SELECT LAST_MODIFIC_TIME FROM EMERGENCY_MEDICAL_RECORDS GROUP BY LAST_MODIFIC_TIME;

