---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OBSERVATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OBSERVATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OBSERVATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSERVATION_NAME  VARCHAR2(100)  Y    护理观察项目名称    null  null
SELECT NURSING_OBSERVATION_NAME FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    null  null
SELECT NURSING_OBSERVATION_RESULT FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_RESULT;

---NURSING_OBSERVATION_DATE  DATE  Y    护理观察时间    null  null
SELECT NURSING_OBSERVATION_DATE FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_DATE;

---NURSING_TYPE_CODE  NUMBER(18)  Y    护理类型代码  应符合国家标准：CV06.00.221  null  null
SELECT NURSING_TYPE_CODE FROM NURSING_OBSERVATION GROUP BY NURSING_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OBSERVATION GROUP BY NURSE_SIGN;

---NURSING_OBSERVATION_ID  VARCHAR2(18)      护理观察ID    null  null
SELECT NURSING_OBSERVATION_ID FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OBSERVATION GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OBSERVATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OBSERVATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OBSERVATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSERVATION_NAME  VARCHAR2(100)  Y    护理观察项目名称    null  null
SELECT NURSING_OBSERVATION_NAME FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    null  null
SELECT NURSING_OBSERVATION_RESULT FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_RESULT;

---NURSING_OBSERVATION_DATE  DATE  Y    护理观察时间    null  null
SELECT NURSING_OBSERVATION_DATE FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_DATE;

---NURSING_TYPE_CODE  NUMBER(18)  Y    护理类型代码  应符合国家标准：CV06.00.221  null  null
SELECT NURSING_TYPE_CODE FROM NURSING_OBSERVATION GROUP BY NURSING_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OBSERVATION GROUP BY NURSE_SIGN;

---NURSING_OBSERVATION_ID  VARCHAR2(18)      护理观察ID    null  null
SELECT NURSING_OBSERVATION_ID FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OBSERVATION GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM NURSING_OBSERVATION GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM NURSING_OBSERVATION GROUP BY INPATIENT_SN;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识    null  null
SELECT GENERAL_NURSING_ID FROM NURSING_OBSERVATION GROUP BY GENERAL_NURSING_ID;

---NURSING_OBSERVATION_NAME  VARCHAR2(100)  Y    护理观察项目名称    null  null
SELECT NURSING_OBSERVATION_NAME FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_NAME;

---NURSING_OBSERVATION_RESULT  VARCHAR2(1000)  Y    护理观察结果    null  null
SELECT NURSING_OBSERVATION_RESULT FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_RESULT;

---NURSING_OBSERVATION_DATE  DATE  Y    护理观察时间    null  null
SELECT NURSING_OBSERVATION_DATE FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_DATE;

---NURSING_TYPE_CODE  NUMBER(18)  Y    护理类型代码  应符合国家标准：CV06.00.221  null  null
SELECT NURSING_TYPE_CODE FROM NURSING_OBSERVATION GROUP BY NURSING_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    null  null
SELECT NURSE_SIGN FROM NURSING_OBSERVATION GROUP BY NURSE_SIGN;

---NURSING_OBSERVATION_ID  VARCHAR2(18)      护理观察ID    null  null
SELECT NURSING_OBSERVATION_ID FROM NURSING_OBSERVATION GROUP BY NURSING_OBSERVATION_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM NURSING_OBSERVATION GROUP BY LAST_MODIFIC_TIME;

