---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_CARE_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_CARE_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_CARE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM OPERATION_CARE_RECORD GROUP BY PATIENT_ID;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_HISTORY_FLAG FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---SKIN_INSPECTION_DESCRIPTION  VARCHAR2(1000)  Y    皮肤检查描述    S1  AN..1000
SELECT SKIN_INSPECTION_DESCRIPTION FROM OPERATION_CARE_RECORD GROUP BY SKIN_INSPECTION_DESCRIPTION;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---PREPARE_ITEM  VARCHAR2(100)  Y    准备事项    S1  AN.. 100
SELECT PREPARE_ITEM FROM OPERATION_CARE_RECORD GROUP BY PREPARE_ITEM;

---INTRAOPERAT_PATHOLOGICAL_MARK  VARCHAR2(5)  Y    术中病理标志    L  T/F
SELECT INTRAOPERAT_PATHOLOGICAL_MARK FROM OPERATION_CARE_RECORD GROUP BY INTRAOPERAT_PATHOLOGICAL_MARK;

---OPERATION_ITEM  VARCHAR2(50)  Y    术中所用物品名称    S1  AN..50
SELECT OPERATION_ITEM FROM OPERATION_CARE_RECORD GROUP BY OPERATION_ITEM;

---PREOPERATION_CHECK_FLAG  VARCHAR2(5)  Y    术前清点标志    L  T/F
SELECT PREOPERATION_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY PREOPERATION_CHECK_FLAG;

---CLOSEBEFORE_CHECK_FLAG  VARCHAR2(5)  Y    关前核对标志    L  T/F
SELECT CLOSEBEFORE_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEBEFORE_CHECK_FLAG;

---CLOSEAFTER_CHECK_FLAG  VARCHAR2(5)  Y    关后核对标志    L  T/F
SELECT CLOSEAFTER_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEAFTER_CHECK_FLAG;

---PATIENT_TRANSFER_CHECKITEM  VARCHAR2(50)  Y    病人交接核对项目    S1  AN..50
SELECT PATIENT_TRANSFER_CHECKITEM FROM OPERATION_CARE_RECORD GROUP BY PATIENT_TRANSFER_CHECKITEM;

---CIRCULATING_NURSE_SING  VARCHAR2(50)  Y    巡台护士签名    S1  A..50
SELECT CIRCULATING_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY CIRCULATING_NURSE_SING;

---INSTRUMENT_NURSE_SING  VARCHAR2(50)  Y    器械护士签名    S1  A..50
SELECT INSTRUMENT_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY INSTRUMENT_NURSE_SING;

---HANDOVER_NURSE_SIGN  VARCHAR2(50)  Y    交接护士签名    S1  A..50
SELECT HANDOVER_NURSE_SIGN FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_NURSE_SIGN;

---TRANSPORTER_SIGN  VARCHAR2(50)  Y    转运者签名    S1  A..50
SELECT TRANSPORTER_SIGN FROM OPERATION_CARE_RECORD GROUP BY TRANSPORTER_SIGN;

---HANDOVER_DATETIME  DATE  Y    交接日期时间    DT  DT15
SELECT HANDOVER_DATETIME FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_DATETIME;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_CARE_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPERATION_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_CARE_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_CARE_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_CARE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM OPERATION_CARE_RECORD GROUP BY PATIENT_ID;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_HISTORY_FLAG FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---SKIN_INSPECTION_DESCRIPTION  VARCHAR2(1000)  Y    皮肤检查描述    S1  AN..1000
SELECT SKIN_INSPECTION_DESCRIPTION FROM OPERATION_CARE_RECORD GROUP BY SKIN_INSPECTION_DESCRIPTION;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---PREPARE_ITEM  VARCHAR2(100)  Y    准备事项    S1  AN.. 100
SELECT PREPARE_ITEM FROM OPERATION_CARE_RECORD GROUP BY PREPARE_ITEM;

---INTRAOPERAT_PATHOLOGICAL_MARK  VARCHAR2(5)  Y    术中病理标志    L  T/F
SELECT INTRAOPERAT_PATHOLOGICAL_MARK FROM OPERATION_CARE_RECORD GROUP BY INTRAOPERAT_PATHOLOGICAL_MARK;

---OPERATION_ITEM  VARCHAR2(50)  Y    术中所用物品名称    S1  AN..50
SELECT OPERATION_ITEM FROM OPERATION_CARE_RECORD GROUP BY OPERATION_ITEM;

---PREOPERATION_CHECK_FLAG  VARCHAR2(5)  Y    术前清点标志    L  T/F
SELECT PREOPERATION_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY PREOPERATION_CHECK_FLAG;

---CLOSEBEFORE_CHECK_FLAG  VARCHAR2(5)  Y    关前核对标志    L  T/F
SELECT CLOSEBEFORE_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEBEFORE_CHECK_FLAG;

---CLOSEAFTER_CHECK_FLAG  VARCHAR2(5)  Y    关后核对标志    L  T/F
SELECT CLOSEAFTER_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEAFTER_CHECK_FLAG;

---PATIENT_TRANSFER_CHECKITEM  VARCHAR2(50)  Y    病人交接核对项目    S1  AN..50
SELECT PATIENT_TRANSFER_CHECKITEM FROM OPERATION_CARE_RECORD GROUP BY PATIENT_TRANSFER_CHECKITEM;

---CIRCULATING_NURSE_SING  VARCHAR2(50)  Y    巡台护士签名    S1  A..50
SELECT CIRCULATING_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY CIRCULATING_NURSE_SING;

---INSTRUMENT_NURSE_SING  VARCHAR2(50)  Y    器械护士签名    S1  A..50
SELECT INSTRUMENT_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY INSTRUMENT_NURSE_SING;

---HANDOVER_NURSE_SIGN  VARCHAR2(50)  Y    交接护士签名    S1  A..50
SELECT HANDOVER_NURSE_SIGN FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_NURSE_SIGN;

---TRANSPORTER_SIGN  VARCHAR2(50)  Y    转运者签名    S1  A..50
SELECT TRANSPORTER_SIGN FROM OPERATION_CARE_RECORD GROUP BY TRANSPORTER_SIGN;

---HANDOVER_DATETIME  DATE  Y    交接日期时间    DT  DT15
SELECT HANDOVER_DATETIME FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_DATETIME;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_CARE_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPERATION_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OPERATION_CARE_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OPERATION_CARE_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OPERATION_CARE_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OPERATION_CARE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM OPERATION_CARE_RECORD GROUP BY PATIENT_ID;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_HISTORY_FLAG FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM OPERATION_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---SKIN_INSPECTION_DESCRIPTION  VARCHAR2(1000)  Y    皮肤检查描述    S1  AN..1000
SELECT SKIN_INSPECTION_DESCRIPTION FROM OPERATION_CARE_RECORD GROUP BY SKIN_INSPECTION_DESCRIPTION;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM OPERATION_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---PREPARE_ITEM  VARCHAR2(100)  Y    准备事项    S1  AN.. 100
SELECT PREPARE_ITEM FROM OPERATION_CARE_RECORD GROUP BY PREPARE_ITEM;

---INTRAOPERAT_PATHOLOGICAL_MARK  VARCHAR2(5)  Y    术中病理标志    L  T/F
SELECT INTRAOPERAT_PATHOLOGICAL_MARK FROM OPERATION_CARE_RECORD GROUP BY INTRAOPERAT_PATHOLOGICAL_MARK;

---OPERATION_ITEM  VARCHAR2(50)  Y    术中所用物品名称    S1  AN..50
SELECT OPERATION_ITEM FROM OPERATION_CARE_RECORD GROUP BY OPERATION_ITEM;

---PREOPERATION_CHECK_FLAG  VARCHAR2(5)  Y    术前清点标志    L  T/F
SELECT PREOPERATION_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY PREOPERATION_CHECK_FLAG;

---CLOSEBEFORE_CHECK_FLAG  VARCHAR2(5)  Y    关前核对标志    L  T/F
SELECT CLOSEBEFORE_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEBEFORE_CHECK_FLAG;

---CLOSEAFTER_CHECK_FLAG  VARCHAR2(5)  Y    关后核对标志    L  T/F
SELECT CLOSEAFTER_CHECK_FLAG FROM OPERATION_CARE_RECORD GROUP BY CLOSEAFTER_CHECK_FLAG;

---PATIENT_TRANSFER_CHECKITEM  VARCHAR2(50)  Y    病人交接核对项目    S1  AN..50
SELECT PATIENT_TRANSFER_CHECKITEM FROM OPERATION_CARE_RECORD GROUP BY PATIENT_TRANSFER_CHECKITEM;

---CIRCULATING_NURSE_SING  VARCHAR2(50)  Y    巡台护士签名    S1  A..50
SELECT CIRCULATING_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY CIRCULATING_NURSE_SING;

---INSTRUMENT_NURSE_SING  VARCHAR2(50)  Y    器械护士签名    S1  A..50
SELECT INSTRUMENT_NURSE_SING FROM OPERATION_CARE_RECORD GROUP BY INSTRUMENT_NURSE_SING;

---HANDOVER_NURSE_SIGN  VARCHAR2(50)  Y    交接护士签名    S1  A..50
SELECT HANDOVER_NURSE_SIGN FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_NURSE_SIGN;

---TRANSPORTER_SIGN  VARCHAR2(50)  Y    转运者签名    S1  A..50
SELECT TRANSPORTER_SIGN FROM OPERATION_CARE_RECORD GROUP BY TRANSPORTER_SIGN;

---HANDOVER_DATETIME  DATE  Y    交接日期时间    DT  DT15
SELECT HANDOVER_DATETIME FROM OPERATION_CARE_RECORD GROUP BY HANDOVER_DATETIME;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OPERATION_CARE_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM OPERATION_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM OPERATION_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

