---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INSPECTION_RECORD GROUP BY DOC_NO;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM INSPECTION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM INSPECTION_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM INSPECTION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INSPECTION_RECORD GROUP BY INP_NO;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM INSPECTION_RECORD GROUP BY OPER_REQ_SN;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INSPECTION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM INSPECTION_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检查申请机构名称    S1  AN.. 70
SELECT EXAMINATION_APPLY_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检查申请科室    S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM INSPECTION_RECORD GROUP BY CHIEF_COMPLAINT;

---START_SYMPTOMS_DATE  DATE  Y    症状开始日期时间    DT  DTI 5
SELECT START_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY START_SYMPTOMS_DATE;

---STOP_SYMPTOMS_DATE  DATE  Y    症状停止日期时间    DT  DTI 5
SELECT STOP_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY STOP_SYMPTOMS_DATE;

---SYMPTOM_DESC  VARCHAR2(1000)  Y    症状描述    S1  AN..1000
SELECT SYMPTOM_DESC FROM INSPECTION_RECORD GROUP BY SYMPTOM_DESC;

---SPECIAL_EXAMINATION_FLAG  VARCHAR2(5)  Y    特殊检查标志  TRUE/FALSE  L  T/F
SELECT SPECIAL_EXAMINATION_FLAG FROM INSPECTION_RECORD GROUP BY SPECIAL_EXAMINATION_FLAG;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检查标本号    S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM INSPECTION_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM INSPECTION_RECORD GROUP BY DIAG_DESC;

---EXAMINATION_ITEM_CODE  VARCHAR2(20)  Y    检查项目代码    S1  AN..20
SELECT EXAMINATION_ITEM_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_ITEM_CODE;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检查方法名称    S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM INSPECTION_RECORD GROUP BY INSPECTION_METHOD_NAME;

---EXAMINATION_TYPE  VARCHAR2(100)  Y    检查类别    S1  AN..100
SELECT EXAMINATION_TYPE FROM INSPECTION_RECORD GROUP BY EXAMINATION_TYPE;

---EXAMINATION_RESULT_CODE  VARCHAR2(1)  Y    检查结果代码  1.正常2.异常3.不确定  S2  N1
SELECT EXAMINATION_RESULT_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM INSPECTION_RECORD GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUTIFY_UNIT  VARCHAR2(20)  Y    检查定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUTIFY_UNIT FROM INSPECTION_RECORD GROUP BY EXAMINATION_QUTIFY_UNIT;

---INSPECT_ENGINEER_NAME  VARCHAR2(50)  Y    检查技师签名    S1  A..50
SELECT INSPECT_ENGINEER_NAME FROM INSPECTION_RECORD GROUP BY INSPECT_ENGINEER_NAME;

---EXAMINATION_DOCTOR  VARCHAR2(50)  Y    检查医师签名    S1  A.. 50
SELECT EXAMINATION_DOCTOR FROM INSPECTION_RECORD GROUP BY EXAMINATION_DOCTOR;

---EXAMINATION_DATE  DATE  Y    检查日期    D  D8
SELECT EXAMINATION_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_DATE;

---EXAMINATION_REPORT_NO  VARCHAR2(20)  Y    检查报告单编号    S1  AN..20
SELECT EXAMINATION_REPORT_NO FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_NO;

---EXAMINATION_REPORT_ORGAN  VARCHAR2(70)  Y    检查报告机构名称    S1  AN..70
SELECT EXAMINATION_REPORT_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ORGAN;

---EXAMINATION_REPORT_ROOM  VARCHAR2(50)  Y    检查报告科室    S1  AN..50
SELECT EXAMINATION_REPORT_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ROOM;

---OBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-客观所见    S1  AN..200
SELECT OBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY OBJECTIVE_EXAMINATION_RESULT;

---SUBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-主观提示    S1  AN..200
SELECT SUBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY SUBJECTIVE_EXAMINATION_RESULT;

---EXAMINATION_RT_REMARKS  VARCHAR2(100)  Y    检查报告备注    S1  AN..100
SELECT EXAMINATION_RT_REMARKS FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_REMARKS;

---EXAMINATION_RT_DATE  DATE  Y    检查报告日期    D  D8
SELECT EXAMINATION_RT_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名    S1  A..50
SELECT REPORT_DOCTOR FROM INSPECTION_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名    S1  A..50
SELECT REPORTAUDIT FROM INSPECTION_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INSPECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INSPECTION_RECORD GROUP BY DOC_NO;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM INSPECTION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM INSPECTION_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM INSPECTION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INSPECTION_RECORD GROUP BY INP_NO;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM INSPECTION_RECORD GROUP BY OPER_REQ_SN;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INSPECTION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM INSPECTION_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检查申请机构名称    S1  AN.. 70
SELECT EXAMINATION_APPLY_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检查申请科室    S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM INSPECTION_RECORD GROUP BY CHIEF_COMPLAINT;

---START_SYMPTOMS_DATE  DATE  Y    症状开始日期时间    DT  DTI 5
SELECT START_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY START_SYMPTOMS_DATE;

---STOP_SYMPTOMS_DATE  DATE  Y    症状停止日期时间    DT  DTI 5
SELECT STOP_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY STOP_SYMPTOMS_DATE;

---SYMPTOM_DESC  VARCHAR2(1000)  Y    症状描述    S1  AN..1000
SELECT SYMPTOM_DESC FROM INSPECTION_RECORD GROUP BY SYMPTOM_DESC;

---SPECIAL_EXAMINATION_FLAG  VARCHAR2(5)  Y    特殊检查标志  TRUE/FALSE  L  T/F
SELECT SPECIAL_EXAMINATION_FLAG FROM INSPECTION_RECORD GROUP BY SPECIAL_EXAMINATION_FLAG;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检查标本号    S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM INSPECTION_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM INSPECTION_RECORD GROUP BY DIAG_DESC;

---EXAMINATION_ITEM_CODE  VARCHAR2(20)  Y    检查项目代码    S1  AN..20
SELECT EXAMINATION_ITEM_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_ITEM_CODE;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检查方法名称    S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM INSPECTION_RECORD GROUP BY INSPECTION_METHOD_NAME;

---EXAMINATION_TYPE  VARCHAR2(100)  Y    检查类别    S1  AN..100
SELECT EXAMINATION_TYPE FROM INSPECTION_RECORD GROUP BY EXAMINATION_TYPE;

---EXAMINATION_RESULT_CODE  VARCHAR2(1)  Y    检查结果代码  1.正常2.异常3.不确定  S2  N1
SELECT EXAMINATION_RESULT_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM INSPECTION_RECORD GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUTIFY_UNIT  VARCHAR2(20)  Y    检查定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUTIFY_UNIT FROM INSPECTION_RECORD GROUP BY EXAMINATION_QUTIFY_UNIT;

---INSPECT_ENGINEER_NAME  VARCHAR2(50)  Y    检查技师签名    S1  A..50
SELECT INSPECT_ENGINEER_NAME FROM INSPECTION_RECORD GROUP BY INSPECT_ENGINEER_NAME;

---EXAMINATION_DOCTOR  VARCHAR2(50)  Y    检查医师签名    S1  A.. 50
SELECT EXAMINATION_DOCTOR FROM INSPECTION_RECORD GROUP BY EXAMINATION_DOCTOR;

---EXAMINATION_DATE  DATE  Y    检查日期    D  D8
SELECT EXAMINATION_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_DATE;

---EXAMINATION_REPORT_NO  VARCHAR2(20)  Y    检查报告单编号    S1  AN..20
SELECT EXAMINATION_REPORT_NO FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_NO;

---EXAMINATION_REPORT_ORGAN  VARCHAR2(70)  Y    检查报告机构名称    S1  AN..70
SELECT EXAMINATION_REPORT_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ORGAN;

---EXAMINATION_REPORT_ROOM  VARCHAR2(50)  Y    检查报告科室    S1  AN..50
SELECT EXAMINATION_REPORT_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ROOM;

---OBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-客观所见    S1  AN..200
SELECT OBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY OBJECTIVE_EXAMINATION_RESULT;

---SUBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-主观提示    S1  AN..200
SELECT SUBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY SUBJECTIVE_EXAMINATION_RESULT;

---EXAMINATION_RT_REMARKS  VARCHAR2(100)  Y    检查报告备注    S1  AN..100
SELECT EXAMINATION_RT_REMARKS FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_REMARKS;

---EXAMINATION_RT_DATE  DATE  Y    检查报告日期    D  D8
SELECT EXAMINATION_RT_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名    S1  A..50
SELECT REPORT_DOCTOR FROM INSPECTION_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名    S1  A..50
SELECT REPORTAUDIT FROM INSPECTION_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INSPECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INSPECTION_RECORD GROUP BY DOC_NO;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM INSPECTION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM INSPECTION_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM INSPECTION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INSPECTION_RECORD GROUP BY INP_NO;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM INSPECTION_RECORD GROUP BY OPER_REQ_SN;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM INSPECTION_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT APPLY_NO FROM INSPECTION_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检查申请机构名称    S1  AN.. 70
SELECT EXAMINATION_APPLY_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检查申请科室    S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM INSPECTION_RECORD GROUP BY CHIEF_COMPLAINT;

---START_SYMPTOMS_DATE  DATE  Y    症状开始日期时间    DT  DTI 5
SELECT START_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY START_SYMPTOMS_DATE;

---STOP_SYMPTOMS_DATE  DATE  Y    症状停止日期时间    DT  DTI 5
SELECT STOP_SYMPTOMS_DATE FROM INSPECTION_RECORD GROUP BY STOP_SYMPTOMS_DATE;

---SYMPTOM_DESC  VARCHAR2(1000)  Y    症状描述    S1  AN..1000
SELECT SYMPTOM_DESC FROM INSPECTION_RECORD GROUP BY SYMPTOM_DESC;

---SPECIAL_EXAMINATION_FLAG  VARCHAR2(5)  Y    特殊检查标志  TRUE/FALSE  L  T/F
SELECT SPECIAL_EXAMINATION_FLAG FROM INSPECTION_RECORD GROUP BY SPECIAL_EXAMINATION_FLAG;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检查标本号    S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM INSPECTION_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM INSPECTION_RECORD GROUP BY DIAG_DESC;

---EXAMINATION_ITEM_CODE  VARCHAR2(20)  Y    检查项目代码    S1  AN..20
SELECT EXAMINATION_ITEM_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_ITEM_CODE;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检查方法名称    S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM INSPECTION_RECORD GROUP BY INSPECTION_METHOD_NAME;

---EXAMINATION_TYPE  VARCHAR2(100)  Y    检查类别    S1  AN..100
SELECT EXAMINATION_TYPE FROM INSPECTION_RECORD GROUP BY EXAMINATION_TYPE;

---EXAMINATION_RESULT_CODE  VARCHAR2(1)  Y    检查结果代码  1.正常2.异常3.不确定  S2  N1
SELECT EXAMINATION_RESULT_CODE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RESULT_CODE;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM INSPECTION_RECORD GROUP BY INSPECTION_QUANTIFY_RESULT;

---EXAMINATION_QUTIFY_UNIT  VARCHAR2(20)  Y    检查定量结果计量单位    S1  A..20
SELECT EXAMINATION_QUTIFY_UNIT FROM INSPECTION_RECORD GROUP BY EXAMINATION_QUTIFY_UNIT;

---INSPECT_ENGINEER_NAME  VARCHAR2(50)  Y    检查技师签名    S1  A..50
SELECT INSPECT_ENGINEER_NAME FROM INSPECTION_RECORD GROUP BY INSPECT_ENGINEER_NAME;

---EXAMINATION_DOCTOR  VARCHAR2(50)  Y    检查医师签名    S1  A.. 50
SELECT EXAMINATION_DOCTOR FROM INSPECTION_RECORD GROUP BY EXAMINATION_DOCTOR;

---EXAMINATION_DATE  DATE  Y    检查日期    D  D8
SELECT EXAMINATION_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_DATE;

---EXAMINATION_REPORT_NO  VARCHAR2(20)  Y    检查报告单编号    S1  AN..20
SELECT EXAMINATION_REPORT_NO FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_NO;

---EXAMINATION_REPORT_ORGAN  VARCHAR2(70)  Y    检查报告机构名称    S1  AN..70
SELECT EXAMINATION_REPORT_ORGAN FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ORGAN;

---EXAMINATION_REPORT_ROOM  VARCHAR2(50)  Y    检查报告科室    S1  AN..50
SELECT EXAMINATION_REPORT_ROOM FROM INSPECTION_RECORD GROUP BY EXAMINATION_REPORT_ROOM;

---OBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-客观所见    S1  AN..200
SELECT OBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY OBJECTIVE_EXAMINATION_RESULT;

---SUBJECTIVE_EXAMINATION_RESULT  VARCHAR2(200)  Y    检查报告结果-主观提示    S1  AN..200
SELECT SUBJECTIVE_EXAMINATION_RESULT FROM INSPECTION_RECORD GROUP BY SUBJECTIVE_EXAMINATION_RESULT;

---EXAMINATION_RT_REMARKS  VARCHAR2(100)  Y    检查报告备注    S1  AN..100
SELECT EXAMINATION_RT_REMARKS FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_REMARKS;

---EXAMINATION_RT_DATE  DATE  Y    检查报告日期    D  D8
SELECT EXAMINATION_RT_DATE FROM INSPECTION_RECORD GROUP BY EXAMINATION_RT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名    S1  A..50
SELECT REPORT_DOCTOR FROM INSPECTION_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名    S1  A..50
SELECT REPORTAUDIT FROM INSPECTION_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INSPECTION_RECORD GROUP BY LAST_MODIFIC_TIME;

