---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OUTPATIENT_RECORDS_ORDER GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM OUTPATIENT_RECORDS_ORDER GROUP BY PRESC_ID;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDEPT_NAME;

---ADVICE_OPENDOCTOR_SIGN  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDOCTOR_SIGN;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPEN_DATETIME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核者签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_ADVICE_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_DEPT_NAME;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A” 50
SELECT EXEC_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DTI 5
SELECT ADVICE_EXEC_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_DATETIME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_STATUS;

---CANCEL_PERSON_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_PERSON_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DTI 5
SELECT CANCEL_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_ADVICE_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_REMARK;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  CV06.00.229  S3  N2
SELECT ORDER_ITEM_TYPE_CODE FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_ITEM_CONTENT;

---ORDER_BEGIN_TIME  DATE  Y    医嘱计划开始时间      
SELECT ORDER_BEGIN_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_BEGIN_TIME;

---ORDER_END_TIME  DATE  Y    医嘱计划结束时间      
SELECT ORDER_END_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_END_TIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OUTPATIENT_RECORDS_ORDER GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM OUTPATIENT_RECORDS_ORDER GROUP BY PRESC_ID;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDEPT_NAME;

---ADVICE_OPENDOCTOR_SIGN  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDOCTOR_SIGN;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPEN_DATETIME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核者签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_ADVICE_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_DEPT_NAME;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A” 50
SELECT EXEC_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DTI 5
SELECT ADVICE_EXEC_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_DATETIME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_STATUS;

---CANCEL_PERSON_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_PERSON_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DTI 5
SELECT CANCEL_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_ADVICE_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_REMARK;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  CV06.00.229  S3  N2
SELECT ORDER_ITEM_TYPE_CODE FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_ITEM_CONTENT;

---ORDER_BEGIN_TIME  DATE  Y    医嘱计划开始时间      
SELECT ORDER_BEGIN_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_BEGIN_TIME;

---ORDER_END_TIME  DATE  Y    医嘱计划结束时间      
SELECT ORDER_END_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_END_TIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OUTPATIENT_RECORDS_ORDER GROUP BY OUTPATIENT_SN;

---PRESC_ID  VARCHAR2(50)      医嘱ID      
SELECT PRESC_ID FROM OUTPATIENT_RECORDS_ORDER GROUP BY PRESC_ID;

---ADVICE_OPENDEPT_NAME  VARCHAR2(50)  Y    医嘱开立科室    S1  AN..50
SELECT ADVICE_OPENDEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDEPT_NAME;

---ADVICE_OPENDOCTOR_SIGN  VARCHAR2(50)  Y    医嘱开立者签名    S1  A..50
SELECT ADVICE_OPENDOCTOR_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPENDOCTOR_SIGN;

---ADVICE_OPEN_DATETIME  DATE  Y    医嘱开立日期时间    DT  DT15
SELECT ADVICE_OPEN_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_OPEN_DATETIME;

---CHECK_PERSON_SIGN  VARCHAR2(50)  Y    医嘱审核者签名    S1  A..50
SELECT CHECK_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_PERSON_SIGN;

---CHECK_ADVICE_DATETIME  DATE  Y    医嘱审核日期时间    DT  DT15
SELECT CHECK_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CHECK_ADVICE_DATETIME;

---EXEC_DEPT_NAME  VARCHAR2(50)  Y    医嘱执行科室    S1  AN..50
SELECT EXEC_DEPT_NAME FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_DEPT_NAME;

---EXEC_PERSON_SIGN  VARCHAR2(50)  Y    医嘱执行者签名    S1  A” 50
SELECT EXEC_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY EXEC_PERSON_SIGN;

---ADVICE_EXEC_DATETIME  DATE  Y    医嘱执行日期时间    DT  DTI 5
SELECT ADVICE_EXEC_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_DATETIME;

---ADVICE_EXEC_STATUS  VARCHAR2(50)  Y    医嘱执行状态    S1  A..50
SELECT ADVICE_EXEC_STATUS FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_EXEC_STATUS;

---CANCEL_PERSON_SIGN  VARCHAR2(50)  Y    取消医嘱者签名    S1  A..50
SELECT CANCEL_PERSON_SIGN FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_PERSON_SIGN;

---CANCEL_ADVICE_DATETIME  DATE  Y    医嘱取消日期时间    DT  DTI 5
SELECT CANCEL_ADVICE_DATETIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY CANCEL_ADVICE_DATETIME;

---ADVICE_REMARK  VARCHAR2(100)  Y    医嘱备注信息    S1  AN..100
SELECT ADVICE_REMARK FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_REMARK;

---ORDER_ITEM_TYPE_CODE  VARCHAR2(2)  Y    医嘱项目类型代码  CV06.00.229  S3  N2
SELECT ORDER_ITEM_TYPE_CODE FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_ITEM_TYPE_CODE;

---ADVICE_ITEM_CONTENT  VARCHAR2(100)  Y    医嘱项目内容    S1  AN..100
SELECT ADVICE_ITEM_CONTENT FROM OUTPATIENT_RECORDS_ORDER GROUP BY ADVICE_ITEM_CONTENT;

---ORDER_BEGIN_TIME  DATE  Y    医嘱计划开始时间      
SELECT ORDER_BEGIN_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_BEGIN_TIME;

---ORDER_END_TIME  DATE  Y    医嘱计划结束时间      
SELECT ORDER_END_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY ORDER_END_TIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_RECORDS_ORDER GROUP BY LAST_MODIFIC_TIME;

