---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM GENERAL_CARER_ECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM GENERAL_CARER_ECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM GENERAL_CARER_ECORDS GROUP BY INP_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(2)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM GENERAL_CARER_ECORDS GROUP BY ALLERGY_HISTORY;

---DPAP_FLAG  VARCHAR2(5)  Y    足背动脉搏动标志  TRUE/FALSE  L  T/F
SELECT DPAP_FLAG FROM GENERAL_CARER_ECORDS GROUP BY DPAP_FLAG;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好2.—般3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIETARY_STATUS_CODE;

---CATHETER_CARE_CODE  VARCHAR2(1000)  Y    导管护理描述  —  S1  AN..1000
SELECT CATHETER_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY CATHETER_CARE_CODE;

---ENDOTRACHEAL_CARE_CODE  NUMBER(1)  Y    气管护理代码  标准值：1.翻身拍背2.雾化吸人3.吸痰  S2  N1
SELECT ENDOTRACHEAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ENDOTRACHEAL_CARE_CODE;

---BODY_POSITION_CARE  VARCHAR2(30)  Y    体位护理  —  S1  AN..30
SELECT BODY_POSITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY BODY_POSITION_CARE;

---SKIN_CARE  VARCHAR2(50)  Y    皮肤护理  —  S1  AN..50
SELECT SKIN_CARE FROM GENERAL_CARER_ECORDS GROUP BY SKIN_CARE;

---NUTRITION_CARE  VARCHAR2(100)  Y    营养护理  —  S1  AN..100
SELECT NUTRITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY NUTRITION_CARE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIET_GUIDE_CODE;

---PSYCHOLOGICAL_CARE_CODE  NUMBER(1)  Y    心理护理代码  标准值：1.根据病人心理状况施行心理护理2.家属心理支持  S2  N1
SELECT PSYCHOLOGICAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY PSYCHOLOGICAL_CARE_CODE;

---SAFETY_NURSING_CODE  NUMBER(1)  Y    安全护理代码  标准值：1.勤巡视病房2.加床档3.约束四肢  S2  N1
SELECT SAFETY_NURSING_CODE FROM GENERAL_CARER_ECORDS GROUP BY SAFETY_NURSING_CODE;

---PATIENT_CONDITION  VARCHAR2(2000)  Y    简要病情  —  S1  AN..2000
SELECT PATIENT_CONDITION FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_CONDITION;

---ISSUE_SSC_FLAG  VARCHAR2(5)  Y    发出手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_SSC_FLAG;

---WITHDRAW_SSC_FLAG  VARCHAR2(5)  Y    收回手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_SSC_FLAG;

---ISSUE_ORA_FLAG  VARCHAR2(5)  Y    发出手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_ORA_FLAG;

---WITHDRAW_ORA_FLAG  VARCHAR2(5)  Y    收回手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_ORA_FLAG;

---ISOLATION_INDICATOR  VARCHAR2(5)  Y    隔离标志  TRUE/FALSE  L  T/F
SELECT ISOLATION_INDICATOR FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_INDICATOR;

---ISOLATION_TYPE_CODE  NUMBER(1)  Y    隔离种类代码  应符合国标：CV06.00.222  S3  N1
SELECT ISOLATION_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名  —  S1  A..50
SELECT NURSE_SIGN FROM GENERAL_CARER_ECORDS GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DTI 5
SELECT SIGN_DATETIME FROM GENERAL_CARER_ECORDS GROUP BY SIGN_DATETIME;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）  —  N  N4,l
SELECT TEMPERATURE FROM GENERAL_CARER_ECORDS GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)  —  N  N..3
SELECT BREATH_FREQUENCY FROM GENERAL_CARER_ECORDS GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)  —  N  N2..3
SELECT SPHYGMUS FROM GENERAL_CARER_ECORDS GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)  —  N  N2..3
SELECT SYSTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)  —  N  N2..3
SELECT DIASTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY DIASTOLIC_PRESSURE;

---OXYGEN_SATURATION  NUMBER(4,1)  Y    血氧饱和度（％)  —  N  N3..4,l
SELECT OXYGEN_SATURATION FROM GENERAL_CARER_ECORDS GROUP BY OXYGEN_SATURATION;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM GENERAL_CARER_ECORDS GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM GENERAL_CARER_ECORDS GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM GENERAL_CARER_ECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM GENERAL_CARER_ECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM GENERAL_CARER_ECORDS GROUP BY INP_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(2)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM GENERAL_CARER_ECORDS GROUP BY ALLERGY_HISTORY;

---DPAP_FLAG  VARCHAR2(5)  Y    足背动脉搏动标志  TRUE/FALSE  L  T/F
SELECT DPAP_FLAG FROM GENERAL_CARER_ECORDS GROUP BY DPAP_FLAG;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好2.—般3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIETARY_STATUS_CODE;

---CATHETER_CARE_CODE  VARCHAR2(1000)  Y    导管护理描述  —  S1  AN..1000
SELECT CATHETER_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY CATHETER_CARE_CODE;

---ENDOTRACHEAL_CARE_CODE  NUMBER(1)  Y    气管护理代码  标准值：1.翻身拍背2.雾化吸人3.吸痰  S2  N1
SELECT ENDOTRACHEAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ENDOTRACHEAL_CARE_CODE;

---BODY_POSITION_CARE  VARCHAR2(30)  Y    体位护理  —  S1  AN..30
SELECT BODY_POSITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY BODY_POSITION_CARE;

---SKIN_CARE  VARCHAR2(50)  Y    皮肤护理  —  S1  AN..50
SELECT SKIN_CARE FROM GENERAL_CARER_ECORDS GROUP BY SKIN_CARE;

---NUTRITION_CARE  VARCHAR2(100)  Y    营养护理  —  S1  AN..100
SELECT NUTRITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY NUTRITION_CARE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIET_GUIDE_CODE;

---PSYCHOLOGICAL_CARE_CODE  NUMBER(1)  Y    心理护理代码  标准值：1.根据病人心理状况施行心理护理2.家属心理支持  S2  N1
SELECT PSYCHOLOGICAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY PSYCHOLOGICAL_CARE_CODE;

---SAFETY_NURSING_CODE  NUMBER(1)  Y    安全护理代码  标准值：1.勤巡视病房2.加床档3.约束四肢  S2  N1
SELECT SAFETY_NURSING_CODE FROM GENERAL_CARER_ECORDS GROUP BY SAFETY_NURSING_CODE;

---PATIENT_CONDITION  VARCHAR2(2000)  Y    简要病情  —  S1  AN..2000
SELECT PATIENT_CONDITION FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_CONDITION;

---ISSUE_SSC_FLAG  VARCHAR2(5)  Y    发出手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_SSC_FLAG;

---WITHDRAW_SSC_FLAG  VARCHAR2(5)  Y    收回手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_SSC_FLAG;

---ISSUE_ORA_FLAG  VARCHAR2(5)  Y    发出手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_ORA_FLAG;

---WITHDRAW_ORA_FLAG  VARCHAR2(5)  Y    收回手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_ORA_FLAG;

---ISOLATION_INDICATOR  VARCHAR2(5)  Y    隔离标志  TRUE/FALSE  L  T/F
SELECT ISOLATION_INDICATOR FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_INDICATOR;

---ISOLATION_TYPE_CODE  NUMBER(1)  Y    隔离种类代码  应符合国标：CV06.00.222  S3  N1
SELECT ISOLATION_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名  —  S1  A..50
SELECT NURSE_SIGN FROM GENERAL_CARER_ECORDS GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DTI 5
SELECT SIGN_DATETIME FROM GENERAL_CARER_ECORDS GROUP BY SIGN_DATETIME;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）  —  N  N4,l
SELECT TEMPERATURE FROM GENERAL_CARER_ECORDS GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)  —  N  N..3
SELECT BREATH_FREQUENCY FROM GENERAL_CARER_ECORDS GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)  —  N  N2..3
SELECT SPHYGMUS FROM GENERAL_CARER_ECORDS GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)  —  N  N2..3
SELECT SYSTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)  —  N  N2..3
SELECT DIASTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY DIASTOLIC_PRESSURE;

---OXYGEN_SATURATION  NUMBER(4,1)  Y    血氧饱和度（％)  —  N  N3..4,l
SELECT OXYGEN_SATURATION FROM GENERAL_CARER_ECORDS GROUP BY OXYGEN_SATURATION;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM GENERAL_CARER_ECORDS GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM GENERAL_CARER_ECORDS GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM GENERAL_CARER_ECORDS GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM GENERAL_CARER_ECORDS GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM GENERAL_CARER_ECORDS GROUP BY INP_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(2)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  —  S1  AN..1000
SELECT ALLERGY_HISTORY FROM GENERAL_CARER_ECORDS GROUP BY ALLERGY_HISTORY;

---DPAP_FLAG  VARCHAR2(5)  Y    足背动脉搏动标志  TRUE/FALSE  L  T/F
SELECT DPAP_FLAG FROM GENERAL_CARER_ECORDS GROUP BY DPAP_FLAG;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好2.—般3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIETARY_STATUS_CODE;

---CATHETER_CARE_CODE  VARCHAR2(1000)  Y    导管护理描述  —  S1  AN..1000
SELECT CATHETER_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY CATHETER_CARE_CODE;

---ENDOTRACHEAL_CARE_CODE  NUMBER(1)  Y    气管护理代码  标准值：1.翻身拍背2.雾化吸人3.吸痰  S2  N1
SELECT ENDOTRACHEAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ENDOTRACHEAL_CARE_CODE;

---BODY_POSITION_CARE  VARCHAR2(30)  Y    体位护理  —  S1  AN..30
SELECT BODY_POSITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY BODY_POSITION_CARE;

---SKIN_CARE  VARCHAR2(50)  Y    皮肤护理  —  S1  AN..50
SELECT SKIN_CARE FROM GENERAL_CARER_ECORDS GROUP BY SKIN_CARE;

---NUTRITION_CARE  VARCHAR2(100)  Y    营养护理  —  S1  AN..100
SELECT NUTRITION_CARE FROM GENERAL_CARER_ECORDS GROUP BY NUTRITION_CARE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM GENERAL_CARER_ECORDS GROUP BY DIET_GUIDE_CODE;

---PSYCHOLOGICAL_CARE_CODE  NUMBER(1)  Y    心理护理代码  标准值：1.根据病人心理状况施行心理护理2.家属心理支持  S2  N1
SELECT PSYCHOLOGICAL_CARE_CODE FROM GENERAL_CARER_ECORDS GROUP BY PSYCHOLOGICAL_CARE_CODE;

---SAFETY_NURSING_CODE  NUMBER(1)  Y    安全护理代码  标准值：1.勤巡视病房2.加床档3.约束四肢  S2  N1
SELECT SAFETY_NURSING_CODE FROM GENERAL_CARER_ECORDS GROUP BY SAFETY_NURSING_CODE;

---PATIENT_CONDITION  VARCHAR2(2000)  Y    简要病情  —  S1  AN..2000
SELECT PATIENT_CONDITION FROM GENERAL_CARER_ECORDS GROUP BY PATIENT_CONDITION;

---ISSUE_SSC_FLAG  VARCHAR2(5)  Y    发出手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_SSC_FLAG;

---WITHDRAW_SSC_FLAG  VARCHAR2(5)  Y    收回手术安全核对表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_SSC_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_SSC_FLAG;

---ISSUE_ORA_FLAG  VARCHAR2(5)  Y    发出手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT ISSUE_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY ISSUE_ORA_FLAG;

---WITHDRAW_ORA_FLAG  VARCHAR2(5)  Y    收回手术风险评估表标志  TRUE/FALSE  L  T/F
SELECT WITHDRAW_ORA_FLAG FROM GENERAL_CARER_ECORDS GROUP BY WITHDRAW_ORA_FLAG;

---ISOLATION_INDICATOR  VARCHAR2(5)  Y    隔离标志  TRUE/FALSE  L  T/F
SELECT ISOLATION_INDICATOR FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_INDICATOR;

---ISOLATION_TYPE_CODE  NUMBER(1)  Y    隔离种类代码  应符合国标：CV06.00.222  S3  N1
SELECT ISOLATION_TYPE_CODE FROM GENERAL_CARER_ECORDS GROUP BY ISOLATION_TYPE_CODE;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名  —  S1  A..50
SELECT NURSE_SIGN FROM GENERAL_CARER_ECORDS GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  —  DT  DTI 5
SELECT SIGN_DATETIME FROM GENERAL_CARER_ECORDS GROUP BY SIGN_DATETIME;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）  —  N  N4,l
SELECT TEMPERATURE FROM GENERAL_CARER_ECORDS GROUP BY TEMPERATURE;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率(次/min)  —  N  N..3
SELECT BREATH_FREQUENCY FROM GENERAL_CARER_ECORDS GROUP BY BREATH_FREQUENCY;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)  —  N  N2..3
SELECT SPHYGMUS FROM GENERAL_CARER_ECORDS GROUP BY SPHYGMUS;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)  —  N  N2..3
SELECT SYSTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)  —  N  N2..3
SELECT DIASTOLIC_PRESSURE FROM GENERAL_CARER_ECORDS GROUP BY DIASTOLIC_PRESSURE;

---OXYGEN_SATURATION  NUMBER(4,1)  Y    血氧饱和度（％)  —  N  N3..4,l
SELECT OXYGEN_SATURATION FROM GENERAL_CARER_ECORDS GROUP BY OXYGEN_SATURATION;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM GENERAL_CARER_ECORDS GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM GENERAL_CARER_ECORDS GROUP BY LAST_MODIFIC_TIME;

