---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_OPER GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_OPER GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_OPER GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_OPER GROUP BY OPERA_SN;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_OPER GROUP BY OPERATE_ROOM_NO;

---OPERATION_BEGIN_DATETIME  DATE  Y    手术开始日期时间    null  null
SELECT OPERATION_BEGIN_DATETIME FROM OPERATION_OPER GROUP BY OPERATION_BEGIN_DATETIME;

---OPERATIION_END_DATETIME  DATE  Y    手术结束日期时间    null  null
SELECT OPERATIION_END_DATETIME FROM OPERATION_OPER GROUP BY OPERATIION_END_DATETIME;

---OUT_OPERATEROOM_DATETIME  DATE  Y    出手术室时间    null  null
SELECT OUT_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY OUT_OPERATEROOM_DATETIME;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国家标准：ICD-9-CM-3  null  null
SELECT OPERATION_CODE FROM OPERATION_OPER GROUP BY OPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_OPER GROUP BY OPERATION_NAME;

---OPERATION_LEVEL_CODE  NUMBER(1)  Y    手术级别代码  应符合国家标准：CV05.10.024  null  null
SELECT OPERATION_LEVEL_CODE FROM OPERATION_OPER GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生    null  null
SELECT OPERATION_DOCTOR_NAME FROM OPERATION_OPER GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    null  null
SELECT FIRST_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    null  null
SELECT SECONDE_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY SECONDE_ASSISTANT_NAME;

---INSTRU_NURSE_NAME  VARCHAR2(50)  Y    器械护士姓名    null  null
SELECT INSTRU_NURSE_NAME FROM OPERATION_OPER GROUP BY INSTRU_NURSE_NAME;

---TOUR_NURSE_NAME  VARCHAR2(50)  Y    巡台护士姓名    null  null
SELECT TOUR_NURSE_NAME FROM OPERATION_OPER GROUP BY TOUR_NURSE_NAME;

---OPERATION_POSITION_CODE  VARCHAR2(4)  Y    操作部位代码  应符合国家标准：CV06.00.227  null  null
SELECT OPERATION_POSITION_CODE FROM OPERATION_OPER GROUP BY OPERATION_POSITION_CODE;

---OPERTATION_TARGET_CODE  NUMBER(4)  Y    操作体位代码  应符合国家标准：CV06.00.223  null  null
SELECT OPERTATION_TARGET_CODE FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_CODE;

---OPERTATION_TARGET_NAME  VARCHAR2(50)  Y    手术及操作目标部位名称    null  null
SELECT OPERTATION_TARGET_NAME FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_NAME;

---INTER_NAME  VARCHAR2(100)  Y    介入物名称    null  null
SELECT INTER_NAME FROM OPERATION_OPER GROUP BY INTER_NAME;

---OPERATION  VARCHAR2(2000)  Y    手术及操作方法    null  null
SELECT OPERATION FROM OPERATION_OPER GROUP BY OPERATION;

---OPERATION_TIMES  NUMBER(3)  Y    手术及操作次数    null  null
SELECT OPERATION_TIMES FROM OPERATION_OPER GROUP BY OPERATION_TIMES;

---OPERATION_OPER_NO  VARCHAR2(18)      手术操作流水号    null  null
SELECT OPERATION_OPER_NO FROM OPERATION_OPER GROUP BY OPERATION_OPER_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_OPER GROUP BY LAST_MODIFIC_TIME;

---ENTER_OPERATEROOM_DATETIME  DATE  Y    入手术室时间    null  null
SELECT ENTER_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY ENTER_OPERATEROOM_DATETIME;

---OPERATIVE_SITE_COOD  VARCHAR2(10)  Y    实施手术的人体部位代码  应符合国家标准：CV5201.23手术/操作体表
  null  null
SELECT OPERATIVE_SITE_COOD FROM OPERATION_OPER GROUP BY OPERATIVE_SITE_COOD;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_OPER GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_OPER GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_OPER GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_OPER GROUP BY OPERA_SN;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_OPER GROUP BY OPERATE_ROOM_NO;

---OPERATION_BEGIN_DATETIME  DATE  Y    手术开始日期时间    null  null
SELECT OPERATION_BEGIN_DATETIME FROM OPERATION_OPER GROUP BY OPERATION_BEGIN_DATETIME;

---OPERATIION_END_DATETIME  DATE  Y    手术结束日期时间    null  null
SELECT OPERATIION_END_DATETIME FROM OPERATION_OPER GROUP BY OPERATIION_END_DATETIME;

---OUT_OPERATEROOM_DATETIME  DATE  Y    出手术室时间    null  null
SELECT OUT_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY OUT_OPERATEROOM_DATETIME;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国家标准：ICD-9-CM-3  null  null
SELECT OPERATION_CODE FROM OPERATION_OPER GROUP BY OPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_OPER GROUP BY OPERATION_NAME;

---OPERATION_LEVEL_CODE  NUMBER(1)  Y    手术级别代码  应符合国家标准：CV05.10.024  null  null
SELECT OPERATION_LEVEL_CODE FROM OPERATION_OPER GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生    null  null
SELECT OPERATION_DOCTOR_NAME FROM OPERATION_OPER GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    null  null
SELECT FIRST_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    null  null
SELECT SECONDE_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY SECONDE_ASSISTANT_NAME;

---INSTRU_NURSE_NAME  VARCHAR2(50)  Y    器械护士姓名    null  null
SELECT INSTRU_NURSE_NAME FROM OPERATION_OPER GROUP BY INSTRU_NURSE_NAME;

---TOUR_NURSE_NAME  VARCHAR2(50)  Y    巡台护士姓名    null  null
SELECT TOUR_NURSE_NAME FROM OPERATION_OPER GROUP BY TOUR_NURSE_NAME;

---OPERATION_POSITION_CODE  VARCHAR2(4)  Y    操作部位代码  应符合国家标准：CV06.00.227  null  null
SELECT OPERATION_POSITION_CODE FROM OPERATION_OPER GROUP BY OPERATION_POSITION_CODE;

---OPERTATION_TARGET_CODE  NUMBER(4)  Y    操作体位代码  应符合国家标准：CV06.00.223  null  null
SELECT OPERTATION_TARGET_CODE FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_CODE;

---OPERTATION_TARGET_NAME  VARCHAR2(50)  Y    手术及操作目标部位名称    null  null
SELECT OPERTATION_TARGET_NAME FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_NAME;

---INTER_NAME  VARCHAR2(100)  Y    介入物名称    null  null
SELECT INTER_NAME FROM OPERATION_OPER GROUP BY INTER_NAME;

---OPERATION  VARCHAR2(2000)  Y    手术及操作方法    null  null
SELECT OPERATION FROM OPERATION_OPER GROUP BY OPERATION;

---OPERATION_TIMES  NUMBER(3)  Y    手术及操作次数    null  null
SELECT OPERATION_TIMES FROM OPERATION_OPER GROUP BY OPERATION_TIMES;

---OPERATION_OPER_NO  VARCHAR2(18)      手术操作流水号    null  null
SELECT OPERATION_OPER_NO FROM OPERATION_OPER GROUP BY OPERATION_OPER_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_OPER GROUP BY LAST_MODIFIC_TIME;

---ENTER_OPERATEROOM_DATETIME  DATE  Y    入手术室时间    null  null
SELECT ENTER_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY ENTER_OPERATEROOM_DATETIME;

---OPERATIVE_SITE_COOD  VARCHAR2(10)  Y    实施手术的人体部位代码  应符合国家标准：CV5201.23手术/操作体表
  null  null
SELECT OPERATIVE_SITE_COOD FROM OPERATION_OPER GROUP BY OPERATIVE_SITE_COOD;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_OPER GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_OPER GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_OPER GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_OPER GROUP BY OPERA_SN;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_OPER GROUP BY OPERATE_ROOM_NO;

---OPERATION_BEGIN_DATETIME  DATE  Y    手术开始日期时间    null  null
SELECT OPERATION_BEGIN_DATETIME FROM OPERATION_OPER GROUP BY OPERATION_BEGIN_DATETIME;

---OPERATIION_END_DATETIME  DATE  Y    手术结束日期时间    null  null
SELECT OPERATIION_END_DATETIME FROM OPERATION_OPER GROUP BY OPERATIION_END_DATETIME;

---OUT_OPERATEROOM_DATETIME  DATE  Y    出手术室时间    null  null
SELECT OUT_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY OUT_OPERATEROOM_DATETIME;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国家标准：ICD-9-CM-3  null  null
SELECT OPERATION_CODE FROM OPERATION_OPER GROUP BY OPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_OPER GROUP BY OPERATION_NAME;

---OPERATION_LEVEL_CODE  NUMBER(1)  Y    手术级别代码  应符合国家标准：CV05.10.024  null  null
SELECT OPERATION_LEVEL_CODE FROM OPERATION_OPER GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术医生    null  null
SELECT OPERATION_DOCTOR_NAME FROM OPERATION_OPER GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    null  null
SELECT FIRST_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    null  null
SELECT SECONDE_ASSISTANT_NAME FROM OPERATION_OPER GROUP BY SECONDE_ASSISTANT_NAME;

---INSTRU_NURSE_NAME  VARCHAR2(50)  Y    器械护士姓名    null  null
SELECT INSTRU_NURSE_NAME FROM OPERATION_OPER GROUP BY INSTRU_NURSE_NAME;

---TOUR_NURSE_NAME  VARCHAR2(50)  Y    巡台护士姓名    null  null
SELECT TOUR_NURSE_NAME FROM OPERATION_OPER GROUP BY TOUR_NURSE_NAME;

---OPERATION_POSITION_CODE  VARCHAR2(4)  Y    操作部位代码  应符合国家标准：CV06.00.227  null  null
SELECT OPERATION_POSITION_CODE FROM OPERATION_OPER GROUP BY OPERATION_POSITION_CODE;

---OPERTATION_TARGET_CODE  NUMBER(4)  Y    操作体位代码  应符合国家标准：CV06.00.223  null  null
SELECT OPERTATION_TARGET_CODE FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_CODE;

---OPERTATION_TARGET_NAME  VARCHAR2(50)  Y    手术及操作目标部位名称    null  null
SELECT OPERTATION_TARGET_NAME FROM OPERATION_OPER GROUP BY OPERTATION_TARGET_NAME;

---INTER_NAME  VARCHAR2(100)  Y    介入物名称    null  null
SELECT INTER_NAME FROM OPERATION_OPER GROUP BY INTER_NAME;

---OPERATION  VARCHAR2(2000)  Y    手术及操作方法    null  null
SELECT OPERATION FROM OPERATION_OPER GROUP BY OPERATION;

---OPERATION_TIMES  NUMBER(3)  Y    手术及操作次数    null  null
SELECT OPERATION_TIMES FROM OPERATION_OPER GROUP BY OPERATION_TIMES;

---OPERATION_OPER_NO  VARCHAR2(18)      手术操作流水号    null  null
SELECT OPERATION_OPER_NO FROM OPERATION_OPER GROUP BY OPERATION_OPER_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_OPER GROUP BY LAST_MODIFIC_TIME;

---ENTER_OPERATEROOM_DATETIME  DATE  Y    入手术室时间    null  null
SELECT ENTER_OPERATEROOM_DATETIME FROM OPERATION_OPER GROUP BY ENTER_OPERATEROOM_DATETIME;

---OPERATIVE_SITE_COOD  VARCHAR2(10)  Y    实施手术的人体部位代码  应符合国家标准：CV5201.23手术/操作体表
  null  null
SELECT OPERATIVE_SITE_COOD FROM OPERATION_OPER GROUP BY OPERATIVE_SITE_COOD;

