---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SALVAGE_RECROD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SALVAGE_RECROD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SALVAGE_RECROD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM SALVAGE_RECROD GROUP BY INP_NO;

---ILLNESS_CHANGE_SITUATION  VARCHAR2(1000)  Y    病情变化情况    S1  AN..1000
SELECT ILLNESS_CHANGE_SITUATION FROM SALVAGE_RECROD GROUP BY ILLNESS_CHANGE_SITUATION;

---RESCUE_MEASURES  VARCHAR2(1000)  Y    抢救措施    S1  AN..1000
SELECT RESCUE_MEASURES FROM SALVAGE_RECROD GROUP BY RESCUE_MEASURES;

---SALVAGE_BEGIN_DATATIME  DATE  Y    抢救开始日期时间    DT  DT15
SELECT SALVAGE_BEGIN_DATATIME FROM SALVAGE_RECROD GROUP BY SALVAGE_BEGIN_DATATIME;

---SALVAGE_END_DATETIME  DATE  Y    抢救结束日期时间    DT  DT15
SELECT SALVAGE_END_DATETIME FROM SALVAGE_RECROD GROUP BY SALVAGE_END_DATETIME;

---INSPECTION_ITEM_NAME  VARCHAR2(80)  Y    检查/检验项目名称    S1  AN..80
SELECT INSPECTION_ITEM_NAME FROM SALVAGE_RECROD GROUP BY INSPECTION_ITEM_NAME;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查/检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_RESULT;

---INSPECTION_RESULT_CODE  NUMBER(1)  Y    检查/检验结果代码  标准值：1.正常  2.异常  3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检查/检验定量结果单位      
SELECT INSPECTION_QUANTIFY_UNIT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_UNIT;

---INSPECTION_RESULT  VARCHAR2(1000)  Y    检查/检验结果    S1  AN..1000
SELECT INSPECTION_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM SALVAGE_RECROD GROUP BY MATTERS_NEED_ATTENTION;

---SALVAGE_NAMES  VARCHAR2(200)  Y    参加抢救人员名单    S1  A..200
SELECT SALVAGE_NAMES FROM SALVAGE_RECROD GROUP BY SALVAGE_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM SALVAGE_RECROD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM SALVAGE_RECROD GROUP BY DOCTOR_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM SALVAGE_RECROD GROUP BY OPER_REQ_SN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SALVAGE_RECROD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SALVAGE_RECROD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SALVAGE_RECROD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SALVAGE_RECROD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SALVAGE_RECROD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM SALVAGE_RECROD GROUP BY INP_NO;

---ILLNESS_CHANGE_SITUATION  VARCHAR2(1000)  Y    病情变化情况    S1  AN..1000
SELECT ILLNESS_CHANGE_SITUATION FROM SALVAGE_RECROD GROUP BY ILLNESS_CHANGE_SITUATION;

---RESCUE_MEASURES  VARCHAR2(1000)  Y    抢救措施    S1  AN..1000
SELECT RESCUE_MEASURES FROM SALVAGE_RECROD GROUP BY RESCUE_MEASURES;

---SALVAGE_BEGIN_DATATIME  DATE  Y    抢救开始日期时间    DT  DT15
SELECT SALVAGE_BEGIN_DATATIME FROM SALVAGE_RECROD GROUP BY SALVAGE_BEGIN_DATATIME;

---SALVAGE_END_DATETIME  DATE  Y    抢救结束日期时间    DT  DT15
SELECT SALVAGE_END_DATETIME FROM SALVAGE_RECROD GROUP BY SALVAGE_END_DATETIME;

---INSPECTION_ITEM_NAME  VARCHAR2(80)  Y    检查/检验项目名称    S1  AN..80
SELECT INSPECTION_ITEM_NAME FROM SALVAGE_RECROD GROUP BY INSPECTION_ITEM_NAME;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查/检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_RESULT;

---INSPECTION_RESULT_CODE  NUMBER(1)  Y    检查/检验结果代码  标准值：1.正常  2.异常  3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检查/检验定量结果单位      
SELECT INSPECTION_QUANTIFY_UNIT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_UNIT;

---INSPECTION_RESULT  VARCHAR2(1000)  Y    检查/检验结果    S1  AN..1000
SELECT INSPECTION_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM SALVAGE_RECROD GROUP BY MATTERS_NEED_ATTENTION;

---SALVAGE_NAMES  VARCHAR2(200)  Y    参加抢救人员名单    S1  A..200
SELECT SALVAGE_NAMES FROM SALVAGE_RECROD GROUP BY SALVAGE_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM SALVAGE_RECROD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM SALVAGE_RECROD GROUP BY DOCTOR_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM SALVAGE_RECROD GROUP BY OPER_REQ_SN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SALVAGE_RECROD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SALVAGE_RECROD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SALVAGE_RECROD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SALVAGE_RECROD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SALVAGE_RECROD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM SALVAGE_RECROD GROUP BY INP_NO;

---ILLNESS_CHANGE_SITUATION  VARCHAR2(1000)  Y    病情变化情况    S1  AN..1000
SELECT ILLNESS_CHANGE_SITUATION FROM SALVAGE_RECROD GROUP BY ILLNESS_CHANGE_SITUATION;

---RESCUE_MEASURES  VARCHAR2(1000)  Y    抢救措施    S1  AN..1000
SELECT RESCUE_MEASURES FROM SALVAGE_RECROD GROUP BY RESCUE_MEASURES;

---SALVAGE_BEGIN_DATATIME  DATE  Y    抢救开始日期时间    DT  DT15
SELECT SALVAGE_BEGIN_DATATIME FROM SALVAGE_RECROD GROUP BY SALVAGE_BEGIN_DATATIME;

---SALVAGE_END_DATETIME  DATE  Y    抢救结束日期时间    DT  DT15
SELECT SALVAGE_END_DATETIME FROM SALVAGE_RECROD GROUP BY SALVAGE_END_DATETIME;

---INSPECTION_ITEM_NAME  VARCHAR2(80)  Y    检查/检验项目名称    S1  AN..80
SELECT INSPECTION_ITEM_NAME FROM SALVAGE_RECROD GROUP BY INSPECTION_ITEM_NAME;

---INSPECTION_QUANTIFY_RESULT  NUMBER(14,4)  Y    检查/检验定量结果    N  N..14,4
SELECT INSPECTION_QUANTIFY_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_RESULT;

---INSPECTION_RESULT_CODE  NUMBER(1)  Y    检查/检验结果代码  标准值：1.正常  2.异常  3.不确定  S2  N1
SELECT INSPECTION_RESULT_CODE FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT_CODE;

---INSPECTION_QUANTIFY_UNIT  VARCHAR2(20)  Y    检查/检验定量结果单位      
SELECT INSPECTION_QUANTIFY_UNIT FROM SALVAGE_RECROD GROUP BY INSPECTION_QUANTIFY_UNIT;

---INSPECTION_RESULT  VARCHAR2(1000)  Y    检查/检验结果    S1  AN..1000
SELECT INSPECTION_RESULT FROM SALVAGE_RECROD GROUP BY INSPECTION_RESULT;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM SALVAGE_RECROD GROUP BY MATTERS_NEED_ATTENTION;

---SALVAGE_NAMES  VARCHAR2(200)  Y    参加抢救人员名单    S1  A..200
SELECT SALVAGE_NAMES FROM SALVAGE_RECROD GROUP BY SALVAGE_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM SALVAGE_RECROD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM SALVAGE_RECROD GROUP BY DOCTOR_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM SALVAGE_RECROD GROUP BY OPER_REQ_SN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SALVAGE_RECROD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SALVAGE_RECROD GROUP BY LAST_MODIFIC_TIME;

