---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名    S1  A..50
SELECT MEDICALHIS_NAME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(2)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT PRESENTER_PATIENT_RELAT_CODE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE  L  T/F
SELECT IS_CREDIBLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY IS_CREDIBLE;

---DEATH_DATE  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_DATE;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_PROCESS_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_PROCESS_DESC FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DIAG_PROCESS_DESC;

---DEATH_REASON  VARCHAR2(100)  Y    死亡原因    S1  AN..100
SELECT DEATH_REASON FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_REASON;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名    S1  A..50
SELECT RECEIVE_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY CHIEF_COMPLAINT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名    S1  A..50
SELECT MEDICALHIS_NAME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(2)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT PRESENTER_PATIENT_RELAT_CODE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE  L  T/F
SELECT IS_CREDIBLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY IS_CREDIBLE;

---DEATH_DATE  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_DATE;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_PROCESS_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_PROCESS_DESC FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DIAG_PROCESS_DESC;

---DEATH_REASON  VARCHAR2(100)  Y    死亡原因    S1  AN..100
SELECT DEATH_REASON FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_REASON;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名    S1  A..50
SELECT RECEIVE_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY CHIEF_COMPLAINT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名    S1  A..50
SELECT MEDICALHIS_NAME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(2)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761—2008  S3  N1
SELECT PRESENTER_PATIENT_RELAT_CODE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE  L  T/F
SELECT IS_CREDIBLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY IS_CREDIBLE;

---DEATH_DATE  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_DATE;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_PROCESS_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_PROCESS_DESC FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DIAG_PROCESS_DESC;

---DEATH_REASON  VARCHAR2(100)  Y    死亡原因    S1  AN..100
SELECT DEATH_REASON FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY DEATH_REASON;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名    S1  A..50
SELECT RECEIVE_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY CHIEF_COMPLAINT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM HOURS24_ADMISSION_DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

