---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM SAMPLE_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM SAMPLE_INFO GROUP BY INPATIENT_SN;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)      检验标本号    null  null
SELECT INSPECTION_INSPECTION_NO FROM SAMPLE_INFO GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号    null  null
SELECT INSPECTION_REPORT_NO FROM SAMPLE_INFO GROUP BY INSPECTION_REPORT_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  null
SELECT APPLY_NO FROM SAMPLE_INFO GROUP BY APPLY_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称    null  null
SELECT INSPECTION_METHOD_NAME FROM SAMPLE_INFO GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别    null  null
SELECT INSPECTION_TYPE FROM SAMPLE_INFO GROUP BY INSPECTION_TYPE;

---SAMPLE_TYPE  VARCHAR2(20)  Y    标本类别    null  null
SELECT SAMPLE_TYPE FROM SAMPLE_INFO GROUP BY SAMPLE_TYPE;

---SAMPLE_STATE  VARCHAR2(20)  Y    标本状态    null  null
SELECT SAMPLE_STATE FROM SAMPLE_INFO GROUP BY SAMPLE_STATE;

---SPECIMEN_SAMPLE_DATE  DATE  Y    标本采样日期时间    null  null
SELECT SPECIMEN_SAMPLE_DATE FROM SAMPLE_INFO GROUP BY SPECIMEN_SAMPLE_DATE;

---RECEIVE_SPECIMEN_DATE  DATE  Y    接收标本日期时间    null  null
SELECT RECEIVE_SPECIMEN_DATE FROM SAMPLE_INFO GROUP BY RECEIVE_SPECIMEN_DATE;

---SPECIMEN_FIXATIVE_NAME  VARCHAR2(50)  Y    标本固定液名称    null  null
SELECT SPECIMEN_FIXATIVE_NAME FROM SAMPLE_INFO GROUP BY SPECIMEN_FIXATIVE_NAME;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM SAMPLE_INFO GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM SAMPLE_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM SAMPLE_INFO GROUP BY INPATIENT_SN;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)      检验标本号    null  null
SELECT INSPECTION_INSPECTION_NO FROM SAMPLE_INFO GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号    null  null
SELECT INSPECTION_REPORT_NO FROM SAMPLE_INFO GROUP BY INSPECTION_REPORT_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  null
SELECT APPLY_NO FROM SAMPLE_INFO GROUP BY APPLY_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称    null  null
SELECT INSPECTION_METHOD_NAME FROM SAMPLE_INFO GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别    null  null
SELECT INSPECTION_TYPE FROM SAMPLE_INFO GROUP BY INSPECTION_TYPE;

---SAMPLE_TYPE  VARCHAR2(20)  Y    标本类别    null  null
SELECT SAMPLE_TYPE FROM SAMPLE_INFO GROUP BY SAMPLE_TYPE;

---SAMPLE_STATE  VARCHAR2(20)  Y    标本状态    null  null
SELECT SAMPLE_STATE FROM SAMPLE_INFO GROUP BY SAMPLE_STATE;

---SPECIMEN_SAMPLE_DATE  DATE  Y    标本采样日期时间    null  null
SELECT SPECIMEN_SAMPLE_DATE FROM SAMPLE_INFO GROUP BY SPECIMEN_SAMPLE_DATE;

---RECEIVE_SPECIMEN_DATE  DATE  Y    接收标本日期时间    null  null
SELECT RECEIVE_SPECIMEN_DATE FROM SAMPLE_INFO GROUP BY RECEIVE_SPECIMEN_DATE;

---SPECIMEN_FIXATIVE_NAME  VARCHAR2(50)  Y    标本固定液名称    null  null
SELECT SPECIMEN_FIXATIVE_NAME FROM SAMPLE_INFO GROUP BY SPECIMEN_FIXATIVE_NAME;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM SAMPLE_INFO GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM SAMPLE_INFO GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM SAMPLE_INFO GROUP BY INPATIENT_SN;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)      检验标本号    null  null
SELECT INSPECTION_INSPECTION_NO FROM SAMPLE_INFO GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号    null  null
SELECT INSPECTION_REPORT_NO FROM SAMPLE_INFO GROUP BY INSPECTION_REPORT_NO;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    null  null
SELECT APPLY_NO FROM SAMPLE_INFO GROUP BY APPLY_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称    null  null
SELECT INSPECTION_METHOD_NAME FROM SAMPLE_INFO GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别    null  null
SELECT INSPECTION_TYPE FROM SAMPLE_INFO GROUP BY INSPECTION_TYPE;

---SAMPLE_TYPE  VARCHAR2(20)  Y    标本类别    null  null
SELECT SAMPLE_TYPE FROM SAMPLE_INFO GROUP BY SAMPLE_TYPE;

---SAMPLE_STATE  VARCHAR2(20)  Y    标本状态    null  null
SELECT SAMPLE_STATE FROM SAMPLE_INFO GROUP BY SAMPLE_STATE;

---SPECIMEN_SAMPLE_DATE  DATE  Y    标本采样日期时间    null  null
SELECT SPECIMEN_SAMPLE_DATE FROM SAMPLE_INFO GROUP BY SPECIMEN_SAMPLE_DATE;

---RECEIVE_SPECIMEN_DATE  DATE  Y    接收标本日期时间    null  null
SELECT RECEIVE_SPECIMEN_DATE FROM SAMPLE_INFO GROUP BY RECEIVE_SPECIMEN_DATE;

---SPECIMEN_FIXATIVE_NAME  VARCHAR2(50)  Y    标本固定液名称    null  null
SELECT SPECIMEN_FIXATIVE_NAME FROM SAMPLE_INFO GROUP BY SPECIMEN_FIXATIVE_NAME;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM SAMPLE_INFO GROUP BY LAST_MODIFIC_TIME;

