---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DIS_DEATH_RECORDS  VARCHAR2(2000)  Y    死亡讨论记录    S1  AN..2000
SELECT DIS_DEATH_RECORDS FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DIS_DEATH_RECORDS;

---COMPERE_SUMMARY_SUGGESTION  VARCHAR2(2000)  Y    主持人总结意见    S1  AN..2000
SELECT COMPERE_SUMMARY_SUGGESTION FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_SUMMARY_SUGGESTION;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY SIGN_DATATIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DIS_DEATH_RECORDS  VARCHAR2(2000)  Y    死亡讨论记录    S1  AN..2000
SELECT DIS_DEATH_RECORDS FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DIS_DEATH_RECORDS;

---COMPERE_SUMMARY_SUGGESTION  VARCHAR2(2000)  Y    主持人总结意见    S1  AN..2000
SELECT COMPERE_SUMMARY_SUGGESTION FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_SUMMARY_SUGGESTION;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY SIGN_DATATIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DISCUSS_NAMES;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DIS_DEATH_RECORDS  VARCHAR2(2000)  Y    死亡讨论记录    S1  AN..2000
SELECT DIS_DEATH_RECORDS FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY DIS_DEATH_RECORDS;

---COMPERE_SUMMARY_SUGGESTION  VARCHAR2(2000)  Y    主持人总结意见    S1  AN..2000
SELECT COMPERE_SUMMARY_SUGGESTION FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY COMPERE_SUMMARY_SUGGESTION;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY SIGN_DATATIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_CASE_DISCUSSION_RECORD GROUP BY LAST_MODIFIC_TIME;

