---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM SURVEY_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM SURVEY_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN.. 18
SELECT OUTP_NO FROM SURVEY_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM SURVEY_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SURVEY_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM SURVEY_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  S1  AN..20
SELECT APPLY_NO FROM SURVEY_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检验申请机构名称  —  S1  AN..70
SELECT EXAMINATION_APPLY_ORGAN FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检验申请科室  —  S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检验标本号  —  S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM SURVEY_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称  —  S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM SURVEY_RECORD GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别  —  S1  AN..100
SELECT INSPECTION_TYPE FROM SURVEY_RECORD GROUP BY INSPECTION_TYPE;

---INSPECTION_ITEM_CODE  VARCHAR2(20)  Y    检验项目代码  —  S1  AN..20
SELECT INSPECTION_ITEM_CODE FROM SURVEY_RECORD GROUP BY INSPECTION_ITEM_CODE;

---INSPECTION_ENGINEER  VARCHAR2(50)  Y    检验技师签名  —  S1  A..50
SELECT INSPECTION_ENGINEER FROM SURVEY_RECORD GROUP BY INSPECTION_ENGINEER;

---INSPECTION_DOCTOR  VARCHAR2(50)  Y    检验医师签名  —  S1  A..50
SELECT INSPECTION_DOCTOR FROM SURVEY_RECORD GROUP BY INSPECTION_DOCTOR;

---INSPECTION_DATE  DATE  Y    检验日期  —  D  D8
SELECT INSPECTION_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_DATE;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号  —  S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_NO;

---INSPECTION_REPORT_ORGAN  VARCHAR2(70)  Y    检验报告机构名称  ―  S1  AN..70
SELECT INSPECTION_REPORT_ORGAN FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ORGAN;

---INSPECTION_REPORT_ROOM  VARCHAR2(50)  Y    检验报告科室  ―  S1  AN..50
SELECT INSPECTION_REPORT_ROOM FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ROOM;

---INSPECTION_REPORT_RESULT  VARCHAR2(200)  Y    检验报告结果  ―  S1  AN..200
SELECT INSPECTION_REPORT_RESULT FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_RESULT;

---INSPECTION_REPORT_REMARKS  VARCHAR2(100)  Y    检验报告备注  ―  S1  AN..100
SELECT INSPECTION_REPORT_REMARKS FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_REMARKS;

---INSPECTION_REPORT_DATE  DATE  Y    检验报告日期  ―  D  D8
SELECT INSPECTION_REPORT_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名  ―  S1  A..50
SELECT REPORT_DOCTOR FROM SURVEY_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名  ―  S1  A..50
SELECT REPORTAUDIT FROM SURVEY_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM SURVEY_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM SURVEY_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN.. 18
SELECT OUTP_NO FROM SURVEY_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM SURVEY_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SURVEY_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM SURVEY_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  S1  AN..20
SELECT APPLY_NO FROM SURVEY_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检验申请机构名称  —  S1  AN..70
SELECT EXAMINATION_APPLY_ORGAN FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检验申请科室  —  S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检验标本号  —  S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM SURVEY_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称  —  S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM SURVEY_RECORD GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别  —  S1  AN..100
SELECT INSPECTION_TYPE FROM SURVEY_RECORD GROUP BY INSPECTION_TYPE;

---INSPECTION_ITEM_CODE  VARCHAR2(20)  Y    检验项目代码  —  S1  AN..20
SELECT INSPECTION_ITEM_CODE FROM SURVEY_RECORD GROUP BY INSPECTION_ITEM_CODE;

---INSPECTION_ENGINEER  VARCHAR2(50)  Y    检验技师签名  —  S1  A..50
SELECT INSPECTION_ENGINEER FROM SURVEY_RECORD GROUP BY INSPECTION_ENGINEER;

---INSPECTION_DOCTOR  VARCHAR2(50)  Y    检验医师签名  —  S1  A..50
SELECT INSPECTION_DOCTOR FROM SURVEY_RECORD GROUP BY INSPECTION_DOCTOR;

---INSPECTION_DATE  DATE  Y    检验日期  —  D  D8
SELECT INSPECTION_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_DATE;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号  —  S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_NO;

---INSPECTION_REPORT_ORGAN  VARCHAR2(70)  Y    检验报告机构名称  ―  S1  AN..70
SELECT INSPECTION_REPORT_ORGAN FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ORGAN;

---INSPECTION_REPORT_ROOM  VARCHAR2(50)  Y    检验报告科室  ―  S1  AN..50
SELECT INSPECTION_REPORT_ROOM FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ROOM;

---INSPECTION_REPORT_RESULT  VARCHAR2(200)  Y    检验报告结果  ―  S1  AN..200
SELECT INSPECTION_REPORT_RESULT FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_RESULT;

---INSPECTION_REPORT_REMARKS  VARCHAR2(100)  Y    检验报告备注  ―  S1  AN..100
SELECT INSPECTION_REPORT_REMARKS FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_REMARKS;

---INSPECTION_REPORT_DATE  DATE  Y    检验报告日期  ―  D  D8
SELECT INSPECTION_REPORT_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名  ―  S1  A..50
SELECT REPORT_DOCTOR FROM SURVEY_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名  ―  S1  A..50
SELECT REPORTAUDIT FROM SURVEY_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊就诊流水号      
SELECT OUTPATIENT_SN FROM SURVEY_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院就诊流水号      
SELECT INPATIENT_SN FROM SURVEY_RECORD GROUP BY INPATIENT_SN;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN.. 18
SELECT OUTP_NO FROM SURVEY_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM SURVEY_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SURVEY_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM SURVEY_RECORD GROUP BY PATIENT_ID;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  S1  AN..20
SELECT APPLY_NO FROM SURVEY_RECORD GROUP BY APPLY_NO;

---EXAMINATION_APPLY_ORGAN  VARCHAR2(70)  Y    检验申请机构名称  —  S1  AN..70
SELECT EXAMINATION_APPLY_ORGAN FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ORGAN;

---EXAMINATION_APPLY_ROOM  VARCHAR2(50)  Y    检验申请科室  —  S1  AN..50
SELECT EXAMINATION_APPLY_ROOM FROM SURVEY_RECORD GROUP BY EXAMINATION_APPLY_ROOM;

---INSPECTION_INSPECTION_NO  VARCHAR2(20)  Y    检验标本号  —  S1  AN..20
SELECT INSPECTION_INSPECTION_NO FROM SURVEY_RECORD GROUP BY INSPECTION_INSPECTION_NO;

---INSPECTION_METHOD_NAME  VARCHAR2(100)  Y    检验方法名称  —  S1  AN..100
SELECT INSPECTION_METHOD_NAME FROM SURVEY_RECORD GROUP BY INSPECTION_METHOD_NAME;

---INSPECTION_TYPE  VARCHAR2(100)  Y    检验类别  —  S1  AN..100
SELECT INSPECTION_TYPE FROM SURVEY_RECORD GROUP BY INSPECTION_TYPE;

---INSPECTION_ITEM_CODE  VARCHAR2(20)  Y    检验项目代码  —  S1  AN..20
SELECT INSPECTION_ITEM_CODE FROM SURVEY_RECORD GROUP BY INSPECTION_ITEM_CODE;

---INSPECTION_ENGINEER  VARCHAR2(50)  Y    检验技师签名  —  S1  A..50
SELECT INSPECTION_ENGINEER FROM SURVEY_RECORD GROUP BY INSPECTION_ENGINEER;

---INSPECTION_DOCTOR  VARCHAR2(50)  Y    检验医师签名  —  S1  A..50
SELECT INSPECTION_DOCTOR FROM SURVEY_RECORD GROUP BY INSPECTION_DOCTOR;

---INSPECTION_DATE  DATE  Y    检验日期  —  D  D8
SELECT INSPECTION_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_DATE;

---INSPECTION_REPORT_NO  VARCHAR2(20)  Y    检验报告单编号  —  S1  AN. .20
SELECT INSPECTION_REPORT_NO FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_NO;

---INSPECTION_REPORT_ORGAN  VARCHAR2(70)  Y    检验报告机构名称  ―  S1  AN..70
SELECT INSPECTION_REPORT_ORGAN FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ORGAN;

---INSPECTION_REPORT_ROOM  VARCHAR2(50)  Y    检验报告科室  ―  S1  AN..50
SELECT INSPECTION_REPORT_ROOM FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_ROOM;

---INSPECTION_REPORT_RESULT  VARCHAR2(200)  Y    检验报告结果  ―  S1  AN..200
SELECT INSPECTION_REPORT_RESULT FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_RESULT;

---INSPECTION_REPORT_REMARKS  VARCHAR2(100)  Y    检验报告备注  ―  S1  AN..100
SELECT INSPECTION_REPORT_REMARKS FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_REMARKS;

---INSPECTION_REPORT_DATE  DATE  Y    检验报告日期  ―  D  D8
SELECT INSPECTION_REPORT_DATE FROM SURVEY_RECORD GROUP BY INSPECTION_REPORT_DATE;

---REPORT_DOCTOR  VARCHAR2(50)  Y    报告医师签名  ―  S1  A..50
SELECT REPORT_DOCTOR FROM SURVEY_RECORD GROUP BY REPORT_DOCTOR;

---REPORTAUDIT  VARCHAR2(50)  Y    审核医师签名  ―  S1  A..50
SELECT REPORTAUDIT FROM SURVEY_RECORD GROUP BY REPORTAUDIT;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM SURVEY_RECORD GROUP BY LAST_MODIFIC_TIME;

