---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_PREP GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_PREP GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)      手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_PREP GROUP BY OPER_REQ_SN;

---SIMULOPERATION_CODE  VARCHAR2(20)  Y    拟实施手术及操作编码    null  null
SELECT SIMULOPERATION_CODE FROM OPERATION_PREP GROUP BY SIMULOPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    拟实施手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_PREP GROUP BY OPERATION_NAME;

---OPERATION_POSITION_NAME  VARCHAR2(50)  Y    拟实施手术目标部位名称    null  null
SELECT OPERATION_POSITION_NAME FROM OPERATION_PREP GROUP BY OPERATION_POSITION_NAME;

---INTENT_ANESTHESIA_CODE  NUMBER(2)  Y    拟实施麻醉方法代码    null  null
SELECT INTENT_ANESTHESIA_CODE FROM OPERATION_PREP GROUP BY INTENT_ANESTHESIA_CODE;

---OPERATE_ANESTHESIA_ADVICE  VARCHAR2(1000)  Y    术前麻醉医嘱    null  null
SELECT OPERATE_ANESTHESIA_ADVICE FROM OPERATION_PREP GROUP BY OPERATE_ANESTHESIA_ADVICE;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证    null  null
SELECT ANESTHESIA_INDICATION FROM OPERATION_PREP GROUP BY ANESTHESIA_INDICATION;

---ATTENTION  VARCHAR2(1000)  Y    注意事项    null  null
SELECT ATTENTION FROM OPERATION_PREP GROUP BY ATTENTION;

---INTENT_OPERATE_DATETIME  DATE  Y    拟实施手术及操作日期时间    null  null
SELECT INTENT_OPERATE_DATETIME FROM OPERATION_PREP GROUP BY INTENT_OPERATE_DATETIME;

---OPERATION_INDICATION  VARCHAR2(500)  Y    手术指征    null  null
SELECT OPERATION_INDICATION FROM OPERATION_PREP GROUP BY OPERATION_INDICATION;

---OPERATION_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    null  null
SELECT OPERATION_CONTRAINDICATION FROM OPERATION_PREP GROUP BY OPERATION_CONTRAINDICATION;

---OPERATION_METHOD  VARCHAR2(30)  Y    手术方式    null  null
SELECT OPERATION_METHOD FROM OPERATION_PREP GROUP BY OPERATION_METHOD;

---OPERATION_BEFORE_PREPARE  VARCHAR2(1000)  Y    术前准备    null  null
SELECT OPERATION_BEFORE_PREPARE FROM OPERATION_PREP GROUP BY OPERATION_BEFORE_PREPARE;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_PREP GROUP BY OPERATE_ROOM_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_PREP GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_PREP GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_PREP GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)      手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_PREP GROUP BY OPER_REQ_SN;

---SIMULOPERATION_CODE  VARCHAR2(20)  Y    拟实施手术及操作编码    null  null
SELECT SIMULOPERATION_CODE FROM OPERATION_PREP GROUP BY SIMULOPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    拟实施手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_PREP GROUP BY OPERATION_NAME;

---OPERATION_POSITION_NAME  VARCHAR2(50)  Y    拟实施手术目标部位名称    null  null
SELECT OPERATION_POSITION_NAME FROM OPERATION_PREP GROUP BY OPERATION_POSITION_NAME;

---INTENT_ANESTHESIA_CODE  NUMBER(2)  Y    拟实施麻醉方法代码    null  null
SELECT INTENT_ANESTHESIA_CODE FROM OPERATION_PREP GROUP BY INTENT_ANESTHESIA_CODE;

---OPERATE_ANESTHESIA_ADVICE  VARCHAR2(1000)  Y    术前麻醉医嘱    null  null
SELECT OPERATE_ANESTHESIA_ADVICE FROM OPERATION_PREP GROUP BY OPERATE_ANESTHESIA_ADVICE;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证    null  null
SELECT ANESTHESIA_INDICATION FROM OPERATION_PREP GROUP BY ANESTHESIA_INDICATION;

---ATTENTION  VARCHAR2(1000)  Y    注意事项    null  null
SELECT ATTENTION FROM OPERATION_PREP GROUP BY ATTENTION;

---INTENT_OPERATE_DATETIME  DATE  Y    拟实施手术及操作日期时间    null  null
SELECT INTENT_OPERATE_DATETIME FROM OPERATION_PREP GROUP BY INTENT_OPERATE_DATETIME;

---OPERATION_INDICATION  VARCHAR2(500)  Y    手术指征    null  null
SELECT OPERATION_INDICATION FROM OPERATION_PREP GROUP BY OPERATION_INDICATION;

---OPERATION_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    null  null
SELECT OPERATION_CONTRAINDICATION FROM OPERATION_PREP GROUP BY OPERATION_CONTRAINDICATION;

---OPERATION_METHOD  VARCHAR2(30)  Y    手术方式    null  null
SELECT OPERATION_METHOD FROM OPERATION_PREP GROUP BY OPERATION_METHOD;

---OPERATION_BEFORE_PREPARE  VARCHAR2(1000)  Y    术前准备    null  null
SELECT OPERATION_BEFORE_PREPARE FROM OPERATION_PREP GROUP BY OPERATION_BEFORE_PREPARE;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_PREP GROUP BY OPERATE_ROOM_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_PREP GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_PREP GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_PREP GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)      手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_PREP GROUP BY OPER_REQ_SN;

---SIMULOPERATION_CODE  VARCHAR2(20)  Y    拟实施手术及操作编码    null  null
SELECT SIMULOPERATION_CODE FROM OPERATION_PREP GROUP BY SIMULOPERATION_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    拟实施手术及操作名称    null  null
SELECT OPERATION_NAME FROM OPERATION_PREP GROUP BY OPERATION_NAME;

---OPERATION_POSITION_NAME  VARCHAR2(50)  Y    拟实施手术目标部位名称    null  null
SELECT OPERATION_POSITION_NAME FROM OPERATION_PREP GROUP BY OPERATION_POSITION_NAME;

---INTENT_ANESTHESIA_CODE  NUMBER(2)  Y    拟实施麻醉方法代码    null  null
SELECT INTENT_ANESTHESIA_CODE FROM OPERATION_PREP GROUP BY INTENT_ANESTHESIA_CODE;

---OPERATE_ANESTHESIA_ADVICE  VARCHAR2(1000)  Y    术前麻醉医嘱    null  null
SELECT OPERATE_ANESTHESIA_ADVICE FROM OPERATION_PREP GROUP BY OPERATE_ANESTHESIA_ADVICE;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证    null  null
SELECT ANESTHESIA_INDICATION FROM OPERATION_PREP GROUP BY ANESTHESIA_INDICATION;

---ATTENTION  VARCHAR2(1000)  Y    注意事项    null  null
SELECT ATTENTION FROM OPERATION_PREP GROUP BY ATTENTION;

---INTENT_OPERATE_DATETIME  DATE  Y    拟实施手术及操作日期时间    null  null
SELECT INTENT_OPERATE_DATETIME FROM OPERATION_PREP GROUP BY INTENT_OPERATE_DATETIME;

---OPERATION_INDICATION  VARCHAR2(500)  Y    手术指征    null  null
SELECT OPERATION_INDICATION FROM OPERATION_PREP GROUP BY OPERATION_INDICATION;

---OPERATION_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    null  null
SELECT OPERATION_CONTRAINDICATION FROM OPERATION_PREP GROUP BY OPERATION_CONTRAINDICATION;

---OPERATION_METHOD  VARCHAR2(30)  Y    手术方式    null  null
SELECT OPERATION_METHOD FROM OPERATION_PREP GROUP BY OPERATION_METHOD;

---OPERATION_BEFORE_PREPARE  VARCHAR2(1000)  Y    术前准备    null  null
SELECT OPERATION_BEFORE_PREPARE FROM OPERATION_PREP GROUP BY OPERATION_BEFORE_PREPARE;

---OPERATE_ROOM_NO  VARCHAR2(20)  Y    手术间编号    null  null
SELECT OPERATE_ROOM_NO FROM OPERATION_PREP GROUP BY OPERATE_ROOM_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_PREP GROUP BY LAST_MODIFIC_TIME;

