---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_MEDICALBILL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_MEDICALBILL GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EMR_MEDICALBILL GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM EMR_MEDICALBILL GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号  —  S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_MEDICALBILL GROUP BY HEALTH_CARD_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM EMR_MEDICALBILL GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM EMR_MEDICALBILL GROUP BY INP_NO;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  CV07.10.005  S3  N2
SELECT PAY_WAY FROM EMR_MEDICALBILL GROUP BY PAY_WAY;

---OUTP_COST_AMOUNT  NUMBER(8,2)  Y    门诊费用金额  —  N  N..8,2
SELECT OUTP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY OUTP_COST_AMOUNT;

---INP_COST_AMOUNT  NUMBER(10,2)  Y    住院费用金额  —  N  N..10,2
SELECT INP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY INP_COST_AMOUNT;

---PERSONAL_COST_AMOUNT  NUMBER(10,2)  Y    个人承担费用金额  —  N  N..10,2
SELECT PERSONAL_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY PERSONAL_COST_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_MEDICALBILL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_MEDICALBILL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_MEDICALBILL GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EMR_MEDICALBILL GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM EMR_MEDICALBILL GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号  —  S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_MEDICALBILL GROUP BY HEALTH_CARD_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM EMR_MEDICALBILL GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM EMR_MEDICALBILL GROUP BY INP_NO;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  CV07.10.005  S3  N2
SELECT PAY_WAY FROM EMR_MEDICALBILL GROUP BY PAY_WAY;

---OUTP_COST_AMOUNT  NUMBER(8,2)  Y    门诊费用金额  —  N  N..8,2
SELECT OUTP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY OUTP_COST_AMOUNT;

---INP_COST_AMOUNT  NUMBER(10,2)  Y    住院费用金额  —  N  N..10,2
SELECT INP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY INP_COST_AMOUNT;

---PERSONAL_COST_AMOUNT  NUMBER(10,2)  Y    个人承担费用金额  —  N  N..10,2
SELECT PERSONAL_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY PERSONAL_COST_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_MEDICALBILL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM EMR_MEDICALBILL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM EMR_MEDICALBILL GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM EMR_MEDICALBILL GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID      
SELECT PATIENT_ID FROM EMR_MEDICALBILL GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)  Y    居民健康卡号  —  S1  AN..18
SELECT HEALTH_CARD_NO FROM EMR_MEDICALBILL GROUP BY HEALTH_CARD_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM EMR_MEDICALBILL GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM EMR_MEDICALBILL GROUP BY INP_NO;

---PAY_WAY  VARCHAR2(2)  Y    医疗付费方式代码  CV07.10.005  S3  N2
SELECT PAY_WAY FROM EMR_MEDICALBILL GROUP BY PAY_WAY;

---OUTP_COST_AMOUNT  NUMBER(8,2)  Y    门诊费用金额  —  N  N..8,2
SELECT OUTP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY OUTP_COST_AMOUNT;

---INP_COST_AMOUNT  NUMBER(10,2)  Y    住院费用金额  —  N  N..10,2
SELECT INP_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY INP_COST_AMOUNT;

---PERSONAL_COST_AMOUNT  NUMBER(10,2)  Y    个人承担费用金额  —  N  N..10,2
SELECT PERSONAL_COST_AMOUNT FROM EMR_MEDICALBILL GROUP BY PERSONAL_COST_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM EMR_MEDICALBILL GROUP BY LAST_MODIFIC_TIME;

