---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_SUMMARY GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_SUMMARY GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_SUMMARY GROUP BY PATIENT_ID;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM PRE_OPERATION_SUMMARY GROUP BY MR_EXCERPTS;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM PRE_OPERATION_SUMMARY GROUP BY OPER_REQ_SN;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM PRE_OPERATION_SUMMARY GROUP BY DIAG_EVIDENCE;

---ALLERGY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_FLAG FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_HISTORY;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM PRE_OPERATION_SUMMARY GROUP BY AUXILIARYEXAMI_RESULT;

---SURGICAL_INDICATION  VARCHAR2(100)  Y    手术适应证    S1  AN..100
SELECT SURGICAL_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGICAL_INDICATION;

---SURGERY_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    S1  AN..100
SELECT SURGERY_CONTRAINDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGERY_CONTRAINDICATION;

---OPERATIVE_INDICATION  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATIVE_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_INDICATION;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊意见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM PRE_OPERATION_SUMMARY GROUP BY CONSULTATION_SUGGESTION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_SUMMARY GROUP BY MATTERS_NEED_ATTENTION;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_SUMMARY GROUP BY OPERATION_POINTS;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_SIGN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_SUMMARY GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_SUMMARY GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_SUMMARY GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_SUMMARY GROUP BY PATIENT_ID;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM PRE_OPERATION_SUMMARY GROUP BY MR_EXCERPTS;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM PRE_OPERATION_SUMMARY GROUP BY OPER_REQ_SN;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM PRE_OPERATION_SUMMARY GROUP BY DIAG_EVIDENCE;

---ALLERGY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_FLAG FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_HISTORY;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM PRE_OPERATION_SUMMARY GROUP BY AUXILIARYEXAMI_RESULT;

---SURGICAL_INDICATION  VARCHAR2(100)  Y    手术适应证    S1  AN..100
SELECT SURGICAL_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGICAL_INDICATION;

---SURGERY_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    S1  AN..100
SELECT SURGERY_CONTRAINDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGERY_CONTRAINDICATION;

---OPERATIVE_INDICATION  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATIVE_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_INDICATION;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊意见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM PRE_OPERATION_SUMMARY GROUP BY CONSULTATION_SUGGESTION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_SUMMARY GROUP BY MATTERS_NEED_ATTENTION;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_SUMMARY GROUP BY OPERATION_POINTS;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_SIGN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_SUMMARY GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_SUMMARY GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_SUMMARY GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_SUMMARY GROUP BY PATIENT_ID;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---MR_EXCERPTS  VARCHAR2(200)  Y    病历摘要    S1  AN..200
SELECT MR_EXCERPTS FROM PRE_OPERATION_SUMMARY GROUP BY MR_EXCERPTS;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM PRE_OPERATION_SUMMARY GROUP BY OPER_REQ_SN;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM PRE_OPERATION_SUMMARY GROUP BY DIAG_EVIDENCE;

---ALLERGY_FLAG  VARCHAR2(5)  Y    过敏史标志    L  T/F
SELECT ALLERGY_FLAG FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM PRE_OPERATION_SUMMARY GROUP BY ALLERGY_HISTORY;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果    S1  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM PRE_OPERATION_SUMMARY GROUP BY AUXILIARYEXAMI_RESULT;

---SURGICAL_INDICATION  VARCHAR2(100)  Y    手术适应证    S1  AN..100
SELECT SURGICAL_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGICAL_INDICATION;

---SURGERY_CONTRAINDICATION  VARCHAR2(100)  Y    手术禁忌症    S1  AN..100
SELECT SURGERY_CONTRAINDICATION FROM PRE_OPERATION_SUMMARY GROUP BY SURGERY_CONTRAINDICATION;

---OPERATIVE_INDICATION  VARCHAR2(500)  Y    手术指征    S1  AN..500
SELECT OPERATIVE_INDICATION FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_INDICATION;

---CONSULTATION_SUGGESTION  VARCHAR2(2000)  Y    会诊意见    S1  AN..2000
SELECT CONSULTATION_SUGGESTION FROM PRE_OPERATION_SUMMARY GROUP BY CONSULTATION_SUGGESTION;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_SUMMARY GROUP BY MATTERS_NEED_ATTENTION;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_SUMMARY GROUP BY OPERATION_POINTS;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  A..50
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY OPERATIVE_SIGN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_SUMMARY GROUP BY LAST_MODIFIC_TIME;

