---ADDRESS_ID  VARCHAR2(20)      地址基本信息唯一标识    null  null
SELECT ADDRESS_ID FROM BSPATADDRESS GROUP BY ADDRESS_ID;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM BSPATADDRESS GROUP BY PATIENT_ID;

---ADDRESS_TYPE_CODE  VARCHAR2(2)  Y    地址类别代码（01-户籍住址，02-工作场所地址，03-家庭常住住址，04-通讯地址，05-暂住地址，06-出生地址，07-产后修养地址，08-变迁地址，09-现住址，99-其他地址）备注：联系人地址用其他地址标识  应符合国标：CV02.01.205  null  null
SELECT ADDRESS_TYPE_CODE FROM BSPATADDRESS GROUP BY ADDRESS_TYPE_CODE;

---ADDRESS_PROVINCE  VARCHAR2(70)  Y    地址-省（自治区、直辖市）    null  null
SELECT ADDRESS_PROVINCE FROM BSPATADDRESS GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)  Y    地址-市（地区、州）    null  null
SELECT ADDRESS_CITY FROM BSPATADDRESS GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)  Y    地址-县（区）    null  null
SELECT ADDRESS_COUNTY FROM BSPATADDRESS GROUP BY ADDRESS_COUNTY;

---ADDRESS_TOWNSHIP  VARCHAR2(70)  Y    地址-乡（镇、街道办事处）    null  null
SELECT ADDRESS_TOWNSHIP FROM BSPATADDRESS GROUP BY ADDRESS_TOWNSHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)  Y    地址-村（街、路、弄等）    null  null
SELECT ADDRESS_VILLAGE FROM BSPATADDRESS GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)  Y    地址-门牌号码    null  null
SELECT ADDRESS_DOORS FROM BSPATADDRESS GROUP BY ADDRESS_DOORS;

---ZIP_CODE  VARCHAR2(6)  Y    邮政编码    null  null
SELECT ZIP_CODE FROM BSPATADDRESS GROUP BY ZIP_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSPATADDRESS GROUP BY LAST_MODIFIC_TIME;

---ADDRESS_ID  VARCHAR2(20)      地址基本信息唯一标识    null  null
SELECT ADDRESS_ID FROM BSPATADDRESS GROUP BY ADDRESS_ID;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM BSPATADDRESS GROUP BY PATIENT_ID;

---ADDRESS_TYPE_CODE  VARCHAR2(2)  Y    地址类别代码（01-户籍住址，02-工作场所地址，03-家庭常住住址，04-通讯地址，05-暂住地址，06-出生地址，07-产后修养地址，08-变迁地址，09-现住址，99-其他地址）备注：联系人地址用其他地址标识  应符合国标：CV02.01.205  null  null
SELECT ADDRESS_TYPE_CODE FROM BSPATADDRESS GROUP BY ADDRESS_TYPE_CODE;

---ADDRESS_PROVINCE  VARCHAR2(70)  Y    地址-省（自治区、直辖市）    null  null
SELECT ADDRESS_PROVINCE FROM BSPATADDRESS GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)  Y    地址-市（地区、州）    null  null
SELECT ADDRESS_CITY FROM BSPATADDRESS GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)  Y    地址-县（区）    null  null
SELECT ADDRESS_COUNTY FROM BSPATADDRESS GROUP BY ADDRESS_COUNTY;

---ADDRESS_TOWNSHIP  VARCHAR2(70)  Y    地址-乡（镇、街道办事处）    null  null
SELECT ADDRESS_TOWNSHIP FROM BSPATADDRESS GROUP BY ADDRESS_TOWNSHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)  Y    地址-村（街、路、弄等）    null  null
SELECT ADDRESS_VILLAGE FROM BSPATADDRESS GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)  Y    地址-门牌号码    null  null
SELECT ADDRESS_DOORS FROM BSPATADDRESS GROUP BY ADDRESS_DOORS;

---ZIP_CODE  VARCHAR2(6)  Y    邮政编码    null  null
SELECT ZIP_CODE FROM BSPATADDRESS GROUP BY ZIP_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSPATADDRESS GROUP BY LAST_MODIFIC_TIME;

---ADDRESS_ID  VARCHAR2(20)      地址基本信息唯一标识    null  null
SELECT ADDRESS_ID FROM BSPATADDRESS GROUP BY ADDRESS_ID;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM BSPATADDRESS GROUP BY PATIENT_ID;

---ADDRESS_TYPE_CODE  VARCHAR2(2)  Y    地址类别代码（01-户籍住址，02-工作场所地址，03-家庭常住住址，04-通讯地址，05-暂住地址，06-出生地址，07-产后修养地址，08-变迁地址，09-现住址，99-其他地址）备注：联系人地址用其他地址标识  应符合国标：CV02.01.205  null  null
SELECT ADDRESS_TYPE_CODE FROM BSPATADDRESS GROUP BY ADDRESS_TYPE_CODE;

---ADDRESS_PROVINCE  VARCHAR2(70)  Y    地址-省（自治区、直辖市）    null  null
SELECT ADDRESS_PROVINCE FROM BSPATADDRESS GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)  Y    地址-市（地区、州）    null  null
SELECT ADDRESS_CITY FROM BSPATADDRESS GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)  Y    地址-县（区）    null  null
SELECT ADDRESS_COUNTY FROM BSPATADDRESS GROUP BY ADDRESS_COUNTY;

---ADDRESS_TOWNSHIP  VARCHAR2(70)  Y    地址-乡（镇、街道办事处）    null  null
SELECT ADDRESS_TOWNSHIP FROM BSPATADDRESS GROUP BY ADDRESS_TOWNSHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)  Y    地址-村（街、路、弄等）    null  null
SELECT ADDRESS_VILLAGE FROM BSPATADDRESS GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)  Y    地址-门牌号码    null  null
SELECT ADDRESS_DOORS FROM BSPATADDRESS GROUP BY ADDRESS_DOORS;

---ZIP_CODE  VARCHAR2(6)  Y    邮政编码    null  null
SELECT ZIP_CODE FROM BSPATADDRESS GROUP BY ZIP_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM BSPATADDRESS GROUP BY LAST_MODIFIC_TIME;

