---CN_INP_OPERATION_ID  VARCHAR2(50)      手术子表ID      
SELECT CN_INP_OPERATION_ID FROM CN_INPATIENT_OPERATION GROUP BY CN_INP_OPERATION_ID;

---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM CN_INPATIENT_OPERATION GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM CN_INPATIENT_OPERATION GROUP BY INP_NO;

---FOPTIMES  NUMBER(2)  Y    手术次数      
SELECT FOPTIMES FROM CN_INPATIENT_OPERATION GROUP BY FOPTIMES;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国标：ICD-9-CM-3  S3  AN..5
SELECT OPERATION_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_CODE;

---OPERATION_START_DATETIME  DATE  Y    手术及操作日期    DT  DT15
SELECT OPERATION_START_DATETIME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_START_DATETIME;

---OPERATION_LEVEL_CODE  VARCHAR2(1)  Y    手术级别代码  应符合国标：CV05.10.024  S3  N1
SELECT OPERATION_LEVEL_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    S1  AN..80
SELECT OPERATION_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_NAME;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术者姓名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    S1  A..50
SELECT FIRST_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    S1  A..50
SELECT SECONDE_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY SECONDE_ASSISTANT_NAME;

---OPERATION_TYPE_CODE  VARCHAR2(1)  Y    乎术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  VARCHAR2(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---ANESTHESIA_METHOD_CODE  VARCHAR2(2)  Y    麻醉方式代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT ANESTHESIA_METHOD_CODE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    麻醉医师姓名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGNATURE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_DOCTOR_SIGNATURE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CN_INPATIENT_OPERATION GROUP BY LAST_MODIFIC_TIME;

---CN_INP_OPERATION_ID  VARCHAR2(50)      手术子表ID      
SELECT CN_INP_OPERATION_ID FROM CN_INPATIENT_OPERATION GROUP BY CN_INP_OPERATION_ID;

---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM CN_INPATIENT_OPERATION GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM CN_INPATIENT_OPERATION GROUP BY INP_NO;

---FOPTIMES  NUMBER(2)  Y    手术次数      
SELECT FOPTIMES FROM CN_INPATIENT_OPERATION GROUP BY FOPTIMES;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国标：ICD-9-CM-3  S3  AN..5
SELECT OPERATION_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_CODE;

---OPERATION_START_DATETIME  DATE  Y    手术及操作日期    DT  DT15
SELECT OPERATION_START_DATETIME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_START_DATETIME;

---OPERATION_LEVEL_CODE  VARCHAR2(1)  Y    手术级别代码  应符合国标：CV05.10.024  S3  N1
SELECT OPERATION_LEVEL_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    S1  AN..80
SELECT OPERATION_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_NAME;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术者姓名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    S1  A..50
SELECT FIRST_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    S1  A..50
SELECT SECONDE_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY SECONDE_ASSISTANT_NAME;

---OPERATION_TYPE_CODE  VARCHAR2(1)  Y    乎术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  VARCHAR2(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---ANESTHESIA_METHOD_CODE  VARCHAR2(2)  Y    麻醉方式代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT ANESTHESIA_METHOD_CODE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    麻醉医师姓名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGNATURE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_DOCTOR_SIGNATURE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CN_INPATIENT_OPERATION GROUP BY LAST_MODIFIC_TIME;

---CN_INP_OPERATION_ID  VARCHAR2(50)      手术子表ID      
SELECT CN_INP_OPERATION_ID FROM CN_INPATIENT_OPERATION GROUP BY CN_INP_OPERATION_ID;

---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM CN_INPATIENT_OPERATION GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM CN_INPATIENT_OPERATION GROUP BY INP_NO;

---FOPTIMES  NUMBER(2)  Y    手术次数      
SELECT FOPTIMES FROM CN_INPATIENT_OPERATION GROUP BY FOPTIMES;

---OPERATION_CODE  VARCHAR2(20)  Y    手术及操作编码  应符合国标：ICD-9-CM-3  S3  AN..5
SELECT OPERATION_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_CODE;

---OPERATION_START_DATETIME  DATE  Y    手术及操作日期    DT  DT15
SELECT OPERATION_START_DATETIME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_START_DATETIME;

---OPERATION_LEVEL_CODE  VARCHAR2(1)  Y    手术级别代码  应符合国标：CV05.10.024  S3  N1
SELECT OPERATION_LEVEL_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_LEVEL_CODE;

---OPERATION_NAME  VARCHAR2(80)  Y    手术及操作名称    S1  AN..80
SELECT OPERATION_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_NAME;

---OPERATION_DOCTOR_NAME  VARCHAR2(50)  Y    手术者姓名    S1  A..50
SELECT OPERATION_DOCTOR_NAME FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_DOCTOR_NAME;

---FIRST_ASSISTANT_NAME  VARCHAR2(50)  Y    I助姓名    S1  A..50
SELECT FIRST_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY FIRST_ASSISTANT_NAME;

---SECONDE_ASSISTANT_NAME  VARCHAR2(50)  Y    II助姓名    S1  A..50
SELECT SECONDE_ASSISTANT_NAME FROM CN_INPATIENT_OPERATION GROUP BY SECONDE_ASSISTANT_NAME;

---OPERATION_TYPE_CODE  VARCHAR2(1)  Y    乎术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  VARCHAR2(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM CN_INPATIENT_OPERATION GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---ANESTHESIA_METHOD_CODE  VARCHAR2(2)  Y    麻醉方式代码  应符合国标：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  S3  N..2
SELECT ANESTHESIA_METHOD_CODE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_SIGNATURE  VARCHAR2(50)  Y    麻醉医师姓名    S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGNATURE FROM CN_INPATIENT_OPERATION GROUP BY ANESTHESIA_DOCTOR_SIGNATURE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM CN_INPATIENT_OPERATION GROUP BY LAST_MODIFIC_TIME;

