---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VISITS_REC_AFT_ANESTHESIA GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OPER_REQ_SN;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_AFT_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---ANAESTHESIA_RECOVERY  VARCHAR2(100)  Y    麻醉恢复情况  —    
SELECT ANAESTHESIA_RECOVERY FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANAESTHESIA_RECOVERY;

---CONSCIOUS_DATETIME  DATE  Y    淸醒日期时间  —    
SELECT CONSCIOUS_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY CONSCIOUS_DATETIME;

---TRACHEAL_INTUB_CODE  VARCHAR2(5)  Y    拔除气管插管标志  —    
SELECT TRACHEAL_INTUB_CODE FROM VISITS_REC_AFT_ANESTHESIA GROUP BY TRACHEAL_INTUB_CODE;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况  —    
SELECT SPECIAL_STATUS FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SPECIAL_STATUS;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证  —  S1  AN..100
SELECT ANESTHESIA_INDICATION FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_INDICATION;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  ―  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VISITS_REC_AFT_ANESTHESIA GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OPER_REQ_SN;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_AFT_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---ANAESTHESIA_RECOVERY  VARCHAR2(100)  Y    麻醉恢复情况  —    
SELECT ANAESTHESIA_RECOVERY FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANAESTHESIA_RECOVERY;

---CONSCIOUS_DATETIME  DATE  Y    淸醒日期时间  —    
SELECT CONSCIOUS_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY CONSCIOUS_DATETIME;

---TRACHEAL_INTUB_CODE  VARCHAR2(5)  Y    拔除气管插管标志  —    
SELECT TRACHEAL_INTUB_CODE FROM VISITS_REC_AFT_ANESTHESIA GROUP BY TRACHEAL_INTUB_CODE;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况  —    
SELECT SPECIAL_STATUS FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SPECIAL_STATUS;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证  —  S1  AN..100
SELECT ANESTHESIA_INDICATION FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_INDICATION;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  ―  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号  —  S1  AN..18
SELECT OUTP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号  —  S1  AN..18
SELECT INP_NO FROM VISITS_REC_AFT_ANESTHESIA GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM VISITS_REC_AFT_ANESTHESIA GROUP BY PATIENT_ID;

---OPER_REQ_SN  VARCHAR2(20)  Y    电子申请单编号（手术申请单编号）  —    
SELECT OPER_REQ_SN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY OPER_REQ_SN;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    一般状况检查结果  —  S1  AN..1000
SELECT GENERALHEALTH_CHECK_RESULT FROM VISITS_REC_AFT_ANESTHESIA GROUP BY GENERALHEALTH_CHECK_RESULT;

---ANAESTHESIA_RECOVERY  VARCHAR2(100)  Y    麻醉恢复情况  —    
SELECT ANAESTHESIA_RECOVERY FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANAESTHESIA_RECOVERY;

---CONSCIOUS_DATETIME  DATE  Y    淸醒日期时间  —    
SELECT CONSCIOUS_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY CONSCIOUS_DATETIME;

---TRACHEAL_INTUB_CODE  VARCHAR2(5)  Y    拔除气管插管标志  —    
SELECT TRACHEAL_INTUB_CODE FROM VISITS_REC_AFT_ANESTHESIA GROUP BY TRACHEAL_INTUB_CODE;

---SPECIAL_STATUS  VARCHAR2(1000)  Y    特殊情况  —    
SELECT SPECIAL_STATUS FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SPECIAL_STATUS;

---ANESTHESIA_INDICATION  VARCHAR2(100)  Y    麻醉适应证  —  S1  AN..100
SELECT ANESTHESIA_INDICATION FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_INDICATION;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名  —  S1  A..50
SELECT ANESTHESIA_DOCTOR_SIGN FROM VISITS_REC_AFT_ANESTHESIA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间  ―  DT  DT15
SELECT SIGN_DATETIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM VISITS_REC_AFT_ANESTHESIA GROUP BY LAST_MODIFIC_TIME;

