---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM INTAKE_OUTPUT_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INTAKE_OUTPUT_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INTAKE_OUTPUT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM INTAKE_OUTPUT_RECORD GROUP BY PATIENT_ID;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_TYPE_CODE;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DT15
SELECT CREATE_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY CREATE_DATETIME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    S1  AN..100
SELECT DRUG_USAGE FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  NUMBER(1)  Y    中药使用类别代码  应符合国标：WS 364.12—2011 表 1 CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY TCD_TYPE_CODE;

---FREQUENCY  VARCHAR2(2)  Y    药物使用频率  应符合国标：CV06.00.228  S3  AN2
SELECT FREQUENCY FROM INTAKE_OUTPUT_RECORD GROUP BY FREQUENCY;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    S1  AN..6
SELECT DOSAGE_UNIT FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_UNIT;

---SINGLE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    N  N..5,2
SELECT SINGLE_DOSAGE FROM INTAKE_OUTPUT_RECORD GROUP BY SINGLE_DOSAGE;

---DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    S1  N..12,2
SELECT DOSAGE_TOTAL FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  Y    用药途径代码  应符合国标：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  S3  N..3
SELECT ROUTE_ADMINISTRATION FROM INTAKE_OUTPUT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---DRUG_NAME  VARCHAR2(50)  Y    药物名称    S1  AN..50
SELECT DRUG_NAME FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_NAME;

---EMESIS_FLAG  VARCHAR2(5)  Y    呕吐标志  TRUE/FALSE  L  T/F
SELECT EMESIS_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY EMESIS_FLAG;

---DYSURIA_FLAG  VARCHAR2(5)  Y    排尿困难标志  TRUE/FALSE  L  T/F
SELECT DYSURIA_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY DYSURIA_FLAG;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM INTAKE_OUTPUT_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM INTAKE_OUTPUT_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INTAKE_OUTPUT_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM INTAKE_OUTPUT_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INTAKE_OUTPUT_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INTAKE_OUTPUT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM INTAKE_OUTPUT_RECORD GROUP BY PATIENT_ID;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_TYPE_CODE;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DT15
SELECT CREATE_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY CREATE_DATETIME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    S1  AN..100
SELECT DRUG_USAGE FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  NUMBER(1)  Y    中药使用类别代码  应符合国标：WS 364.12—2011 表 1 CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY TCD_TYPE_CODE;

---FREQUENCY  VARCHAR2(2)  Y    药物使用频率  应符合国标：CV06.00.228  S3  AN2
SELECT FREQUENCY FROM INTAKE_OUTPUT_RECORD GROUP BY FREQUENCY;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    S1  AN..6
SELECT DOSAGE_UNIT FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_UNIT;

---SINGLE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    N  N..5,2
SELECT SINGLE_DOSAGE FROM INTAKE_OUTPUT_RECORD GROUP BY SINGLE_DOSAGE;

---DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    S1  N..12,2
SELECT DOSAGE_TOTAL FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  Y    用药途径代码  应符合国标：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  S3  N..3
SELECT ROUTE_ADMINISTRATION FROM INTAKE_OUTPUT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---DRUG_NAME  VARCHAR2(50)  Y    药物名称    S1  AN..50
SELECT DRUG_NAME FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_NAME;

---EMESIS_FLAG  VARCHAR2(5)  Y    呕吐标志  TRUE/FALSE  L  T/F
SELECT EMESIS_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY EMESIS_FLAG;

---DYSURIA_FLAG  VARCHAR2(5)  Y    排尿困难标志  TRUE/FALSE  L  T/F
SELECT DYSURIA_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY DYSURIA_FLAG;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM INTAKE_OUTPUT_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM INTAKE_OUTPUT_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INTAKE_OUTPUT_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM INTAKE_OUTPUT_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM INTAKE_OUTPUT_RECORD GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM INTAKE_OUTPUT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM INTAKE_OUTPUT_RECORD GROUP BY PATIENT_ID;

---NURSING_GRADE_CODE  VARCHAR2(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  VARCHAR2(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY NURSING_TYPE_CODE;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DT15
SELECT CREATE_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY CREATE_DATETIME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    S1  AN..100
SELECT DRUG_USAGE FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  NUMBER(1)  Y    中药使用类别代码  应符合国标：WS 364.12—2011 表 1 CV06.00.101中药使用类别代码表  S3  N1
SELECT TCD_TYPE_CODE FROM INTAKE_OUTPUT_RECORD GROUP BY TCD_TYPE_CODE;

---FREQUENCY  VARCHAR2(2)  Y    药物使用频率  应符合国标：CV06.00.228  S3  AN2
SELECT FREQUENCY FROM INTAKE_OUTPUT_RECORD GROUP BY FREQUENCY;

---DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    S1  AN..6
SELECT DOSAGE_UNIT FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_UNIT;

---SINGLE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    N  N..5,2
SELECT SINGLE_DOSAGE FROM INTAKE_OUTPUT_RECORD GROUP BY SINGLE_DOSAGE;

---DOSAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    S1  N..12,2
SELECT DOSAGE_TOTAL FROM INTAKE_OUTPUT_RECORD GROUP BY DOSAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  Y    用药途径代码  应符合国标：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  S3  N..3
SELECT ROUTE_ADMINISTRATION FROM INTAKE_OUTPUT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---DRUG_NAME  VARCHAR2(50)  Y    药物名称    S1  AN..50
SELECT DRUG_NAME FROM INTAKE_OUTPUT_RECORD GROUP BY DRUG_NAME;

---EMESIS_FLAG  VARCHAR2(5)  Y    呕吐标志  TRUE/FALSE  L  T/F
SELECT EMESIS_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY EMESIS_FLAG;

---DYSURIA_FLAG  VARCHAR2(5)  Y    排尿困难标志  TRUE/FALSE  L  T/F
SELECT DYSURIA_FLAG FROM INTAKE_OUTPUT_RECORD GROUP BY DYSURIA_FLAG;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM INTAKE_OUTPUT_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM INTAKE_OUTPUT_RECORD GROUP BY SIGN_DATETIME;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM INTAKE_OUTPUT_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INTAKE_OUTPUT_RECORD GROUP BY LAST_MODIFIC_TIME;

