---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM WORSE_PATIENT_CARE_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY DOC_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    N  N2..3
SELECT CARDIOTACH FROM WORSE_PATIENT_CARE_RECORD GROUP BY CARDIOTACH;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM WORSE_PATIENT_CARE_RECORD GROUP BY BREATH_FREQUENCY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIASTOLIC_PRESSURE;

---BLOOD_GLUCOSE_VALUE  NUMBER(4,1)  Y    血糖检测值（mmol/L)    N  N3..4.l
SELECT BLOOD_GLUCOSE_VALUE FROM WORSE_PATIENT_CARE_RECORD GROUP BY BLOOD_GLUCOSE_VALUE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好 2.—般 3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIETARY_STATUS_CODE;

---RESPIRATOR_MONITORING_ITEM  VARCHAR2(20)  Y    呼吸机监护项目    S1  AN..20
SELECT RESPIRATOR_MONITORING_ITEM FROM WORSE_PATIENT_CARE_RECORD GROUP BY RESPIRATOR_MONITORING_ITEM;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY SIGN_DATETIME;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志      
SELECT ALLERGY_HISTORY_FLAG FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM WORSE_PATIENT_CARE_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY DOC_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    N  N2..3
SELECT CARDIOTACH FROM WORSE_PATIENT_CARE_RECORD GROUP BY CARDIOTACH;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM WORSE_PATIENT_CARE_RECORD GROUP BY BREATH_FREQUENCY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIASTOLIC_PRESSURE;

---BLOOD_GLUCOSE_VALUE  NUMBER(4,1)  Y    血糖检测值（mmol/L)    N  N3..4.l
SELECT BLOOD_GLUCOSE_VALUE FROM WORSE_PATIENT_CARE_RECORD GROUP BY BLOOD_GLUCOSE_VALUE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好 2.—般 3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIETARY_STATUS_CODE;

---RESPIRATOR_MONITORING_ITEM  VARCHAR2(20)  Y    呼吸机监护项目    S1  AN..20
SELECT RESPIRATOR_MONITORING_ITEM FROM WORSE_PATIENT_CARE_RECORD GROUP BY RESPIRATOR_MONITORING_ITEM;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY SIGN_DATETIME;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志      
SELECT ALLERGY_HISTORY_FLAG FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM WORSE_PATIENT_CARE_RECORD GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY PATIENT_ID;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM WORSE_PATIENT_CARE_RECORD GROUP BY DOC_NO;

---NURSING_GRADE_CODE  NUMBER(1)  Y    护理等级代码  应符合国标：CV06.00.220  S3  N1
SELECT NURSING_GRADE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_GRADE_CODE;

---NURSING_TYPE_CODE  NUMBER(1)  Y    护理类型代码  应符合国标：CV06.00.221  S3  N1
SELECT NURSING_TYPE_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSING_TYPE_CODE;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    S1  AN..1000
SELECT ALLERGY_HISTORY FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    N  N4，l
SELECT TEMPERATURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    N  N2..3
SELECT CARDIOTACH FROM WORSE_PATIENT_CARE_RECORD GROUP BY CARDIOTACH;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    N  N..3
SELECT BREATH_FREQUENCY FROM WORSE_PATIENT_CARE_RECORD GROUP BY BREATH_FREQUENCY;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    N  N2..3
SELECT SYSTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    N  N2..3
SELECT DIASTOLIC_PRESSURE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIASTOLIC_PRESSURE;

---BLOOD_GLUCOSE_VALUE  NUMBER(4,1)  Y    血糖检测值（mmol/L)    N  N3..4.l
SELECT BLOOD_GLUCOSE_VALUE FROM WORSE_PATIENT_CARE_RECORD GROUP BY BLOOD_GLUCOSE_VALUE;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好 2.—般 3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM WORSE_PATIENT_CARE_RECORD GROUP BY DIETARY_STATUS_CODE;

---RESPIRATOR_MONITORING_ITEM  VARCHAR2(20)  Y    呼吸机监护项目    S1  AN..20
SELECT RESPIRATOR_MONITORING_ITEM FROM WORSE_PATIENT_CARE_RECORD GROUP BY RESPIRATOR_MONITORING_ITEM;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM WORSE_PATIENT_CARE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY SIGN_DATETIME;

---ALLERGY_HISTORY_FLAG  VARCHAR2(5)  Y    过敏史标志      
SELECT ALLERGY_HISTORY_FLAG FROM WORSE_PATIENT_CARE_RECORD GROUP BY ALLERGY_HISTORY_FLAG;

---GENERAL_NURSING_ID  VARCHAR2(18)  Y    护理记录唯一标识      
SELECT GENERAL_NURSING_ID FROM WORSE_PATIENT_CARE_RECORD GROUP BY GENERAL_NURSING_ID;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM WORSE_PATIENT_CARE_RECORD GROUP BY LAST_MODIFIC_TIME;

