---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)      门（急）诊号  -  null  AN..18
SELECT OUTP_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PATIENT_ID;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  -  null  AN" 1000
SELECT ALLERGY_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉  ―  null  AN..100
SELECT CHIEF_COMPLAINT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史  ―  null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史  ―  null  AN..1000
SELECT PAST_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查  —  null  AN..500
SELECT PHYSICAL_EXAMINATION FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果  —  null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检查项目  —  null  AN..100
SELECT AUXILIARYEXAMI_ITEM FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果  —  null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据  —  null  AN..100
SELECT DIALECTICAL_ACCROD FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  null  AN.. 20
SELECT APPLY_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY APPLY_NO;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名  —  null  A..50
SELECT DOCTOR_SIGN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)      门（急）诊号  -  null  AN..18
SELECT OUTP_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PATIENT_ID;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  -  null  AN" 1000
SELECT ALLERGY_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉  ―  null  AN..100
SELECT CHIEF_COMPLAINT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史  ―  null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史  ―  null  AN..1000
SELECT PAST_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查  —  null  AN..500
SELECT PHYSICAL_EXAMINATION FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果  —  null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检查项目  —  null  AN..100
SELECT AUXILIARYEXAMI_ITEM FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果  —  null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据  —  null  AN..100
SELECT DIALECTICAL_ACCROD FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  null  AN.. 20
SELECT APPLY_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY APPLY_NO;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名  —  null  A..50
SELECT DOCTOR_SIGN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号    null  
SELECT OUTPATIENT_SN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号    null  
SELECT DOC_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOC_NO;

---OUTP_NO  VARCHAR2(18)      门（急）诊号  -  null  AN..18
SELECT OUTP_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY OUTP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID    null  
SELECT PATIENT_ID FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PATIENT_ID;

---ALLERGY_HOSTORY_FLAG  VARCHAR2(5)  Y    过敏史标志  TRUE/FALSE  null  T/F
SELECT ALLERGY_HOSTORY_FLAG FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HOSTORY_FLAG;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史  -  null  AN" 1000
SELECT ALLERGY_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY ALLERGY_HISTORY;

---NEWLY_DIAGNOSED_CODE  VARCHAR2(1)  Y    初诊标志代码  1.初诊2.复诊  null  N1
SELECT NEWLY_DIAGNOSED_CODE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY NEWLY_DIAGNOSED_CODE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉  ―  null  AN..100
SELECT CHIEF_COMPLAINT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史  ―  null  AN..2000
SELECT PRESENT_DISEASE_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PRESENT_DISEASE_HISTORY;

---PAST_HISTORY  VARCHAR2(1000)  Y    既往史  ―  null  AN..1000
SELECT PAST_HISTORY FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PAST_HISTORY;

---PHYSICAL_EXAMINATION  VARCHAR2(500)  Y    体格检查  —  null  AN..500
SELECT PHYSICAL_EXAMINATION FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY PHYSICAL_EXAMINATION;

---TCM_FOUR_OBSERVATIONS  VARCHAR2(1000)  Y    中医“四诊”观察结果  —  null  AN..1000
SELECT TCM_FOUR_OBSERVATIONS FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY TCM_FOUR_OBSERVATIONS;

---AUXILIARYEXAMI_ITEM  VARCHAR2(100)  Y    辅助检查项目  —  null  AN..100
SELECT AUXILIARYEXAMI_ITEM FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_ITEM;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果  —  null  AN..1000
SELECT AUXILIARYEXAMI_RESULT FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY AUXILIARYEXAMI_RESULT;

---DIALECTICAL_ACCROD  VARCHAR2(100)  Y    辨证依据  —  null  AN..100
SELECT DIALECTICAL_ACCROD FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DIALECTICAL_ACCROD;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  null  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY THERAPEUTIC_PRINCIPLE;

---APPLY_NO  VARCHAR2(20)  Y    电子申请单编号  —  null  AN.. 20
SELECT APPLY_NO FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY APPLY_NO;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名  —  null  A..50
SELECT DOCTOR_SIGN FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y        null  
SELECT LAST_MODIFIC_TIME FROM OUTPATIENT_EMERGENCY_RECORDS GROUP BY LAST_MODIFIC_TIME;

