---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PHASE_SUMMARY GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PHASE_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PHASE_SUMMARY GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PHASE_SUMMARY GROUP BY INP_NO;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PHASE_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM PHASE_SUMMARY GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM PHASE_SUMMARY GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM PHASE_SUMMARY GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PHASE_SUMMARY GROUP BY THERAPEUTIC_PRINCIPLE;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DRINK_DECWAY;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM PHASE_SUMMARY GROUP BY ADVICE_CONTENT;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM PHASE_SUMMARY GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM PHASE_SUMMARY GROUP BY CURRENTLY_SITUATION;

---NEXT_TREATMENT_PLAN  VARCHAR2(1000)  Y    今后治疗方案    S1  AN..1000
SELECT NEXT_TREATMENT_PLAN FROM PHASE_SUMMARY GROUP BY NEXT_TREATMENT_PLAN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PHASE_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PHASE_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PHASE_SUMMARY GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PHASE_SUMMARY GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PHASE_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PHASE_SUMMARY GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PHASE_SUMMARY GROUP BY INP_NO;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PHASE_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM PHASE_SUMMARY GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM PHASE_SUMMARY GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM PHASE_SUMMARY GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PHASE_SUMMARY GROUP BY THERAPEUTIC_PRINCIPLE;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DRINK_DECWAY;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM PHASE_SUMMARY GROUP BY ADVICE_CONTENT;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM PHASE_SUMMARY GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM PHASE_SUMMARY GROUP BY CURRENTLY_SITUATION;

---NEXT_TREATMENT_PLAN  VARCHAR2(1000)  Y    今后治疗方案    S1  AN..1000
SELECT NEXT_TREATMENT_PLAN FROM PHASE_SUMMARY GROUP BY NEXT_TREATMENT_PLAN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PHASE_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PHASE_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PHASE_SUMMARY GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PHASE_SUMMARY GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PHASE_SUMMARY GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PHASE_SUMMARY GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PHASE_SUMMARY GROUP BY INP_NO;

---STAGE_SUMMARY_DATATIME  DATE  Y    小结日期时间    DT  DT15
SELECT STAGE_SUMMARY_DATATIME FROM PHASE_SUMMARY GROUP BY STAGE_SUMMARY_DATATIME;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉    S1  AN..100
SELECT CHIEF_COMPLAINT FROM PHASE_SUMMARY GROUP BY CHIEF_COMPLAINT;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM PHASE_SUMMARY GROUP BY INP_SITUATION;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM PHASE_SUMMARY GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PHASE_SUMMARY GROUP BY THERAPEUTIC_PRINCIPLE;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM PHASE_SUMMARY GROUP BY CHIN_DRINK_DECWAY;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM PHASE_SUMMARY GROUP BY ADVICE_CONTENT;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM PHASE_SUMMARY GROUP BY DIAG_DESC;

---CURRENTLY_SITUATION  VARCHAR2(2000)  Y    目前情况    S1  AN..2000
SELECT CURRENTLY_SITUATION FROM PHASE_SUMMARY GROUP BY CURRENTLY_SITUATION;

---NEXT_TREATMENT_PLAN  VARCHAR2(1000)  Y    今后治疗方案    S1  AN..1000
SELECT NEXT_TREATMENT_PLAN FROM PHASE_SUMMARY GROUP BY NEXT_TREATMENT_PLAN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PHASE_SUMMARY GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PHASE_SUMMARY GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PHASE_SUMMARY GROUP BY LAST_MODIFIC_TIME;

