---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DAILY_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DAILY_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DAILY_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DAILY_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE      记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM DAILY_COURSE_RECORD GROUP BY RECORD_DATATIME;

---INP_COURSE  VARCHAR2(2000)  Y    住院病程    S1  AN..2000
SELECT INP_COURSE FROM DAILY_COURSE_RECORD GROUP BY INP_COURSE;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM DAILY_COURSE_RECORD GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DAILY_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM DAILY_COURSE_RECORD GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DAILY_COURSE_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)      医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM DAILY_COURSE_RECORD GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DAILY_COURSE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DAILY_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DAILY_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DAILY_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DAILY_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DAILY_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE      记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM DAILY_COURSE_RECORD GROUP BY RECORD_DATATIME;

---INP_COURSE  VARCHAR2(2000)  Y    住院病程    S1  AN..2000
SELECT INP_COURSE FROM DAILY_COURSE_RECORD GROUP BY INP_COURSE;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM DAILY_COURSE_RECORD GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DAILY_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM DAILY_COURSE_RECORD GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DAILY_COURSE_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)      医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM DAILY_COURSE_RECORD GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DAILY_COURSE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DAILY_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DAILY_COURSE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DAILY_COURSE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DAILY_COURSE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DAILY_COURSE_RECORD GROUP BY INP_NO;

---RECORD_DATATIME  DATE      记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM DAILY_COURSE_RECORD GROUP BY RECORD_DATATIME;

---INP_COURSE  VARCHAR2(2000)  Y    住院病程    S1  AN..2000
SELECT INP_COURSE FROM DAILY_COURSE_RECORD GROUP BY INP_COURSE;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM DAILY_COURSE_RECORD GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DAILY_COURSE_RECORD GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM DAILY_COURSE_RECORD GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DAILY_COURSE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM DAILY_COURSE_RECORD GROUP BY PROFESSIONAL_CATAGORY_CODE;

---DOCTOR_SIGN  VARCHAR2(50)      医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM DAILY_COURSE_RECORD GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DAILY_COURSE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DAILY_COURSE_RECORD GROUP BY LAST_MODIFIC_TIME;

