---OUTPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT OUTPATIENT_SN FROM TREATMENT_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT INPATIENT_SN FROM TREATMENT_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)  null  null  null  null  null  null
SELECT DOC_NO FROM TREATMENT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  null  null  null  null  null  null
SELECT PATIENT_ID FROM TREATMENT_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT OUTP_NO FROM TREATMENT_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT INP_NO FROM TREATMENT_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  null    null  null  null  null
SELECT ELECTRONIC_APPLY_NO FROM TREATMENT_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---DISPOSE_OPINION  VARCHAR2(2000)  null    null  null  null  null
SELECT DISPOSE_OPINION FROM TREATMENT_RECORD GROUP BY DISPOSE_OPINION;

---INCASIVE_OPERTOR_CODE  VARCHAR2(5)  null    null  null  null  null
SELECT INCASIVE_OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY INCASIVE_OPERTOR_CODE;

---ALLERGY_HISTORY_TYPE  VARCHAR2(5)  null    null  null  null  null
SELECT ALLERGY_HISTORY_TYPE FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY_TYPE;

---ALLERGY_HISTORY  VARCHAR2(1000)  null    null  null  null  null
SELECT ALLERGY_HISTORY FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY;

---ADVICE_REMAKR  VARCHAR2(100)  null    null  null  null  null
SELECT ADVICE_REMAKR FROM TREATMENT_RECORD GROUP BY ADVICE_REMAKR;

---AFTER_TREAT_PLAN  VARCHAR2(1000)  null    null  null  null  null
SELECT AFTER_TREAT_PLAN FROM TREATMENT_RECORD GROUP BY AFTER_TREAT_PLAN;

---VISIT_WAY_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT VISIT_WAY_CODE FROM TREATMENT_RECORD GROUP BY VISIT_WAY_CODE;

---FOLLOWUP_DATE  DATE  null    null  null  null  null
SELECT FOLLOWUP_DATE FROM TREATMENT_RECORD GROUP BY FOLLOWUP_DATE;

---VISIT_PERIODIC_PROPOSAL_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT VISIT_PERIODIC_PROPOSAL_CODE FROM TREATMENT_RECORD GROUP BY VISIT_PERIODIC_PROPOSAL_CODE;

---ADVICE_EXEC_SIGN  VARCHAR2(50)  null    null  null  null  null
SELECT ADVICE_EXEC_SIGN FROM TREATMENT_RECORD GROUP BY ADVICE_EXEC_SIGN;

---SIGN_DATETIME  DATE  null    null  null  null  null
SELECT SIGN_DATETIME FROM TREATMENT_RECORD GROUP BY SIGN_DATETIME;

---DRUG_NAME  VARCHAR2(50)  null    null  null  null  null
SELECT DRUG_NAME FROM TREATMENT_RECORD GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  null    null  null  null  null
SELECT DRUG_USAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT TCD_TYPE_CODE FROM TREATMENT_RECORD GROUP BY TCD_TYPE_CODE;

---DRUG_USAGE_FRE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_USAGE_FRE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_DOSAGE_CODE FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  null    null  null  null  null
SELECT DRUG_DOSAGE_UNIT FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  null    null  null  null  null
SELECT DRUG_USAGE_DOSAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  null    null  null  null  null
SELECT DRUG_USAGE_TOTAL FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  null    null  null  null  null
SELECT ROUTE_ADMINISTRATION FROM TREATMENT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---OPERTOR_CODE  VARCHAR2(20)  null    null  null  null  null
SELECT OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY OPERTOR_CODE;

---OPTERTOR_NAME  VARCHAR2(80)  null    null  null  null  null
SELECT OPTERTOR_NAME FROM TREATMENT_RECORD GROUP BY OPTERTOR_NAME;

---OPERTOR_TARGET  VARCHAR2(50)  null    null  null  null  null
SELECT OPERTOR_TARGET FROM TREATMENT_RECORD GROUP BY OPERTOR_TARGET;

---INTER_NAME  VARCHAR2(100)  null    null  null  null  null
SELECT INTER_NAME FROM TREATMENT_RECORD GROUP BY INTER_NAME;

---OPERATOR_DESC  VARCHAR2(2000)  null    null  null  null  null
SELECT OPERATOR_DESC FROM TREATMENT_RECORD GROUP BY OPERATOR_DESC;

---OPERATOR_NUM  NUMBER(3)  null    null  null  null  null
SELECT OPERATOR_NUM FROM TREATMENT_RECORD GROUP BY OPERATOR_NUM;

---OPERATOR_DATE  DATE  null    null  null  null  null
SELECT OPERATOR_DATE FROM TREATMENT_RECORD GROUP BY OPERATOR_DATE;

---LAST_MODIFIC_TIME  DATE  null    null  null  null  null
SELECT LAST_MODIFIC_TIME FROM TREATMENT_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT OUTPATIENT_SN FROM TREATMENT_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT INPATIENT_SN FROM TREATMENT_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)  null  null  null  null  null  null
SELECT DOC_NO FROM TREATMENT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  null  null  null  null  null  null
SELECT PATIENT_ID FROM TREATMENT_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT OUTP_NO FROM TREATMENT_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT INP_NO FROM TREATMENT_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  null    null  null  null  null
SELECT ELECTRONIC_APPLY_NO FROM TREATMENT_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---DISPOSE_OPINION  VARCHAR2(2000)  null    null  null  null  null
SELECT DISPOSE_OPINION FROM TREATMENT_RECORD GROUP BY DISPOSE_OPINION;

---INCASIVE_OPERTOR_CODE  VARCHAR2(5)  null    null  null  null  null
SELECT INCASIVE_OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY INCASIVE_OPERTOR_CODE;

---ALLERGY_HISTORY_TYPE  VARCHAR2(5)  null    null  null  null  null
SELECT ALLERGY_HISTORY_TYPE FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY_TYPE;

---ALLERGY_HISTORY  VARCHAR2(1000)  null    null  null  null  null
SELECT ALLERGY_HISTORY FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY;

---ADVICE_REMAKR  VARCHAR2(100)  null    null  null  null  null
SELECT ADVICE_REMAKR FROM TREATMENT_RECORD GROUP BY ADVICE_REMAKR;

---AFTER_TREAT_PLAN  VARCHAR2(1000)  null    null  null  null  null
SELECT AFTER_TREAT_PLAN FROM TREATMENT_RECORD GROUP BY AFTER_TREAT_PLAN;

---VISIT_WAY_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT VISIT_WAY_CODE FROM TREATMENT_RECORD GROUP BY VISIT_WAY_CODE;

---FOLLOWUP_DATE  DATE  null    null  null  null  null
SELECT FOLLOWUP_DATE FROM TREATMENT_RECORD GROUP BY FOLLOWUP_DATE;

---VISIT_PERIODIC_PROPOSAL_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT VISIT_PERIODIC_PROPOSAL_CODE FROM TREATMENT_RECORD GROUP BY VISIT_PERIODIC_PROPOSAL_CODE;

---ADVICE_EXEC_SIGN  VARCHAR2(50)  null    null  null  null  null
SELECT ADVICE_EXEC_SIGN FROM TREATMENT_RECORD GROUP BY ADVICE_EXEC_SIGN;

---SIGN_DATETIME  DATE  null    null  null  null  null
SELECT SIGN_DATETIME FROM TREATMENT_RECORD GROUP BY SIGN_DATETIME;

---DRUG_NAME  VARCHAR2(50)  null    null  null  null  null
SELECT DRUG_NAME FROM TREATMENT_RECORD GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  null    null  null  null  null
SELECT DRUG_USAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT TCD_TYPE_CODE FROM TREATMENT_RECORD GROUP BY TCD_TYPE_CODE;

---DRUG_USAGE_FRE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_USAGE_FRE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_DOSAGE_CODE FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  null    null  null  null  null
SELECT DRUG_DOSAGE_UNIT FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  null    null  null  null  null
SELECT DRUG_USAGE_DOSAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  null    null  null  null  null
SELECT DRUG_USAGE_TOTAL FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  null    null  null  null  null
SELECT ROUTE_ADMINISTRATION FROM TREATMENT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---OPERTOR_CODE  VARCHAR2(20)  null    null  null  null  null
SELECT OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY OPERTOR_CODE;

---OPTERTOR_NAME  VARCHAR2(80)  null    null  null  null  null
SELECT OPTERTOR_NAME FROM TREATMENT_RECORD GROUP BY OPTERTOR_NAME;

---OPERTOR_TARGET  VARCHAR2(50)  null    null  null  null  null
SELECT OPERTOR_TARGET FROM TREATMENT_RECORD GROUP BY OPERTOR_TARGET;

---INTER_NAME  VARCHAR2(100)  null    null  null  null  null
SELECT INTER_NAME FROM TREATMENT_RECORD GROUP BY INTER_NAME;

---OPERATOR_DESC  VARCHAR2(2000)  null    null  null  null  null
SELECT OPERATOR_DESC FROM TREATMENT_RECORD GROUP BY OPERATOR_DESC;

---OPERATOR_NUM  NUMBER(3)  null    null  null  null  null
SELECT OPERATOR_NUM FROM TREATMENT_RECORD GROUP BY OPERATOR_NUM;

---OPERATOR_DATE  DATE  null    null  null  null  null
SELECT OPERATOR_DATE FROM TREATMENT_RECORD GROUP BY OPERATOR_DATE;

---LAST_MODIFIC_TIME  DATE  null    null  null  null  null
SELECT LAST_MODIFIC_TIME FROM TREATMENT_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT OUTPATIENT_SN FROM TREATMENT_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  null    null  null  null  null
SELECT INPATIENT_SN FROM TREATMENT_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)  null  null  null  null  null  null
SELECT DOC_NO FROM TREATMENT_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)  null  null  null  null  null  null
SELECT PATIENT_ID FROM TREATMENT_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT OUTP_NO FROM TREATMENT_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  null    null  null  null  null
SELECT INP_NO FROM TREATMENT_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  null    null  null  null  null
SELECT ELECTRONIC_APPLY_NO FROM TREATMENT_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---DISPOSE_OPINION  VARCHAR2(2000)  null    null  null  null  null
SELECT DISPOSE_OPINION FROM TREATMENT_RECORD GROUP BY DISPOSE_OPINION;

---INCASIVE_OPERTOR_CODE  VARCHAR2(5)  null    null  null  null  null
SELECT INCASIVE_OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY INCASIVE_OPERTOR_CODE;

---ALLERGY_HISTORY_TYPE  VARCHAR2(5)  null    null  null  null  null
SELECT ALLERGY_HISTORY_TYPE FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY_TYPE;

---ALLERGY_HISTORY  VARCHAR2(1000)  null    null  null  null  null
SELECT ALLERGY_HISTORY FROM TREATMENT_RECORD GROUP BY ALLERGY_HISTORY;

---ADVICE_REMAKR  VARCHAR2(100)  null    null  null  null  null
SELECT ADVICE_REMAKR FROM TREATMENT_RECORD GROUP BY ADVICE_REMAKR;

---AFTER_TREAT_PLAN  VARCHAR2(1000)  null    null  null  null  null
SELECT AFTER_TREAT_PLAN FROM TREATMENT_RECORD GROUP BY AFTER_TREAT_PLAN;

---VISIT_WAY_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT VISIT_WAY_CODE FROM TREATMENT_RECORD GROUP BY VISIT_WAY_CODE;

---FOLLOWUP_DATE  DATE  null    null  null  null  null
SELECT FOLLOWUP_DATE FROM TREATMENT_RECORD GROUP BY FOLLOWUP_DATE;

---VISIT_PERIODIC_PROPOSAL_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT VISIT_PERIODIC_PROPOSAL_CODE FROM TREATMENT_RECORD GROUP BY VISIT_PERIODIC_PROPOSAL_CODE;

---ADVICE_EXEC_SIGN  VARCHAR2(50)  null    null  null  null  null
SELECT ADVICE_EXEC_SIGN FROM TREATMENT_RECORD GROUP BY ADVICE_EXEC_SIGN;

---SIGN_DATETIME  DATE  null    null  null  null  null
SELECT SIGN_DATETIME FROM TREATMENT_RECORD GROUP BY SIGN_DATETIME;

---DRUG_NAME  VARCHAR2(50)  null    null  null  null  null
SELECT DRUG_NAME FROM TREATMENT_RECORD GROUP BY DRUG_NAME;

---DRUG_USAGE  VARCHAR2(100)  null    null  null  null  null
SELECT DRUG_USAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE;

---TCD_TYPE_CODE  VARCHAR2(1)  null    null  null  null  null
SELECT TCD_TYPE_CODE FROM TREATMENT_RECORD GROUP BY TCD_TYPE_CODE;

---DRUG_USAGE_FRE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_USAGE_FRE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_CODE  VARCHAR2(2)  null    null  null  null  null
SELECT DRUG_DOSAGE_CODE FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_CODE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  null    null  null  null  null
SELECT DRUG_DOSAGE_UNIT FROM TREATMENT_RECORD GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  null    null  null  null  null
SELECT DRUG_USAGE_DOSAGE FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  null    null  null  null  null
SELECT DRUG_USAGE_TOTAL FROM TREATMENT_RECORD GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  VARCHAR2(3)  null    null  null  null  null
SELECT ROUTE_ADMINISTRATION FROM TREATMENT_RECORD GROUP BY ROUTE_ADMINISTRATION;

---OPERTOR_CODE  VARCHAR2(20)  null    null  null  null  null
SELECT OPERTOR_CODE FROM TREATMENT_RECORD GROUP BY OPERTOR_CODE;

---OPTERTOR_NAME  VARCHAR2(80)  null    null  null  null  null
SELECT OPTERTOR_NAME FROM TREATMENT_RECORD GROUP BY OPTERTOR_NAME;

---OPERTOR_TARGET  VARCHAR2(50)  null    null  null  null  null
SELECT OPERTOR_TARGET FROM TREATMENT_RECORD GROUP BY OPERTOR_TARGET;

---INTER_NAME  VARCHAR2(100)  null    null  null  null  null
SELECT INTER_NAME FROM TREATMENT_RECORD GROUP BY INTER_NAME;

---OPERATOR_DESC  VARCHAR2(2000)  null    null  null  null  null
SELECT OPERATOR_DESC FROM TREATMENT_RECORD GROUP BY OPERATOR_DESC;

---OPERATOR_NUM  NUMBER(3)  null    null  null  null  null
SELECT OPERATOR_NUM FROM TREATMENT_RECORD GROUP BY OPERATOR_NUM;

---OPERATOR_DATE  DATE  null    null  null  null  null
SELECT OPERATOR_DATE FROM TREATMENT_RECORD GROUP BY OPERATOR_DATE;

---LAST_MODIFIC_TIME  DATE  null    null  null  null  null
SELECT LAST_MODIFIC_TIME FROM TREATMENT_RECORD GROUP BY LAST_MODIFIC_TIME;

