---ORGAN_NAME  VARCHAR2(70)      医疗机构名称    null  null
SELECT ORGAN_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_NAME;

---ORGAN_CODE  VARCHAR2(10)      医疗机构组织结构代码    null  null
SELECT ORGAN_CODE FROM HOSPITAL_INFO GROUP BY ORGAN_CODE;

---ORGAN_NUMBER  VARCHAR2(20)      医疗机构联系电话    null  null
SELECT ORGAN_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_NUMBER;

---ORGAN_HEAD_NAME  VARCHAR2(50)      医疗机构负责人（法人）姓名    null  null
SELECT ORGAN_HEAD_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NAME;

---ORGAN_HEAD_NUMBER  VARCHAR2(20)      医疗机构负责人联系电话    null  null
SELECT ORGAN_HEAD_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NUMBER;

---ADDRESS_PROVINCE  VARCHAR2(70)      医疗机构地址中的省、自治区或直辖市名称    null  null
SELECT ADDRESS_PROVINCE FROM HOSPITAL_INFO GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)      医疗机构地址中的市、地区或州的名称    null  null
SELECT ADDRESS_CITY FROM HOSPITAL_INFO GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)      医疗机构地址中的县（区）的名称    null  null
SELECT ADDRESS_COUNTY FROM HOSPITAL_INFO GROUP BY ADDRESS_COUNTY;

---TOWN_SHIP  VARCHAR2(70)      医疗机构地址中的乡、镇或城市的街道办事处名称    null  null
SELECT TOWN_SHIP FROM HOSPITAL_INFO GROUP BY TOWN_SHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)      医疗机构地址中的村或城市的街、路、里、弄等名称    null  null
SELECT ADDRESS_VILLAGE FROM HOSPITAL_INFO GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)      医疗机构地址中的门牌号码    null  null
SELECT ADDRESS_DOORS FROM HOSPITAL_INFO GROUP BY ADDRESS_DOORS;

---POST_CODE  NUMBER(6)      由阿拉伯数字组成，用来表示与医疗机构地址对应的邮局及其投递区域的邮政通信代号    null  null
SELECT POST_CODE FROM HOSPITAL_INFO GROUP BY POST_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM HOSPITAL_INFO GROUP BY LAST_MODIFIC_TIME;

---ORGAN_NAME  VARCHAR2(70)      医疗机构名称    null  null
SELECT ORGAN_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_NAME;

---ORGAN_CODE  VARCHAR2(10)      医疗机构组织结构代码    null  null
SELECT ORGAN_CODE FROM HOSPITAL_INFO GROUP BY ORGAN_CODE;

---ORGAN_NUMBER  VARCHAR2(20)      医疗机构联系电话    null  null
SELECT ORGAN_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_NUMBER;

---ORGAN_HEAD_NAME  VARCHAR2(50)      医疗机构负责人（法人）姓名    null  null
SELECT ORGAN_HEAD_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NAME;

---ORGAN_HEAD_NUMBER  VARCHAR2(20)      医疗机构负责人联系电话    null  null
SELECT ORGAN_HEAD_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NUMBER;

---ADDRESS_PROVINCE  VARCHAR2(70)      医疗机构地址中的省、自治区或直辖市名称    null  null
SELECT ADDRESS_PROVINCE FROM HOSPITAL_INFO GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)      医疗机构地址中的市、地区或州的名称    null  null
SELECT ADDRESS_CITY FROM HOSPITAL_INFO GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)      医疗机构地址中的县（区）的名称    null  null
SELECT ADDRESS_COUNTY FROM HOSPITAL_INFO GROUP BY ADDRESS_COUNTY;

---TOWN_SHIP  VARCHAR2(70)      医疗机构地址中的乡、镇或城市的街道办事处名称    null  null
SELECT TOWN_SHIP FROM HOSPITAL_INFO GROUP BY TOWN_SHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)      医疗机构地址中的村或城市的街、路、里、弄等名称    null  null
SELECT ADDRESS_VILLAGE FROM HOSPITAL_INFO GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)      医疗机构地址中的门牌号码    null  null
SELECT ADDRESS_DOORS FROM HOSPITAL_INFO GROUP BY ADDRESS_DOORS;

---POST_CODE  NUMBER(6)      由阿拉伯数字组成，用来表示与医疗机构地址对应的邮局及其投递区域的邮政通信代号    null  null
SELECT POST_CODE FROM HOSPITAL_INFO GROUP BY POST_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM HOSPITAL_INFO GROUP BY LAST_MODIFIC_TIME;

---ORGAN_NAME  VARCHAR2(70)      医疗机构名称    null  null
SELECT ORGAN_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_NAME;

---ORGAN_CODE  VARCHAR2(10)      医疗机构组织结构代码    null  null
SELECT ORGAN_CODE FROM HOSPITAL_INFO GROUP BY ORGAN_CODE;

---ORGAN_NUMBER  VARCHAR2(20)      医疗机构联系电话    null  null
SELECT ORGAN_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_NUMBER;

---ORGAN_HEAD_NAME  VARCHAR2(50)      医疗机构负责人（法人）姓名    null  null
SELECT ORGAN_HEAD_NAME FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NAME;

---ORGAN_HEAD_NUMBER  VARCHAR2(20)      医疗机构负责人联系电话    null  null
SELECT ORGAN_HEAD_NUMBER FROM HOSPITAL_INFO GROUP BY ORGAN_HEAD_NUMBER;

---ADDRESS_PROVINCE  VARCHAR2(70)      医疗机构地址中的省、自治区或直辖市名称    null  null
SELECT ADDRESS_PROVINCE FROM HOSPITAL_INFO GROUP BY ADDRESS_PROVINCE;

---ADDRESS_CITY  VARCHAR2(70)      医疗机构地址中的市、地区或州的名称    null  null
SELECT ADDRESS_CITY FROM HOSPITAL_INFO GROUP BY ADDRESS_CITY;

---ADDRESS_COUNTY  VARCHAR2(70)      医疗机构地址中的县（区）的名称    null  null
SELECT ADDRESS_COUNTY FROM HOSPITAL_INFO GROUP BY ADDRESS_COUNTY;

---TOWN_SHIP  VARCHAR2(70)      医疗机构地址中的乡、镇或城市的街道办事处名称    null  null
SELECT TOWN_SHIP FROM HOSPITAL_INFO GROUP BY TOWN_SHIP;

---ADDRESS_VILLAGE  VARCHAR2(70)      医疗机构地址中的村或城市的街、路、里、弄等名称    null  null
SELECT ADDRESS_VILLAGE FROM HOSPITAL_INFO GROUP BY ADDRESS_VILLAGE;

---ADDRESS_DOORS  VARCHAR2(70)      医疗机构地址中的门牌号码    null  null
SELECT ADDRESS_DOORS FROM HOSPITAL_INFO GROUP BY ADDRESS_DOORS;

---POST_CODE  NUMBER(6)      由阿拉伯数字组成，用来表示与医疗机构地址对应的邮局及其投递区域的邮政通信代号    null  null
SELECT POST_CODE FROM HOSPITAL_INFO GROUP BY POST_CODE;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM HOSPITAL_INFO GROUP BY LAST_MODIFIC_TIME;

