---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICHEALTH GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICHEALTH GROUP BY HEALTH_CARD_NO;

---ABO_BLOOD_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国家标准：WS 364.9—2011 表 5CV04.50.005ABO 血型代码表  null  null
SELECT ABO_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY ABO_BLOOD_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国家标准：CV04.50.020  null  null
SELECT RH_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY RH_BLOOD_CODE;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    null  null
SELECT DISEASE_HISTORY FROM EMR_BASICHEALTH GROUP BY DISEASE_HISTORY;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    null  null
SELECT INFECT_HISTORY FROM EMR_BASICHEALTH GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    null  null
SELECT PREVENT_HISTORY FROM EMR_BASICHEALTH GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    null  null
SELECT OPERATION_HISTORY FROM EMR_BASICHEALTH GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    null  null
SELECT BLOOD_TRANSFUSION_HISTORY FROM EMR_BASICHEALTH GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  null
SELECT ALLERGY_HISTORY FROM EMR_BASICHEALTH GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史    null  null
SELECT PERSON_HISTORY FROM EMR_BASICHEALTH GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史    null  null
SELECT MARITAL_HISTORY FROM EMR_BASICHEALTH GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史    null  null
SELECT MENSTRUATION_HISTORY FROM EMR_BASICHEALTH GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    null  null
SELECT FAMILY_HISTORY FROM EMR_BASICHEALTH GROUP BY FAMILY_HISTORY;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门诊流水号    null  null
SELECT OUTPATIENT_SN FROM EMR_BASICHEALTH GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM EMR_BASICHEALTH GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      主键-文档ID（patient_id+"_"+outpatient_sn+"_"+inpatient_sn某个流水号为空就直接给空即可，如“PID01_123_”或“PID01__123”）    null  null
SELECT DOC_NO FROM EMR_BASICHEALTH GROUP BY DOC_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICHEALTH GROUP BY LAST_MODIFIC_TIME;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICHEALTH GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICHEALTH GROUP BY HEALTH_CARD_NO;

---ABO_BLOOD_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国家标准：WS 364.9—2011 表 5CV04.50.005ABO 血型代码表  null  null
SELECT ABO_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY ABO_BLOOD_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国家标准：CV04.50.020  null  null
SELECT RH_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY RH_BLOOD_CODE;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    null  null
SELECT DISEASE_HISTORY FROM EMR_BASICHEALTH GROUP BY DISEASE_HISTORY;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    null  null
SELECT INFECT_HISTORY FROM EMR_BASICHEALTH GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    null  null
SELECT PREVENT_HISTORY FROM EMR_BASICHEALTH GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    null  null
SELECT OPERATION_HISTORY FROM EMR_BASICHEALTH GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    null  null
SELECT BLOOD_TRANSFUSION_HISTORY FROM EMR_BASICHEALTH GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  null
SELECT ALLERGY_HISTORY FROM EMR_BASICHEALTH GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史    null  null
SELECT PERSON_HISTORY FROM EMR_BASICHEALTH GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史    null  null
SELECT MARITAL_HISTORY FROM EMR_BASICHEALTH GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史    null  null
SELECT MENSTRUATION_HISTORY FROM EMR_BASICHEALTH GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    null  null
SELECT FAMILY_HISTORY FROM EMR_BASICHEALTH GROUP BY FAMILY_HISTORY;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门诊流水号    null  null
SELECT OUTPATIENT_SN FROM EMR_BASICHEALTH GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM EMR_BASICHEALTH GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      主键-文档ID（patient_id+"_"+outpatient_sn+"_"+inpatient_sn某个流水号为空就直接给空即可，如“PID01_123_”或“PID01__123”）    null  null
SELECT DOC_NO FROM EMR_BASICHEALTH GROUP BY DOC_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICHEALTH GROUP BY LAST_MODIFIC_TIME;

---PATIENT_ID  VARCHAR2(20)  Y    患者ID    null  null
SELECT PATIENT_ID FROM EMR_BASICHEALTH GROUP BY PATIENT_ID;

---HEALTH_CARD_NO  VARCHAR2(18)      居民健康卡号    null  null
SELECT HEALTH_CARD_NO FROM EMR_BASICHEALTH GROUP BY HEALTH_CARD_NO;

---ABO_BLOOD_CODE  VARCHAR2(1)  Y    ABO血型代码  应符合国家标准：WS 364.9—2011 表 5CV04.50.005ABO 血型代码表  null  null
SELECT ABO_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY ABO_BLOOD_CODE;

---RH_BLOOD_CODE  VARCHAR2(1)  Y    Rh血型代码  应符合国家标准：CV04.50.020  null  null
SELECT RH_BLOOD_CODE FROM EMR_BASICHEALTH GROUP BY RH_BLOOD_CODE;

---DISEASE_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）    null  null
SELECT DISEASE_HISTORY FROM EMR_BASICHEALTH GROUP BY DISEASE_HISTORY;

---INFECT_HISTORY  VARCHAR2(1000)  Y    传染病史    null  null
SELECT INFECT_HISTORY FROM EMR_BASICHEALTH GROUP BY INFECT_HISTORY;

---PREVENT_HISTORY  VARCHAR2(1000)  Y    预防接种史    null  null
SELECT PREVENT_HISTORY FROM EMR_BASICHEALTH GROUP BY PREVENT_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史    null  null
SELECT OPERATION_HISTORY FROM EMR_BASICHEALTH GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史    null  null
SELECT BLOOD_TRANSFUSION_HISTORY FROM EMR_BASICHEALTH GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史    null  null
SELECT ALLERGY_HISTORY FROM EMR_BASICHEALTH GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史    null  null
SELECT PERSON_HISTORY FROM EMR_BASICHEALTH GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史    null  null
SELECT MARITAL_HISTORY FROM EMR_BASICHEALTH GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史    null  null
SELECT MENSTRUATION_HISTORY FROM EMR_BASICHEALTH GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史    null  null
SELECT FAMILY_HISTORY FROM EMR_BASICHEALTH GROUP BY FAMILY_HISTORY;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门诊流水号    null  null
SELECT OUTPATIENT_SN FROM EMR_BASICHEALTH GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM EMR_BASICHEALTH GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      主键-文档ID（patient_id+"_"+outpatient_sn+"_"+inpatient_sn某个流水号为空就直接给空即可，如“PID01_123_”或“PID01__123”）    null  null
SELECT DOC_NO FROM EMR_BASICHEALTH GROUP BY DOC_NO;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM EMR_BASICHEALTH GROUP BY LAST_MODIFIC_TIME;

