---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OTHER_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OTHER_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OTHER_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NAME  VARCHAR2(200)  Y    知情同意书名称    S1  AN..200
SELECT INFORMED_CONSENT_NAME FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NAME;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---INFORMED_CONSENT_CONENT  VARCHAR2(1000)  Y    知情同意内容    S1  AN..1000
SELECT INFORMED_CONSENT_CONENT FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_CONENT;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM OTHER_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OTHER_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OTHER_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OTHER_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OTHER_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NAME  VARCHAR2(200)  Y    知情同意书名称    S1  AN..200
SELECT INFORMED_CONSENT_NAME FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NAME;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---INFORMED_CONSENT_CONENT  VARCHAR2(1000)  Y    知情同意内容    S1  AN..1000
SELECT INFORMED_CONSENT_CONENT FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_CONENT;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM OTHER_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OTHER_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM OTHER_INFORMED_CONSENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM OTHER_INFORMED_CONSENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM OTHER_INFORMED_CONSENT GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM OTHER_INFORMED_CONSENT GROUP BY INP_NO;

---INFORMED_CONSENT_NAME  VARCHAR2(200)  Y    知情同意书名称    S1  AN..200
SELECT INFORMED_CONSENT_NAME FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NAME;

---INFORMED_CONSENT_NO  VARCHAR2(20)  Y    知情同意书编号    S1  AN..20
SELECT INFORMED_CONSENT_NO FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_NO;

---INFORMED_CONSENT_CONENT  VARCHAR2(1000)  Y    知情同意内容    S1  AN..1000
SELECT INFORMED_CONSENT_CONENT FROM OTHER_INFORMED_CONSENT GROUP BY INFORMED_CONSENT_CONENT;

---ORG_OPINION  VARCHAR2(2000)  Y    医疗机构意见    S1  AN..2000
SELECT ORG_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY ORG_OPINION;

---PATIENT_AGENT_OPINION  VARCHAR2(2000)  Y    患者/法定代理人意见    S1  AN..2000
SELECT PATIENT_AGENT_OPINION FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_AGENT_OPINION;

---PATIENT_SIGN  VARCHAR2(50)  Y    患者签名    S1  A..50
SELECT PATIENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY PATIENT_SIGN;

---LEGAL_AGENT_SIGN  VARCHAR2(50)  Y    法定代理人签名    S1  A..50
SELECT LEGAL_AGENT_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY LEGAL_AGENT_SIGN;

---RELATION_CODE  VARCHAR2(2)  Y    法定代理人与患者的关系代码  应符合国标：GB/T4761—2008  S3  N1
SELECT RELATION_CODE FROM OTHER_INFORMED_CONSENT GROUP BY RELATION_CODE;

---SIGN_DATETIME  DATE  Y    患者/法定代理人签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY SIGN_DATETIME;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN;

---DOCTOR_SIGN_DATETIME  DATE  Y    医师签名日期时间    DT  DT15
SELECT DOCTOR_SIGN_DATETIME FROM OTHER_INFORMED_CONSENT GROUP BY DOCTOR_SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM OTHER_INFORMED_CONSENT GROUP BY LAST_MODIFIC_TIME;

