---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ASSESSMENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ASSESSMENT GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ASSESSMENT GROUP BY INP_NO;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---DISHOSPITAL_STATUS  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_STATUS;

---DISHOSPITAL_DISPOSITION_CODE  NUMBER(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---DRUG_USAGE  VARCHAR2(100)  Y    用药指导    S1  AN..100
SELECT DRUG_USAGE FROM DISCHARGE_ASSESSMENT GROUP BY DRUG_USAGE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIET_GUIDE_CODE;

---LIFESTYLE_COUNSELLING  VARCHAR2(50)  Y    生活方式指导    S1  AN..50
SELECT LIFESTYLE_COUNSELLING FROM DISCHARGE_ASSESSMENT GROUP BY LIFESTYLE_COUNSELLING;

---EDUCATIONAL_CONTENTS  VARCHAR2(100)  Y    宣教内容    S1  AN..100
SELECT EDUCATIONAL_CONTENTS FROM DISCHARGE_ASSESSMENT GROUP BY EDUCATIONAL_CONTENTS;

---SECOND_CLINIC  VARCHAR2(100)  Y    复诊指导    S1  AN..100
SELECT SECOND_CLINIC FROM DISCHARGE_ASSESSMENT GROUP BY SECOND_CLINIC;

---NURSING_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSING_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ASSESSMENT GROUP BY SIGN_DATETIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ASSESSMENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ASSESSMENT GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ASSESSMENT GROUP BY INP_NO;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---DISHOSPITAL_STATUS  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_STATUS;

---DISHOSPITAL_DISPOSITION_CODE  NUMBER(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---DRUG_USAGE  VARCHAR2(100)  Y    用药指导    S1  AN..100
SELECT DRUG_USAGE FROM DISCHARGE_ASSESSMENT GROUP BY DRUG_USAGE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIET_GUIDE_CODE;

---LIFESTYLE_COUNSELLING  VARCHAR2(50)  Y    生活方式指导    S1  AN..50
SELECT LIFESTYLE_COUNSELLING FROM DISCHARGE_ASSESSMENT GROUP BY LIFESTYLE_COUNSELLING;

---EDUCATIONAL_CONTENTS  VARCHAR2(100)  Y    宣教内容    S1  AN..100
SELECT EDUCATIONAL_CONTENTS FROM DISCHARGE_ASSESSMENT GROUP BY EDUCATIONAL_CONTENTS;

---SECOND_CLINIC  VARCHAR2(100)  Y    复诊指导    S1  AN..100
SELECT SECOND_CLINIC FROM DISCHARGE_ASSESSMENT GROUP BY SECOND_CLINIC;

---NURSING_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSING_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ASSESSMENT GROUP BY SIGN_DATETIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ASSESSMENT GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ASSESSMENT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ASSESSMENT GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ASSESSMENT GROUP BY INP_NO;

---DIETARY_STATUS_CODE  NUMBER(1)  Y    饮食情况代码  标准值：1.良好  2.—般  3.较差  S2  N1
SELECT DIETARY_STATUS_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIETARY_STATUS_CODE;

---SELF_CARE_STATUS  NUMBER(1)  Y    自理能力代码  标准值：1.完全自理  2.部分自理  3.不能自理  S2  N1
SELECT SELF_CARE_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY SELF_CARE_STATUS;

---DISHOSPITAL_STATUS  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_STATUS FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_STATUS;

---DISHOSPITAL_DISPOSITION_CODE  NUMBER(1)  Y    离院方式代码  应符合国标：CV06.00.226  S3  N1
SELECT DISHOSPITAL_DISPOSITION_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DISHOSPITAL_DISPOSITION_CODE;

---DRUG_USAGE  VARCHAR2(100)  Y    用药指导    S1  AN..100
SELECT DRUG_USAGE FROM DISCHARGE_ASSESSMENT GROUP BY DRUG_USAGE;

---DIET_GUIDE_CODE  VARCHAR2(2)  Y    饮食指导代码  应符合国标：CV06.00.224  S3  N2
SELECT DIET_GUIDE_CODE FROM DISCHARGE_ASSESSMENT GROUP BY DIET_GUIDE_CODE;

---LIFESTYLE_COUNSELLING  VARCHAR2(50)  Y    生活方式指导    S1  AN..50
SELECT LIFESTYLE_COUNSELLING FROM DISCHARGE_ASSESSMENT GROUP BY LIFESTYLE_COUNSELLING;

---EDUCATIONAL_CONTENTS  VARCHAR2(100)  Y    宣教内容    S1  AN..100
SELECT EDUCATIONAL_CONTENTS FROM DISCHARGE_ASSESSMENT GROUP BY EDUCATIONAL_CONTENTS;

---SECOND_CLINIC  VARCHAR2(100)  Y    复诊指导    S1  AN..100
SELECT SECOND_CLINIC FROM DISCHARGE_ASSESSMENT GROUP BY SECOND_CLINIC;

---NURSING_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSING_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY NURSING_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ASSESSMENT GROUP BY SIGN_DATETIME;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ASSESSMENT GROUP BY INP_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ASSESSMENT GROUP BY LAST_MODIFIC_TIME;

