---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM POSTOPERAT_FIRST_COURSE GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY RECORD_DATATIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY OPER_REQ_SN;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM POSTOPERAT_FIRST_COURSE GROUP BY OPERATION_PROCESS_DESC;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM POSTOPERAT_FIRST_COURSE GROUP BY DIAG_EVIDENCE;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM POSTOPERAT_FIRST_COURSE GROUP BY MATTERS_NEED_ATTENTION;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM POSTOPERAT_FIRST_COURSE GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM POSTOPERAT_FIRST_COURSE GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM POSTOPERAT_FIRST_COURSE GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY RECORD_DATATIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY OPER_REQ_SN;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM POSTOPERAT_FIRST_COURSE GROUP BY OPERATION_PROCESS_DESC;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM POSTOPERAT_FIRST_COURSE GROUP BY DIAG_EVIDENCE;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM POSTOPERAT_FIRST_COURSE GROUP BY MATTERS_NEED_ATTENTION;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM POSTOPERAT_FIRST_COURSE GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM POSTOPERAT_FIRST_COURSE GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM POSTOPERAT_FIRST_COURSE GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM POSTOPERAT_FIRST_COURSE GROUP BY INP_NO;

---RECORD_DATATIME  DATE  Y    记录日期时间    DT  DT15
SELECT RECORD_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY RECORD_DATATIME;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号      
SELECT OPER_REQ_SN FROM POSTOPERAT_FIRST_COURSE GROUP BY OPER_REQ_SN;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM POSTOPERAT_FIRST_COURSE GROUP BY OPERATION_PROCESS_DESC;

---DIAG_EVIDENCE  VARCHAR2(1000)  Y    诊断依据    S1  AN..1000
SELECT DIAG_EVIDENCE FROM POSTOPERAT_FIRST_COURSE GROUP BY DIAG_EVIDENCE;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..1000
SELECT MATTERS_NEED_ATTENTION FROM POSTOPERAT_FIRST_COURSE GROUP BY MATTERS_NEED_ATTENTION;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM POSTOPERAT_FIRST_COURSE GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM POSTOPERAT_FIRST_COURSE GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM POSTOPERAT_FIRST_COURSE GROUP BY LAST_MODIFIC_TIME;

