---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ABSTRACT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ABSTRACT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ABSTRACT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ABSTRACT GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM DISCHARGE_ABSTRACT GROUP BY INP_DAYS;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY TCM_FOUR_RESULTS;

---OPERATION_TYPE_CODE  NUMBER(1)  Y    手术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  NUMBER(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_PROCESS_DESC;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_ABSTRACT GROUP BY THERAPEUTIC_PRINCIPLE;

---TCD_DECOCTION_METHOD  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT TCD_DECOCTION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_DECOCTION_METHOD;

---TCD_MEDICATION_METHOD  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_MEDICATION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_MEDICATION_METHOD;

---DIAG_TREAT_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_TREAT_DESC FROM DISCHARGE_ABSTRACT GROUP BY DIAG_TREAT_DESC;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SIGNS  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SIGNS FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SIGNS;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_ABSTRACT GROUP BY OUTHOS_ADVIC;

---UNDERLYING_DEATH_CODE  NUMBER(1)  Y    病情转归代码  应符合国标：WS 364.11—2011 表 10  CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM DISCHARGE_ABSTRACT GROUP BY UNDERLYING_DEATH_CODE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY INP_DOCTOR_SIGN;

---SUPERIOR_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPERIOR_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY SUPERIOR_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ABSTRACT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ABSTRACT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ABSTRACT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ABSTRACT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ABSTRACT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ABSTRACT GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM DISCHARGE_ABSTRACT GROUP BY INP_DAYS;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY TCM_FOUR_RESULTS;

---OPERATION_TYPE_CODE  NUMBER(1)  Y    手术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  NUMBER(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_PROCESS_DESC;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_ABSTRACT GROUP BY THERAPEUTIC_PRINCIPLE;

---TCD_DECOCTION_METHOD  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT TCD_DECOCTION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_DECOCTION_METHOD;

---TCD_MEDICATION_METHOD  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_MEDICATION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_MEDICATION_METHOD;

---DIAG_TREAT_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_TREAT_DESC FROM DISCHARGE_ABSTRACT GROUP BY DIAG_TREAT_DESC;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SIGNS  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SIGNS FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SIGNS;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_ABSTRACT GROUP BY OUTHOS_ADVIC;

---UNDERLYING_DEATH_CODE  NUMBER(1)  Y    病情转归代码  应符合国标：WS 364.11—2011 表 10  CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM DISCHARGE_ABSTRACT GROUP BY UNDERLYING_DEATH_CODE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY INP_DOCTOR_SIGN;

---SUPERIOR_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPERIOR_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY SUPERIOR_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ABSTRACT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ABSTRACT GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_ABSTRACT GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_ABSTRACT GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_ABSTRACT GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_ABSTRACT GROUP BY PATIENT_ID;

---INP_DAYS  NUMBER(4)  Y    实际住院天数    N  N..4
SELECT INP_DAYS FROM DISCHARGE_ABSTRACT GROUP BY INP_DAYS;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_ABSTRACT GROUP BY TCM_FOUR_RESULTS;

---OPERATION_TYPE_CODE  NUMBER(1)  Y    手术切口类别代码  应符合国标：CV05.10.022  S3  N1
SELECT OPERATION_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_TYPE_CODE;

---OPERAT_INCIS_HEAL_TYPE_CODE  NUMBER(1)  Y    手术切口愈合等级代码  应符合国标：CV05.10.023  S3  N1
SELECT OPERAT_INCIS_HEAL_TYPE_CODE FROM DISCHARGE_ABSTRACT GROUP BY OPERAT_INCIS_HEAL_TYPE_CODE;

---OPERATION_PROCESS_DESC  VARCHAR2(2000)  Y    手术过程    S1  AN..2000
SELECT OPERATION_PROCESS_DESC FROM DISCHARGE_ABSTRACT GROUP BY OPERATION_PROCESS_DESC;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_ABSTRACT GROUP BY THERAPEUTIC_PRINCIPLE;

---TCD_DECOCTION_METHOD  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT TCD_DECOCTION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_DECOCTION_METHOD;

---TCD_MEDICATION_METHOD  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_MEDICATION_METHOD FROM DISCHARGE_ABSTRACT GROUP BY TCD_MEDICATION_METHOD;

---DIAG_TREAT_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_TREAT_DESC FROM DISCHARGE_ABSTRACT GROUP BY DIAG_TREAT_DESC;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SIGNS  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SIGNS FROM DISCHARGE_ABSTRACT GROUP BY DISHOSPITAL_SIGNS;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_ABSTRACT GROUP BY OUTHOS_ADVIC;

---UNDERLYING_DEATH_CODE  NUMBER(1)  Y    病情转归代码  应符合国标：WS 364.11—2011 表 10  CV05.10.010病情转归代码表  S3  N1
SELECT UNDERLYING_DEATH_CODE FROM DISCHARGE_ABSTRACT GROUP BY UNDERLYING_DEATH_CODE;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY INP_DOCTOR_SIGN;

---SUPERIOR_DOCTOR_SIGN  VARCHAR2(50)  Y    上级医师签名    S1  A..50
SELECT SUPERIOR_DOCTOR_SIGN FROM DISCHARGE_ABSTRACT GROUP BY SUPERIOR_DOCTOR_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM DISCHARGE_ABSTRACT GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_ABSTRACT GROUP BY LAST_MODIFIC_TIME;

