---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_DIAGNOSIS GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_DIAGNOSIS GROUP BY INP_NO;

---DIAG_TYPE  VARCHAR2(2)  Y    诊断类型(1-门诊诊断、2-初步诊断 3-入院诊断 4-修正诊断 5-出院诊断,6-死亡诊断 7-术前诊断 8-术中诊断 9-术后诊断, 10-确定诊断 11-补充诊断 12-目前诊断 13-直接死亡原因 14-病理诊断 15-损伤中毒)      
SELECT DIAG_TYPE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_TYPE;

---DIAG_DIAGNOSIS  VARCHAR2(100)  Y    主诊断标识(1-主诊断、2-其他诊断、3-附属诊断)      
SELECT DIAG_DIAGNOSIS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DIAGNOSIS;

---DIAG_CLASSIFICATIONS  VARCHAR2(100)  Y    诊断类别(1-西医诊断，2-中医诊断，3-中医症候)      
SELECT DIAG_CLASSIFICATIONS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CLASSIFICATIONS;

---DIAG_NO  VARCHAR2(10)  Y    诊断顺位      
SELECT DIAG_NO FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NO;

---DIAG_NAME  VARCHAR2(50)  Y    诊断名称      
SELECT DIAG_NAME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NAME;

---DIAG_CODE  VARCHAR2(50)  Y    诊断编码      
SELECT DIAG_CODE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CODE;

---DIAG_DATATIME  DATE  Y    诊断时间      
SELECT DIAG_DATATIME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DATATIME;

---OUTHOS_INHOS_CODE  VARCHAR2(1)  Y    入院病情代码  应符合国标：CV05.10.019    
SELECT OUTHOS_INHOS_CODE FROM INPATIENT_DIAGNOSIS GROUP BY OUTHOS_INHOS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_DIAGNOSIS GROUP BY LAST_MODIFIC_TIME;

---DIAG_ID  VARCHAR2(18)      主键      
SELECT DIAG_ID FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_ID;

---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_DIAGNOSIS GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_DIAGNOSIS GROUP BY INP_NO;

---DIAG_TYPE  VARCHAR2(2)  Y    诊断类型(1-门诊诊断、2-初步诊断 3-入院诊断 4-修正诊断 5-出院诊断,6-死亡诊断 7-术前诊断 8-术中诊断 9-术后诊断, 10-确定诊断 11-补充诊断 12-目前诊断 13-直接死亡原因 14-病理诊断 15-损伤中毒)      
SELECT DIAG_TYPE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_TYPE;

---DIAG_DIAGNOSIS  VARCHAR2(100)  Y    主诊断标识(1-主诊断、2-其他诊断、3-附属诊断)      
SELECT DIAG_DIAGNOSIS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DIAGNOSIS;

---DIAG_CLASSIFICATIONS  VARCHAR2(100)  Y    诊断类别(1-西医诊断，2-中医诊断，3-中医症候)      
SELECT DIAG_CLASSIFICATIONS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CLASSIFICATIONS;

---DIAG_NO  VARCHAR2(10)  Y    诊断顺位      
SELECT DIAG_NO FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NO;

---DIAG_NAME  VARCHAR2(50)  Y    诊断名称      
SELECT DIAG_NAME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NAME;

---DIAG_CODE  VARCHAR2(50)  Y    诊断编码      
SELECT DIAG_CODE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CODE;

---DIAG_DATATIME  DATE  Y    诊断时间      
SELECT DIAG_DATATIME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DATATIME;

---OUTHOS_INHOS_CODE  VARCHAR2(1)  Y    入院病情代码  应符合国标：CV05.10.019    
SELECT OUTHOS_INHOS_CODE FROM INPATIENT_DIAGNOSIS GROUP BY OUTHOS_INHOS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_DIAGNOSIS GROUP BY LAST_MODIFIC_TIME;

---DIAG_ID  VARCHAR2(18)      主键      
SELECT DIAG_ID FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_ID;

---INHOS_COUNT  NUMBER(2)      住院次数    N  N..2
SELECT INHOS_COUNT FROM INPATIENT_DIAGNOSIS GROUP BY INHOS_COUNT;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM INPATIENT_DIAGNOSIS GROUP BY INP_NO;

---DIAG_TYPE  VARCHAR2(2)  Y    诊断类型(1-门诊诊断、2-初步诊断 3-入院诊断 4-修正诊断 5-出院诊断,6-死亡诊断 7-术前诊断 8-术中诊断 9-术后诊断, 10-确定诊断 11-补充诊断 12-目前诊断 13-直接死亡原因 14-病理诊断 15-损伤中毒)      
SELECT DIAG_TYPE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_TYPE;

---DIAG_DIAGNOSIS  VARCHAR2(100)  Y    主诊断标识(1-主诊断、2-其他诊断、3-附属诊断)      
SELECT DIAG_DIAGNOSIS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DIAGNOSIS;

---DIAG_CLASSIFICATIONS  VARCHAR2(100)  Y    诊断类别(1-西医诊断，2-中医诊断，3-中医症候)      
SELECT DIAG_CLASSIFICATIONS FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CLASSIFICATIONS;

---DIAG_NO  VARCHAR2(10)  Y    诊断顺位      
SELECT DIAG_NO FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NO;

---DIAG_NAME  VARCHAR2(50)  Y    诊断名称      
SELECT DIAG_NAME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_NAME;

---DIAG_CODE  VARCHAR2(50)  Y    诊断编码      
SELECT DIAG_CODE FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_CODE;

---DIAG_DATATIME  DATE  Y    诊断时间      
SELECT DIAG_DATATIME FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_DATATIME;

---OUTHOS_INHOS_CODE  VARCHAR2(1)  Y    入院病情代码  应符合国标：CV05.10.019    
SELECT OUTHOS_INHOS_CODE FROM INPATIENT_DIAGNOSIS GROUP BY OUTHOS_INHOS_CODE;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM INPATIENT_DIAGNOSIS GROUP BY LAST_MODIFIC_TIME;

---DIAG_ID  VARCHAR2(18)      主键      
SELECT DIAG_ID FROM INPATIENT_DIAGNOSIS GROUP BY DIAG_ID;

