---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_CHINE GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_CHINE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_CHINE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_CHINE GROUP BY OUTP_NO;

---PRESC_ID  VARCHAR2(50)      处方id      
SELECT PRESC_ID FROM PRESCRIPTION_CHINE GROUP BY PRESC_ID;

---RECIPE_NO  NUMBER(30)      处方编号    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_CHINE GROUP BY RECIPE_NO;

---PRESCRIPTION_CATEGORY_CODE  VARCHAR2(1)  Y    处方类别代码  1.中药饮片处方2.中成药处方  S2  N1
SELECT PRESCRIPTION_CATEGORY_CODE FROM PRESCRIPTION_CHINE GROUP BY PRESCRIPTION_CATEGORY_CODE;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_CHINE GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDEPT_NAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PRESCRIPTION_CHINE GROUP BY THERAPEUTIC_PRINCIPLE;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDOCTOR_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN..100
SELECT RECIPE_REMARK FROM PRESCRIPTION_CHINE GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8,2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_CHINE GROUP BY RECIPE_COSTS_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_CHINE GROUP BY LAST_MODIFIC_TIME;

---TCD_DECOCTIONPIECES  VARCHAR2(500)  Y    中药饮片处方    S1  AN.. 500
SELECT TCD_DECOCTIONPIECES FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES;

---TCD_DECOCTIONPIECES_FORM  NUMBER(2)  Y    中药饮片剂数（剂）    N  N..2
SELECT TCD_DECOCTIONPIECES_FORM FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_FORM;

---TCD_DECOCTIONPIECES_DECOCTION  VARCHAR2(100)  Y    中药饮片煎煮法    S1  AN.. 100
SELECT TCD_DECOCTIONPIECES_DECOCTION FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_DECOCTION;

---TCD_USAGE  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_USAGE FROM PRESCRIPTION_CHINE GROUP BY TCD_USAGE;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_CHINE GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_CHINE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_CHINE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_CHINE GROUP BY OUTP_NO;

---PRESC_ID  VARCHAR2(50)      处方id      
SELECT PRESC_ID FROM PRESCRIPTION_CHINE GROUP BY PRESC_ID;

---RECIPE_NO  NUMBER(30)      处方编号    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_CHINE GROUP BY RECIPE_NO;

---PRESCRIPTION_CATEGORY_CODE  VARCHAR2(1)  Y    处方类别代码  1.中药饮片处方2.中成药处方  S2  N1
SELECT PRESCRIPTION_CATEGORY_CODE FROM PRESCRIPTION_CHINE GROUP BY PRESCRIPTION_CATEGORY_CODE;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_CHINE GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDEPT_NAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PRESCRIPTION_CHINE GROUP BY THERAPEUTIC_PRINCIPLE;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDOCTOR_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN..100
SELECT RECIPE_REMARK FROM PRESCRIPTION_CHINE GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8,2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_CHINE GROUP BY RECIPE_COSTS_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_CHINE GROUP BY LAST_MODIFIC_TIME;

---TCD_DECOCTIONPIECES  VARCHAR2(500)  Y    中药饮片处方    S1  AN.. 500
SELECT TCD_DECOCTIONPIECES FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES;

---TCD_DECOCTIONPIECES_FORM  NUMBER(2)  Y    中药饮片剂数（剂）    N  N..2
SELECT TCD_DECOCTIONPIECES_FORM FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_FORM;

---TCD_DECOCTIONPIECES_DECOCTION  VARCHAR2(100)  Y    中药饮片煎煮法    S1  AN.. 100
SELECT TCD_DECOCTIONPIECES_DECOCTION FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_DECOCTION;

---TCD_USAGE  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_USAGE FROM PRESCRIPTION_CHINE GROUP BY TCD_USAGE;

---OUTPATIENT_SN  VARCHAR2(18)      门（急）诊流水号      
SELECT OUTPATIENT_SN FROM PRESCRIPTION_CHINE GROUP BY OUTPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRESCRIPTION_CHINE GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRESCRIPTION_CHINE GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)      门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM PRESCRIPTION_CHINE GROUP BY OUTP_NO;

---PRESC_ID  VARCHAR2(50)      处方id      
SELECT PRESC_ID FROM PRESCRIPTION_CHINE GROUP BY PRESC_ID;

---RECIPE_NO  NUMBER(30)      处方编号    S1  N..30
SELECT RECIPE_NO FROM PRESCRIPTION_CHINE GROUP BY RECIPE_NO;

---PRESCRIPTION_CATEGORY_CODE  VARCHAR2(1)  Y    处方类别代码  1.中药饮片处方2.中成药处方  S2  N1
SELECT PRESCRIPTION_CATEGORY_CODE FROM PRESCRIPTION_CHINE GROUP BY PRESCRIPTION_CATEGORY_CODE;

---RECIPE_OPEN_DATE  DATE  Y    处方开立日期    D  D8
SELECT RECIPE_OPEN_DATE FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPEN_DATE;

---RECIPE_EFFECTIVE_DAY  NUMBER(2)  Y    处方有效天数    N  N..2
SELECT RECIPE_EFFECTIVE_DAY FROM PRESCRIPTION_CHINE GROUP BY RECIPE_EFFECTIVE_DAY;

---RECIPE_OPENDEPT_NAME  VARCHAR2(50)  Y    处方开立科室名称    S1  AN..50
SELECT RECIPE_OPENDEPT_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDEPT_NAME;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  GB/T 16751.3—1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM PRESCRIPTION_CHINE GROUP BY THERAPEUTIC_PRINCIPLE;

---RECIPE_OPENDOCTOR_NAME  VARCHAR2(50)  Y    处方开立医师签名    S1  A..50
SELECT RECIPE_OPENDOCTOR_NAME FROM PRESCRIPTION_CHINE GROUP BY RECIPE_OPENDOCTOR_NAME;

---RECIPE_REMARK  VARCHAR2(100)  Y    处方备注信息    S1  AN..100
SELECT RECIPE_REMARK FROM PRESCRIPTION_CHINE GROUP BY RECIPE_REMARK;

---RECIPE_COSTS_AMOUNT  NUMBER(8,2)  Y    处方药品金额    N  N..8,2
SELECT RECIPE_COSTS_AMOUNT FROM PRESCRIPTION_CHINE GROUP BY RECIPE_COSTS_AMOUNT;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRESCRIPTION_CHINE GROUP BY LAST_MODIFIC_TIME;

---TCD_DECOCTIONPIECES  VARCHAR2(500)  Y    中药饮片处方    S1  AN.. 500
SELECT TCD_DECOCTIONPIECES FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES;

---TCD_DECOCTIONPIECES_FORM  NUMBER(2)  Y    中药饮片剂数（剂）    N  N..2
SELECT TCD_DECOCTIONPIECES_FORM FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_FORM;

---TCD_DECOCTIONPIECES_DECOCTION  VARCHAR2(100)  Y    中药饮片煎煮法    S1  AN.. 100
SELECT TCD_DECOCTIONPIECES_DECOCTION FROM PRESCRIPTION_CHINE GROUP BY TCD_DECOCTIONPIECES_DECOCTION;

---TCD_USAGE  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT TCD_USAGE FROM PRESCRIPTION_CHINE GROUP BY TCD_USAGE;

