---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_MONI GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_MONI GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_MONI GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_MONI GROUP BY OPERA_SN;

---MONITOR_TYPE  NUMBER(1)  Y    监测类型  标准值：1-常规，2-特殊  null  null
SELECT MONITOR_TYPE FROM OPERATION_MONI GROUP BY MONITOR_TYPE;

---ROUTINE_MONITOR_PROJ_NAME  VARCHAR2(100)  Y    常规监测项目名称    null  null
SELECT ROUTINE_MONITOR_PROJ_NAME FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_NAME;

---ROUTINE_MONITOR_PROJ_RESULT  VARCHAR2(200)  Y    常规监测项目结果    null  null
SELECT ROUTINE_MONITOR_PROJ_RESULT FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_RESULT;

---SPECMONITORPROJECT_NAME  VARCHAR2(200)  Y    特殊监测项目名称    null  null
SELECT SPECMONITORPROJECT_NAME FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_NAME;

---SPECMONITORPROJECT_RESULT  VARCHAR2(200)  Y    特殊监测项目结果    null  null
SELECT SPECMONITORPROJECT_RESULT FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_RESULT;

---OPERATION_MONI_ID  VARCHAR2(18)      手术监测ID    null  null
SELECT OPERATION_MONI_ID FROM OPERATION_MONI GROUP BY OPERATION_MONI_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_MONI GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_MONI GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_MONI GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_MONI GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_MONI GROUP BY OPERA_SN;

---MONITOR_TYPE  NUMBER(1)  Y    监测类型  标准值：1-常规，2-特殊  null  null
SELECT MONITOR_TYPE FROM OPERATION_MONI GROUP BY MONITOR_TYPE;

---ROUTINE_MONITOR_PROJ_NAME  VARCHAR2(100)  Y    常规监测项目名称    null  null
SELECT ROUTINE_MONITOR_PROJ_NAME FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_NAME;

---ROUTINE_MONITOR_PROJ_RESULT  VARCHAR2(200)  Y    常规监测项目结果    null  null
SELECT ROUTINE_MONITOR_PROJ_RESULT FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_RESULT;

---SPECMONITORPROJECT_NAME  VARCHAR2(200)  Y    特殊监测项目名称    null  null
SELECT SPECMONITORPROJECT_NAME FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_NAME;

---SPECMONITORPROJECT_RESULT  VARCHAR2(200)  Y    特殊监测项目结果    null  null
SELECT SPECMONITORPROJECT_RESULT FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_RESULT;

---OPERATION_MONI_ID  VARCHAR2(18)      手术监测ID    null  null
SELECT OPERATION_MONI_ID FROM OPERATION_MONI GROUP BY OPERATION_MONI_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_MONI GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_MONI GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_MONI GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_MONI GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_MONI GROUP BY OPERA_SN;

---MONITOR_TYPE  NUMBER(1)  Y    监测类型  标准值：1-常规，2-特殊  null  null
SELECT MONITOR_TYPE FROM OPERATION_MONI GROUP BY MONITOR_TYPE;

---ROUTINE_MONITOR_PROJ_NAME  VARCHAR2(100)  Y    常规监测项目名称    null  null
SELECT ROUTINE_MONITOR_PROJ_NAME FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_NAME;

---ROUTINE_MONITOR_PROJ_RESULT  VARCHAR2(200)  Y    常规监测项目结果    null  null
SELECT ROUTINE_MONITOR_PROJ_RESULT FROM OPERATION_MONI GROUP BY ROUTINE_MONITOR_PROJ_RESULT;

---SPECMONITORPROJECT_NAME  VARCHAR2(200)  Y    特殊监测项目名称    null  null
SELECT SPECMONITORPROJECT_NAME FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_NAME;

---SPECMONITORPROJECT_RESULT  VARCHAR2(200)  Y    特殊监测项目结果    null  null
SELECT SPECMONITORPROJECT_RESULT FROM OPERATION_MONI GROUP BY SPECMONITORPROJECT_RESULT;

---OPERATION_MONI_ID  VARCHAR2(18)      手术监测ID    null  null
SELECT OPERATION_MONI_ID FROM OPERATION_MONI GROUP BY OPERATION_MONI_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_MONI GROUP BY LAST_MODIFIC_TIME;

