---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_RECORD GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_RECORD GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DISCHARGE_RECORD GROUP BY DIAG_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SYMPTOM  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SYMPTOM FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SYMPTOM;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_RECORD GROUP BY OUTHOS_ADVIC;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DISCHARGE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_RECORD GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_RECORD GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DISCHARGE_RECORD GROUP BY DIAG_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SYMPTOM  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SYMPTOM FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SYMPTOM;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_RECORD GROUP BY OUTHOS_ADVIC;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DISCHARGE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DISCHARGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DISCHARGE_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DISCHARGE_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DISCHARGE_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DISCHARGE_RECORD GROUP BY INP_SITUATION;

---POSITIVE_TEST_RESULTS  VARCHAR2(1000)  Y    阳性辅助检查结果    S1  AN..1000
SELECT POSITIVE_TEST_RESULTS FROM DISCHARGE_RECORD GROUP BY POSITIVE_TEST_RESULTS;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM DISCHARGE_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3-1997  S1  AN..100
SELECT THERAPEUTIC_PRINCIPLE FROM DISCHARGE_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DISCHARGE_RECORD GROUP BY DIAG_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM DISCHARGE_RECORD GROUP BY CHIN_DRINK_DECWAY;

---DISHOSPITAL_SITUATION  VARCHAR2(2000)  Y    出院情况    S1  AN..2000
SELECT DISHOSPITAL_SITUATION FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SITUATION;

---DISHOSPITAL_SYMPTOM  VARCHAR2(1000)  Y    出院时症状与体征    S1  AN..1000
SELECT DISHOSPITAL_SYMPTOM FROM DISCHARGE_RECORD GROUP BY DISHOSPITAL_SYMPTOM;

---OUTHOS_ADVIC  VARCHAR2(1000)  Y    出院医嘱    S1  AN..1000
SELECT OUTHOS_ADVIC FROM DISCHARGE_RECORD GROUP BY OUTHOS_ADVIC;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DISCHARGE_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DISCHARGE_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DISCHARGE_RECORD GROUP BY LAST_MODIFIC_TIME;

