---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFUSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFUSION_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM TRANSFUSION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM TRANSFUSION_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT ELECTRONIC_APPLY_NO FROM TRANSFUSION_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1)  Y    输血史标识代码  1.无2.有9.未说明  S2  N1
SELECT BLOOD_TRANSFUSION_HISTORY FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---TRANSFUSION_NATURE_CODE  VARCHAR2(1)  Y    输血性质代码  1.备血2.常规3.紧急  S2  N1
SELECT TRANSFUSION_NATURE_CODE FROM TRANSFUSION_RECORD GROUP BY TRANSFUSION_NATURE_CODE;

---APPLICATION_ABO_BLOOD_TYPE  VARCHAR2(1)  Y    申请ABO血型代码  WS 364.9—2011 表 5  S3  N1
SELECT APPLICATION_ABO_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_ABO_BLOOD_TYPE;

---APPLICATION_RH_BLOOD_TYPE  VARCHAR2(1)  Y    申请Rh血型代码  CV04.50.020  S3  N1
SELECT APPLICATION_RH_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_RH_BLOOD_TYPE;

---BLOOD_TRANSFUSION_INDICATION  VARCHAR2(500)  Y    输血指征    S1  AN..500
SELECT BLOOD_TRANSFUSION_INDICATION FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_INDICATION;

---BLOOD_TRANSFUSION_PROCESS  VARCHAR2(2000)  Y    输血过程记录    S1  AN..2000
SELECT BLOOD_TRANSFUSION_PROCESS FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_PROCESS;

---BLOOD_TRANSFUSION_VARIETY_CODE  VARCHAR2(2)  Y    输血品种代码  CV04.50.021  S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_NO  VARCHAR2(10)  Y    血袋编码    S1  N10
SELECT BLOOD_NO FROM TRANSFUSION_RECORD GROUP BY BLOOD_NO;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM TRANSFUSION_RECORD GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REACTION_CODE;

---BLOOD_REACTION_TYPE_CODE  VARCHAR2(1)  Y    输血反应类型代码  CV05.01.040  S3  N1
SELECT BLOOD_REACTION_TYPE_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_REACTION_TYPE_CODE;

---TIME_BLOOD  NUMBER(2)  Y    输血次数    N  N..2
SELECT TIME_BLOOD FROM TRANSFUSION_RECORD GROUP BY TIME_BLOOD;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOODTRANSFERED_REASON  VARCHAR2(100)  Y    输血原因    S1  AN..100
SELECT BLOODTRANSFERED_REASON FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REASON;

---DOCTOR_NAME_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_NAME_SIGN FROM TRANSFUSION_RECORD GROUP BY DOCTOR_NAME_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM TRANSFUSION_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFUSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFUSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFUSION_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM TRANSFUSION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM TRANSFUSION_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT ELECTRONIC_APPLY_NO FROM TRANSFUSION_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1)  Y    输血史标识代码  1.无2.有9.未说明  S2  N1
SELECT BLOOD_TRANSFUSION_HISTORY FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---TRANSFUSION_NATURE_CODE  VARCHAR2(1)  Y    输血性质代码  1.备血2.常规3.紧急  S2  N1
SELECT TRANSFUSION_NATURE_CODE FROM TRANSFUSION_RECORD GROUP BY TRANSFUSION_NATURE_CODE;

---APPLICATION_ABO_BLOOD_TYPE  VARCHAR2(1)  Y    申请ABO血型代码  WS 364.9—2011 表 5  S3  N1
SELECT APPLICATION_ABO_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_ABO_BLOOD_TYPE;

---APPLICATION_RH_BLOOD_TYPE  VARCHAR2(1)  Y    申请Rh血型代码  CV04.50.020  S3  N1
SELECT APPLICATION_RH_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_RH_BLOOD_TYPE;

---BLOOD_TRANSFUSION_INDICATION  VARCHAR2(500)  Y    输血指征    S1  AN..500
SELECT BLOOD_TRANSFUSION_INDICATION FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_INDICATION;

---BLOOD_TRANSFUSION_PROCESS  VARCHAR2(2000)  Y    输血过程记录    S1  AN..2000
SELECT BLOOD_TRANSFUSION_PROCESS FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_PROCESS;

---BLOOD_TRANSFUSION_VARIETY_CODE  VARCHAR2(2)  Y    输血品种代码  CV04.50.021  S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_NO  VARCHAR2(10)  Y    血袋编码    S1  N10
SELECT BLOOD_NO FROM TRANSFUSION_RECORD GROUP BY BLOOD_NO;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM TRANSFUSION_RECORD GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REACTION_CODE;

---BLOOD_REACTION_TYPE_CODE  VARCHAR2(1)  Y    输血反应类型代码  CV05.01.040  S3  N1
SELECT BLOOD_REACTION_TYPE_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_REACTION_TYPE_CODE;

---TIME_BLOOD  NUMBER(2)  Y    输血次数    N  N..2
SELECT TIME_BLOOD FROM TRANSFUSION_RECORD GROUP BY TIME_BLOOD;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOODTRANSFERED_REASON  VARCHAR2(100)  Y    输血原因    S1  AN..100
SELECT BLOODTRANSFERED_REASON FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REASON;

---DOCTOR_NAME_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_NAME_SIGN FROM TRANSFUSION_RECORD GROUP BY DOCTOR_NAME_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM TRANSFUSION_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFUSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号      
SELECT OUTPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号      
SELECT INPATIENT_SN FROM TRANSFUSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM TRANSFUSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM TRANSFUSION_RECORD GROUP BY PATIENT_ID;

---OUTP_NO  VARCHAR2(18)  Y    门（急）诊号    S1  AN..18
SELECT OUTP_NO FROM TRANSFUSION_RECORD GROUP BY OUTP_NO;

---INP_NO  VARCHAR2(18)  Y    住院号    S1  AN..18
SELECT INP_NO FROM TRANSFUSION_RECORD GROUP BY INP_NO;

---ELECTRONIC_APPLY_NO  VARCHAR2(20)  Y    电子申请单编号    S1  AN..20
SELECT ELECTRONIC_APPLY_NO FROM TRANSFUSION_RECORD GROUP BY ELECTRONIC_APPLY_NO;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1)  Y    输血史标识代码  1.无2.有9.未说明  S2  N1
SELECT BLOOD_TRANSFUSION_HISTORY FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---TRANSFUSION_NATURE_CODE  VARCHAR2(1)  Y    输血性质代码  1.备血2.常规3.紧急  S2  N1
SELECT TRANSFUSION_NATURE_CODE FROM TRANSFUSION_RECORD GROUP BY TRANSFUSION_NATURE_CODE;

---APPLICATION_ABO_BLOOD_TYPE  VARCHAR2(1)  Y    申请ABO血型代码  WS 364.9—2011 表 5  S3  N1
SELECT APPLICATION_ABO_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_ABO_BLOOD_TYPE;

---APPLICATION_RH_BLOOD_TYPE  VARCHAR2(1)  Y    申请Rh血型代码  CV04.50.020  S3  N1
SELECT APPLICATION_RH_BLOOD_TYPE FROM TRANSFUSION_RECORD GROUP BY APPLICATION_RH_BLOOD_TYPE;

---BLOOD_TRANSFUSION_INDICATION  VARCHAR2(500)  Y    输血指征    S1  AN..500
SELECT BLOOD_TRANSFUSION_INDICATION FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_INDICATION;

---BLOOD_TRANSFUSION_PROCESS  VARCHAR2(2000)  Y    输血过程记录    S1  AN..2000
SELECT BLOOD_TRANSFUSION_PROCESS FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_PROCESS;

---BLOOD_TRANSFUSION_VARIETY_CODE  VARCHAR2(2)  Y    输血品种代码  CV04.50.021  S3  N..2
SELECT BLOOD_TRANSFUSION_VARIETY_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFUSION_VARIETY_CODE;

---BLOOD_NO  VARCHAR2(10)  Y    血袋编码    S1  N10
SELECT BLOOD_NO FROM TRANSFUSION_RECORD GROUP BY BLOOD_NO;

---BLOOD_TRANSFERED_VALUE  NUMBER(4)  Y    输血量（mL)    N  N..4
SELECT BLOOD_TRANSFERED_VALUE FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_VALUE;

---BLOOD_VOLUME_UNIT  VARCHAR2(10)  Y    输血量计量单位    S1  A..10
SELECT BLOOD_VOLUME_UNIT FROM TRANSFUSION_RECORD GROUP BY BLOOD_VOLUME_UNIT;

---BLOODTRANSFERED_REACTION_CODE  VARCHAR2(5)  Y    输血反应标志    L  T/F
SELECT BLOODTRANSFERED_REACTION_CODE FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REACTION_CODE;

---BLOOD_REACTION_TYPE_CODE  VARCHAR2(1)  Y    输血反应类型代码  CV05.01.040  S3  N1
SELECT BLOOD_REACTION_TYPE_CODE FROM TRANSFUSION_RECORD GROUP BY BLOOD_REACTION_TYPE_CODE;

---TIME_BLOOD  NUMBER(2)  Y    输血次数    N  N..2
SELECT TIME_BLOOD FROM TRANSFUSION_RECORD GROUP BY TIME_BLOOD;

---BLOOD_TRANSFERED_DATETIME  DATE  Y    输血日期时间    DT  DTI 5
SELECT BLOOD_TRANSFERED_DATETIME FROM TRANSFUSION_RECORD GROUP BY BLOOD_TRANSFERED_DATETIME;

---BLOODTRANSFERED_REASON  VARCHAR2(100)  Y    输血原因    S1  AN..100
SELECT BLOODTRANSFERED_REASON FROM TRANSFUSION_RECORD GROUP BY BLOODTRANSFERED_REASON;

---DOCTOR_NAME_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_NAME_SIGN FROM TRANSFUSION_RECORD GROUP BY DOCTOR_NAME_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DTI 5
SELECT SIGN_DATETIME FROM TRANSFUSION_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM TRANSFUSION_RECORD GROUP BY LAST_MODIFIC_TIME;

