---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号      
SELECT INP_NO FROM ADMISSION_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名      
SELECT MEDICALHIS_NAME FROM ADMISSION_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(1)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761-2008    
SELECT PRESENTER_PATIENT_RELAT_CODE FROM ADMISSION_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE    
SELECT IS_CREDIBLE FROM ADMISSION_RECORD GROUP BY IS_CREDIBLE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM ADMISSION_RECORD GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史      
SELECT PRESENT_DISEASE_HISTORY FROM ADMISSION_RECORD GROUP BY PRESENT_DISEASE_HISTORY;

---HEALTH_STATUS_CODE  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE    
SELECT HEALTH_STATUS_CODE FROM ADMISSION_RECORD GROUP BY HEALTH_STATUS_CODE;

---DISEASES_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）      
SELECT DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY DISEASES_HISTORY;

---COMMUNICABLE_DISEASES_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE    
SELECT COMMUNICABLE_DISEASES_FLAG FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_FLAG;

---COMMUNICABLE_DISEASES_HISTORY  VARCHAR2(1000)  Y    传染病史      
SELECT COMMUNICABLE_DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_HISTORY;

---PREVENTIVE_INOCULATION_HISTORY  VARCHAR2(1000)  Y    预防接种史      
SELECT PREVENTIVE_INOCULATION_HISTORY FROM ADMISSION_RECORD GROUP BY PREVENTIVE_INOCULATION_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史      
SELECT OPERATION_HISTORY FROM ADMISSION_RECORD GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史      
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史      
SELECT ALLERGY_HISTORY FROM ADMISSION_RECORD GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史      
SELECT PERSON_HISTORY FROM ADMISSION_RECORD GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史      
SELECT MARITAL_HISTORY FROM ADMISSION_RECORD GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史      
SELECT MENSTRUATION_HISTORY FROM ADMISSION_RECORD GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史      
SELECT FAMILY_HISTORY FROM ADMISSION_RECORD GROUP BY FAMILY_HISTORY;

---PHYSICALEXAM_TEMPERATURE  NUMBER(4,1)  Y    体格检查-体温（℃）      
SELECT PHYSICALEXAM_TEMPERATURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_TEMPERATURE;

---PHYSICALEXAM_SPHYGMUS  NUMBER(3)  Y    体格检查-脉率（次/min)      
SELECT PHYSICALEXAM_SPHYGMUS FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SPHYGMUS;

---PHYSICALEXAM_BREATH_FREQUENCY  NUMBER(3)  Y    体格检查-呼吸频率（次/min)      
SELECT PHYSICALEXAM_BREATH_FREQUENCY FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_BREATH_FREQUENCY;

---PHYSICALEXAM_SYSTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-收缩压（mm-Hg)      
SELECT PHYSICALEXAM_SYSTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SYSTOLIC_PRESSURE;

---EXAM_DIASTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-舒张压(mmHg)      
SELECT EXAM_DIASTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY EXAM_DIASTOLIC_PRESSURE;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-一般状况检查结果      
SELECT GENERALHEALTH_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY GENERALHEALTH_CHECK_RESULT;

---PHYSICALEXAM_SKINMUCOSA_RESULT  VARCHAR2(1000)  Y    体格检查-皮肤和黏膜检查结果      
SELECT PHYSICALEXAM_SKINMUCOSA_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SKINMUCOSA_RESULT;

---LYMPH_NODE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-全身浅表淋巴结检查结果      
SELECT LYMPH_NODE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LYMPH_NODE_CHECK_RESULT;

---PHYSICALEXAM_HEADORGAN_RESULT  VARCHAR2(1000)  Y    体格检查-头部及其器官检查结果      
SELECT PHYSICALEXAM_HEADORGAN_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_HEADORGAN_RESULT;

---NECK_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-颈部检查结果      
SELECT NECK_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY NECK_CHECK_RESULT;

---CHEST_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-胸部检查结果      
SELECT CHEST_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY CHEST_CHECK_RESULT;

---ABDOMINAL_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-腹部检查结果      
SELECT ABDOMINAL_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY ABDOMINAL_CHECK_RESULT;

---PHYSICALEXAM_ANUS_RESULT  VARCHAR2(1000)  Y    体格检查-肛门指诊检查结果描述      
SELECT PHYSICALEXAM_ANUS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_ANUS_RESULT;

---PHYSICALEXAM_GENITALS_RESULT  VARCHAR2(1000)  Y    体格检查-外生殖器检查结果      
SELECT PHYSICALEXAM_GENITALS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_GENITALS_RESULT;

---SPINE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-脊柱检查结果      
SELECT SPINE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY SPINE_CHECK_RESULT;

---LIMBS_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-四肢检查结果      
SELECT LIMBS_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LIMBS_CHECK_RESULT;

---EXAM_NERVOUSSYSTEM_RESULT  VARCHAR2(1000)  Y    体格检查-神经系统检查结果      
SELECT EXAM_NERVOUSSYSTEM_RESULT FROM ADMISSION_RECORD GROUP BY EXAM_NERVOUSSYSTEM_RESULT;

---SPECIALIST_STATUS  VARCHAR2(1000)  Y    专科情况      
SELECT SPECIALIST_STATUS FROM ADMISSION_RECORD GROUP BY SPECIALIST_STATUS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果      
SELECT AUXILIARYEXAMI_RESULT FROM ADMISSION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果      
SELECT TCM_FOUR_RESULTS FROM ADMISSION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997    
SELECT THERAPEUTIC_PRINCIPLE FROM ADMISSION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名      
SELECT RECEIVE_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名      
SELECT PHYSICIAN_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名      
SELECT ARCHIATER_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号      
SELECT INP_NO FROM ADMISSION_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名      
SELECT MEDICALHIS_NAME FROM ADMISSION_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(1)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761-2008    
SELECT PRESENTER_PATIENT_RELAT_CODE FROM ADMISSION_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE    
SELECT IS_CREDIBLE FROM ADMISSION_RECORD GROUP BY IS_CREDIBLE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM ADMISSION_RECORD GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史      
SELECT PRESENT_DISEASE_HISTORY FROM ADMISSION_RECORD GROUP BY PRESENT_DISEASE_HISTORY;

---HEALTH_STATUS_CODE  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE    
SELECT HEALTH_STATUS_CODE FROM ADMISSION_RECORD GROUP BY HEALTH_STATUS_CODE;

---DISEASES_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）      
SELECT DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY DISEASES_HISTORY;

---COMMUNICABLE_DISEASES_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE    
SELECT COMMUNICABLE_DISEASES_FLAG FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_FLAG;

---COMMUNICABLE_DISEASES_HISTORY  VARCHAR2(1000)  Y    传染病史      
SELECT COMMUNICABLE_DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_HISTORY;

---PREVENTIVE_INOCULATION_HISTORY  VARCHAR2(1000)  Y    预防接种史      
SELECT PREVENTIVE_INOCULATION_HISTORY FROM ADMISSION_RECORD GROUP BY PREVENTIVE_INOCULATION_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史      
SELECT OPERATION_HISTORY FROM ADMISSION_RECORD GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史      
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史      
SELECT ALLERGY_HISTORY FROM ADMISSION_RECORD GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史      
SELECT PERSON_HISTORY FROM ADMISSION_RECORD GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史      
SELECT MARITAL_HISTORY FROM ADMISSION_RECORD GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史      
SELECT MENSTRUATION_HISTORY FROM ADMISSION_RECORD GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史      
SELECT FAMILY_HISTORY FROM ADMISSION_RECORD GROUP BY FAMILY_HISTORY;

---PHYSICALEXAM_TEMPERATURE  NUMBER(4,1)  Y    体格检查-体温（℃）      
SELECT PHYSICALEXAM_TEMPERATURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_TEMPERATURE;

---PHYSICALEXAM_SPHYGMUS  NUMBER(3)  Y    体格检查-脉率（次/min)      
SELECT PHYSICALEXAM_SPHYGMUS FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SPHYGMUS;

---PHYSICALEXAM_BREATH_FREQUENCY  NUMBER(3)  Y    体格检查-呼吸频率（次/min)      
SELECT PHYSICALEXAM_BREATH_FREQUENCY FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_BREATH_FREQUENCY;

---PHYSICALEXAM_SYSTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-收缩压（mm-Hg)      
SELECT PHYSICALEXAM_SYSTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SYSTOLIC_PRESSURE;

---EXAM_DIASTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-舒张压(mmHg)      
SELECT EXAM_DIASTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY EXAM_DIASTOLIC_PRESSURE;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-一般状况检查结果      
SELECT GENERALHEALTH_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY GENERALHEALTH_CHECK_RESULT;

---PHYSICALEXAM_SKINMUCOSA_RESULT  VARCHAR2(1000)  Y    体格检查-皮肤和黏膜检查结果      
SELECT PHYSICALEXAM_SKINMUCOSA_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SKINMUCOSA_RESULT;

---LYMPH_NODE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-全身浅表淋巴结检查结果      
SELECT LYMPH_NODE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LYMPH_NODE_CHECK_RESULT;

---PHYSICALEXAM_HEADORGAN_RESULT  VARCHAR2(1000)  Y    体格检查-头部及其器官检查结果      
SELECT PHYSICALEXAM_HEADORGAN_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_HEADORGAN_RESULT;

---NECK_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-颈部检查结果      
SELECT NECK_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY NECK_CHECK_RESULT;

---CHEST_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-胸部检查结果      
SELECT CHEST_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY CHEST_CHECK_RESULT;

---ABDOMINAL_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-腹部检查结果      
SELECT ABDOMINAL_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY ABDOMINAL_CHECK_RESULT;

---PHYSICALEXAM_ANUS_RESULT  VARCHAR2(1000)  Y    体格检查-肛门指诊检查结果描述      
SELECT PHYSICALEXAM_ANUS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_ANUS_RESULT;

---PHYSICALEXAM_GENITALS_RESULT  VARCHAR2(1000)  Y    体格检查-外生殖器检查结果      
SELECT PHYSICALEXAM_GENITALS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_GENITALS_RESULT;

---SPINE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-脊柱检查结果      
SELECT SPINE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY SPINE_CHECK_RESULT;

---LIMBS_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-四肢检查结果      
SELECT LIMBS_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LIMBS_CHECK_RESULT;

---EXAM_NERVOUSSYSTEM_RESULT  VARCHAR2(1000)  Y    体格检查-神经系统检查结果      
SELECT EXAM_NERVOUSSYSTEM_RESULT FROM ADMISSION_RECORD GROUP BY EXAM_NERVOUSSYSTEM_RESULT;

---SPECIALIST_STATUS  VARCHAR2(1000)  Y    专科情况      
SELECT SPECIALIST_STATUS FROM ADMISSION_RECORD GROUP BY SPECIALIST_STATUS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果      
SELECT AUXILIARYEXAMI_RESULT FROM ADMISSION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果      
SELECT TCM_FOUR_RESULTS FROM ADMISSION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997    
SELECT THERAPEUTIC_PRINCIPLE FROM ADMISSION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名      
SELECT RECEIVE_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名      
SELECT PHYSICIAN_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名      
SELECT ARCHIATER_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM ADMISSION_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM ADMISSION_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM ADMISSION_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)  Y    住院号      
SELECT INP_NO FROM ADMISSION_RECORD GROUP BY INP_NO;

---MEDICALHIS_NAME  VARCHAR2(50)  Y    病史陈述者姓名      
SELECT MEDICALHIS_NAME FROM ADMISSION_RECORD GROUP BY MEDICALHIS_NAME;

---PRESENTER_PATIENT_RELAT_CODE  VARCHAR2(1)  Y    陈述者与患者的关系代码  应符合国标：GB/T 4761-2008    
SELECT PRESENTER_PATIENT_RELAT_CODE FROM ADMISSION_RECORD GROUP BY PRESENTER_PATIENT_RELAT_CODE;

---IS_CREDIBLE  VARCHAR2(5)  Y    陈述内容可靠标志  TRUE/FALSE    
SELECT IS_CREDIBLE FROM ADMISSION_RECORD GROUP BY IS_CREDIBLE;

---CHIEF_COMPLAINT  VARCHAR2(100)  Y    主诉      
SELECT CHIEF_COMPLAINT FROM ADMISSION_RECORD GROUP BY CHIEF_COMPLAINT;

---PRESENT_DISEASE_HISTORY  VARCHAR2(2000)  Y    现病史      
SELECT PRESENT_DISEASE_HISTORY FROM ADMISSION_RECORD GROUP BY PRESENT_DISEASE_HISTORY;

---HEALTH_STATUS_CODE  VARCHAR2(5)  Y    一般健康状况标志  TRUE/FALSE    
SELECT HEALTH_STATUS_CODE FROM ADMISSION_RECORD GROUP BY HEALTH_STATUS_CODE;

---DISEASES_HISTORY  VARCHAR2(1000)  Y    疾病史（含外伤）      
SELECT DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY DISEASES_HISTORY;

---COMMUNICABLE_DISEASES_FLAG  VARCHAR2(5)  Y    患者传染性标志  TRUE/FALSE    
SELECT COMMUNICABLE_DISEASES_FLAG FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_FLAG;

---COMMUNICABLE_DISEASES_HISTORY  VARCHAR2(1000)  Y    传染病史      
SELECT COMMUNICABLE_DISEASES_HISTORY FROM ADMISSION_RECORD GROUP BY COMMUNICABLE_DISEASES_HISTORY;

---PREVENTIVE_INOCULATION_HISTORY  VARCHAR2(1000)  Y    预防接种史      
SELECT PREVENTIVE_INOCULATION_HISTORY FROM ADMISSION_RECORD GROUP BY PREVENTIVE_INOCULATION_HISTORY;

---OPERATION_HISTORY  VARCHAR2(1000)  Y    手术史      
SELECT OPERATION_HISTORY FROM ADMISSION_RECORD GROUP BY OPERATION_HISTORY;

---BLOOD_TRANSFUSION_HISTORY  VARCHAR2(1000)  Y    输血史      
SELECT BLOOD_TRANSFUSION_HISTORY FROM ADMISSION_RECORD GROUP BY BLOOD_TRANSFUSION_HISTORY;

---ALLERGY_HISTORY  VARCHAR2(1000)  Y    过敏史      
SELECT ALLERGY_HISTORY FROM ADMISSION_RECORD GROUP BY ALLERGY_HISTORY;

---PERSON_HISTORY  VARCHAR2(1000)  Y    个人史      
SELECT PERSON_HISTORY FROM ADMISSION_RECORD GROUP BY PERSON_HISTORY;

---MARITAL_HISTORY  VARCHAR2(1000)  Y    婚育史      
SELECT MARITAL_HISTORY FROM ADMISSION_RECORD GROUP BY MARITAL_HISTORY;

---MENSTRUATION_HISTORY  VARCHAR2(1000)  Y    月经史      
SELECT MENSTRUATION_HISTORY FROM ADMISSION_RECORD GROUP BY MENSTRUATION_HISTORY;

---FAMILY_HISTORY  VARCHAR2(1000)  Y    家族史      
SELECT FAMILY_HISTORY FROM ADMISSION_RECORD GROUP BY FAMILY_HISTORY;

---PHYSICALEXAM_TEMPERATURE  NUMBER(4,1)  Y    体格检查-体温（℃）      
SELECT PHYSICALEXAM_TEMPERATURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_TEMPERATURE;

---PHYSICALEXAM_SPHYGMUS  NUMBER(3)  Y    体格检查-脉率（次/min)      
SELECT PHYSICALEXAM_SPHYGMUS FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SPHYGMUS;

---PHYSICALEXAM_BREATH_FREQUENCY  NUMBER(3)  Y    体格检查-呼吸频率（次/min)      
SELECT PHYSICALEXAM_BREATH_FREQUENCY FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_BREATH_FREQUENCY;

---PHYSICALEXAM_SYSTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-收缩压（mm-Hg)      
SELECT PHYSICALEXAM_SYSTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SYSTOLIC_PRESSURE;

---EXAM_DIASTOLIC_PRESSURE  NUMBER(3)  Y    体格检查-舒张压(mmHg)      
SELECT EXAM_DIASTOLIC_PRESSURE FROM ADMISSION_RECORD GROUP BY EXAM_DIASTOLIC_PRESSURE;

---GENERALHEALTH_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-一般状况检查结果      
SELECT GENERALHEALTH_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY GENERALHEALTH_CHECK_RESULT;

---PHYSICALEXAM_SKINMUCOSA_RESULT  VARCHAR2(1000)  Y    体格检查-皮肤和黏膜检查结果      
SELECT PHYSICALEXAM_SKINMUCOSA_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_SKINMUCOSA_RESULT;

---LYMPH_NODE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-全身浅表淋巴结检查结果      
SELECT LYMPH_NODE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LYMPH_NODE_CHECK_RESULT;

---PHYSICALEXAM_HEADORGAN_RESULT  VARCHAR2(1000)  Y    体格检查-头部及其器官检查结果      
SELECT PHYSICALEXAM_HEADORGAN_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_HEADORGAN_RESULT;

---NECK_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-颈部检查结果      
SELECT NECK_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY NECK_CHECK_RESULT;

---CHEST_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-胸部检查结果      
SELECT CHEST_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY CHEST_CHECK_RESULT;

---ABDOMINAL_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-腹部检查结果      
SELECT ABDOMINAL_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY ABDOMINAL_CHECK_RESULT;

---PHYSICALEXAM_ANUS_RESULT  VARCHAR2(1000)  Y    体格检查-肛门指诊检查结果描述      
SELECT PHYSICALEXAM_ANUS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_ANUS_RESULT;

---PHYSICALEXAM_GENITALS_RESULT  VARCHAR2(1000)  Y    体格检查-外生殖器检查结果      
SELECT PHYSICALEXAM_GENITALS_RESULT FROM ADMISSION_RECORD GROUP BY PHYSICALEXAM_GENITALS_RESULT;

---SPINE_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-脊柱检查结果      
SELECT SPINE_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY SPINE_CHECK_RESULT;

---LIMBS_CHECK_RESULT  VARCHAR2(1000)  Y    体格检查-四肢检查结果      
SELECT LIMBS_CHECK_RESULT FROM ADMISSION_RECORD GROUP BY LIMBS_CHECK_RESULT;

---EXAM_NERVOUSSYSTEM_RESULT  VARCHAR2(1000)  Y    体格检查-神经系统检查结果      
SELECT EXAM_NERVOUSSYSTEM_RESULT FROM ADMISSION_RECORD GROUP BY EXAM_NERVOUSSYSTEM_RESULT;

---SPECIALIST_STATUS  VARCHAR2(1000)  Y    专科情况      
SELECT SPECIALIST_STATUS FROM ADMISSION_RECORD GROUP BY SPECIALIST_STATUS;

---AUXILIARYEXAMI_RESULT  VARCHAR2(1000)  Y    辅助检查结果      
SELECT AUXILIARYEXAMI_RESULT FROM ADMISSION_RECORD GROUP BY AUXILIARYEXAMI_RESULT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果      
SELECT TCM_FOUR_RESULTS FROM ADMISSION_RECORD GROUP BY TCM_FOUR_RESULTS;

---THERAPEUTIC_PRINCIPLE  VARCHAR2(100)  Y    治则治法  应符合国标：GB/T 16751.3—1997    
SELECT THERAPEUTIC_PRINCIPLE FROM ADMISSION_RECORD GROUP BY THERAPEUTIC_PRINCIPLE;

---RECEIVE_DOCTOR_SIGN  VARCHAR2(50)  Y    接诊医师签名      
SELECT RECEIVE_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY RECEIVE_DOCTOR_SIGN;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名      
SELECT INP_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名      
SELECT PHYSICIAN_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名      
SELECT ARCHIATER_DOCTOR_SIGN FROM ADMISSION_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM ADMISSION_RECORD GROUP BY LAST_MODIFIC_TIME;

