---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INP_NO;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY CREATE_DATETIME;

---EXP_IMPLANTABLE_FLAG  VARCHAR2(10)  Y    植入性耗材标志  TRUE/FALSE  L  T/F
SELECT EXP_IMPLANTABLE_FLAG FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_IMPLANTABLE_FLAG;

---EXP_NAME  VARCHAR2(200)  Y    材料名称    S1  AN..200
SELECT EXP_NAME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_NAME;

---EXP_CODE  VARCHAR2(20)  Y    产品编码    S1  N..20
SELECT EXP_CODE FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_CODE;

---EXP_FACTORY  VARCHAR2(70)  Y    产品生产厂家    S1  AN..70
SELECT EXP_FACTORY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_FACTORY;

---EXP_SUPPLIER  VARCHAR2(70)  Y    产品供应商    S1  AN..70
SELECT EXP_SUPPLIER FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_SUPPLIER;

---EXP_UNIT  VARCHAR2(6)  Y    耗材单位    S1  AN..6
SELECT EXP_UNIT FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_UNIT;

---QUANTITY  NUMBER(5)  Y    数量    N  N..5
SELECT QUANTITY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY QUANTITY;

---USE_WAYS  VARCHAR2(30)  Y    使用途径    S1  AN..30
SELECT USE_WAYS FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY USE_WAYS;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INP_NO;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY CREATE_DATETIME;

---EXP_IMPLANTABLE_FLAG  VARCHAR2(10)  Y    植入性耗材标志  TRUE/FALSE  L  T/F
SELECT EXP_IMPLANTABLE_FLAG FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_IMPLANTABLE_FLAG;

---EXP_NAME  VARCHAR2(200)  Y    材料名称    S1  AN..200
SELECT EXP_NAME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_NAME;

---EXP_CODE  VARCHAR2(20)  Y    产品编码    S1  N..20
SELECT EXP_CODE FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_CODE;

---EXP_FACTORY  VARCHAR2(70)  Y    产品生产厂家    S1  AN..70
SELECT EXP_FACTORY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_FACTORY;

---EXP_SUPPLIER  VARCHAR2(70)  Y    产品供应商    S1  AN..70
SELECT EXP_SUPPLIER FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_SUPPLIER;

---EXP_UNIT  VARCHAR2(6)  Y    耗材单位    S1  AN..6
SELECT EXP_UNIT FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_UNIT;

---QUANTITY  NUMBER(5)  Y    数量    N  N..5
SELECT QUANTITY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY QUANTITY;

---USE_WAYS  VARCHAR2(30)  Y    使用途径    S1  AN..30
SELECT USE_WAYS FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY USE_WAYS;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY INP_NO;

---CREATE_DATETIME  DATE  Y    记录日期时间    DT  DTI 5
SELECT CREATE_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY CREATE_DATETIME;

---EXP_IMPLANTABLE_FLAG  VARCHAR2(10)  Y    植入性耗材标志  TRUE/FALSE  L  T/F
SELECT EXP_IMPLANTABLE_FLAG FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_IMPLANTABLE_FLAG;

---EXP_NAME  VARCHAR2(200)  Y    材料名称    S1  AN..200
SELECT EXP_NAME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_NAME;

---EXP_CODE  VARCHAR2(20)  Y    产品编码    S1  N..20
SELECT EXP_CODE FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_CODE;

---EXP_FACTORY  VARCHAR2(70)  Y    产品生产厂家    S1  AN..70
SELECT EXP_FACTORY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_FACTORY;

---EXP_SUPPLIER  VARCHAR2(70)  Y    产品供应商    S1  AN..70
SELECT EXP_SUPPLIER FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_SUPPLIER;

---EXP_UNIT  VARCHAR2(6)  Y    耗材单位    S1  AN..6
SELECT EXP_UNIT FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY EXP_UNIT;

---QUANTITY  NUMBER(5)  Y    数量    N  N..5
SELECT QUANTITY FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY QUANTITY;

---USE_WAYS  VARCHAR2(30)  Y    使用途径    S1  AN..30
SELECT USE_WAYS FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY USE_WAYS;

---NURSE_SIGN  VARCHAR2(50)  Y    护士签名    S1  A..50
SELECT NURSE_SIGN FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY NURSE_SIGN;

---SIGN_DATETIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATETIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY SIGN_DATETIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM PRECIOUS_CONSUM_USAGE_RECORD GROUP BY LAST_MODIFIC_TIME;

