---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INP_NO;

---WARDROUNDS_DATATIME  DATE      查房日期时间    DT  DT15
SELECT WARDROUNDS_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUNDS_DATATIME;

---WARDROUND_RECORD  VARCHAR2(2000)      查房记录    S1  AN..2000
SELECT WARDROUND_RECORD FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUND_RECORD;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DRINK_DECWAY;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ASSESSMENT_PLAN;

---RECORD_SIGN  VARCHAR2(50)      记录人签名    S1  A..50
SELECT RECORD_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY RECORD_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)      主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)      主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INP_NO;

---WARDROUNDS_DATATIME  DATE      查房日期时间    DT  DT15
SELECT WARDROUNDS_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUNDS_DATATIME;

---WARDROUND_RECORD  VARCHAR2(2000)      查房记录    S1  AN..2000
SELECT WARDROUND_RECORD FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUND_RECORD;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DRINK_DECWAY;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ASSESSMENT_PLAN;

---RECORD_SIGN  VARCHAR2(50)      记录人签名    S1  A..50
SELECT RECORD_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY RECORD_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)      主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)      主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PATIENT_ID;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY INP_NO;

---WARDROUNDS_DATATIME  DATE      查房日期时间    DT  DT15
SELECT WARDROUNDS_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUNDS_DATATIME;

---WARDROUND_RECORD  VARCHAR2(2000)      查房记录    S1  AN..2000
SELECT WARDROUND_RECORD FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY WARDROUND_RECORD;

---ADVICE_CONTENT  VARCHAR2(1000)  Y    医嘱内容    S1  AN..1000
SELECT ADVICE_CONTENT FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ADVICE_CONTENT;

---TCM_FOUR_RESULTS  VARCHAR2(1000)  Y    中医“四诊”观察结果    S1  AN..1000
SELECT TCM_FOUR_RESULTS FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY TCM_FOUR_RESULTS;

---DIALECTICAL_DESC  VARCHAR2(1000)  Y    辨证论治详细描述    S1  AN..1000
SELECT DIALECTICAL_DESC FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY DIALECTICAL_DESC;

---CHIN_DECOC_DECWAY  VARCHAR2(100)  Y    中药煎煮方法    S1  AN..100
SELECT CHIN_DECOC_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DECOC_DECWAY;

---CHIN_DRINK_DECWAY  VARCHAR2(100)  Y    中药用药方法    S1  AN..100
SELECT CHIN_DRINK_DECWAY FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY CHIN_DRINK_DECWAY;

---ASSESSMENT_PLAN  VARCHAR2(2000)  Y    诊疗计划    S1  AN..2000
SELECT ASSESSMENT_PLAN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ASSESSMENT_PLAN;

---RECORD_SIGN  VARCHAR2(50)      记录人签名    S1  A..50
SELECT RECORD_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY RECORD_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)      主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)      主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE      签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM SUPERIOR_DOCTOR_WARDROUND GROUP BY LAST_MODIFIC_TIME;

