---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_VITAL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_VITAL GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_VITAL GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_VITAL GROUP BY OPERA_SN;

---RECORD_DATE  DATE  Y    记录时间    null  null
SELECT RECORD_DATE FROM OPERATION_VITAL GROUP BY RECORD_DATE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    null  null
SELECT SYSTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    null  null
SELECT DIASTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    null  null
SELECT TEMPERATURE FROM OPERATION_VITAL GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    null  null
SELECT CARDIOTACH FROM OPERATION_VITAL GROUP BY CARDIOTACH;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    null  null
SELECT SPHYGMUS FROM OPERATION_VITAL GROUP BY SPHYGMUS;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    null  null
SELECT BREATH_FREQUENCY FROM OPERATION_VITAL GROUP BY BREATH_FREQUENCY;

---OPERATION_VITAL_ID  VARCHAR2(18)      手术体征ID    null  null
SELECT OPERATION_VITAL_ID FROM OPERATION_VITAL GROUP BY OPERATION_VITAL_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_VITAL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_VITAL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_VITAL GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_VITAL GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_VITAL GROUP BY OPERA_SN;

---RECORD_DATE  DATE  Y    记录时间    null  null
SELECT RECORD_DATE FROM OPERATION_VITAL GROUP BY RECORD_DATE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    null  null
SELECT SYSTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    null  null
SELECT DIASTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    null  null
SELECT TEMPERATURE FROM OPERATION_VITAL GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    null  null
SELECT CARDIOTACH FROM OPERATION_VITAL GROUP BY CARDIOTACH;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    null  null
SELECT SPHYGMUS FROM OPERATION_VITAL GROUP BY SPHYGMUS;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    null  null
SELECT BREATH_FREQUENCY FROM OPERATION_VITAL GROUP BY BREATH_FREQUENCY;

---OPERATION_VITAL_ID  VARCHAR2(18)      手术体征ID    null  null
SELECT OPERATION_VITAL_ID FROM OPERATION_VITAL GROUP BY OPERATION_VITAL_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_VITAL GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_VITAL GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_VITAL GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_VITAL GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_VITAL GROUP BY OPERA_SN;

---RECORD_DATE  DATE  Y    记录时间    null  null
SELECT RECORD_DATE FROM OPERATION_VITAL GROUP BY RECORD_DATE;

---SYSTOLIC_PRESSURE  NUMBER(3)  Y    收缩压(mmHg)    null  null
SELECT SYSTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY SYSTOLIC_PRESSURE;

---DIASTOLIC_PRESSURE  NUMBER(3)  Y    舒张压(mmHg)    null  null
SELECT DIASTOLIC_PRESSURE FROM OPERATION_VITAL GROUP BY DIASTOLIC_PRESSURE;

---TEMPERATURE  NUMBER(4,1)  Y    体温（℃）    null  null
SELECT TEMPERATURE FROM OPERATION_VITAL GROUP BY TEMPERATURE;

---CARDIOTACH  NUMBER(3)  Y    心率(次/min)    null  null
SELECT CARDIOTACH FROM OPERATION_VITAL GROUP BY CARDIOTACH;

---SPHYGMUS  NUMBER(3)  Y    脉率(次/min)    null  null
SELECT SPHYGMUS FROM OPERATION_VITAL GROUP BY SPHYGMUS;

---BREATH_FREQUENCY  NUMBER(3)  Y    呼吸频率（次/min)    null  null
SELECT BREATH_FREQUENCY FROM OPERATION_VITAL GROUP BY BREATH_FREQUENCY;

---OPERATION_VITAL_ID  VARCHAR2(18)      手术体征ID    null  null
SELECT OPERATION_VITAL_ID FROM OPERATION_VITAL GROUP BY OPERATION_VITAL_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_VITAL GROUP BY LAST_MODIFIC_TIME;

