---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_ANA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_ANA GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_ANA GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_ANA GROUP BY OPERA_SN;

---ANESTHESIA_METHOD_CODE  NUMBER(2)  Y    麻醉方法代码  应符合国家标准：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  null  null
SELECT ANESTHESIA_METHOD_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_FLAG_CODE  NUMBER(1)  Y    麻醉中西医标识代码  标准值：1.西医麻醉  2.中医麻醉  null  null
SELECT ANESTHESIA_DOCTOR_FLAG_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_FLAG_CODE;

---ANESTHE_BEGIN_DATE  DATE  Y    麻醉开始日期时间    null  null
SELECT ANESTHE_BEGIN_DATE FROM OPERATION_ANA GROUP BY ANESTHE_BEGIN_DATE;

---ASA_STANDARD_CODE  NUMBER(1)  Y    美国麻醉医师协会(ASA)分级标准代码  应符合国家标准：CV05.10.021  null  null
SELECT ASA_STANDARD_CODE FROM OPERATION_ANA GROUP BY ASA_STANDARD_CODE;

---ANESTHESIA_COMPLICAT_CODE  NUMBER(1)  Y    麻醉合并症标志代码  标准值：1.否 2.是 3.不确定  null  null
SELECT ANESTHESIA_COMPLICAT_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_COMPLICAT_CODE;

---ANESTHESIA_EFFECT  VARCHAR2(100)  Y    麻醉效果    null  null
SELECT ANESTHESIA_EFFECT FROM OPERATION_ANA GROUP BY ANESTHESIA_EFFECT;

---PRE_ANAESTHESIA_DRUG  VARCHAR2(100)  Y    麻醉前用药    null  null
SELECT PRE_ANAESTHESIA_DRUG FROM OPERATION_ANA GROUP BY PRE_ANAESTHESIA_DRUG;

---TRACHEAL_INTUBATION_CODE  VARCHAR2(100)  Y    气管插管分类    null  null
SELECT TRACHEAL_INTUBATION_CODE FROM OPERATION_ANA GROUP BY TRACHEAL_INTUBATION_CODE;

---ANAESTHESIA_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    null  null
SELECT ANAESTHESIA_DRUG_NAME FROM OPERATION_ANA GROUP BY ANAESTHESIA_DRUG_NAME;

---ANAESTHESIA_LOCATION  VARCHAR2(100)  Y    麻醉体位    null  null
SELECT ANAESTHESIA_LOCATION FROM OPERATION_ANA GROUP BY ANAESTHESIA_LOCATION;

---RESPIRATORY_TYPE_CODE  NUMBER(1)  Y    呼吸类型代码  标准值：1.自主呼吸 2.辅助呼吸 3.控制呼吸  null  null
SELECT RESPIRATORY_TYPE_CODE FROM OPERATION_ANA GROUP BY RESPIRATORY_TYPE_CODE;

---PUNCTURE_PROCESS  VARCHAR2(2000)  Y    穿刺过程    null  null
SELECT PUNCTURE_PROCESS FROM OPERATION_ANA GROUP BY PUNCTURE_PROCESS;

---ANAESTHESIA_DESC  VARCHAR2(200)  Y    麻醉描述    null  null
SELECT ANAESTHESIA_DESC FROM OPERATION_ANA GROUP BY ANAESTHESIA_DESC;

---ANESTHESIA_OBSERVATION_RESULT  VARCHAR2(1000)  Y    麻醉观察结果    null  null
SELECT ANESTHESIA_OBSERVATION_RESULT FROM OPERATION_ANA GROUP BY ANESTHESIA_OBSERVATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    null  null
SELECT ANESTHESIA_DOCTOR_SIGN FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---OPERATION_ANA_ID  VARCHAR2(18)      麻醉操作表ID    null  null
SELECT OPERATION_ANA_ID FROM OPERATION_ANA GROUP BY OPERATION_ANA_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_ANA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_ANA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_ANA GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_ANA GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_ANA GROUP BY OPERA_SN;

---ANESTHESIA_METHOD_CODE  NUMBER(2)  Y    麻醉方法代码  应符合国家标准：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  null  null
SELECT ANESTHESIA_METHOD_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_FLAG_CODE  NUMBER(1)  Y    麻醉中西医标识代码  标准值：1.西医麻醉  2.中医麻醉  null  null
SELECT ANESTHESIA_DOCTOR_FLAG_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_FLAG_CODE;

---ANESTHE_BEGIN_DATE  DATE  Y    麻醉开始日期时间    null  null
SELECT ANESTHE_BEGIN_DATE FROM OPERATION_ANA GROUP BY ANESTHE_BEGIN_DATE;

---ASA_STANDARD_CODE  NUMBER(1)  Y    美国麻醉医师协会(ASA)分级标准代码  应符合国家标准：CV05.10.021  null  null
SELECT ASA_STANDARD_CODE FROM OPERATION_ANA GROUP BY ASA_STANDARD_CODE;

---ANESTHESIA_COMPLICAT_CODE  NUMBER(1)  Y    麻醉合并症标志代码  标准值：1.否 2.是 3.不确定  null  null
SELECT ANESTHESIA_COMPLICAT_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_COMPLICAT_CODE;

---ANESTHESIA_EFFECT  VARCHAR2(100)  Y    麻醉效果    null  null
SELECT ANESTHESIA_EFFECT FROM OPERATION_ANA GROUP BY ANESTHESIA_EFFECT;

---PRE_ANAESTHESIA_DRUG  VARCHAR2(100)  Y    麻醉前用药    null  null
SELECT PRE_ANAESTHESIA_DRUG FROM OPERATION_ANA GROUP BY PRE_ANAESTHESIA_DRUG;

---TRACHEAL_INTUBATION_CODE  VARCHAR2(100)  Y    气管插管分类    null  null
SELECT TRACHEAL_INTUBATION_CODE FROM OPERATION_ANA GROUP BY TRACHEAL_INTUBATION_CODE;

---ANAESTHESIA_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    null  null
SELECT ANAESTHESIA_DRUG_NAME FROM OPERATION_ANA GROUP BY ANAESTHESIA_DRUG_NAME;

---ANAESTHESIA_LOCATION  VARCHAR2(100)  Y    麻醉体位    null  null
SELECT ANAESTHESIA_LOCATION FROM OPERATION_ANA GROUP BY ANAESTHESIA_LOCATION;

---RESPIRATORY_TYPE_CODE  NUMBER(1)  Y    呼吸类型代码  标准值：1.自主呼吸 2.辅助呼吸 3.控制呼吸  null  null
SELECT RESPIRATORY_TYPE_CODE FROM OPERATION_ANA GROUP BY RESPIRATORY_TYPE_CODE;

---PUNCTURE_PROCESS  VARCHAR2(2000)  Y    穿刺过程    null  null
SELECT PUNCTURE_PROCESS FROM OPERATION_ANA GROUP BY PUNCTURE_PROCESS;

---ANAESTHESIA_DESC  VARCHAR2(200)  Y    麻醉描述    null  null
SELECT ANAESTHESIA_DESC FROM OPERATION_ANA GROUP BY ANAESTHESIA_DESC;

---ANESTHESIA_OBSERVATION_RESULT  VARCHAR2(1000)  Y    麻醉观察结果    null  null
SELECT ANESTHESIA_OBSERVATION_RESULT FROM OPERATION_ANA GROUP BY ANESTHESIA_OBSERVATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    null  null
SELECT ANESTHESIA_DOCTOR_SIGN FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---OPERATION_ANA_ID  VARCHAR2(18)      麻醉操作表ID    null  null
SELECT OPERATION_ANA_ID FROM OPERATION_ANA GROUP BY OPERATION_ANA_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_ANA GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊流水号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_ANA GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_ANA GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_ANA GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_ANA GROUP BY OPERA_SN;

---ANESTHESIA_METHOD_CODE  NUMBER(2)  Y    麻醉方法代码  应符合国家标准：WS 364.12—2011 表 3 CV06.00.103麻醉方法代码表  null  null
SELECT ANESTHESIA_METHOD_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_METHOD_CODE;

---ANESTHESIA_DOCTOR_FLAG_CODE  NUMBER(1)  Y    麻醉中西医标识代码  标准值：1.西医麻醉  2.中医麻醉  null  null
SELECT ANESTHESIA_DOCTOR_FLAG_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_FLAG_CODE;

---ANESTHE_BEGIN_DATE  DATE  Y    麻醉开始日期时间    null  null
SELECT ANESTHE_BEGIN_DATE FROM OPERATION_ANA GROUP BY ANESTHE_BEGIN_DATE;

---ASA_STANDARD_CODE  NUMBER(1)  Y    美国麻醉医师协会(ASA)分级标准代码  应符合国家标准：CV05.10.021  null  null
SELECT ASA_STANDARD_CODE FROM OPERATION_ANA GROUP BY ASA_STANDARD_CODE;

---ANESTHESIA_COMPLICAT_CODE  NUMBER(1)  Y    麻醉合并症标志代码  标准值：1.否 2.是 3.不确定  null  null
SELECT ANESTHESIA_COMPLICAT_CODE FROM OPERATION_ANA GROUP BY ANESTHESIA_COMPLICAT_CODE;

---ANESTHESIA_EFFECT  VARCHAR2(100)  Y    麻醉效果    null  null
SELECT ANESTHESIA_EFFECT FROM OPERATION_ANA GROUP BY ANESTHESIA_EFFECT;

---PRE_ANAESTHESIA_DRUG  VARCHAR2(100)  Y    麻醉前用药    null  null
SELECT PRE_ANAESTHESIA_DRUG FROM OPERATION_ANA GROUP BY PRE_ANAESTHESIA_DRUG;

---TRACHEAL_INTUBATION_CODE  VARCHAR2(100)  Y    气管插管分类    null  null
SELECT TRACHEAL_INTUBATION_CODE FROM OPERATION_ANA GROUP BY TRACHEAL_INTUBATION_CODE;

---ANAESTHESIA_DRUG_NAME  VARCHAR2(50)  Y    麻醉药物名称    null  null
SELECT ANAESTHESIA_DRUG_NAME FROM OPERATION_ANA GROUP BY ANAESTHESIA_DRUG_NAME;

---ANAESTHESIA_LOCATION  VARCHAR2(100)  Y    麻醉体位    null  null
SELECT ANAESTHESIA_LOCATION FROM OPERATION_ANA GROUP BY ANAESTHESIA_LOCATION;

---RESPIRATORY_TYPE_CODE  NUMBER(1)  Y    呼吸类型代码  标准值：1.自主呼吸 2.辅助呼吸 3.控制呼吸  null  null
SELECT RESPIRATORY_TYPE_CODE FROM OPERATION_ANA GROUP BY RESPIRATORY_TYPE_CODE;

---PUNCTURE_PROCESS  VARCHAR2(2000)  Y    穿刺过程    null  null
SELECT PUNCTURE_PROCESS FROM OPERATION_ANA GROUP BY PUNCTURE_PROCESS;

---ANAESTHESIA_DESC  VARCHAR2(200)  Y    麻醉描述    null  null
SELECT ANAESTHESIA_DESC FROM OPERATION_ANA GROUP BY ANAESTHESIA_DESC;

---ANESTHESIA_OBSERVATION_RESULT  VARCHAR2(1000)  Y    麻醉观察结果    null  null
SELECT ANESTHESIA_OBSERVATION_RESULT FROM OPERATION_ANA GROUP BY ANESTHESIA_OBSERVATION_RESULT;

---ANESTHESIA_DOCTOR_SIGN  VARCHAR2(50)  Y    麻醉医师签名    null  null
SELECT ANESTHESIA_DOCTOR_SIGN FROM OPERATION_ANA GROUP BY ANESTHESIA_DOCTOR_SIGN;

---OPERATION_ANA_ID  VARCHAR2(18)      麻醉操作表ID    null  null
SELECT OPERATION_ANA_ID FROM OPERATION_ANA GROUP BY OPERATION_ANA_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_ANA GROUP BY LAST_MODIFIC_TIME;

