---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DEATH_RECORD GROUP BY INP_SITUATION;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DEATH_RECORD GROUP BY DIAG_DESC;

---DEATH_DATETIME  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATETIME FROM DEATH_RECORD GROUP BY DEATH_DATETIME;

---IS_AGREE_POSTMORTEM  VARCHAR2(5)  Y    家属是否同意尸体解剖标志    L  T/F
SELECT IS_AGREE_POSTMORTEM FROM DEATH_RECORD GROUP BY IS_AGREE_POSTMORTEM;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DEATH_RECORD GROUP BY INP_SITUATION;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DEATH_RECORD GROUP BY DIAG_DESC;

---DEATH_DATETIME  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATETIME FROM DEATH_RECORD GROUP BY DEATH_DATETIME;

---IS_AGREE_POSTMORTEM  VARCHAR2(5)  Y    家属是否同意尸体解剖标志    L  T/F
SELECT IS_AGREE_POSTMORTEM FROM DEATH_RECORD GROUP BY IS_AGREE_POSTMORTEM;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM DEATH_RECORD GROUP BY INPATIENT_SN;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM DEATH_RECORD GROUP BY DOC_NO;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM DEATH_RECORD GROUP BY INP_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM DEATH_RECORD GROUP BY PATIENT_ID;

---INP_SITUATION  VARCHAR2(2000)  Y    入院情况    S1  AN..2000
SELECT INP_SITUATION FROM DEATH_RECORD GROUP BY INP_SITUATION;

---DIAG_DESC  VARCHAR2(2000)  Y    诊疗过程描述    S1  AN..2000
SELECT DIAG_DESC FROM DEATH_RECORD GROUP BY DIAG_DESC;

---DEATH_DATETIME  DATE  Y    死亡日期时间    DT  DT15
SELECT DEATH_DATETIME FROM DEATH_RECORD GROUP BY DEATH_DATETIME;

---IS_AGREE_POSTMORTEM  VARCHAR2(5)  Y    家属是否同意尸体解剖标志    L  T/F
SELECT IS_AGREE_POSTMORTEM FROM DEATH_RECORD GROUP BY IS_AGREE_POSTMORTEM;

---INP_DOCTOR_SIGN  VARCHAR2(50)  Y    住院医师签名    S1  A..50
SELECT INP_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY INP_DOCTOR_SIGN;

---PHYSICIAN_DOCTOR_SIGN  VARCHAR2(50)  Y    主治医师签名    S1  A..50
SELECT PHYSICIAN_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY PHYSICIAN_DOCTOR_SIGN;

---ARCHIATER_DOCTOR_SIGN  VARCHAR2(50)  Y    主任医师签名    S1  A..50
SELECT ARCHIATER_DOCTOR_SIGN FROM DEATH_RECORD GROUP BY ARCHIATER_DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM DEATH_RECORD GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y          
SELECT LAST_MODIFIC_TIME FROM DEATH_RECORD GROUP BY LAST_MODIFIC_TIME;

