---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_DRUG GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_DRUG GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_DRUG GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_DRUG GROUP BY OPERA_SN;

---MED_TYPE  NUMBER(1)  Y    用药类型(1-术前用药，2-术中用药)  标准值：1-术前用药，2-术中用药  null  null
SELECT MED_TYPE FROM OPERATION_DRUG GROUP BY MED_TYPE;

---MED_NAME  VARCHAR2(100)  Y    用药名称    null  null
SELECT MED_NAME FROM OPERATION_DRUG GROUP BY MED_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE;

---DRUG_USAGE_FRE  VARCHAR2(2)  Y    药物使用频次代码  应符合国家标准：CV06.00.228  null  null
SELECT DRUG_USAGE_FRE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DRUG_DOSAGE_UNIT FROM OPERATION_DRUG GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    null  null
SELECT DRUG_USAGE_DOSAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT DRUG_USAGE_TOTAL FROM OPERATION_DRUG GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码  应符合国家标准：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  null  null
SELECT ROUTE_ADMINISTRATION FROM OPERATION_DRUG GROUP BY ROUTE_ADMINISTRATION;

---OPERATION_DRUG_ID  VARCHAR2(18)      手术用药ID    null  null
SELECT OPERATION_DRUG_ID FROM OPERATION_DRUG GROUP BY OPERATION_DRUG_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_DRUG GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_DRUG GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_DRUG GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_DRUG GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_DRUG GROUP BY OPERA_SN;

---MED_TYPE  NUMBER(1)  Y    用药类型(1-术前用药，2-术中用药)  标准值：1-术前用药，2-术中用药  null  null
SELECT MED_TYPE FROM OPERATION_DRUG GROUP BY MED_TYPE;

---MED_NAME  VARCHAR2(100)  Y    用药名称    null  null
SELECT MED_NAME FROM OPERATION_DRUG GROUP BY MED_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE;

---DRUG_USAGE_FRE  VARCHAR2(2)  Y    药物使用频次代码  应符合国家标准：CV06.00.228  null  null
SELECT DRUG_USAGE_FRE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DRUG_DOSAGE_UNIT FROM OPERATION_DRUG GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    null  null
SELECT DRUG_USAGE_DOSAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT DRUG_USAGE_TOTAL FROM OPERATION_DRUG GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码  应符合国家标准：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  null  null
SELECT ROUTE_ADMINISTRATION FROM OPERATION_DRUG GROUP BY ROUTE_ADMINISTRATION;

---OPERATION_DRUG_ID  VARCHAR2(18)      手术用药ID    null  null
SELECT OPERATION_DRUG_ID FROM OPERATION_DRUG GROUP BY OPERATION_DRUG_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_DRUG GROUP BY LAST_MODIFIC_TIME;

---OUTPATIENT_SN  VARCHAR2(18)  Y    门（急）诊号    null  null
SELECT OUTPATIENT_SN FROM OPERATION_DRUG GROUP BY OUTPATIENT_SN;

---INPATIENT_SN  VARCHAR2(18)  Y    住院流水号    null  null
SELECT INPATIENT_SN FROM OPERATION_DRUG GROUP BY INPATIENT_SN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    null  null
SELECT OPER_REQ_SN FROM OPERATION_DRUG GROUP BY OPER_REQ_SN;

---OPERA_SN  VARCHAR2(18)  Y    手术记录流水号    null  null
SELECT OPERA_SN FROM OPERATION_DRUG GROUP BY OPERA_SN;

---MED_TYPE  NUMBER(1)  Y    用药类型(1-术前用药，2-术中用药)  标准值：1-术前用药，2-术中用药  null  null
SELECT MED_TYPE FROM OPERATION_DRUG GROUP BY MED_TYPE;

---MED_NAME  VARCHAR2(100)  Y    用药名称    null  null
SELECT MED_NAME FROM OPERATION_DRUG GROUP BY MED_NAME;

---DRUG_USAGE  VARCHAR2(100)  Y    药物用法    null  null
SELECT DRUG_USAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE;

---DRUG_USAGE_FRE  VARCHAR2(2)  Y    药物使用频次代码  应符合国家标准：CV06.00.228  null  null
SELECT DRUG_USAGE_FRE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_FRE;

---DRUG_DOSAGE_UNIT  VARCHAR2(6)  Y    药物使用剂量单位    null  null
SELECT DRUG_DOSAGE_UNIT FROM OPERATION_DRUG GROUP BY DRUG_DOSAGE_UNIT;

---DRUG_USAGE_DOSAGE  NUMBER(5,2)  Y    药物使用次剂量    null  null
SELECT DRUG_USAGE_DOSAGE FROM OPERATION_DRUG GROUP BY DRUG_USAGE_DOSAGE;

---DRUG_USAGE_TOTAL  NUMBER(12,2)  Y    药物使用总剂量    null  null
SELECT DRUG_USAGE_TOTAL FROM OPERATION_DRUG GROUP BY DRUG_USAGE_TOTAL;

---ROUTE_ADMINISTRATION  NUMBER(3)  Y    用药途径代码  应符合国家标准：WS 364.12—2011 表 2 CV06.00.102用药途径代码表  null  null
SELECT ROUTE_ADMINISTRATION FROM OPERATION_DRUG GROUP BY ROUTE_ADMINISTRATION;

---OPERATION_DRUG_ID  VARCHAR2(18)      手术用药ID    null  null
SELECT OPERATION_DRUG_ID FROM OPERATION_DRUG GROUP BY OPERATION_DRUG_ID;

---LAST_MODIFIC_TIME  DATE  Y        null  null
SELECT LAST_MODIFIC_TIME FROM OPERATION_DRUG GROUP BY LAST_MODIFIC_TIME;

