---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_DISCUSSION GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_DISCUSSION GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_DISCUSSION GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_DISCUSSION GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_NAMES;

---ANAESTHESIA_DOCTOR_NAME  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANAESTHESIA_DOCTOR_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY ANAESTHESIA_DOCTOR_NAME;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM PRE_OPERATION_DISCUSSION GROUP BY PROFESSIONAL_CATAGORY_CODE;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_POINTS;

---OPERATION_PLANS  VARCHAR2(1000)  Y    手术方案    S1  AN..1000
SELECT OPERATION_PLANS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_PLANS;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..500
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_DISCUSSION GROUP BY MATTERS_NEED_ATTENTION;

---DISCUSS_SUGGESTION  VARCHAR2(2000)  Y    讨论意见    S1  AN..1000
SELECT DISCUSS_SUGGESTION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_SUGGESTION;

---DISCUSS_CONCLUSION  VARCHAR2(2000)  Y    讨论结论    S1  AN..1000
SELECT DISCUSS_CONCLUSION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_CONCLUSION;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  AN..2000
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATIVE_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    S1  AN..2000
SELECT OPER_REQ_SN FROM PRE_OPERATION_DISCUSSION GROUP BY OPER_REQ_SN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_DISCUSSION GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_DISCUSSION GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_DISCUSSION GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_DISCUSSION GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_DISCUSSION GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_NAMES;

---ANAESTHESIA_DOCTOR_NAME  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANAESTHESIA_DOCTOR_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY ANAESTHESIA_DOCTOR_NAME;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM PRE_OPERATION_DISCUSSION GROUP BY PROFESSIONAL_CATAGORY_CODE;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_POINTS;

---OPERATION_PLANS  VARCHAR2(1000)  Y    手术方案    S1  AN..1000
SELECT OPERATION_PLANS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_PLANS;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..500
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_DISCUSSION GROUP BY MATTERS_NEED_ATTENTION;

---DISCUSS_SUGGESTION  VARCHAR2(2000)  Y    讨论意见    S1  AN..1000
SELECT DISCUSS_SUGGESTION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_SUGGESTION;

---DISCUSS_CONCLUSION  VARCHAR2(2000)  Y    讨论结论    S1  AN..1000
SELECT DISCUSS_CONCLUSION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_CONCLUSION;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  AN..2000
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATIVE_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    S1  AN..2000
SELECT OPER_REQ_SN FROM PRE_OPERATION_DISCUSSION GROUP BY OPER_REQ_SN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_DISCUSSION GROUP BY LAST_MODIFIC_TIME;

---INPATIENT_SN  VARCHAR2(18)      住院流水号      
SELECT INPATIENT_SN FROM PRE_OPERATION_DISCUSSION GROUP BY INPATIENT_SN;

---INP_NO  VARCHAR2(18)      住院号    S1  AN..18
SELECT INP_NO FROM PRE_OPERATION_DISCUSSION GROUP BY INP_NO;

---DOC_NO  VARCHAR2(50)      文档编号      
SELECT DOC_NO FROM PRE_OPERATION_DISCUSSION GROUP BY DOC_NO;

---PATIENT_ID  VARCHAR2(20)      患者ID      
SELECT PATIENT_ID FROM PRE_OPERATION_DISCUSSION GROUP BY PATIENT_ID;

---DISCUSS_DATATIME  DATE  Y    讨论日期时间    DT  DT15
SELECT DISCUSS_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_DATATIME;

---DISCUSS_PLACE  VARCHAR2(50)  Y    讨论地点    S1  AN..50
SELECT DISCUSS_PLACE FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_PLACE;

---COMPERE_NAME  VARCHAR2(50)  Y    主持人姓名    S1  A..50
SELECT COMPERE_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY COMPERE_NAME;

---DISCUSS_NAMES  VARCHAR2(200)  Y    参加讨论人员名单    S1  A..200
SELECT DISCUSS_NAMES FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_NAMES;

---ANAESTHESIA_DOCTOR_NAME  VARCHAR2(50)  Y    麻醉医师签名    S1  A..50
SELECT ANAESTHESIA_DOCTOR_NAME FROM PRE_OPERATION_DISCUSSION GROUP BY ANAESTHESIA_DOCTOR_NAME;

---PROFESSIONAL_CATAGORY_CODE  NUMBER(1)  Y    专业技术职务类别代码  应符合国标：WS 364.15—2011 表 5 CV08.30.005专业技术职务类别代码表  S3  N1
SELECT PROFESSIONAL_CATAGORY_CODE FROM PRE_OPERATION_DISCUSSION GROUP BY PROFESSIONAL_CATAGORY_CODE;

---OPERATION_POINTS  VARCHAR2(200)  Y    手术要点    S1  AN..200
SELECT OPERATION_POINTS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_POINTS;

---OPERATION_PLANS  VARCHAR2(1000)  Y    手术方案    S1  AN..1000
SELECT OPERATION_PLANS FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATION_PLANS;

---MATTERS_NEED_ATTENTION  VARCHAR2(1000)  Y    注意事项    S1  AN..500
SELECT MATTERS_NEED_ATTENTION FROM PRE_OPERATION_DISCUSSION GROUP BY MATTERS_NEED_ATTENTION;

---DISCUSS_SUGGESTION  VARCHAR2(2000)  Y    讨论意见    S1  AN..1000
SELECT DISCUSS_SUGGESTION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_SUGGESTION;

---DISCUSS_CONCLUSION  VARCHAR2(2000)  Y    讨论结论    S1  AN..1000
SELECT DISCUSS_CONCLUSION FROM PRE_OPERATION_DISCUSSION GROUP BY DISCUSS_CONCLUSION;

---OPERATIVE_SIGN  VARCHAR2(50)  Y    手术者签名    S1  AN..2000
SELECT OPERATIVE_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY OPERATIVE_SIGN;

---OPER_REQ_SN  VARCHAR2(18)  Y    手术申请单号    S1  AN..2000
SELECT OPER_REQ_SN FROM PRE_OPERATION_DISCUSSION GROUP BY OPER_REQ_SN;

---DOCTOR_SIGN  VARCHAR2(50)  Y    医师签名    S1  A..50
SELECT DOCTOR_SIGN FROM PRE_OPERATION_DISCUSSION GROUP BY DOCTOR_SIGN;

---SIGN_DATATIME  DATE  Y    签名日期时间    DT  DT15
SELECT SIGN_DATATIME FROM PRE_OPERATION_DISCUSSION GROUP BY SIGN_DATATIME;

---LAST_MODIFIC_TIME  DATE  Y    最后修改时间      
SELECT LAST_MODIFIC_TIME FROM PRE_OPERATION_DISCUSSION GROUP BY LAST_MODIFIC_TIME;

